### ISSUE TITLE
StreamCorruptedException  used version 5.6.8   es

### ISSUE THREAD

**Issue by jklliang** [apache/incubator-skywalking#1020]
es version 5.6.8 , starte collecter throw StreamCorruptedException  :
exception info:

```
2018-04-03 16:42:34,348 - org.skywalking.apm.collector.core.data.StorageDefineLoader -154008 [main] INFO  [] - loaded storage definition class: org.skywalking.apm.collector.storage.es.define.NodeComponentEsTableDefine
2018-04-03 16:42:34,334 - org.elasticsearch.transport.netty4.Netty4Transport -153994 [elasticsearch[_client_][transport_client_boss][T#10]] WARN  [] - exception caught on transport layer [[id: 0x48bb3543, L:/10.164.204.51:42842 - R:/10.164.204.53:9200]], closing connection
io.netty.handler.codec.DecoderException: java.io.StreamCorruptedException: invalid internal transport message format, got (48,54,54,50)
	at io.netty.handler.codec.ByteToMessageDecoder.callDecode(ByteToMessageDecoder.java:459) ~[netty-codec-4.1.17.Final.jar:4.1.17.Final]
	at io.netty.handler.codec.ByteToMessageDecoder.channelRead(ByteToMessageDecoder.java:265) ~[netty-codec-4.1.17.Final.jar:4.1.17.Final]
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:362) [netty-transport-4.1.17.Final.jar:4.1.17.Final]
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:348) [netty-transport-4.1.17.Final.jar:4.1.17.Final]
	at io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:340) [netty-transport-4.1.17.Final.jar:4.1.17.Final]
	at io.netty.channel.DefaultChannelPipeline$HeadContext.channelRead(DefaultChannelPipeline.java:1359) [netty-transport-4.1.17.Final.jar:4.1.17.Final]
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:362) [netty-transport-4.1.17.Final.jar:4.1.17.Final]
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:348) [netty-transport-4.1.17.Final.jar:4.1.17.Final]
	at io.netty.channel.DefaultChannelPipeline.fireChannelRead(DefaultChannelPipeline.java:935) [netty-transport-4.1.17.Final.jar:4.1.17.Final]
	at io.netty.channel.nio.AbstractNioByteChannel$NioByteUnsafe.read(AbstractNioByteChannel.java:138) [netty-transport-4.1.17.Final.jar:4.1.17.Final]
	at io.netty.channel.nio.NioEventLoop.processSelectedKey(NioEventLoop.java:645) [netty-transport-4.1.17.Final.jar:4.1.17.Final]
	at io.netty.channel.nio.NioEventLoop.processSelectedKeysPlain(NioEventLoop.java:545) [netty-transport-4.1.17.Final.jar:4.1.17.Final]
	at io.netty.channel.nio.NioEventLoop.processSelectedKeys(NioEventLoop.java:499) [netty-transport-4.1.17.Final.jar:4.1.17.Final]
	at io.netty.channel.nio.NioEventLoop.run(NioEventLoop.java:459) [netty-transport-4.1.17.Final.jar:4.1.17.Final]
	at io.netty.util.concurrent.SingleThreadEventExecutor$5.run(SingleThreadEventExecutor.java:858) [netty-common-4.1.17.Final.jar:4.1.17.Final]
	at java.lang.Thread.run(Thread.java:745) [?:1.8.0_40]
Caused by: java.io.StreamCorruptedException: invalid internal transport message format, got (48,54,54,50)
	at org.elasticsearch.transport.TcpTransport.validateMessageHeader(TcpTransport.java:1282) ~[elasticsearch-5.5.0.jar:5.5.0]
	at org.elasticsearch.transport.netty4.Netty4SizeHeaderFrameDecoder.decode(Netty4SizeHeaderFrameDecoder.java:36) ~[transport-netty4-client-5.5.0.jar:5.5.0]
	at io.netty.handler.codec.ByteToMessageDecoder.decodeRemovalReentryProtection(ByteToMessageDecoder.java:489) ~[netty-codec-4.1.17.Final.jar:4.1.17.Final]
	at io.netty.handler.codec.ByteToMessageDecoder.callDecode(ByteToMessageDecoder.java:428) ~[netty-codec-4.1.17.Final.jar:4.1.17.Final]
	... 15 more
```
  
 yml config: 
```

  cluster:
  zookeeper:
    hostPort: 10.164.204.51:2181
    sessionTimeout: 100000
naming:
  jetty:
    host: 10.164.204.51
    port: 10800
    context_path: /
remote:
  gRPC:
    host: 10.164.204.51
    port: 11800
agent_gRPC:
  gRPC:
    host: 10.164.204.51
    port: 11800
agent_jetty:
  jetty:
    host: 10.164.204.51
    port: 12800
    context_path: /
agent_stream:
  default:
    buffer_file_path: ../buffer/
    buffer_offset_max_file_size: 10M
    buffer_segment_max_file_size: 500M
ui:
  jetty:
    host: 10.164.204.51
    port: 12800
    context_path: /
storage:
  elasticsearch:
    cluster_name: CollectorDBCluster
    cluster_transport_sniffer: true
    cluster_nodes: 10.164.204.51:9200,10.164.204.52:9200,10.164.204.53:9200
    index_shards_number: 2
    index_replicas_number: 0
    ttl: 7
```

**Comment by wu-sheng** [comment]
5.6.8 is not our supported version. Maybe you can correct the document for use. 5.5 is latest version we supported.
