### ISSUE TITLE
Collector throws NoNodeAvailableException using Elasticsearch 6.2.3

### ISSUE THREAD

**Issue by weenyaimac** [apache/incubator-skywalking#1061]
Please answer these questions before submitting your issue.

- Why do you submit this issue?
- [ ] Question or discussion

Collector will throw 'NoNodeAvailableException' when starting if I use ES 6.2.3 as storage. The detailed exception message from collector.log is as follows:

`Exception in thread "main" NoNodeAvailableException[None of the configured nodes are available: [{#transport#-1}{S77BV75vRxewCFuNupH8LQ}{10.79.10.69}{10.79.10.69:9200}, {#transpor
t#-2}{ptgYMMWCSIamqACJMgnwkQ}{10.79.10.68}{10.79.10.68:9200}]]
	at org.elasticsearch.client.transport.TransportClientNodesService.ensureNodesAreAvailable(TransportClientNodesService.java:347)
	at org.elasticsearch.client.transport.TransportClientNodesService.execute(TransportClientNodesService.java:245)
	at org.elasticsearch.client.transport.TransportProxyClient.execute(TransportProxyClient.java:59)
	at org.elasticsearch.client.transport.TransportClient.doExecute(TransportClient.java:363)
	at org.elasticsearch.client.support.AbstractClient.execute(AbstractClient.java:408)
	at org.elasticsearch.client.support.AbstractClient$IndicesAdmin.execute(AbstractClient.java:1256)
	at org.elasticsearch.action.ActionRequestBuilder.execute(ActionRequestBuilder.java:80)
	at org.elasticsearch.action.ActionRequestBuilder.execute(ActionRequestBuilder.java:54)
	at org.elasticsearch.action.ActionRequestBuilder.get(ActionRequestBuilder.java:62)
	at org.apache.skywalking.apm.collector.client.elasticsearch.ElasticSearchClient.isExistsIndex(ElasticSearchClient.java:131)
	at org.apache.skywalking.apm.collector.storage.es.base.define.ElasticSearchStorageInstaller.isExists(ElasticSearchStorageInstaller.java:129)
	at org.apache.skywalking.apm.collector.storage.StorageInstaller.install(StorageInstaller.java:46)
	at org.apache.skywalking.apm.collector.storage.es.StorageModuleEsProvider.start(StorageModuleEsProvider.java:294)
	at org.apache.skywalking.apm.collector.core.module.BootstrapFlow.start(BootstrapFlow.java:63)
	at org.apache.skywalking.apm.collector.core.module.ModuleManager.init(ModuleManager.java:70)
	at org.apache.skywalking.apm.collector.boot.CollectorBootStartUp.main(CollectorBootStartUp.java:43)
`

My collector is  a standalone server, and related detailed configuration from application.yml is as follows:

`ui:
  jetty:
    host: 10.79.10.69
    port: 12800
    context_path: /

storage:
  elasticsearch:
    cluster_name: collector-db-cluster
    cluster_transport_sniffer: true
    cluster_nodes: 10.79.10.69:9200,10.79.10.68:9200
    index_shards_number: 2
    index_replicas_number: 0
    ttl: 7` 

Is the ES version too high, right?

**Comment by wu-sheng** [comment]
Hi, from the document, we only supported 5.x (https://github.com/apache/incubator-skywalking/blob/master/docs/en/Deploy-backend-in-cluster-mode.md#required-of-third-party-softwares), already mentioned. 

From my experience, 5.3 or 5.5 should be a good choice.

@peng-yongsheng I think we don't support 5.6, the document isn't right.

**Comment by weenyaimac** [comment]
Thanks. I see, and the document isn't right, it writes 'Elasticsearch 5.x'

**Comment by wu-sheng** [comment]
> Thanks. I see, and the document isn't right, it writes 'Elasticsearch 5.x'

Yes. If you have time, please send a pull request to fix this document for helping others.

**Comment by weenyaimac** [comment]
Ok, I will try my best. 
I also have another question with it. Why webapp process also quits when collector process quits?

**Comment by wu-sheng** [comment]
@weenyaimac I don't know that. They are two separated processes in OS, just start up by one script. So I didn't think there is any connection between them.

**Comment by weenyaimac** [comment]
@wu-sheng yes, I agree with your opinion because I also see the starting script. So I just wonder the reason.

**Comment by carlvine500** [comment]
5.0.0-beta work ok with 5.6.2 in production env .
