### ISSUE TITLE
Agent connecting to remote collector fails

### ISSUE THREAD

**Issue by arghya88** [apache/incubator-skywalking#1083]
Please answer these questions before submitting your issue.

- Why do you submit this issue?
- [ ] Question or discussion
- [X] Bug
- [ ] Requirement
- [ ] Feature or performance improvement

- Which version of SkyWalking, OS and JRE?

JRE 8, Skywalking 5

- What happen?

**Getting below error while connecting to standalone mode collector**

```
DEBUG 2018-04-16 14:46:20 GRPCChannelManager :  Selected collector grpc service running, reconnect:true. 
DEBUG 2018-04-16 14:46:20 GRPCChannelManager :  Selected collector grpc service is not available. Wait 30 seconds to retry 
ERROR 2018-04-16 14:46:20 DiscoveryRestServiceClient :  Find server list fail. 
org.skywalking.apm.agent.core.remote.RESTResponseStatusError: Unexpected service response code: 404
	at org.skywalking.apm.agent.core.remote.DiscoveryRestServiceClient.findServerList(DiscoveryRestServiceClient.java:83)
	at org.skywalking.apm.agent.core.remote.DiscoveryRestServiceClient.run(DiscoveryRestServiceClient.java:68)
	at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511)
	at java.util.concurrent.FutureTask.runAndReset(FutureTask.java:308)
	at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.access$301(ScheduledThreadPoolExecutor.java:180)
	at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.run(ScheduledThreadPoolExecutor.java:294)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
	at java.lang.Thread.run(Thread.java:748)
```
___
### Requirement or improvement
- Please describe about your requirements or improvement suggestions.

**Comment by wu-sheng** [comment]
Do you set the server addresses right? Please read our document and server address should be `ip:10800` by default.

**Comment by wu-sheng** [comment]
Agent uses `naming/jetty` for service discovery, and `agent_gRPC/gRPC` for real connection. From your 404, I think you didn't set the address to `naming/jetty`.

Another thing may cause this, because your collector didn't start up right. Please recheck your collector log.

**Comment by arghya88** [comment]
How to set the address to naming/jetty..
Nothing found in collector.log or webapp.log-both are empty..
Found some logs in walking-collector-server.log but no error/exception

**Comment by wu-sheng** [comment]
The `collector.servers` setting is based on this section in `application.yml`:
```
naming:
  jetty:
    host: localhost
    port: 10800
    contextPath: /
```

**Comment by wu-sheng** [comment]
No further discussion. Closing this.
