### ISSUE TITLE
NoNodeAvailableException starting collector (when connecting to Elasticsearch)

### ISSUE THREAD

**Issue by gregpierro** [apache/incubator-skywalking#1140]
Please answer these questions before submitting your issue.

- Why do you submit this issue?
- [ ] Question or discussion
- [ x] Bug
- [ ] Requirement
- [ ] Feature or performance improvement

___
### Question
- What do you want to know?

___
### Bug
- Which version of SkyWalking, OS and JRE? 
SkyWalking Alpha 5.0
Java 8
Elasticseach 6.2.4

- Which company or project?

- What happen?
I get the following in collector log and it does not start. i verified Elasticsearch transport responding on 9300

Exception in thread "main" NoNodeAvailableException[None of the configured nodes are available: [{#transport#-1}{wjscH_BPSTyxF7d_UNjW
iA}{localhost}{127.0.0.1:9300}]]
        at org.elasticsearch.client.transport.TransportClientNodesService.ensureNodesAreAvailable(TransportClientNodesService.java:34
7)
        at org.elasticsearch.client.transport.TransportClientNodesService.execute(TransportClientNodesService.java:245)
        at org.elasticsearch.client.transport.TransportProxyClient.execute(TransportProxyClient.java:59)
        at org.elasticsearch.client.transport.TransportClient.doExecute(TransportClient.java:363)
        at org.elasticsearch.client.support.AbstractClient.execute(AbstractClient.java:408)
        at org.elasticsearch.client.support.AbstractClient$IndicesAdmin.execute(AbstractClient.java:1256)
        at org.elasticsearch.action.ActionRequestBuilder.execute(ActionRequestBuilder.java:80)
        at org.elasticsearch.action.ActionRequestBuilder.execute(ActionRequestBuilder.java:54)
        at org.elasticsearch.action.ActionRequestBuilder.get(ActionRequestBuilder.java:62)
        at org.apache.skywalking.apm.collector.client.elasticsearch.ElasticSearchClient.isExistsIndex(ElasticSearchClient.java:131)
        at org.apache.skywalking.apm.collector.storage.es.base.define.ElasticSearchStorageInstaller.isExists(ElasticSearchStorageInst
aller.java:129)
        at org.apache.skywalking.apm.collector.storage.StorageInstaller.install(StorageInstaller.java:46)
        at org.apache.skywalking.apm.collector.storage.es.StorageModuleEsProvider.start(StorageModuleEsProvider.java:294)
        at org.apache.skywalking.apm.collector.core.module.BootstrapFlow.start(BootstrapFlow.java:63)
        at org.apache.skywalking.apm.collector.core.module.ModuleManager.init(ModuleManager.java:70)
        at org.apache.skywalking.apm.collector.boot.CollectorBootStartUp.main(CollectorBootStartUp.java:43)

___
### Requirement or improvement
- Please describe about your requirements or improvement suggestions.

**Comment by wu-sheng** [comment]
From your info, I found two possibilities could trigger this:
- ElasticSearch should be 5.x, recommend 5.5 or 5.3 from my test. Some one said 5.6 is OK, but I have some concern, because we are using 5.5.0 driver.
- Do you set your ElasticSearch by following this: https://github.com/apache/incubator-skywalking/blob/master/docs/en/Deploy-backend-in-standalone-mode.md#deploy-elasticsearch-server  .

**Comment by wu-sheng** [comment]
BTW, at this moment( and next few days ), master branch is preparing the beta release, the codes could be not so usable, more error expected, because we are going to do integration test for our beta UI.

**Comment by gregpierro** [comment]
I am only using the tar.gz compiled version, not building. 
Elasticsearch 5.5 fixed it! Thank you!!!
