### ISSUE TITLE
SkyWalking 5.0.0-beta  e2e test

### ISSUE THREAD

**Issue by ascrutae** [apache/incubator-skywalking#1146]

**Comment by ascrutae** [comment]
# Report @ 2018/05/03
the prefix description of Issue:

|prefix|description|
|:---|:---|
|**[AGENT]** | This prefix represent that this issue is an agent issue|
|**[COLLECTOR]**| This prefix represent that this issue is a collector issue|
|**[UI]**| This prefix represent that this issue is an UI issue|
|**[UNKNOWN]**| This prefix represent that everyone should pay attention to this issue|
|**[APP_STANDBY]**| This prefix represent that this issue happened after server started|
|**[APP_SERVICE_PROVIDED]**|This prefix represent that this issue happened after call service|

## Issue
### Topology
* **[COLLECTOR]**  The `Application Alarm` count is incorrect

Screen snapshot:

<img width="366" alt="topology" src="https://user-images.githubusercontent.com/12436447/39561792-8d057d28-4eda-11e8-8630-8267d3d3602f.png">

request url:
```
http://localhost:8080/api/topology
```

request paramter:
```
{"variables":{"duration":{"start":"2018-05-02 13","end":"2018-05-03 13","step":"HOUR"}},"query":"\n    query Topology($duration: Duration!) {\n      getClusterTopology(duration: $duration) {\n        nodes {\n          id\n          name\n          type\n          ... on ApplicationNode {\n            sla\n            cpm\n            avgResponseTime\n            apdex\n            isAlarm\n            numOfServer\n            numOfServerAlarm\n            numOfServiceAlarm\n          }\n        }\n        calls {\n          source\n          target\n          isAlert\n          callType\n          cpm\n          avgResponseTime\n        }\n      }\n    }\n  "}
```

response body:
```
{"data":{"getClusterTopology":{"nodes":[{"id":"-1","name":"persistence-service","type":"Dubbo","sla":100,"cpm":0,"avgResponseTime":1772,"apdex":100,"isAlarm":false,"numOfServer":1,"numOfServerAlarm":0,"numOfServiceAlarm":0},{"id":"2","name":"cache-service","type":"Motan","sla":100,"cpm":0,"avgResponseTime":323,"apdex":100,"isAlarm":false,"numOfServer":1,"numOfServerAlarm":0,"numOfServiceAlarm":0},{"id":"3","name":"portal-service","type":"SpringMVC","sla":100,"cpm":0,"avgResponseTime":4947,"apdex":0,"isAlarm":false,"numOfServer":1,"numOfServerAlarm":0,"numOfServiceAlarm":0},{"id":"-5","name":"localhost:27017","type":"MongoDB"},{"id":"-3","name":"127.0.0.1:6379","type":"Redis"},{"id":"-2","name":"localhost:-1","type":"H2"},{"id":"4","name":"127.0.0.1:3307","type":"Mysql"},{"id":"1","name":"User","type":"USER"}],"calls":[{"source":"2","target":"-5","isAlert":false,"callType":"MongoDB","cpm":0,"avgResponseTime":60},{"source":"2","target":"-3","isAlert":false,"callType":"Redis","cpm":0,"avgResponseTime":1},{"source":"2","target":"-2","isAlert":false,"callType":"H2","cpm":0,"avgResponseTime":1},{"source":"3","target":"2","isAlert":false,"callType":"Motan","cpm":0,"avgResponseTime":390},{"source":"3","target":"-1","isAlert":false,"callType":"Dubbo","cpm":0,"avgResponseTime":3046},{"source":"-1","target":"4","isAlert":false,"callType":"Mysql","cpm":0,"avgResponseTime":3},{"source":"1","target":"3","isAlert":false,"callType":"","cpm":0,"avgResponseTime":4947}]}}}
```
Notice Request url:
```
http://localhost:8080/api/notice
```

request parameter:
```
{"query":"\n  query Notice($duration:Duration!){\n    applicationAlarmList: loadAlarmList(alarmType: APPLICATION, duration: $duration, paging: { pageNum: 1, pageSize: 5, needTotal: true }) {\n      items {\n        title\n        startTime\n        causeType\n      }\n      total\n    }\n    serverAlarmList: loadAlarmList(alarmType: SERVER, duration: $duration, paging: { pageNum: 1, pageSize: 5, needTotal: true }) {\n      items {\n        title\n        startTime\n        causeType\n      }\n      total\n    }\n  }\n","variables":{"duration":{"start":"2018-05-02 13","end":"2018-05-03 13","step":"HOUR"}}}
```
response body:

```
{"data":{"applicationAlarmList":{"items":[{"title":"Application portal-service response time alarm.","startTime":"2018-05-03 13:22","causeType":"SLOW_RESPONSE"},{"title":"Application 192.168.5.38:20880 response time alarm.","startTime":"2018-05-03 13:22","causeType":"SLOW_RESPONSE"}],"total":2},"serverAlarmList":{"items":[{"title":"Server ascrutae of Application portal-service response time alarm.","startTime":"2018-05-03 13:22","causeType":"SLOW_RESPONSE"}],"total":1}}}
```
 
### Server
*  **[AGENT]** The `GC` value is incorrect

Screen snapshot:
<img width="1065" alt="server" src="https://user-images.githubusercontent.com/12436447/39561855-f9203dcc-4eda-11e8-8096-a6579281de24.png">

Request URL:
```
http://localhost:8080/api/server
```

request parameter:
```
{"variables":{"duration":{"start":"2018-05-03 1317","end":"2018-05-03 1332","step":"MINUTE"},"serverId":"2"},"query":"\nquery Application($serverId: ID!, $duration: Duration!) {\n  getServerResponseTimeTrend(serverId: $serverId, duration: $duration) {\n    trendList\n  }\n  getServerThroughputTrend(serverId: $serverId, duration: $duration) {\n    trendList\n  }\n  getCPUTrend(serverId: $serverId, duration: $duration) {\n    cost\n  }\n  getGCTrend(serverId: $serverId, duration: $duration) {\n    youngGCCount\n    oldGCount\n    youngGCTime\n    oldGCTime\n  }\n  getMemoryTrend(serverId: $serverId, duration: $duration) {\n    heap\n    maxHeap\n    noheap\n    maxNoheap\n  }\n}\n"}
```

response body:
```
{"data":{"getServerResponseTimeTrend":{"trendList":[0,0,0,0,0,1772,0,0,0,0,0,0,0,0,0,0]},"getServerThroughputTrend":{"trendList":[0,0,0,0,0,2,0,0,0,0,0,0,0,0,0,0]},"getCPUTrend":{"cost":[0,0,6,0,0,0,0,0,0,0,0,0,0,0,0,0]},"getGCTrend":{"youngGCCount":[0,0,14,14,14,14,16,16,16,16,16,16,16,16,16,16],"oldGCount":[0,0,-14,-14,-14,-14,-16,-16,-16,-16,-16,-16,-16,-16,-16,-16],"youngGCTime":[0,0,4,-16,-16,-9,9,9,9,9,9,9,9,9,9,9],"oldGCTime":[0,0,16,16,16,9,-9,-9,-9,-9,-9,-9,-9,-9,-9,-9]},"getMemoryTrend":{"heap":[0,0,166238547,171449144,175401897,190184972,234289253,239443707,242472644,244873871,247501716,250321448,252839238,255130268,257479694,259835858],"maxHeap":[0,0,545409316,63631086,63631086,63631086,63631086,63631086,63631086,63631086,63631086,63631086,63631086,63631086,63631086,141402415],"noheap":[0,0,62165760,62366768,62889268,66356143,75470034,75332149,75692865,75985991,76410386,76940723,77078423,77324614,77285820,77353330],"maxNoheap":[0,0,62165760,62366768,62889268,66356143,75470034,75332149,75692865,75985991,76410386,76940723,77078423,77324614,77285820,77353330]}}}
```

### Application
* **[COLLECTOR]** **[UI]** The `server` value is incorrect

Screen snapshot:
<img width="1417" alt="application" src="https://user-images.githubusercontent.com/12436447/39561938-809636f8-4edb-11e8-980c-e070de8133cb.png">

request url:
```
http://localhost:8080/api/application
```

request paramter:
```
{"variables":{"duration":{"start":"2018-05-03 1311","end":"2018-05-03 1326","step":"MINUTE"},"applicationId":"2"},"query":"\n  query Application($applicationId: ID!, $duration: Duration!) {\n    getSlowService(applicationId: $applicationId, duration: $duration, topN: 10) {\n      key: id\n      label: name\n      value: avgResponseTime\n    }\n    getServerThroughput(applicationId: $applicationId, duration: $duration, topN: 999999) {\n      key: id\n      osName\n      host\n      pid\n      ipv4\n      value: cpm\n    }\n    getApplicationTopology(applicationId: $applicationId, duration: $duration) {\n      nodes {\n        id\n        name\n        type\n        ... on ApplicationNode {\n          sla\n          cpm\n          avgResponseTime\n          apdex\n          isAlarm\n          numOfServer\n          numOfServerAlarm\n          numOfServiceAlarm\n        }\n      }\n      calls {\n        source\n        target\n        isAlert\n        callType\n        cpm\n        avgResponseTime\n      }\n    }\n  }\n"}
```

response body:

```
{"data":{"getSlowService":[{"key":"-7","label":"com.a.eye.skywalking.test.cache.CacheService.updateCache(java.lang.String,java.lang.String)","value":550},{"key":"-3","label":"com.a.eye.skywalking.test.cache.CacheService.findCache(java.lang.String)","value":0}],"getServerThroughput":[{"key":"3","osName":"Mac OS X","host":"ascrutae","pid":13452,"ipv4":["192.168.5.38"],"value":0}],"getApplicationTopology":{"nodes":[{"id":"2","name":"cache-service","type":"Motan","sla":100,"cpm":0,"avgResponseTime":323,"apdex":100,"isAlarm":true,"numOfServer":1,"numOfServerAlarm":1,"numOfServiceAlarm":2},{"id":"3","name":"portal-service","type":"SpringMVC","sla":100,"cpm":0,"avgResponseTime":4947,"apdex":0,"isAlarm":true,"numOfServer":1,"numOfServerAlarm":1,"numOfServiceAlarm":2},{"id":"-2","name":"localhost:-1","type":"H2"},{"id":"-5","name":"localhost:27017","type":"MongoDB"},{"id":"-3","name":"127.0.0.1:6379","type":"Redis"}],"calls":[{"source":"2","target":"-2","isAlert":false,"callType":"H2","cpm":1,"avgResponseTime":1},{"source":"2","target":"-5","isAlert":false,"callType":"MongoDB","cpm":0,"avgResponseTime":60},{"source":"2","target":"-3","isAlert":false,"callType":"Redis","cpm":0,"avgResponseTime":1},{"source":"3","target":"2","isAlert":false,"callType":"Motan","cpm":0,"avgResponseTime":390}]}}}
```

**Comment by wu-sheng** [comment]
FYI @liuhaoyang @candyleer we have started the test for beta release. Welcome to join me. @ascrutae has reported some issues,

**Comment by wu-sheng** [comment]
@peng-yongsheng @hanahmily @ascrutae `Topology` issue is caused by a complex scenario: didn't use mapping to transform alarm. I will talk with @hanahmily and @peng-yongsheng about new design to this sub page.

**Comment by candyleer** [comment]
got it

**Comment by liuhaoyang** [comment]
# Report @ 2018/05/03
## Issue
### Topology
* **[UI]**  The `Alarm` link is invalid. Click the `Alarm` icon will redirect to the 404 page
Screen snapshot:
![image](https://user-images.githubusercontent.com/10701915/39566757-353525a2-4eef-11e8-8b08-9f007f24e89f.png)

## Solution
https://github.com/apache/incubator-skywalking-ui/pull/166

**Comment by hanahmily** [comment]
Fix UI issues in https://github.com/apache/incubator-skywalking/pull/1155

**Comment by wu-sheng** [comment]
@ascrutae @liuhaoyang  All known and reported issues have been declared **fixed**. Please run the test. 

FYI @peng-yongsheng has one or two features to be done.

**Comment by candyleer** [comment]
![image](https://user-images.githubusercontent.com/11530760/39580819-a1658ce4-4f1c-11e8-9a59-041af09f78f9.png)

in dashboard ,when i turn `15 minutes` to `30 minutes`

**Comment by candyleer** [comment]
## Report @ 2018/05/03
* [Collector]
![image](https://user-images.githubusercontent.com/11530760/39581737-d628cdd6-4f1e-11e8-8a10-60a6f39a2bc2.png)
0 maybe not correct

**Comment by liuhaoyang** [comment]
#Report @ 2018/05/03
### Issue
### Topology
When a component icon is not added to [skywalking-ui/public/img/node](https://github.com/apache/incubator-skywalking-ui/tree/master/public/img/node), the component is shown as blank in the topology page. Whether this should show a default icon instead of blank?
Screen snapshot:
![image](https://user-images.githubusercontent.com/10701915/39585311-12450dfe-4f27-11e8-9a4c-9c091db7aca6.png)

**Comment by wu-sheng** [comment]
@hanahmily Maybe you should take care this, I remember I mentioned this, before.

**Comment by candyleer** [comment]
## Report @2018/05/04
### Issue
* [Collector] Block Error
```
java.lang.ClassCastException: org.apache.skywalking.apm.collector.analysis.metric.provider.worker.application.component.ApplicationComponentSpanListener cannot be cast to org.apache.skywalking.apm.collector.analysis.segment.parser.define.listener.FirstSpanListener
	at org.apache.skywalking.apm.collector.analysis.segment.parser.provider.parser.SegmentParse.lambda$notifyFirstListener$3(SegmentParse.java:223) ~[classes/:?]
	at java.lang.Iterable.forEach(Iterable.java:75) ~[?:1.8.0_144]
	at org.apache.skywalking.apm.collector.analysis.segment.parser.provider.parser.SegmentParse.notifyFirstListener(SegmentParse.java:221) ~[classes/:?]
	at org.apache.skywalking.apm.collector.analysis.segment.parser.provider.parser.SegmentParse.preBuild(SegmentParse.java:151) ~[classes/:?]
	at org.apache.skywalking.apm.collector.analysis.segment.parser.provider.parser.SegmentParse.parse(SegmentParse.java:68) ~[classes/:?]
	at org.apache.skywalking.apm.collector.analysis.segment.parser.provider.buffer.SegmentBufferReader.read(SegmentBufferReader.java:134) ~[classes/:?]
	at org.apache.skywalking.apm.collector.analysis.segment.parser.provider.buffer.SegmentBufferReader.preRead(SegmentBufferReader.java:70) ~[classes/:?]
	at org.apache.skywalking.apm.util.RunnableWithExceptionProtection.run(RunnableWithExceptionProtection.java:36) [classes/:?]
	at java.util.concurrent.Executors$RunnableAdapter.call$$$capture(Executors.java:511) [?:1.8.0_144]
	at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java) [?:1.8.0_144]
	at java.util.concurrent.FutureTask.runAndReset(FutureTask.java:308) [?:1.8.0_144]
	at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.access$301(ScheduledThreadPoolExecutor.java:180) [?:1.8.0_144]
	at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.run(ScheduledThreadPoolExecutor.java:294) [?:1.8.0_144]
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149) [?:1.8.0_144]
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624) [?:1.8.0_144]
	at java.lang.Thread.run(Thread.java:748) [?:1.8.0_144]
2018-05-04 12:32:19,066 - org.apache.skywalking.apm.collector.analysis.segment.parser.provider.buffer.SegmentBufferReader -1248569 [pool-4-thread-1] ERROR [] - Segment buffer pre read failure.
java.lang.ClassCastException: org.apache.skywalking.apm.collector.analysis.metric.provider.worker.application.component.ApplicationComponentSpanListener cannot be cast to org.apache.skywalking.apm.collector.analysis.segment.parser.define.listener.FirstSpanListener
	at org.apache.skywalking.apm.collector.analysis.segment.parser.provider.parser.SegmentParse.lambda$notifyFirstListener$3(SegmentParse.java:223) ~[classes/:?]
	at java.lang.Iterable.forEach(Iterable.java:75) ~[?:1.8.0_144]
	at org.apache.skywalking.apm.collector.analysis.segment.parser.provider.parser.SegmentParse.notifyFirstListener(SegmentParse.java:221) ~[classes/:?]
	at org.apache.skywalking.apm.collector.analysis.segment.parser.provider.parser.SegmentParse.preBuild(SegmentParse.java:151) ~[classes/:?]
	at org.apache.skywalking.apm.collector.analysis.segment.parser.provider.parser.SegmentParse.parse(SegmentParse.java:68) ~[classes/:?]
	at org.apache.skywalking.apm.collector.analysis.segment.parser.provider.buffer.SegmentBufferReader.read(SegmentBufferReader.java:134) ~[classes/:?]
	at org.apache.skywalking.apm.collector.analysis.segment.parser.provider.buffer.SegmentBufferReader.preRead(SegmentBufferReader.java:70) ~[classes/:?]
	at org.apache.skywalking.apm.util.RunnableWithExceptionProtection.run(RunnableWithExceptionProtection.java:36) [classes/:?]
	at java.util.concurrent.Executors$RunnableAdapter.call$$$capture(Executors.java:511) [?:1.8.0_144]
	at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java) [?:1.8.0_144]
	at java.util.concurrent.FutureTask.runAndReset(FutureTask.java:308) [?:1.8.0_144]
	at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.access$301(ScheduledThreadPoolExecutor.java:180) [?:1.8.0_144]
	at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.run(ScheduledThreadPoolExecutor.java:294) [?:1.8.0_144]
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149) [?:1.8.0_144]
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624) [?:1.8.0_144]
	at java.lang.Thread.run(Thread.java:748) [?:1.8.0_144]
```

**Comment by wu-sheng** [comment]
@candyleer your blocking should be removed by now.

**Comment by wu-sheng** [comment]
@liuhaoyang #1165 should fix your server type issue, but need your test case to recheck.

**Comment by ascrutae** [comment]
# Report @ 2018/05/04

## Issue

### Topology

* **[COLLECTOR]** the server alarm value is incorrect. Except is 1, but it was 2

screensnapshot

<img width="383" alt="topology-server" src="https://user-images.githubusercontent.com/12436447/39622549-416efdf8-4fc5-11e8-92b0-b557c8411ed4.png">

Request URL: `http://localhost:8080/api/topology`

Request param:
```
{"variables":{"duration":{"start":"2018-05-04 1713","end":"2018-05-04 1728","step":"MINUTE"}},"query":"\n    query Topology($duration: Duration!) {\n      getClusterTopology(duration: $duration) {\n        nodes {\n          id\n          name\n          type\n          ... on ApplicationNode {\n            sla\n            cpm\n            avgResponseTime\n            apdex\n            isAlarm\n            numOfServer\n            numOfServerAlarm\n            numOfServiceAlarm\n          }\n        }\n        calls {\n          source\n          target\n          isAlert\n          callType\n          cpm\n          avgResponseTime\n        }\n      }\n    }\n  "}
```

Response Data:
```
{"data":{"getClusterTopology":{"nodes":[{"id":"-2","name":"portal-service","type":"Tomcat","sla":99,"cpm":150,"avgResponseTime":3514,"apdex":88,"isAlarm":true,"numOfServer":1,"numOfServerAlarm":2,"numOfServiceAlarm":5},{"id":"-1","name":"persistence-service","type":"Dubbo","sla":100,"cpm":147,"avgResponseTime":1,"apdex":100,"isAlarm":true,"numOfServer":1,"numOfServerAlarm":2,"numOfServiceAlarm":5},{"id":"2","name":"cache-service","type":"Motan","sla":100,"cpm":299,"avgResponseTime":556,"apdex":98,"isAlarm":true,"numOfServer":1,"numOfServerAlarm":2,"numOfServiceAlarm":5},{"id":"-5","name":"localhost:27017","type":"MongoDB"},{"id":"-3","name":"127.0.0.1:6379","type":"Redis"},{"id":"3","name":"localhost:-1","type":"H2"},{"id":"4","name":"127.0.0.1:3307","type":"Mysql"},{"id":"1","name":"User","type":"USER"}],"calls":[{"source":"2","target":"-5","isAlert":false,"callType":"MongoDB","cpm":296,"avgResponseTime":117},{"source":"2","target":"-3","isAlert":false,"callType":"Redis","cpm":298,"avgResponseTime":1},{"source":"2","target":"3","isAlert":false,"callType":"H2","cpm":597,"avgResponseTime":0},{"source":"-2","target":"2","isAlert":false,"callType":"Motan","cpm":300,"avgResponseTime":550},{"source":"-2","target":"-1","isAlert":false,"callType":"Dubbo","cpm":150,"avgResponseTime":257},{"source":"-1","target":"4","isAlert":false,"callType":"Mysql","cpm":295,"avgResponseTime":0},{"source":"1","target":"-2","isAlert":false,"callType":"","cpm":149,"avgResponseTime":3511}]}}}
```


request URL: `http://localhost:8080/api/notice`

request param:
```
{"query":"\n  query Notice($duration:Duration!){\n    applicationAlarmList: loadAlarmList(alarmType: APPLICATION, duration: $duration, paging: { pageNum: 1, pageSize: 5, needTotal: true }) {\n      items {\n        title\n        startTime\n        causeType\n      }\n      total\n    }\n    serverAlarmList: loadAlarmList(alarmType: SERVER, duration: $duration, paging: { pageNum: 1, pageSize: 5, needTotal: true }) {\n      items {\n        title\n        startTime\n        causeType\n      }\n      total\n    }\n  }\n","variables":{"duration":{"start":"2018-05-04 1713","end":"2018-05-04 1728","step":"MINUTE"}}}
```

Response body:
```
{"data":{"applicationAlarmList":{"items":[{"title":"Application cache-service response time alarm.","startTime":"2018-05-04 17:21","causeType":"SLOW_RESPONSE"},{"title":"Application cache-service response time alarm.","startTime":"2018-05-04 17:21","causeType":"SLOW_RESPONSE"},{"title":"Application portal-service response time alarm.","startTime":"2018-05-04 17:23","causeType":"SLOW_RESPONSE"}],"total":3},"serverAlarmList":{"items":[{"title":"Server ascrutae of Application cache-service response time alarm.","startTime":"2018-05-04 17:21","causeType":"SLOW_RESPONSE"},{"title":"Server ascrutae of Application portal-service response time alarm.","startTime":"2018-05-04 17:23","causeType":"SLOW_RESPONSE"}],"total":2}}}
```

**Comment by wu-sheng** [comment]
@ascrutae @liuhaoyang @candyleer  Maybe we should run second round test again. 

@ascrutae If your local test is OK, please consider to deploy this into demo env for us to do design review.

**Comment by ascrutae** [comment]
@candyleer  @liuhaoyang  The 5.0.0-beta tested and we are going to send the vote mail about 5.0-beta release next week. I will close this issue. Please open a new issue if anybody has any issue.

**Comment by wu-sheng** [comment]
Thanks everyone. Before and during release vote, feel free to open question. Especially for @liuhaoyang about .NET CORE related features. Native release supported is very important.

The PMC will consider the issue, whether it blocks the end user.
