### ISSUE TITLE
Field named mi in application_alarm_list_month index not found

### ISSUE THREAD

**Issue by Anarchists** [apache/incubator-skywalking#1150]
start collectorService.bat following this error.
elasticsearch : 5.6.8
```
2018-05-03 15:40:36,107 - org.apache.skywalking.apm.collector.boot.CollectorBootStartUp -4026 [main] ERROR [] - Field named mi in application_alarm_list_month index not found.
org.apache.skywalking.apm.collector.core.module.ModuleStartException: Field named mi in application_alarm_list_month index not found.
	at org.apache.skywalking.apm.collector.storage.es.StorageModuleEsProvider.start(StorageModuleEsProvider.java:300) ~[collector-storage-es-provider-5.0.0-beta-SNAPSHOT.jar:5.0.0-beta-SNAPSHOT]
	at org.apache.skywalking.apm.collector.core.module.BootstrapFlow.start(BootstrapFlow.java:61) ~[apm-collector-core-5.0.0-beta-SNAPSHOT.jar:5.0.0-beta-SNAPSHOT]
	at org.apache.skywalking.apm.collector.core.module.ModuleManager.init(ModuleManager.java:68) ~[apm-collector-core-5.0.0-beta-SNAPSHOT.jar:5.0.0-beta-SNAPSHOT]
	at org.apache.skywalking.apm.collector.boot.CollectorBootStartUp.main(CollectorBootStartUp.java:45) [apm-collector-boot-5.0.0-beta-SNAPSHOT.jar:5.0.0-beta-SNAPSHOT]
Caused by: org.apache.skywalking.apm.collector.storage.StorageInstallException: Field named mi in application_alarm_list_month index not found.
	at org.apache.skywalking.apm.collector.storage.es.base.define.ElasticSearchStorageInstaller.columnCheck(ElasticSearchStorageInstaller.java:72) ~[collector-storage-es-provider-5.0.0-beta-SNAPSHOT.jar:5.0.0-beta-SNAPSHOT]
	at org.apache.skywalking.apm.collector.storage.StorageInstaller.install(StorageInstaller.java:60) ~[collector-storage-define-5.0.0-beta-SNAPSHOT.jar:5.0.0-beta-SNAPSHOT]
	at org.apache.skywalking.apm.collector.storage.es.StorageModuleEsProvider.start(StorageModuleEsProvider.java:298) ~[collector-storage-es-provider-5.0.0-beta-SNAPSHOT.jar:5.0.0-beta-SNAPSHOT]
	... 3 more
```

**Comment by wu-sheng** [comment]
Do you upgrade the collector, but using the old es?

**Comment by Anarchists** [comment]
the collector is the latest version

**Comment by wu-sheng** [comment]
> the collector is the latest version

Which do you mean latest version? Short column name only exists in dev version, which is not released.

**Comment by wu-sheng** [comment]
And we have just started the e2e test. https://github.com/apache/incubator-skywalking/issues/1146 but didn't find your problem, So, I assume you are using the dev branch, but having some env issue.

**Comment by Anarchists** [comment]
I am using the master branch

**Comment by Anarchists** [comment]
I pull the latest code in master branch and built it in the idea

**Comment by wu-sheng** [comment]
I didn't find any problem from the codes. The best way to resolve this is, try to find out which columns exist in `application_alarm_list_month` type of your own ES. This is very easy to check.

**Comment by Anarchists** [comment]
ok,thanks,i will check

**Comment by Anarchists** [comment]
I upgrade the version of elasticsearch,it works, thanks.

**Comment by wu-sheng** [comment]
In doc, it said, 5.x

**Comment by dinggel** [comment]
my elasticsearch is elasticsearch-5.6.6

**Comment by wu-sheng** [comment]
The issue is caused by dirty data. Clear your es when you upgrade.

**Comment by shipengyan** [comment]
@wu-sheng how to avoid this dirty data? I donot produce data, all data are collected by skywalking-collector

**Comment by wu-sheng** [comment]
@shipengyan This error means, for example, you used to use SkyWalking alpha, then use the same es in beta/beta2.

**Comment by zouy1222** [comment]
my elasticsearch is elasticsearch-5.6.8。Many people encounter this problem.
by'Field named mi in application_alarm_list_month index not found'

**Comment by wu-sheng** [comment]
This is not an issue. This is because they upgrade the version. Please read the comments.

**Comment by zouy1222** [comment]
@wu-sheng    Hi,The es version is 5.6.8, and the skywalking version is 5.0GA. How to solve this problem, is it upgrading es or skywalking?
