### ISSUE TITLE
Exception while executing runnable 

### ISSUE THREAD

**Issue by liliang8858** [apache/incubator-skywalking#1226]
- Why do you submit this issue?
- [0] Question or discussion
- [ ] Bug
- [ ] Requirement
- [ ] Feature or performance improvement

___
### Question
- What do you want to know?
Exception while executing runnable 
___
### Bug
- Which version of SkyWalking, OS and JRE?
5.0.0
- Which company or project?
collector

- What happen?
spring boot - > 11800 
SEVERE: Exception while executing runnable io.grpc.internal.ServerImpl$JumpToApplicationThreadServerStreamListener$1HalfClosed@1667dc5
java.lang.NullPointerException
        at org.apache.skywalking.apm.collector.storage.es.dao.cache.ApplicationEsCacheDAO.getApplicationIdByCode(ApplicationEsCacheDAO.java:66)
        at org.apache.skywalking.apm.collector.cache.caffeine.service.ApplicationCacheCaffeineService.getApplicationIdByCode(ApplicationCacheCaffeineService.java:69)
        at org.apache.skywalking.apm.collector.analysis.register.provider.service.ApplicationIDService.getOrCreateForApplicationCode(ApplicationIDService.java:71)
        at org.apache.skywalking.apm.collector.agent.grpc.provider.handler.ApplicationRegisterServiceHandler.applicationCodeRegister(ApplicationRegisterServiceHandler.java:52)
        at org.apache.skywalking.apm.network.proto.ApplicationRegisterServiceGrpc$MethodHandlers.invoke(ApplicationRegisterServiceGrpc.java:225)
        at io.grpc.stub.ServerCalls$UnaryServerCallHandler$UnaryServerCallListener.onHalfClose(ServerCalls.java:171)
        at io.grpc.internal.ServerCallImpl$ServerStreamListenerImpl.halfClosed(ServerCallImpl.java:272)
        at io.grpc.internal.ServerImpl$JumpToApplicationThreadServerStreamListener$1HalfClosed.runInContext(ServerImpl.java:653)
        at io.grpc.internal.ContextRunnable.run(ContextRunnable.java:37)
        at io.grpc.internal.SerializingExecutor.run(SerializingExecutor.java:123)
        at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
        at java.lang.Thread.run(Thread.java:748)

spring boot + dubbo + zookeeper   
skywalking

**Comment by liliang8858** [comment]
There is no GRPC   
Must the GRPC be started?

**Comment by liliang8858** [comment]
It's my own problem. I upgraded es to 6.2.3 API call error, sorry.
