### ISSUE TITLE
io.grpc.internal.SerializingExecutor run

### ISSUE THREAD

**Issue by Rainbowboys** [apache/incubator-skywalking#1230]
Please answer these questions before submitting your issue.

- Why do you submit this issue?
- [ ] Question or discussion
- [x] Bug
- [ ] Requirement
- [ ] Feature or performance improvement

### desc
   - When I use version Beta, I'd like to use Opentrace to record log manually. But problems raised which didn't occur in version Alpha.

```
May 15, 2018 5:52:02 PM io.grpc.internal.SerializingExecutor run
SEVERE: Exception while executing runnable io.grpc.internal.ServerImpl$JumpToApplicationThreadServerStreamListener$1MessagesAvailable@2e92dd86
java.lang.NullPointerException
	at org.apache.skywalking.apm.collector.configuration.service.ComponentLibraryCatalogService.getComponentId(ComponentLibraryCatalogService.java:50)
	at org.apache.skywalking.apm.collector.analysis.segment.parser.provider.parser.standardization.SpanIdExchanger.exchange(SpanIdExchanger.java:62)
	at org.apache.skywalking.apm.collector.analysis.segment.parser.provider.parser.SegmentParse.preBuild(SegmentParse.java:116)
	at org.apache.skywalking.apm.collector.analysis.segment.parser.provider.parser.SegmentParse.parse(SegmentParse.java:68)
	at org.apache.skywalking.apm.collector.analysis.segment.parser.provider.service.SegmentParseService.parse(SegmentParseService.java:42)
	at org.apache.skywalking.apm.collector.agent.grpc.provider.handler.TraceSegmentServiceHandler$1.onNext(TraceSegmentServiceHandler.java:48)
	at org.apache.skywalking.apm.collector.agent.grpc.provider.handler.TraceSegmentServiceHandler$1.onNext(TraceSegmentServiceHandler.java:45)
	at io.grpc.stub.ServerCalls$StreamingServerCallHandler$StreamingServerCallListener.onMessage(ServerCalls.java:248)
	at io.grpc.internal.ServerCallImpl$ServerStreamListenerImpl.messagesAvailable(ServerCallImpl.java:252)
	at io.grpc.internal.ServerImpl$JumpToApplicationThreadServerStreamListener$1MessagesAvailable.runInContext(ServerImpl.java:629)
	at io.grpc.internal.ContextRunnable.run(ContextRunnable.java:37)
	at io.grpc.internal.SerializingExecutor.run(SerializingExecutor.java:123)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617)
	at java.lang.Thread.run(Thread.java:748)
```

**Comment by Rainbowboys** [comment]
no  in pro ,try cluster and single

**Comment by ascrutae** [comment]
The issue cause by you had tag a custom component and the collector can't find it. [This document](https://github.com/apache/incubator-skywalking/blob/master/docs/en/Component-libraries-extend.md) may help you to define a custom component.

**Comment by Rainbowboys** [comment]
ok thanks so much ，already deal it

**Comment by lei911gang** [comment]
i have the same problem, but the document is not found ,how did you deal it ? very thanks

**Comment by lei911gang** [comment]
@Rainbowboys

**Comment by piaoluoxiaobai** [comment]
i also have the problem

**Comment by piaoluoxiaobai** [comment]
@ascrutae  Can you provide a new document address? thanks
