### ISSUE TITLE
bug:5.0.0-beta:The project contains hystrix1.5.12 and rxjava-1.2.0 packages,

### ISSUE THREAD

**Issue by wfs0902** [apache/incubator-skywalking#1235]
Please answer these questions before submitting your issue.

- Why do you submit this issue?
- [x] Question or discussion
- [x] Bug
- [ ] Requirement
- [ ] Feature or performance improvement

___
### Question
- What do you want to know?
发生调用异常
![image](https://user-images.githubusercontent.com/30229523/40160994-fa076a32-59e1-11e8-8521-dfd940c34631.png)

转发过程Hystrix发生意料外异常.
java.lang.NullPointerException
	at org.apache.skywalking.apm.agent.core.context.ContextManager.capture(ContextManager.java:150)
	at org.apache.skywalking.apm.plugin.hystrix.v1.SWExecutionHookWrapper.onStart(SWExecutionHookWrapper.java:169)
	at com.netflix.hystrix.AbstractCommand$ExecutionHookDeprecationWrapper.onStart(AbstractCommand.java:2125)
	at com.netflix.hystrix.AbstractCommand$ExecutionHookDeprecationWrapper.onStart(AbstractCommand.java:2132)
	at com.netflix.hystrix.AbstractCommand.applyHystrixSemantics(AbstractCommand.java:520)
	at com.netflix.hystrix.AbstractCommand.access$200(AbstractCommand.java:60)
	at com.netflix.hystrix.AbstractCommand$4.call(AbstractCommand.java:419)
	at com.netflix.hystrix.AbstractCommand$4.call(AbstractCommand.java:413)
	at rx.internal.operators.OnSubscribeDefer.call(OnSubscribeDefer.java:46)
	at rx.internal.operators.OnSubscribeDefer.call(OnSubscribeDefer.java:35)
	at rx.Observable.unsafeSubscribe(Observable.java:10151)
	at rx.internal.operators.OnSubscribeMap.call(OnSubscribeMap.java:48)
	at rx.internal.operators.OnSubscribeMap.call(OnSubscribeMap.java:33)
	at rx.Observable.unsafeSubscribe(Observable.java:10151)
	at rx.internal.operators.OnSubscribeDoOnEach.call(OnSubscribeDoOnEach.java:41)
	at rx.internal.operators.OnSubscribeDoOnEach.call(OnSubscribeDoOnEach.java:30)
	at rx.internal.operators.OnSubscribeLift.call(OnSubscribeLift.java:48)
	at rx.internal.operators.OnSubscribeLift.call(OnSubscribeLift.java:30)
	at rx.Observable.unsafeSubscribe(Observable.java:10151)
	at rx.internal.operators.OnSubscribeDoOnEach.call(OnSubscribeDoOnEach.java:41)
	at rx.internal.operators.OnSubscribeDoOnEach.call(OnSubscribeDoOnEach.java:30)
	at rx.Observable.unsafeSubscribe(Observable.java:10151)
	at rx.internal.operators.OnSubscribeDefer.call(OnSubscribeDefer.java:51)
	at rx.internal.operators.OnSubscribeDefer.call(OnSubscribeDefer.java:35)
___
### Bug
- Which version of SkyWalking, OS and JRE?

- Which company or project?

- What happen?
If possible, provide a way for reproducing the error. e.g. demo application, component version.

___
### Requirement or improvement
- Please describe about your requirements or improvement suggestions.

**Comment by wu-sheng** [comment]
@ascrutae Look like an across thread situation.
