### ISSUE TITLE
bug:5.0.0-beta:The project contains hystrix1.5.12 and rxjava-1.2.0 packages

### ISSUE THREAD

**Issue by wfs0902** [apache/incubator-skywalking#1236]
Please answer these questions before submitting your issue.

- Why do you submit this issue?
- [x] Question or discussion
- [x] Bug
- [ ] Requirement
- [ ] Feature or performance improvement

___
### Question
- What do you want to know?
![image](https://user-images.githubusercontent.com/30229523/40161223-a445ce94-59e2-11e8-840a-90d6fb1618d4.png)
[2018-05-17 14:40:10,890] [pushlog] [ERROR] - 登录请求转发过程Hystrix发生意料外异常. longMode[true], serverName[终端通讯框架服务-long], port[8888],session is [19], e is [null], request is [RemotingCommand [type=1, header=Header [code=0, rpc=0, serial=1B4E06FSP4MMGU00A1BC0001402BSRM9, itype=gtsa01, version=2, add=99996552262D, ctime=20161220193451, result=, msg=], body=null, baseinfo={"header":{"rpc":0,"code":0,"add":"99996552262D","serial":"1B4E06FSP4MMGU00A1BC0001402BSRM9","ctime":"20161220193451","version":2,"itype":"gtsa01"}}F66D5885C4FC0FF985398DB677A68F65, baseInfoNoSign={"header":{"rpc":0,"code":0,"add":"99996552262D","serial":"1B4E06FSP4MMGU00A1BC0001402BSRM9","ctime":"20161220193451","version":2,"itype":"gtsa01"}}, sign=F66D5885C4FC0FF985398DB677A68F65, binary.size=0]]
java.lang.NullPointerException
	at org.apache.skywalking.apm.agent.core.context.ContextManager.capture(ContextManager.java:150)
	at org.apache.skywalking.apm.plugin.hystrix.v1.SWExecutionHookWrapper.onStart(SWExecutionHookWrapper.java:169)
	at com.netflix.hystrix.AbstractCommand$ExecutionHookDeprecationWrapper.onStart(AbstractCommand.java:2125)
	at com.netflix.hystrix.AbstractCommand$ExecutionHookDeprecationWrapper.onStart(AbstractCommand.java:2132)
	at com.netflix.hystrix.AbstractCommand.applyHystrixSemantics(AbstractCommand.java:520)
	at com.netflix.hystrix.AbstractCommand.access$200(AbstractCommand.java:60)
___
### Bug
- Which version of SkyWalking, OS and JRE?
JRE1.7 skywalking5.0.0-beta 
- Which company or project?

- What happen?

If possible, provide a way for reproducing the error. e.g. demo application, component version.

___
### Requirement or improvement
- Please describe about your requirements or improvement suggestions.

**Comment by wfs0902** [comment]
No error was started, and rxjava-1.2.0 was called for error.

**Comment by wu-sheng** [comment]
What is rxjava? I am not familiar with that.

**Comment by wfs0902** [comment]
hystrix calls rxjava.jar did the hystrix in my project and the hystrix in skywalking cause some exceptions?

**Comment by wu-sheng** [comment]
Look like same as  #1238

**Comment by wu-sheng** [comment]
@wfs0902 Could you recheck this for our master code? I assume it is fixed. If fix fails, please reopen this issue.
