### ISSUE TITLE
can sw collector start when elasticsearch is not green?

### ISSUE THREAD

**Issue by zpf1989** [apache/incubator-skywalking#1271]
Hi,firstly thank you for your great job!!!
Here is my case:
I'm using elasticsearch as storage.
I start es firstly.
When it prints "started",I start sw collector then,but its console close instantly,and below is the log:
_org.apache.skywalking.apm.collector.core.module.ModuleStartException: **Field named mi in application_alarm_list_month index not found**.
	at org.apache.skywalking.apm.collector.storage.es.StorageModuleEsProvider.start(StorageModuleEsProvider.java:300) ~[collector-storage-es-provider-5.0.0-beta.jar:5.0.0-beta]
	at org.apache.skywalking.apm.collector.core.module.BootstrapFlow.start(BootstrapFlow.java:61) ~[apm-collector-core-5.0.0-beta.jar:5.0.0-beta]
	at org.apache.skywalking.apm.collector.core.module.ModuleManager.init(ModuleManager.java:68) ~[apm-collector-core-5.0.0-beta.jar:5.0.0-beta]
	at org.apache.skywalking.apm.collector.boot.CollectorBootStartUp.main(CollectorBootStartUp.java:45) [apm-collector-boot-5.0.0-beta.jar:5.0.0-beta]
Caused by: org.apache.skywalking.apm.collector.storage.StorageInstallException: Field named mi in application_alarm_list_month index not found.
	at org.apache.skywalking.apm.collector.storage.es.base.define.ElasticSearchStorageInstaller.columnCheck(ElasticSearchStorageInstaller.java:72) ~[collector-storage-es-provider-5.0.0-beta.jar:5.0.0-beta]
	at org.apache.skywalking.apm.collector.storage.StorageInstaller.install(StorageInstaller.java:60) ~[collector-storage-define-5.0.0-beta.jar:5.0.0-beta]
	at org.apache.skywalking.apm.collector.storage.es.StorageModuleEsProvider.start(StorageModuleEsProvider.java:298) ~[collector-storage-es-provider-5.0.0-beta.jar:5.0.0-beta]
	... 3 more_
——————————————————————————————————————————————
I think it may be caused by the state of es.
So I restart es again ,and wait (**about 1 minutes**).
After it prints " Cluster health status changed from [RED] to [GREEN]",like below:
![es-red-green](https://user-images.githubusercontent.com/16696623/40592511-f1667b9c-6252-11e8-8b82-9cbb3d23dc61.jpg)

I start sw collector,and it's OK.
I don't know why es's state from yellow to green costs more than 1 minutes....
**But It seems that sw collector can't start when es in required state.**
And I think it's not friendly for auto deploy,especially in container,because it's hard to determine when the state of es is OK for sw collector.
——————————————————————————————————————————————
**So,could you guys make some retry policies when sw collector start?
Or if it is possible to start sw collector without es's state in green?**
——————————————————————————————————————————————
Below is my system:
skywalking-beta for windows;
elasticsearch 5.6.6
skywalking-aspnetcore 0.2.0
Thank you,master!!!

**Comment by peng-yongsheng** [comment]
> So, could you guys make some retry policies when sw collector start?

As the amount of data increases, es needs more and more times to load data when it starting. So, how long or how much times to retry are hard to setting. I think manual control is the best choose, and most of systems chose this.
The console logging of es told you it’s status when starting. You must waiting for the status changed from RED to GREEN. Then you can start SW collector. 

> Or if it is possible to start sw collector without es's state in green?

No, any systems can not running without dadabase really.

**Comment by wu-sheng** [comment]
@zpf1989 I agree with @peng-yongsheng . If the elastic search is not standby, collector running or not will not be real important. As a storage, please make sure it runs well and healthily.

Try to think in this way, your business system is running with a crash or not standby MySQL.

**Comment by zpf1989** [comment]
OK,thanks for your fast reply.
I get your point,and we will think about some custom process.
Thank you all! @peng-yongsheng @wu-sheng

**Comment by wu-sheng** [comment]
@zpf1989  Sure. Ping us if you want more helps. I am closing this issue.
