### ISSUE TITLE
collector losed elasticsearch 

### ISSUE THREAD

**Issue by dinggel** [apache/incubator-skywalking#1272]
### Question
The skywalking service has ran a few days and everything seemed normal. A sudden error came over the weekend. the version of elasticsearch is elasticsearch-5.6.6,and it runs normaly.The following is the error message

Caused by: org.elasticsearch.transport.NodeNotConnectedException: [node-198][10.0.0.198:9300] Node not connected
        at org.elasticsearch.transport.TcpTransport.getConnection(TcpTransport.java:654) ~[elasticsearch-5.5.0.jar:5.5.0]
        at org.elasticsearch.transport.TcpTransport.getConnection(TcpTransport.java:116) ~[elasticsearch-5.5.0.jar:5.5.0]
        at org.elasticsearch.transport.TransportService.getConnection(TransportService.java:530) ~[elasticsearch-5.5.0.jar:5.5.0]
        at org.elasticsearch.transport.TransportService.sendRequest(TransportService.java:506) ~[elasticsearch-5.5.0.jar:5.5.0]
        ... 44 more
2018-05-27 11:16:55,870 - org.apache.skywalking.apm.collector.cache.caffeine.service.ApplicationCacheCaffeineService -55218578 [grpc-default-executor-1374] ERROR [] - None of the configured nodes were available

**Comment by wu-sheng** [comment]
Have you checked your elastic search status? Look like your elastic search is out of service.

**Comment by dinggel** [comment]
elasticsearch is ok.

**Comment by dinggel** [comment]
maybe you can give me a statement that i can query

**Comment by wu-sheng** [comment]
I think the ElasticSeach client controls the connections by itself. @peng-yongsheng Do you have, or should have, any mechanism to control connection?

**Comment by SoberChina** [comment]
If the connection is not available, you should report a timeout error. This can be restarted by SW to verify.

**Comment by peng-yongsheng** [comment]
Take a look at this issue. [Elastic Search Project Issues 28062](https://github.com/elastic/elasticsearch/issues/28062)

**Comment by dinggel** [comment]
sorry.  One more es service was started.
