### ISSUE TITLE
java.lang.ClassNotFoundException: org.apache.skywalking.apm.agent.core.plugin.interceptor.enhance.StaticMethodsInter

### ISSUE THREAD

**Issue by zouyx** [apache/incubator-skywalking#1298]
Please answer these questions before submitting your issue.

- Why do you submit this issue?
- Question or discussion
- [ ] Bug
- [ ] Requirement
- [ ] Feature or performance improvement

___
### Question
- What do you want to know?

when added jvm arguments ： -javaagent:E:\agent\skywalking-agent.jar , can't start application.
___
### Bug
- Which version of SkyWalking, OS and JRE?

SkyWalking:5.0.0 beta
JRE:jdk 1.8

- Which company or project?

- What happen?

My demo application error log as below:

Caused by: java.lang.reflect.InvocationTargetException: null
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at org.springframework.aop.support.MethodMatchers.<clinit>(MethodMatchers.java)
	... 49 common frames omitted
Caused by: java.lang.reflect.InvocationTargetException: null
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at org.apache.skywalking.apm.dependencies.net.bytebuddy.dynamic.Nexus.initialize(Nexus.java:122)
	... 54 common frames omitted
Caused by: java.lang.NoClassDefFoundError: Lorg/apache/skywalking/apm/agent/core/plugin/interceptor/enhance/StaticMethodsInter;
	at java.lang.Class.getDeclaredFields0(Native Method)
	at java.lang.Class.privateGetDeclaredFields(Class.java:2583)
	at java.lang.Class.getDeclaredField(Class.java:2068)
	at org.apache.skywalking.apm.dependencies.net.bytebuddy.implementation.LoadedTypeInitializer$ForStaticField.onLoad(LoadedTypeInitializer.java:99)
	at org.apache.skywalking.apm.dependencies.net.bytebuddy.implementation.LoadedTypeInitializer$Compound.onLoad(LoadedTypeInitializer.java:162)
	at org.apache.skywalking.apm.dependencies.net.bytebuddy.agent.builder.AgentBuilder$InitializationStrategy$SelfInjection$Dispatcher$InjectingInitializer.onLoad(AgentBuilder.java:2841)
	... 59 common frames omitted
Caused by: java.lang.ClassNotFoundException: org.apache.skywalking.apm.agent.core.plugin.interceptor.enhance.StaticMethodsInter
	at java.net.URLClassLoader.findClass(URLClassLoader.java:381)
	at java.lang.ClassLoader.loadClass(ClassLoader.java:424)
	at java.lang.ClassLoader.loadClass(ClassLoader.java:357)
	... 65 common frames omitted

___
### Requirement or improvement
- Please describe about your requirements or improvement suggestions.

**Comment by wu-sheng** [comment]
I think we need your demo application to see what is happening. SkyWalking is used in many companies and projects widely. It is hard to assume this is bug from our release ways.

I have following questions?
1. Do you download our release from apache.skywalking.org ?
1. Do you try to write some plugins?
1. Are you using some middleware, which is not in our supported list?

**Comment by wu-sheng** [comment]
At the same time, you package folder is not as I expected. `E:\agent\skywalking-agent.jar`.

This is my expected official release, the red mark is agent related.
<img width="982" alt="image" src="https://user-images.githubusercontent.com/5441976/40850940-81471a66-65f8-11e8-8414-f2a41e350269.png">

**Comment by zouyx** [comment]
@wu-sheng thx for your reply.

in my case , i want to connect SkyWalking in my IDEA . but it show me the exception as my question

1.i have downloaded lastest release 5.0.0-beta.

2.maybe future

3.how can i get the list?

**Comment by wu-sheng** [comment]
I am not sure what is happening. What do you mean about connecting from idea? Do you want to debug agent?

First, please use official release to make your monitor works. Agent is very complex, don't try to understand that at the beginning.

The list is the docs. Supported libraries, frameworks.....

**Comment by zouyx** [comment]
@wu-sheng 

IDEA is IntelliJ IDEA: The Java IDE for Professional Developers 

i have run SkyWalking successfully in Linux, but fail in IntelliJ  IDEA , OS: windows.

fail log as my question

**Comment by wu-sheng** [comment]
This is hard to know, we usually use Idea to develop for skywalking. But no such issue.

**Comment by yszzu1** [comment]
I have got the same problem,  which the project depends on elasticsearch-6.3.2 .  May be the reason is ES6 not compatible  with skywalking ?

**Comment by dmsolr** [comment]
> I have got the same problem, which the project depends on elasticsearch-6.3.2 . May be the reason is ES6 not compatible with skywalking ? @wu-sheng

Hi, Which version of skywalking?

**Comment by yszzu1** [comment]
![image](https://user-images.githubusercontent.com/13514547/71477042-e1c4ed80-2822-11ea-90c0-ebc6c9ca4d89.png)

I found the reason:    can't use classpath wrapper in IDEA.

**Comment by superbible** [comment]
> ![image](https://user-images.githubusercontent.com/13514547/71477042-e1c4ed80-2822-11ea-90c0-ebc6c9ca4d89.png)
> 
> I found the reason: can't use classpath wrapper in IDEA.

Thanks, your solution helped me. I environment is IntellJ IDEA 2019.2.4 +Skywalking 8.10

**Comment by icyfox-bupt** [comment]
meet the same error too, above solution worked, thanks.

**Comment by zouyx** [comment]
> meet the same error too, above solution worked, thanks.

thanks bro.

**Comment by alberta0714** [comment]
> ![image](https://user-images.githubusercontent.com/13514547/71477042-e1c4ed80-2822-11ea-90c0-ebc6c9ca4d89.png)
> 
> I found the reason: can't use classpath wrapper in IDEA.

Nice!  Thanks bro!
