### ISSUE TITLE
Fail to start Collector

### ISSUE THREAD

**Issue by elord-dna** [apache/incubator-skywalking#1306]
Please answer these questions before submitting your issue.

- Why do you submit this issue?
- [x] Question or discussion
- [ ] Bug
- [ ] Requirement
- [ ] Feature or performance improvement

- What do you want to know?
At first, I used the original configuration that ip is localhost or 127.0.0.1 at conf/application.yml or bin/webappService.sh, with only elasticsearch ip is real ip. On this condition, apache-skywalking-apm-incubating, version 5.0.0-beta, works well.
After I replaced the 127.0.0.1 with real ip in webappService.sh, and replace localhost with real ip too in application.yml. collector failed to bind this ip and with the fellowing error message:

2018-06-04 18:08:09.931  WARN 2722 --- [PollingServerListUpdater-0] o.a.s.apm.webapp.tools.HttpClientTools   : bad url=http://58.xx.xx.18:10800/ui/jetty

2018-06-04 18:06:54,713 - org.apache.skywalking.apm.collector.server.jetty.JettyServer -14968 [main] INFO  [] - start server, host: 58.xx.xx.18, port: 12800
2018-06-04 18:06:54,713 - org.apache.skywalking.apm.collector.server.jetty.JettyServer -14968 [main] INFO  [] - jetty servlet mappings: [/segments] register by org.apache.skywalking.apm.colle
ctor.agent.jetty.provider.handler.TraceSegmentServletHandler-f0020b1
2018-06-04 18:06:54,713 - org.apache.skywalking.apm.collector.server.jetty.JettyServer -14968 [main] INFO  [] - jetty servlet mappings: [/application/register] register by org.apache.skywalki
ng.apm.collector.agent.jetty.provider.handler.ApplicationRegisterServletHandler-72a2312e
2018-06-04 18:06:54,713 - org.apache.skywalking.apm.collector.server.jetty.JettyServer -14968 [main] INFO  [] - jetty servlet mappings: [/instance/register] register by org.apache.skywalking.
apm.collector.agent.jetty.provider.handler.InstanceDiscoveryServletHandler-47c7a9e5
2018-06-04 18:06:54,713 - org.apache.skywalking.apm.collector.server.jetty.JettyServer -14968 [main] INFO  [] - jetty servlet mappings: [/servicename/discovery] register by org.apache.skywalk
ing.apm.collector.agent.jetty.provider.handler.ServiceNameDiscoveryServiceHandler-7951c3a2
2018-06-04 18:06:54,713 - org.apache.skywalking.apm.collector.server.jetty.JettyServer -14968 [main] INFO  [] - jetty servlet mappings: [/networkAddress/register] register by org.apache.skywa
lking.apm.collector.agent.jetty.provider.handler.NetworkAddressRegisterServletHandler-4ed9f7b1
2018-06-04 18:06:54,713 - org.apache.skywalking.apm.collector.server.jetty.JettyServer -14968 [main] INFO  [] - jetty servlet mappings: [/graphql] register by org.apache.skywalking.apm.collec
tor.ui.jetty.handler.GraphQLHandler-6d69a0d3
2018-06-04 18:06:54,714 - org.eclipse.jetty.server.Server -14969 [main] INFO  [] - jetty-9.4.2.v20170220
2018-06-04 18:06:54,715 - org.eclipse.jetty.server.handler.ContextHandler -14970 [main] INFO  [] - Started o.e.j.s.ServletContextHandler@36ad5f2a{/,null,AVAILABLE}
2018-06-04 18:06:54,715 - org.apache.skywalking.apm.collector.jetty.manager.JettyManagerProvider -14970 [main] ERROR [] - Cannot assign requested address
org.apache.skywalking.apm.collector.server.jetty.JettyServerException: Cannot assign requested address
	at org.apache.skywalking.apm.collector.server.jetty.JettyServer.start(JettyServer.java:96) ~[server-component-5.0.0-beta.jar:5.0.0-beta]
	at org.apache.skywalking.apm.collector.jetty.manager.JettyManagerProvider.lambda$notifyAfterCompleted$0(JettyManagerProvider.java:68) ~[collector-jetty-manager-provider-5.0.0-beta.jar
:5.0.0-beta]
	at java.util.HashMap$Values.forEach(HashMap.java:981) [?:1.8.0_161]
	at org.apache.skywalking.apm.collector.jetty.manager.JettyManagerProvider.notifyAfterCompleted(JettyManagerProvider.java:66) [collector-jetty-manager-provider-5.0.0-beta.jar:5.0.0-bet
a]
	at org.apache.skywalking.apm.collector.core.module.BootstrapFlow.notifyAfterCompleted(BootstrapFlow.java:67) [apm-collector-core-5.0.0-beta.jar:5.0.0-beta]
	at org.apache.skywalking.apm.collector.core.module.ModuleManager.init(ModuleManager.java:69) [apm-collector-core-5.0.0-beta.jar:5.0.0-beta]
	at org.apache.skywalking.apm.collector.boot.CollectorBootStartUp.main(CollectorBootStartUp.java:45) [apm-collector-boot-5.0.0-beta.jar:5.0.0-beta]
Caused by: java.net.BindException: Cannot assign requested address
	at sun.nio.ch.Net.bind0(Native Method) ~[?:1.8.0_161]
	at sun.nio.ch.Net.bind(Net.java:433) ~[?:1.8.0_161]
	at sun.nio.ch.Net.bind(Net.java:425) ~[?:1.8.0_161]
	at sun.nio.ch.ServerSocketChannelImpl.bind(ServerSocketChannelImpl.java:223) ~[?:1.8.0_161]
	at sun.nio.ch.ServerSocketAdaptor.bind(ServerSocketAdaptor.java:74) ~[?:1.8.0_161]
	at org.eclipse.jetty.server.ServerConnector.open(ServerConnector.java:298) ~[jetty-server-9.4.2.v20170220.jar:9.4.2.v20170220]

**Comment by wu-sheng** [comment]
Issue must be in English.

**Comment by wu-sheng** [comment]
You could help on document, the open source project is from community. Feel free to reorganize the doc, and ask community for suggestion. 

I am happy to accept new documents.

**Comment by elord-dna** [comment]
Sorry, I don't know that issue must be in English.
I just tried some different configs on cloud and at local. On cloud, I use External network IP to replace the 'localhost' and '127.0.0.1' in both bin/webappService.sh and config/application.yml. But that doesn't work at all. Log shows that bad ip was used, while I checked it a few times and made sure that it's a right ip.
Then I tried it on local machine. I use inside network ip to repalce those original ip. And this time, it works.
Does the given ip should have some restrictions?

**Comment by wu-sheng** [comment]
Every global open source project should be in English. Chinese is really hard for western people. Could you edit your issue and title? Change them to English too.

For IP stuff, there is no requirement bu us. It is based on JVM, OS rules. Binding IP is a traditional way to build cluster. So I can't tell why, should ask for cloud service provider. I set colloector in huawei and ali cloud. They all provided IP for binding. Btw, hostname could be used too.

**Comment by elord-dna** [comment]
I'd tried many times, but had failed many times too. I thought that I confused by the configurations. Could you explain the meanings of "naming.jetty.host, remote.gRPC.host, agent_gRPC.host, agent_jetty.jetty.host, ui.jetty.host"?
Or given a situation like that, Collector Service and UI Service are on cloud machine (ip:58.xx.xx.xx), and Agent Service is at local machine (ip:202.xx.xx.xx). And a zookeeper machine (ip:69.xx.xx.xx). 
Which ip should I use in config/application.yml, the naming.jetty.host?
I've tried cloud machine's ip on AliCloud and TecentCloud, but failed to start up the Collector due to the binding error.

**Comment by elord-dna** [comment]
Thanks very much! Though that fails again, I'll look through the failure reason.

**Comment by wu-sheng** [comment]
> Thanks very much! Though that fails again, I'll look through the failure reason.

Sure. Open new issue, if you are facing some different problem.
