### ISSUE TITLE
Collector - ElasticSearch

### ISSUE THREAD

**Issue by asivanadi** [apache/incubator-skywalking#1307]
Please answer these questions before submitting your issue.

- Why do you submit this issue?
- [-] Question or discussion
- [ ] Bug
- [ ] Requirement
- [ ] Feature or performance improvement

___
### Question

On trying to connect with the ES , collector gives the following exception.
2018-06-04 12:35:46,285 - org.apache.skywalking.apm.collector.boot.CollectorBootStartUp -9814 [main] ERROR [] - Field named ac in application index not found.
org.apache.skywalking.apm.collector.core.module.ModuleStartException: Field named ac in application index not found.
        at org.apache.skywalking.apm.collector.storage.es.StorageModuleEsProvider.start(StorageModuleEsProvider.java:300) ~[collector-storage-es-provider-5.0.0-beta.jar:5.0.0-beta]
        at org.apache.skywalking.apm.collector.core.module.BootstrapFlow.start(BootstrapFlow.java:61) ~[apm-collector-core-5.0.0-beta.jar:5.0.0-beta]
        at org.apache.skywalking.apm.collector.core.module.ModuleManager.init(ModuleManager.java:68) ~[apm-collector-core-5.0.0-beta.jar:5.0.0-beta]
        at org.apache.skywalking.apm.collector.boot.CollectorBootStartUp.main(CollectorBootStartUp.java:45) [apm-collector-boot-5.0.0-beta.jar:5.0.0-beta]
Caused by: org.apache.skywalking.apm.collector.storage.StorageInstallException: Field named ac in application index not found.
        at org.apache.skywalking.apm.collector.storage.es.base.define.ElasticSearchStorageInstaller.columnCheck(ElasticSearchStorageInstaller.java:72) ~[collector-storage-es-provider-5.0.0-beta.jar:5.0.0-beta]
        at org.apache.skywalking.apm.collector.storage.StorageInstaller.install(StorageInstaller.java:60) ~[collector-storage-define-5.0.0-beta.jar:5.0.0-beta]
        at org.apache.skywalking.apm.collector.storage.es.StorageModuleEsProvider.start(StorageModuleEsProvider.java:298) ~[collector-storage-es-provider-5.0.0-beta.jar:5.0.0-beta]
        ... 3 more
___
### Bug
- Which version of SkyWalking, OS and JRE?

- Which company or project?

- What happen?
If possible, provide a way for reproducing the error. e.g. demo application, component version.

___
### Requirement or improvement
- Please describe about your requirements or improvement suggestions.

**Comment by peng-yongsheng** [comment]
This is a common problem, some advise for you: 
1. Retrieval issues, someone submitted same questions.
2. Read document, FAQ
3. Join our QQ group and ask to the others

**Comment by wu-sheng** [comment]
Clear es data, reboot collector and agents.
