### ISSUE TITLE
Spring boot integration and trying to get this to work

### ISSUE THREAD

**Issue by gamefundas** [apache/incubator-skywalking#1365]
Please answer these questions before submitting your issue.

- Why do you submit this issue?
- [X] Question or discussion
- [ ] Bug
- [ ] Requirement
- [ ] Feature or performance improvement

___
### Question
- What do you want to know?
Spring boot has a startup script for Linux/Unix which allows the application to be started as a service. In this case spring uses the application.conf file to allow JAVA_OPTS. 

application.conf with the following contents

JAVA_OPTS='-javaagent:/opt/skywalking/agent/skywalking-agent.jar'

Does the above typically work, and if it is the right way to configure the agent then is there a way to confirm the agent is actually running from the logs etc? I couldn't find anything printed in the application logs or  /opt/skywalking/agent/logs either.
___
### Bug
- Which version of SkyWalking, OS and JRE?
5.0 Beta, Amazon Linux (CentOs variant), JDK 1.8
___
### Requirement or improvement
- Please describe about your requirements or improvement suggestions.
I also notice that the default agent -> collector port 10800 is only accepting connections locally

netstat shows the following
tcp        0      0 ::ffff:127.0.0.1:10800      :::*                        LISTEN      -

This forced me to use Nginx to reverse proxy my calls to the collector. But at the end of the day I don't see application data appear in the dashboard. No errors anywhere in logs. Am I missing something somewhere?

**Comment by wu-sheng** [comment]
First, I am not familiar with that spring boot script, but in theory, you can check the os startup command by using 'ps -ef'.  If agent starts, you should see the log in agent/log. One thing you should notice, -javaagant need to be in the front of -jar. @ascrutae could you help about this?

For binding, i think you miss application.yml in collector conf folder, which includes all binding IPs and ports.. See collector cluster mode doc.

**Comment by gamefundas** [comment]
Managed to get it running by having javaagent as the first parameter. However I am getting the following error now

`
DEBUG 2018-06-18 00:18:05 DiscoveryRestServiceClient :  Refresh GRPC server list: [xx.xx.xx.xx:11800]
DEBUG 2018-06-18 00:18:05 GRPCChannelManager :  Selected collector grpc service running, reconnect:true.
DEBUG 2018-06-18 00:18:05 AppAndServiceRegisterClient :  AppAndServiceRegisterClient running, status:DISCONNECT.
DEBUG 2018-06-18 00:18:08 AppAndServiceRegisterClient :  AppAndServiceRegisterClient running, status:CONNECTED.
DEBUG 2018-06-18 00:18:08 GRPCChannelManager :  Selected collector grpc service shutdown.
ERROR 2018-06-18 00:18:08 AppAndServiceRegisterClient :  AppAndServiceRegisterClient execute fail.
org.apache.skywalking.apm.dependencies.io.grpc.StatusRuntimeException: CANCELLED: Call was interrupted
        at org.apache.skywalking.apm.dependencies.io.grpc.Status.asRuntimeException(Status.java:517)
        at org.apache.skywalking.apm.dependencies.io.grpc.stub.ClientCalls.blockingUnaryCall(ClientCalls.java:128)
        at org.apache.skywalking.apm.network.proto.ApplicationRegisterServiceGrpc$ApplicationRegisterServiceBlockingStub.applicationCodeRegister(ApplicationRegisterServiceGrpc.java:170)
        at org.apache.skywalking.apm.agent.core.remote.AppAndServiceRegisterClient.run(AppAndServiceRegisterClient.java:112)
        at org.apache.skywalking.apm.util.RunnableWithExceptionProtection.run(RunnableWithExceptionProtection.java:36)
        at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511)
        at java.util.concurrent.FutureTask.runAndReset(FutureTask.java:308)
        at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.access$301(ScheduledThreadPoolExecutor.java:180)
        at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.run(ScheduledThreadPoolExecutor.java:294)
        at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142)
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617)
        at java.lang.Thread.run(Thread.java:745)
Caused by: java.lang.InterruptedException
        at java.util.concurrent.locks.AbstractQueuedSynchronizer.acquireInterruptibly(AbstractQueuedSynchronizer.java:1220)
        at java.util.concurrent.locks.ReentrantLock.lockInterruptibly(ReentrantLock.java:335)
        at java.util.concurrent.LinkedBlockingQueue.take(LinkedBlockingQueue.java:439)
        at org.apache.skywalking.apm.dependencies.io.grpc.stub.ClientCalls$ThreadlessExecutor.waitAndDrain(ClientCalls.java:623)
        at org.apache.skywalking.apm.dependencies.io.grpc.stub.ClientCalls.blockingUnaryCall(ClientCalls.java:122)
        ... 10 more
`
Checked to confirm that 11800 port was reachable on the configured IP.

**Comment by gamefundas** [comment]
Tried various things with application.yml, used localhost, collector host IP, 0.0.0.0 etc. None of it worked. The remote agent couldn't connect to the 11800 port. I was able to telnet on that port which meant TCP connectivity was fine. 

Cant think of any thing else.

**Comment by wu-sheng** [comment]
Have you read this section? https://github.com/apache/incubator-skywalking/blob/master/docs/en/Architecture.md#multiple-connection-ways

**Comment by wu-sheng** [comment]
There are two steps during the connecting from the agent. I think the collector host IP should be the right settings.

**Comment by wu-sheng** [comment]
Please make sure the IP in application.yml, should be used to access from agent side. If not, please use direct link feature: https://github.com/apache/incubator-skywalking/blob/master/docs/en/Direct-uplink.md
