### ISSUE TITLE
Table "APPLICATION" not found

### ISSUE THREAD

**Issue by iitsoft** [apache/incubator-skywalking#1369]
Please answer these questions before submitting your issue.

- Why do you submit this issue?
- [ ] Question or discussion
- [x] Bug
- [ ] Requirement
- [ ] Feature or performance improvement

___
### Question
- What do you want to know?

___
### Bug
- Which version of SkyWalking, OS and JRE?

- Which company or project?

- What happen?
If possible, provide a way for reproducing the error. e.g. demo application, component version.

___
### Requirement or improvement
- Please describe about your requirements or improvement suggestions.

**Comment by iitsoft** [comment]
apache-skywalking-apm-incubating-5.0.0-beta.tar.gz 

skywalking-collector-server.log
2018-06-19 14:50:06,388 - org.apache.skywalking.apm.collector.storage.h2.dao.cache.ApplicationH2CacheDAO -47972 [grpc-default-executor-0] ERROR [] - Table "APPLICATION" not found; SQL statement:
select application_id from application where application_code = ? and is_address = ? [42102-196]
org.apache.skywalking.apm.collector.client.h2.H2ClientException: Table "APPLICATION" not found; SQL statement:
select application_id from application where application_code = ? and is_address = ? [42102-196]
        at org.apache.skywalking.apm.collector.client.h2.H2Client.executeQuery(H2Client.java:97) ~[client-component-5.0.0-beta.jar:5.0.0-beta]
        at org.apache.skywalking.apm.collector.storage.h2.dao.cache.ApplicationH2CacheDAO.getApplicationIdByCode(ApplicationH2CacheDAO.java:54) [collector-storage-h2-provider-5.0.0-beta.jar:5.0.0-beta]
        at org.apache.skywalking.apm.collector.cache.caffeine.service.ApplicationCacheCaffeineService.getApplicationIdByCode(ApplicationCacheCaffeineService.java:69) [collector-cache-caffeine-provider-5.0.0-beta.jar:5.0.0-beta]
        at org.apache.skywalking.apm.collector.analysis.register.provider.service.ApplicationIDService.getOrCreateForApplicationCode(ApplicationIDService.java:71) [register-provider-5.0.0-beta.jar:5.0.0-beta]
        at org.apache.skywalking.apm.collector.agent.grpc.provider.handler.ApplicationRegisterServiceHandler.applicationCodeRegister(ApplicationRegisterServiceHandler.java:52) [agent-grpc-provider-5.0.0-beta.jar:5.0.0-beta]
        at org.apache.skywalking.apm.network.proto.ApplicationRegisterServiceGrpc$MethodHandlers.invoke(ApplicationRegisterServiceGrpc.java:225) [apm-network-5.0.0-beta.jar:5.0.0-beta]
        at io.grpc.stub.ServerCalls$UnaryServerCallHandler$UnaryServerCallListener.onHalfClose(ServerCalls.java:171) [grpc-stub-1.10.0.jar:1.10.0]
        at io.grpc.internal.ServerCallImpl$ServerStreamListenerImpl.halfClosed(ServerCallImpl.java:272) [grpc-core-1.10.0.jar:1.10.0]
        at io.grpc.internal.ServerImpl$JumpToApplicationThreadServerStreamListener$1HalfClosed.runInContext(ServerImpl.java:653) [grpc-core-1.10.0.jar:1.10.0]
        at io.grpc.internal.ContextRunnable.run(ContextRunnable.java:37) [grpc-core-1.10.0.jar:1.10.0]
        at io.grpc.internal.SerializingExecutor.run(SerializingExecutor.java:123) [grpc-core-1.10.0.jar:1.10.0]
        at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142) [?:1.8.0_111]
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617) [?:1.8.0_111]
        at java.lang.Thread.run(Thread.java:745) [?:1.8.0_111]
Caused by: org.h2.jdbc.JdbcSQLException: Table "APPLICATION" not found; SQL statement:
select application_id from application where application_code = ? and is_address = ? [42102-196]
        at org.h2.message.DbException.getJdbcSQLException(DbException.java:345) ~[h2-1.4.196.jar:1.4.196]
        at org.h2.message.DbException.get(DbException.java:179) ~[h2-1.4.196.jar:1.4.196]
        at org.h2.message.DbException.get(DbException.java:155) ~[h2-1.4.196.jar:1.4.196]
        at org.h2.command.Parser.readTableOrView(Parser.java:5552) ~[h2-1.4.196.jar:1.4.196]
        at org.h2.command.Parser.readTableFilter(Parser.java:1266) ~[h2-1.4.196.jar:1.4.196]
        at org.h2.command.Parser.parseSelectSimpleFromPart(Parser.java:1946) ~[h2-1.4.196.jar:1.4.196]
        at org.h2.command.Parser.parseSelectSimple(Parser.java:2095) ~[h2-1.4.196.jar:1.4.196]
        at org.h2.command.Parser.parseSelectSub(Parser.java:1940) ~[h2-1.4.196.jar:1.4.196]
        at org.h2.command.Parser.parseSelectUnion(Parser.java:1755) ~[h2-1.4.196.jar:1.4.196]
        at org.h2.command.Parser.parseSelect(Parser.java:1743) ~[h2-1.4.196.jar:1.4.196]
        at org.h2.command.Parser.parsePrepared(Parser.java:449) ~[h2-1.4.196.jar:1.4.196]
        at org.h2.command.Parser.parse(Parser.java:321) ~[h2-1.4.196.jar:1.4.196]
        at org.h2.command.Parser.parse(Parser.java:293) ~[h2-1.4.196.jar:1.4.196]
        at org.h2.command.Parser.prepareCommand(Parser.java:258) ~[h2-1.4.196.jar:1.4.196]
        at org.h2.engine.Session.prepareLocal(Session.java:578) ~[h2-1.4.196.jar:1.4.196]
        at org.h2.engine.Session.prepareCommand(Session.java:519) ~[h2-1.4.196.jar:1.4.196]
        at org.h2.jdbc.JdbcConnection.prepareCommand(JdbcConnection.java:1204) ~[h2-1.4.196.jar:1.4.196]
        at org.h2.jdbc.JdbcPreparedStatement.<init>(JdbcPreparedStatement.java:73) ~[h2-1.4.196.jar:1.4.196]
        at org.h2.jdbc.JdbcConnection.prepareStatement(JdbcConnection.java:288) ~[h2-1.4.196.jar:1.4.196]
        at org.apache.skywalking.apm.collector.client.h2.H2Client.executeQuery(H2Client.java:88) ~[client-component-5.0.0-beta.jar:5.0.0-beta]
        ... 13 more

**Comment by peng-yongsheng** [comment]
H2 storage is not support now, please use elasticsearch.
