### ISSUE TITLE
None of the configured nodes are available

### ISSUE THREAD

**Issue by iitsoft** [apache/incubator-skywalking#1371]
Please answer these questions before submitting your issue.

- Why do you submit this issue?
- [ ] Question or discussion
- [* ] Bug
- [ ] Requirement
- [ ] Feature or performance improvement

___
### Question
- Why collector cannot start when use my elasticsearch?

___
### Bug
- cat /etc/centos-release
CentOS Linux release 7.4.1708 (Core) 
curl 172.16.34.51:9200
{
  "name" : "sky-node-1",
  "cluster_name" : "CollectorDBCluster",
  "cluster_uuid" : "nWoK3xGxQt-w1JJnVHTCwQ",
  "version" : {
    "number" : "6.2.3",
    "build_hash" : "c59ff00",
    "build_date" : "2018-03-13T10:06:29.741383Z",
    "build_snapshot" : false,
    "lucene_version" : "7.2.1",
    "minimum_wire_compatibility_version" : "5.6.0",
    "minimum_index_compatibility_version" : "5.0.0"
  },
  "tagline" : "You Know, for Search"
}

- elasticsearch configuration in application.yml
storage:
  elasticsearch:
    clusterName: CollectorDBCluster
    clusterTransportSniffer: true
    clusterNodes: 172.16.34.51:9200
    indexShardsNumber: 1
    indexReplicasNumber: 0
    highPerformanceMode: true
    ttl: 7

- collector does not start
collector.log
Exception in thread "main" NoNodeAvailableException[None of the configured nodes are available: [{#transport#-1}{BEeH4_59SDWu6uIuWatipg}{172.16.34.51}{172.16.34.51:9200}]]
        at org.elasticsearch.client.transport.TransportClientNodesService.ensureNodesAreAvailable(TransportClientNodesService.java:347)
        at org.elasticsearch.client.transport.TransportClientNodesService.execute(TransportClientNodesService.java:245)
        at org.elasticsearch.client.transport.TransportProxyClient.execute(TransportProxyClient.java:59)
        at org.elasticsearch.client.transport.TransportClient.doExecute(TransportClient.java:363)
        at org.elasticsearch.client.support.AbstractClient.execute(AbstractClient.java:408)
        at org.elasticsearch.client.support.AbstractClient$IndicesAdmin.execute(AbstractClient.java:1256)
        at org.elasticsearch.action.ActionRequestBuilder.execute(ActionRequestBuilder.java:80)
        at org.elasticsearch.action.ActionRequestBuilder.execute(ActionRequestBuilder.java:54)
        at org.elasticsearch.action.ActionRequestBuilder.get(ActionRequestBuilder.java:62)
        at org.apache.skywalking.apm.collector.client.elasticsearch.ElasticSearchClient.isExistsIndex(ElasticSearchClient.java:153)
        at org.apache.skywalking.apm.collector.storage.es.base.define.ElasticSearchStorageInstaller.isExists(ElasticSearchStorageInstaller.java:151)
        at org.apache.skywalking.apm.collector.storage.StorageInstaller.install(StorageInstaller.java:52)
        at org.apache.skywalking.apm.collector.storage.es.StorageModuleEsProvider.start(StorageModuleEsProvider.java:298)
        at org.apache.skywalking.apm.collector.core.module.BootstrapFlow.start(BootstrapFlow.java:61)
        at org.apache.skywalking.apm.collector.core.module.ModuleManager.init(ModuleManager.java:68)
        at org.apache.skywalking.apm.collector.boot.CollectorBootStartUp.main(CollectorBootStartUp.java:45)

**Comment by peng-yongsheng** [comment]
Collector use tcp transport port 9300. 9200 is http rest port.
