### ISSUE TITLE
Unable to load the library 'org_apache_skywalking_apm_dependencies_netty_tcnative_osx_x86_64'

### ISSUE THREAD

**Issue by liuhaoyang** [apache/incubator-skywalking#1379]
Please answer these questions before submitting your issue.

- Why do you submit this issue?
- [ ] Question or discussion
- [x] Bug
- [ ] Requirement
- [ ] Feature or performance improvement

___
### Question
- What do you want to know?

___
### Bug
- Which version of SkyWalking, OS and JRE?
  1. SkyWalking 5.0 beta
  2. OS: Mac OSX 10.13.4
- Which company or project?

- What happen?
If possible, provide a way for reproducing the error. e.g. demo application, component version.

Once I use TLS, the agent throws an exception when starting the application

```
22:42:44.769 [SkywalkingAgent-1-GRPCChannelManager-0] DEBUG org.apache.skywalking.apm.dependencies.io.netty.util.internal.NativeLibraryLoader - Unable to load the library 'org_apache_skywalking_apm_dependencies_netty_tcnative_osx_x86_64', trying other loading mechanism.
java.lang.UnsatisfiedLinkError: no org_apache_skywalking_apm_dependencies_netty_tcnative_osx_x86_64 in java.library.path
	at java.lang.ClassLoader.loadLibrary(ClassLoader.java:1867)
	at java.lang.Runtime.loadLibrary0(Runtime.java:870)
	at java.lang.System.loadLibrary(System.java:1122)
	at org.apache.skywalking.apm.dependencies.io.netty.util.internal.NativeLibraryUtil.loadLibrary(NativeLibraryUtil.java:38)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at org.apache.skywalking.apm.dependencies.io.netty.util.internal.NativeLibraryLoader$1.run(NativeLibraryLoader.java:263)
	at java.security.AccessController.doPrivileged(Native Method)
	at org.apache.skywalking.apm.dependencies.io.netty.util.internal.NativeLibraryLoader.loadLibraryByHelper(NativeLibraryLoader.java:255)
	at org.apache.skywalking.apm.dependencies.io.netty.util.internal.NativeLibraryLoader.loadLibrary(NativeLibraryLoader.java:233)
	at org.apache.skywalking.apm.dependencies.io.netty.util.internal.NativeLibraryLoader.load(NativeLibraryLoader.java:124)
	at org.apache.skywalking.apm.dependencies.io.netty.util.internal.NativeLibraryLoader.loadFirstAvailable(NativeLibraryLoader.java:85)
	at org.apache.skywalking.apm.dependencies.io.netty.handler.ssl.OpenSsl.loadTcNative(OpenSsl.java:421)
	at org.apache.skywalking.apm.dependencies.io.netty.handler.ssl.OpenSsl.<clinit>(OpenSsl.java:89)
	at org.apache.skywalking.apm.dependencies.io.grpc.netty.GrpcSslContexts.defaultSslProvider(GrpcSslContexts.java:143)
	at org.apache.skywalking.apm.dependencies.io.grpc.netty.GrpcSslContexts.configure(GrpcSslContexts.java:124)
	at org.apache.skywalking.apm.dependencies.io.grpc.netty.GrpcSslContexts.forClient(GrpcSslContexts.java:94)
	at org.apache.skywalking.apm.agent.core.remote.TLSChannelBuilder.build(TLSChannelBuilder.java:43)
	at org.apache.skywalking.apm.agent.core.remote.TLSChannelBuilder.build(TLSChannelBuilder.java:36)
	at org.apache.skywalking.apm.agent.core.remote.GRPCChannel.<init>(GRPCChannel.java:43)
	at org.apache.skywalking.apm.agent.core.remote.GRPCChannel.<init>(GRPCChannel.java:31)
	at org.apache.skywalking.apm.agent.core.remote.GRPCChannel$Builder.build(GRPCChannel.java:95)
	at org.apache.skywalking.apm.agent.core.remote.GRPCChannelManager.run(GRPCChannelManager.java:99)
	at org.apache.skywalking.apm.util.RunnableWithExceptionProtection.run(RunnableWithExceptionProtection.java:36)
	at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511)
	at java.util.concurrent.FutureTask.runAndReset(FutureTask.java:308)
	at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.access$301(ScheduledThreadPoolExecutor.java:180)
	at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.run(ScheduledThreadPoolExecutor.java:294)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
	at java.lang.Thread.run(Thread.java:748)
```

**Comment by JaredTan95** [comment]
I think you can refer to https://github.com/apache/incubator-skywalking/blob/master/docs/en/FAQ/Protoc-Plugin-Fails-When-Build.md
