### ISSUE TITLE
Null Pointer Exception when no apps are present

### ISSUE THREAD

**Issue by apertureqa** [apache/incubator-skywalking#1382]
Please answer these questions before submitting your issue.

- Why do you submit this issue?
- [ ] Question or discussion
- [ -] Bug
- [ ] Requirement
- [ ] Feature or performance improvement

___
### Question
- What do you want to know?

___
### Bug
- Which version of SkyWalking, OS and JRE?
latest
- Which company or project?

- What happen?
If possible, provide a way for reproducing the error. e.g. demo application, component version.
2018-06-24 03:21:59,379 - graphql.execution.SimpleDataFetcherExceptionHandler -614125 [qtp2038484780-137] WARN  [] - Exception while fetching data (/getTopNApplicationThroughput) : null
java.lang.NullPointerException: null
	at org.apache.skywalking.apm.collector.ui.service.ApplicationService.lambda$getTopNApplicationThroughput$11(ApplicationService.java:106) ~[collector-ui-jetty-provider-5.0.0-beta.jar:5.0.0-beta]
	at java.lang.Iterable.forEach(Iterable.java:75) ~[?:1.8.0_171]
	at org.apache.skywalking.apm.collector.ui.service.ApplicationService.getTopNApplicationThroughput(ApplicationService.java:105) ~[collector-ui-jetty-provider-5.0.0-beta.jar:5.0.0-beta]
	at org.apache.skywalking.apm.collector.ui.query.OverViewLayerQuery.getTopNApplicationThroughput(OverViewLayerQuery.java:147) ~[collector-ui-jetty-provider-5.0.0-beta.jar:5.0.0-beta]
	at org.apache.skywalking.apm.collector.ui.query.OverViewLayerQueryMethodAccess.invoke(Unknown Source) ~[reflectasm-1.11.3.jar:5.0.0-beta]
	at com.coxautodev.graphql.tools.MethodFieldResolverDataFetcher.get(MethodFieldResolver.kt:132) ~[graphql-java-tools-4.3.0.jar:?]
	at graphql.execution.ExecutionStrategy.fetchField(ExecutionStrategy.java:219) [graphql-java-6.0.jar:?]
	at graphql.execution.ExecutionStrategy.resolveField(ExecutionStrategy.java:165) [graphql-java-6.0.jar:?]
	at graphql.execution.AsyncExecutionStrategy.execute(AsyncExecutionStrategy.java:55) [graphql-java-6.0.jar:?]
	at graphql.execution.Execution.executeOperation(Execution.java:154) [graphql-java-6.0.jar:?]
	at graphql.execution.Execution.execute(Execution.java:98) [graphql-java-6.0.jar:?]
	at graphql.GraphQL.execute(GraphQL.java:546) [graphql-java-6.0.jar:?]
	at graphql.GraphQL.parseValidateAndExecute(GraphQL.java:488) [graphql-java-6.0.jar:?]
	at graphql.GraphQL.executeAsync(GraphQL.java:463) [graphql-java-6.0.jar:?]
	at graphql.GraphQL.execute(GraphQL.java:394) [graphql-java-6.0.jar:?]
	at org.apache.skywalking.apm.collector.ui.jetty.handler.GraphQLHandler.execute(GraphQLHandler.java:121) [collector-ui-jetty-provider-5.0.0-beta.jar:5.0.0-beta]
	at org.apache.skywalking.apm.collector.ui.jetty.handler.GraphQLHandler.doPost(GraphQLHandler.java:115) [collector-ui-jetty-provider-5.0.0-beta.jar:5.0.0-beta]
	at org.apache.skywalking.apm.collector.server.jetty.JettyHandler.doPost(JettyHandler.java:63) [server-component-5.0.0-beta.jar:5.0.0-beta]
	at javax.servlet.http.HttpServlet.service(HttpServlet.java:707) [javax.servlet-api-3.1.0.jar:3.1.0]
	at org.apache.skywalking.apm.collector.server.jetty.JettyHandler.service(JettyHandler.java:110) [server-component-5.0.0-beta.jar:5.0.0-beta]
	at javax.servlet.http.HttpServlet.service(HttpServlet.java:790) [javax.servlet-api-3.1.0.jar:3.1.0]
	at org.apache.skywalking.apm.collector.server.jetty.JettyHandler.service(JettyHandler.java:114) [server-component-5.0.0-beta.jar:5.0.0-beta]
	at org.eclipse.jetty.servlet.ServletHolder.handle(ServletHolder.java:841) [jetty-servlet-9.4.2.v20170220.jar:9.4.2.v20170220]
	at org.eclipse.jetty.servlet.ServletHandler.doHandle(ServletHandler.java:543) [jetty-servlet-9.4.2.v20170220.jar:9.4.2.v20170220]
	at org.eclipse.jetty.server.handler.ScopedHandler.nextHandle(ScopedHandler.java:188) [jetty-server-9.4.2.v20170220.jar:9.4.2.v20170220]
	at org.eclipse.jetty.server.handler.ContextHandler.doHandle(ContextHandler.java:1239) [jetty-server-9.4.2.v20170220.jar:9.4.2.v20170220]
	at org.eclipse.jetty.server.handler.ScopedHandler.nextScope(ScopedHandler.java:168) [jetty-server-9.4.2.v20170220.jar:9.4.2.v20170220]
	at org.eclipse.jetty.servlet.ServletHandler.doScope(ServletHandler.java:481) [jetty-servlet-9.4.2.v20170220.jar:9.4.2.v20170220]
	at org.eclipse.jetty.server.handler.ScopedHandler.nextScope(ScopedHandler.java:166) [jetty-server-9.4.2.v20170220.jar:9.4.2.v20170220]
	at org.eclipse.jetty.server.handler.ContextHandler.doScope(ContextHandler.java:1141) [jetty-server-9.4.2.v20170220.jar:9.4.2.v20170220]
	at org.eclipse.jetty.server.handler.ScopedHandler.handle(ScopedHandler.java:141) [jetty-server-9.4.2.v20170220.jar:9.4.2.v20170220]
	at org.eclipse.jetty.server.handler.HandlerWrapper.handle(HandlerWrapper.java:132) [jetty-server-9.4.2.v20170220.jar:9.4.2.v20170220]
	at org.eclipse.jetty.server.Server.handle(Server.java:564) [jetty-server-9.4.2.v20170220.jar:9.4.2.v20170220]
	at org.eclipse.jetty.server.HttpChannel.handle(HttpChannel.java:320) [jetty-server-9.4.2.v20170220.jar:9.4.2.v20170220]
	at org.eclipse.jetty.server.HttpConnection.onFillable(HttpConnection.java:251) [jetty-server-9.4.2.v20170220.jar:9.4.2.v20170220]
	at org.eclipse.jetty.io.AbstractConnection$ReadCallback.succeeded(AbstractConnection.java:279) [jetty-io-9.4.2.v20170220.jar:9.4.2.v20170220]
	at org.eclipse.jetty.io.FillInterest.fillable(FillInterest.java:110) [jetty-io-9.4.2.v20170220.jar:9.4.2.v20170220]
	at org.eclipse.jetty.io.ChannelEndPoint$2.run(ChannelEndPoint.java:124) [jetty-io-9.4.2.v20170220.jar:9.4.2.v20170220]
	at org.eclipse.jetty.util.thread.Invocable.invokePreferred(Invocable.java:122) [jetty-util-9.4.2.v20170220.jar:9.4.2.v20170220]
	at org.eclipse.jetty.util.thread.strategy.ExecutingExecutionStrategy.invoke(ExecutingExecutionStrategy.java:58) [jetty-util-9.4.2.v20170220.jar:9.4.2.v20170220]
	at org.eclipse.jetty.util.thread.strategy.ExecuteProduceConsume.produceConsume(ExecuteProduceConsume.java:201) [jetty-util-9.4.2.v20170220.jar:9.4.2.v20170220]
	at org.eclipse.jetty.util.thread.strategy.ExecuteProduceConsume.run(ExecuteProduceConsume.java:133) [jetty-util-9.4.2.v20170220.jar:9.4.2.v20170220]
	at org.eclipse.jetty.util.thread.QueuedThreadPool.runJob(QueuedThreadPool.java:672) [jetty-util-9.4.2.v20170220.jar:9.4.2.v20170220]
	at org.eclipse.jetty.util.thread.QueuedThreadPool$2.run(QueuedThreadPool.java:590) [jetty-util-9.4.2.v20170220.jar:9.4.2.v20170220]
	at java.lang.Thread.run(Thread.java:748) [?:1.8.0_171]
___
### Requirement or improvement
- Please describe about your requirements or improvement suggestions.

**Comment by peng-yongsheng** [comment]
@apertureqa Are you clear ES data and restart collector, but not restart your application?
