### ISSUE TITLE
Exception of oracle plugin

### ISSUE THREAD

**Issue by clorxd** [apache/incubator-skywalking#1391]
Please answer these questions before submitting your issue.

- Why do you submit this issue?
Bug
___
### Bug info

I have upload the demo to github https://github.com/clorxd/test-oracle , hope it's helpful

project environment:
SkyWalking 5.0 beta
JDK 8
ojdbc 6 / ojdbc 8-12.2.0.1
oracle 11g
spring 1.5.4 
mybatis 3.4.4
pagehelper 5.1.2

Exception info:
ERROR 2018-06-26 10:39:28 InstMethodsInter :  class[class oracle.jdbc.driver.T4CPreparedStatement] after method[execute] intercept failure 
java.lang.NullPointerException
	at org.apache.skywalking.apm.plugin.jdbc.oracle.PreparedStatementExecuteMethodsInterceptor.afterMethod(PreparedStatementExecuteMethodsInterceptor.java:57)
	at org.apache.skywalking.apm.agent.core.plugin.interceptor.enhance.InstMethodsInter.intercept(InstMethodsInter.java:105)
	at oracle.jdbc.driver.OraclePreparedStatement.execute(OraclePreparedStatement.java)
	at oracle.jdbc.driver.OraclePreparedStatementWrapper.execute(OraclePreparedStatementWrapper.java:1374)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at org.apache.tomcat.jdbc.pool.StatementFacade$StatementProxy.invoke(StatementFacade.java:114)
	at com.sun.proxy.$Proxy81.execute(Unknown Source)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at org.apache.ibatis.logging.jdbc.PreparedStatementLogger.invoke(PreparedStatementLogger.java:59)
	at com.sun.proxy.$Proxy82.execute(Unknown Source)
	at org.apache.ibatis.executor.statement.PreparedStatementHandler.query(PreparedStatementHandler.java:63)
	at org.apache.ibatis.executor.statement.RoutingStatementHandler.query(RoutingStatementHandler.java:79)
	at org.apache.ibatis.executor.SimpleExecutor.doQuery(SimpleExecutor.java:63)
	at org.apache.ibatis.executor.BaseExecutor.queryFromDatabase(BaseExecutor.java:324)
	at org.apache.ibatis.executor.BaseExecutor.query(BaseExecutor.java:156)
	at org.apache.ibatis.executor.CachingExecutor.query(CachingExecutor.java:109)
	at com.github.pagehelper.PageInterceptor.intercept(PageInterceptor.java:136)
	at org.apache.ibatis.plugin.Plugin.invoke(Plugin.java:61)
	at com.sun.proxy.$Proxy78.query(Unknown Source)
	at org.apache.ibatis.session.defaults.DefaultSqlSession.selectList(DefaultSqlSession.java:148)
	at org.apache.ibatis.session.defaults.DefaultSqlSession.selectList(DefaultSqlSession.java:141)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at org.mybatis.spring.SqlSessionTemplate$SqlSessionInterceptor.invoke(SqlSessionTemplate.java:433)
	at com.sun.proxy.$Proxy63.selectList(Unknown Source)
	at org.mybatis.spring.SqlSessionTemplate.selectList(SqlSessionTemplate.java:230)
	at org.apache.ibatis.binding.MapperMethod.executeForMany(MapperMethod.java:137)
	at org.apache.ibatis.binding.MapperMethod.execute(MapperMethod.java:75)
	at org.apache.ibatis.binding.MapperProxy.invoke(MapperProxy.java:59)
	at com.sun.proxy.$Proxy64.searchDomain(Unknown Source)

**Comment by jklliang** [comment]
存在同样问题

**Comment by wu-sheng** [comment]
@ascrutae This is a potential plugin issue.

**Comment by ascrutae** [comment]
Could you post  the `ojbc8` jar to me?

**Comment by clorxd** [comment]
It seems it's to large to post to you. But you can download it from here  http://www.oracle.com/technetwork/database/features/jdbc/jdbc-ucp-122-3110062.html


------------------------------------------------------------------
发件人：Xin,Zhang <notifications@github.com>
发送时间：2018年8月13日(星期一) 14:44
收件人：apache/incubator-skywalking <incubator-skywalking@noreply.github.com>
抄　送：clorxd <clorxd@aliyun.com>; Author <author@noreply.github.com>
主　题：Re: [apache/incubator-skywalking] Exception of oracle plugin (#1391)

Could you post the ojbc8 jar to me?

**Comment by wu-sheng** [comment]
@clorxd See #1571 , hope that will help.
