### ISSUE TITLE
Exception while fetching data (/applicationAlarmList) : all shards failed

### ISSUE THREAD

**Issue by liliang8858** [apache/incubator-skywalking#1399]
Please answer these questions before submitting your issue.

- Why do you submit this issue?
- [ v] Question or discussion
- [ ] Bug
- [ ] Requirement
- [ ] Feature or performance improvement

___
### Question
- Exception while fetching data (/applicationAlarmList) : all shards failed
- Exception while fetching data (/serverAlarmList) : all shards failed

5.0.0 beta

**Comment by wu-sheng** [comment]
I think there are caused by your ES settings. Not relate with SkyWalking.

**Comment by liliang8858** [comment]
@wu-sheng    ES is normal. This error occurred after running for some time

**Comment by wu-sheng** [comment]
> @wu-sheng ES is normal. This error occurred after running for some time

I doubt that. Shards are managed by ElasticSearch itself, not by us.

**Comment by liliang8858** [comment]
@wu-sheng 
`org.apache.skywalking.apm.collector.core.module.ModuleStartException: Field named mi in application_mapping_minute index not found.
        at org.apache.skywalking.apm.collector.storage.es.StorageModuleEsProvider.start(StorageModuleEsProvider.java:300) ~[collector-storage-es-provider-5.0.0-beta-SNAPSHOT.jar:5.0.0-beta-SNAPSHOT]
        at org.apache.skywalking.apm.collector.core.module.BootstrapFlow.start(BootstrapFlow.java:61) ~[apm-collector-core-5.0.0-beta-SNAPSHOT.jar:5.0.0-beta-SNAPSHOT]
        at org.apache.skywalking.apm.collector.core.module.ModuleManager.init(ModuleManager.java:68) ~[apm-collector-core-5.0.0-beta-SNAPSHOT.jar:5.0.0-beta-SNAPSHOT]
        at org.apache.skywalking.apm.collector.boot.CollectorBootStartUp.main(CollectorBootStartUp.java:45) [apm-collector-boot-5.0.0-beta-SNAPSHOT.jar:5.0.0-beta-SNAPSHOT]
Caused by: org.apache.skywalking.apm.collector.storage.StorageInstallException: Field named mi in application_mapping_minute index not found.
        at org.apache.skywalking.apm.collector.storage.es.base.define.ElasticSearchStorageInstaller.columnCheck(ElasticSearchStorageInstaller.java:72) ~[collector-storage-es-provider-5.0.0-beta-SNAPSHOT.jar:5.0.0-beta-SNAPSHOT]
        at org.apache.skywalking.apm.collector.storage.StorageInstaller.install(StorageInstaller.java:60) ~[collector-storage-define-5.0.0-beta-SNAPSHOT.jar:5.0.0-beta-SNAPSHOT]
        at org.apache.skywalking.apm.collector.storage.es.StorageModuleEsProvider.start(StorageModuleEsProvider.java:298) ~[collector-storage-es-provider-5.0.0-beta-SNAPSHOT.jar:5.0.0-beta-SNAPSHOT]
`

**Comment by wu-sheng** [comment]
That is also another issue caused by you, when you do some upgrades, but didn't clear the ES indexes. beta release is incompatible with alpha.

**Comment by liliang8858** [comment]
@wu-sheng  3q    
es: 6.2.3
 collector-libs/elasticsearch-5.5.0.jar   -> collector-libs/elasticsearch-5.6.0.jar

**Comment by cdoewew** [comment]
> @ wu-sheng ES很正常。运行一段时间后发生此错误



> @ wu-sheng 3q 
> es：6.2.3 
> collector-libs / elasticsearch-5.5.0.jar - > collector-libs / elasticsearch-5.6.0.jar


Did you solve it?I had a similar problem, asking for help

**Comment by wu-sheng** [comment]
Es 6 is not supported. Read document please.
