### ISSUE TITLE
Received an instance heart beat message under instance id= 2005 , which doesn't exist 5.0.0 beta

### ISSUE THREAD

**Issue by liliang8858** [apache/incubator-skywalking#1403]
Please answer these questions before submitting your issue.

- Why do you submit this issue?
- [x] Question or discussion
- [ ] Bug
- [ ] Requirement
- [ ] Feature or performance improvement

___
### Question
-  why?
`2018-06-28 15:57:39,974 - org.apache.skywalking.apm.collector.analysis.worker.model.impl.MergePersistenceWorker -361714 [pool-2-thread-1] ERROR [] - Received an instance heart beat message under instance id= 2005 , which doesn't exist.
org.apache.skywalking.apm.collector.core.UnexpectedException: Received an instance heart beat message under instance id= 2005 , which doesn't exist.
        at org.apache.skywalking.apm.collector.storage.es.dao.InstanceHeartBeatEsPersistenceDAO.prepareBatchInsert(InstanceHeartBeatEsPersistenceDAO.java:66) ~[collector-storage-es-provider-5.0.0-beta.jar:5.0.0-beta]
        at org.apache.skywalking.apm.collector.storage.es.dao.InstanceHeartBeatEsPersistenceDAO.prepareBatchInsert(InstanceHeartBeatEsPersistenceDAO.java:39) ~[collector-storage-es-provider-5.0.0-beta.jar:5.0.0-beta]
        at org.apache.skywalking.apm.collector.analysis.worker.model.impl.MergePersistenceWorker.lambda$prepareBatch$5(MergePersistenceWorker.java:64) ~[analysis-worker-model-5.0.0-beta.jar:5.0.0-beta]
        at java.util.LinkedHashMap.forEach(LinkedHashMap.java:684) ~[?:1.8.0_162]
        at org.apache.skywalking.apm.collector.analysis.worker.model.impl.MergePersistenceWorker.prepareBatch(MergePersistenceWorker.java:51) ~[analysis-worker-model-5.0.0-beta.jar:5.0.0-beta]
        at org.apache.skywalking.apm.collector.analysis.worker.model.impl.MergePersistenceWorker.prepareBatch(MergePersistenceWorker.java:33) ~[analysis-worker-model-5.0.0-beta.jar:5.0.0-beta]
        at org.apache.skywalking.apm.collector.analysis.worker.model.impl.PersistenceWorker.buildBatchCollection(PersistenceWorker.java:95) ~[analysis-worker-model-5.0.0-beta.jar:5.0.0-beta]
        at org.apache.skywalking.apm.collector.analysis.worker.timer.PersistenceTimer.lambda$extractDataAndSave$3(PersistenceTimer.java:72) ~[analysis-worker-model-5.0.0-beta.jar:5.0.0-beta]
        at java.lang.Iterable.forEach(Iterable.java:75) ~[?:1.8.0_162]
        at org.apache.skywalking.apm.collector.analysis.worker.timer.PersistenceTimer.extractDataAndSave(PersistenceTimer.java:69) ~[analysis-worker-model-5.0.0-beta.jar:5.0.0-beta]
        at org.apache.skywalking.apm.collector.analysis.worker.timer.PersistenceTimer.lambda$start$1(PersistenceTimer.java:56) ~[analysis-worker-model-5.0.0-beta.jar:5.0.0-beta]
        at org.apache.skywalking.apm.util.RunnableWithExceptionProtection.run(RunnableWithExceptionProtection.java:36) [apm-util-5.0.0-beta.jar:5.0.0-beta]
        at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511) [?:1.8.0_162]
        at java.util.concurrent.FutureTask.runAndReset(FutureTask.java:308) [?:1.8.0_162]
        at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.access$301(ScheduledThreadPoolExecutor.java:180) [?:1.8.0_162]
        at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.run(ScheduledThreadPoolExecutor.java:294) [?:1.8.0_162]
        at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149) [?:1.8.0_162]
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624) [?:1.8.0_162]
        at java.lang.Thread.run(Thread.java:748) [?:1.8.0_162]`

**Comment by wu-sheng** [comment]
Please make sure reboot your application, after you clear your ElasticSearch.
