### ISSUE TITLE
org.apache.skywalking.apm.agent.core.context.ContextManager.capture Caused by: java.lang.NullPointerException: null

### ISSUE THREAD

**Issue by zhaoxunyong** [apache/incubator-skywalking#1424]
Please answer these questions before submitting your issue.

- Why do you submit this issue?
- [x] Question or discussion
- [x] Bug
- [ ] Requirement
- [ ] Feature or performance improvement

___
### Question
- What do you want to know?
When we use skywalking, the following error occurs:
Caused by: java.lang.NullPointerException: null
	at org.apache.skywalking.apm.agent.core.context.ContextManager.capture(ContextManager.java:142)

When I disabled the skywalking, the request was ok.

___
### Bug
- Which version of SkyWalking, OS and JRE?
spring cloud + Feign + hystrix
skywaling: 5.0.0-beta
OS: centos 7
jdk: dk1.8

- Which company or project?

- What happen?
If possible, provide a way for reproducing the error. e.g. demo application, component version.
The full logs  as follows: 
com.netflix.hystrix.exception.HystrixRuntimeException: AccountTitleClientApi#getAllAccountTitleList() failed while executing.
	at com.netflix.hystrix.AbstractCommand.decomposeException(AbstractCommand.java:1591)
	at com.netflix.hystrix.HystrixCommand.execute(HystrixCommand.java:346)
	at feign.hystrix.HystrixInvocationHandler.invoke(HystrixInvocationHandler.java:159)
	at com.sun.proxy.$Proxy219.getAllAccountTitleList(Unknown Source)
	at com.aeasycredit.hkcash.finance.configService.impl.FinanceConfigServerDataApiImpl.getAllAccountTitleList(FinanceConfigServerDataApiImpl.java:77)
	at com.aeasycredit.hkcash.finance.configService.impl.FinanceConfigServerDataApiImpl$$FastClassBySpringCGLIB$$f76b2b17.invoke(<generated>)
	at org.springframework.cglib.proxy.MethodProxy.invoke(MethodProxy.java:204)
	at org.springframework.aop.framework.CglibAopProxy$DynamicAdvisedInterceptor.intercept(CglibAopProxy.java:669)
	at com.aeasycredit.hkcash.finance.configService.impl.FinanceConfigServerDataApiImpl$$EnhancerBySpringCGLIB$$71a9fdc6.getAllAccountTitleList(<generated>)
	at com.aeasycredit.hkcash.finance.configService.impl.FinanceConfigServerDataTransitApiImpl.queryAccountTitleList(FinanceConfigServerDataTransitApiImpl.java:121)
	at com.aeasycredit.hkcash.finance.gl.listener.GlRecordListener.getAccountTitleId(GlRecordListener.java:1068)
	at com.aeasycredit.hkcash.finance.gl.listener.GlRecordListener.createTxFeeGL(GlRecordListener.java:509)
	at com.aeasycredit.hkcash.finance.gl.listener.GlRecordListener.onApplicationEvent(GlRecordListener.java:96)
	at org.springframework.context.event.SimpleApplicationEventMulticaster.invokeListener(SimpleApplicationEventMulticaster.java:167)
	at org.springframework.context.event.SimpleApplicationEventMulticaster.multicastEvent(SimpleApplicationEventMulticaster.java:139)
	at org.springframework.context.support.AbstractApplicationContext.publishEvent(AbstractApplicationContext.java:393)
	at org.springframework.context.support.AbstractApplicationContext.publishEvent(AbstractApplicationContext.java:347)
	at com.aeasycredit.hkcash.finance.loan.transaction.service.coretx.impl.RepaymentTxServiceImpl.processTx(RepaymentTxServiceImpl.java:468)
	at com.aeasycredit.hkcash.finance.loan.transaction.service.impl.CoreTransactionServiceImpl.oneTxProcess(CoreTransactionServiceImpl.java:153)
	at com.aeasycredit.hkcash.finance.loan.transaction.service.impl.CoreTransactionServiceImpl$$FastClassBySpringCGLIB$$2422382a.invoke(<generated>)
	at org.springframework.cglib.proxy.MethodProxy.invoke(MethodProxy.java:204)
	at org.springframework.aop.framework.CglibAopProxy$CglibMethodInvocation.invokeJoinpoint(CglibAopProxy.java:738)
	at org.springframework.aop.framework.ReflectiveMethodInvocation.proceed(ReflectiveMethodInvocation.java:157)
	at org.springframework.transaction.interceptor.TransactionInterceptor$1.proceedWithInvocation(TransactionInterceptor.java:99)
	at org.springframework.transaction.interceptor.TransactionAspectSupport.invokeWithinTransaction(TransactionAspectSupport.java:282)
	at org.springframework.transaction.interceptor.TransactionInterceptor.invoke(TransactionInterceptor.java:96)
	at org.springframework.aop.framework.ReflectiveMethodInvocation.proceed(ReflectiveMethodInvocation.java:179)
	at org.springframework.aop.framework.CglibAopProxy$DynamicAdvisedInterceptor.intercept(CglibAopProxy.java:673)
	at com.aeasycredit.hkcash.finance.loan.transaction.service.impl.CoreTransactionServiceImpl$$EnhancerBySpringCGLIB$$8d8083ea.oneTxProcess(<generated>)
	at com.aeasycredit.hkcash.finance.loan.transaction.service.impl.CoreTxTaskServiceImpl.processTx(CoreTxTaskServiceImpl.java:191)
	at com.aeasycredit.hkcash.finance.loan.transaction.service.impl.CoreTxTaskServiceImpl.lambda$doCoreTxProcess$0(CoreTxTaskServiceImpl.java:86)
	at com.aeasycredit.commons.distributed.lock.redis.RedisLocker.execute(RedisLocker.java:59)
	at com.aeasycredit.hkcash.finance.loan.transaction.service.impl.CoreTxTaskServiceImpl.doCoreTxProcess(CoreTxTaskServiceImpl.java:76)
	at com.aeasycredit.hkcash.finance.loan.transaction.service.impl.CoreTxTaskServiceImpl.lambda$doCoreTxTask$1(CoreTxTaskServiceImpl.java:122)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
	at java.lang.Thread.run(Thread.java:748)
Caused by: java.util.concurrent.ExecutionException: Observable onError
	at rx.internal.operators.BlockingOperatorToFuture$2.getValue(BlockingOperatorToFuture.java:118)
	at rx.internal.operators.BlockingOperatorToFuture$2.get(BlockingOperatorToFuture.java:102)
	at com.netflix.hystrix.HystrixCommand$4.get(HystrixCommand.java:423)
	at com.netflix.hystrix.HystrixCommand.execute(HystrixCommand.java:344)
	... 35 common frames omitted
Caused by: java.lang.NullPointerException: null
	at org.apache.skywalking.apm.agent.core.context.ContextManager.capture(ContextManager.java:142)
	at org.apache.skywalking.apm.plugin.hystrix.v1.SWExecutionHookWrapper.onStart(SWExecutionHookWrapper.java:169)
	at com.netflix.hystrix.AbstractCommand$ExecutionHookDeprecationWrapper.onStart(AbstractCommand.java:2125)
	at com.netflix.hystrix.AbstractCommand$ExecutionHookDeprecationWrapper.onStart(AbstractCommand.java:2132)
	at com.netflix.hystrix.AbstractCommand.applyHystrixSemantics(AbstractCommand.java:520)
	at com.netflix.hystrix.AbstractCommand.access$200(AbstractCommand.java:60)
	at com.netflix.hystrix.AbstractCommand$4.call(AbstractCommand.java:419)
	at com.netflix.hystrix.AbstractCommand$4.call(AbstractCommand.java:413)
	at rx.internal.operators.OnSubscribeDefer.call(OnSubscribeDefer.java:46)
	at rx.internal.operators.OnSubscribeDefer.call(OnSubscribeDefer.java:35)
	at rx.Observable.unsafeSubscribe(Observable.java:10211)
	at rx.internal.operators.OnSubscribeMap.call(OnSubscribeMap.java:48)
	at rx.internal.operators.OnSubscribeMap.call(OnSubscribeMap.java:33)
	at rx.Observable.unsafeSubscribe(Observable.java:10211)
	at rx.internal.operators.OnSubscribeDoOnEach.call(OnSubscribeDoOnEach.java:41)
	at rx.internal.operators.OnSubscribeDoOnEach.call(OnSubscribeDoOnEach.java:30)
	at rx.internal.operators.OnSubscribeLift.call(OnSubscribeLift.java:48)
	at rx.internal.operators.OnSubscribeLift.call(OnSubscribeLift.java:30)
	at rx.Observable.unsafeSubscribe(Observable.java:10211)
	at rx.internal.operators.OnSubscribeDoOnEach.call(OnSubscribeDoOnEach.java:41)
	at rx.internal.operators.OnSubscribeDoOnEach.call(OnSubscribeDoOnEach.java:30)
	at rx.Observable.unsafeSubscribe(Observable.java:10211)
	at rx.internal.operators.OnSubscribeDefer.call(OnSubscribeDefer.java:51)
	at rx.internal.operators.OnSubscribeDefer.call(OnSubscribeDefer.java:35)
	at rx.internal.operators.OnSubscribeLift.call(OnSubscribeLift.java:48)
	at rx.internal.operators.OnSubscribeLift.call(OnSubscribeLift.java:30)
	at rx.Observable.subscribe(Observable.java:10307)
	at rx.Observable.subscribe(Observable.java:10274)
	at rx.internal.operators.BlockingOperatorToFuture.toFuture(BlockingOperatorToFuture.java:51)
	at rx.observables.BlockingObservable.toFuture(BlockingObservable.java:412)
	at com.netflix.hystrix.HystrixCommand.queue(HystrixCommand.java:378)
	... 36 common frames omitted
___
### Requirement or improvement
- Please describe about your requirements or improvement suggestions.

**Comment by zhaoxunyong** [comment]
There is no this problem in v5.0.0-beta2-RC1 version, please close this issue. Thanks.
