### ISSUE TITLE
InvokeForRequestInterceptor throw java.lang.IllegalStateException: No active context

### ISSUE THREAD

**Issue by BlackEragon** [apache/incubator-skywalking#1429]
Please answer these questions before submitting your issue.

- Why do you submit this issue?
- [ ] Question or discussion
- [x ] Bug
- [ ] Requirement
- [ ] Feature or performance improvement

Related issues
#1280
___
### Question
- What do you want to know?
There still have problem in this place. InvokeForRequestInterceptor seems triggered before RestMappingMethodInterceptor in Spring MVC,so there is no active context.Who can help to fix this problem.
___
### Bug
- Which version of SkyWalking, OS and JRE?
5.0.0-beta2
- Which company or project?

- What happen?
If possible, provide a way for reproducing the error. e.g. demo application, component version.

ERROR 2018-07-05 11:12:06 InstMethodsInter :  class[class org.springframework.web.servlet.mvc.method.annotation.ServletInvocableHandlerMethod] before method[invokeForRequest] intercept failure 
java.lang.IllegalStateException: No active context
	at org.apache.skywalking.apm.agent.core.context.ContextManager.getRuntimeContext(ContextManager.java:204)
	at org.apache.skywalking.apm.plugin.spring.mvc.commons.interceptor.InvokeForRequestInterceptor.beforeMethod(InvokeForRequestInterceptor.java:47)
	at org.apache.skywalking.apm.agent.core.plugin.interceptor.enhance.InstMethodsInter.intercept(InstMethodsInter.java:82)
	at org.springframework.web.method.support.InvocableHandlerMethod.invokeForRequest(InvocableHandlerMethod.java)
	at org.springframework.web.servlet.mvc.method.annotation.ServletInvocableHandlerMethod.invokeAndHandle(ServletInvocableHandlerMethod.java:102)
	at org.springframework.web.servlet.mvc.method.annotation.RequestMappingHandlerAdapter.invokeHandlerMethod(RequestMappingHandlerAdapter.java:877)
	at org.springframework.web.servlet.mvc.method.annotation.RequestMappingHandlerAdapter.handleInternal(RequestMappingHandlerAdapter.java:783)
	at org.springframework.web.servlet.mvc.method.AbstractHandlerMethodAdapter.handle(AbstractHandlerMethodAdapter.java:87)
	at org.springframework.web.servlet.DispatcherServlet.doDispatch(DispatcherServlet.java:991)
	at org.springframework.web.servlet.DispatcherServlet.doService(DispatcherServlet.java:925)
	at org.springframework.web.servlet.FrameworkServlet.processRequest(FrameworkServlet.java:974)
	at org.springframework.web.servlet.FrameworkServlet.doPost(FrameworkServlet.java:877)
	at javax.servlet.http.HttpServlet.service(HttpServlet.java:707)
	at org.springframework.web.servlet.FrameworkServlet.service(FrameworkServlet.java:851)
	at javax.servlet.http.HttpServlet.service(HttpServlet.java:790)
	at io.undertow.servlet.handlers.ServletHandler.handleRequest(ServletHandler.java:74)
	at io.undertow.servlet.handlers.FilterHandler$FilterChainImpl.doFilter(FilterHandler.java:129)
	at com.hpe.msp.admin.AccessFilter.doFilterInternal(AccessFilter.java:123)
	at org.springframework.web.filter.OncePerRequestFilter.doFilter(OncePerRequestFilter.java:107)
	at io.undertow.servlet.core.ManagedFilter.doFilter(ManagedFilter.java:61)
	at io.undertow.servlet.handlers.FilterHandler$FilterChainImpl.doFilter(FilterHandler.java:131)

___
### Requirement or improvement
- Please describe about your requirements or improvement suggestions.

**Comment by wu-sheng** [comment]
Could you provide some demo for us?

**Comment by BlackEragon** [comment]
I have test it by myself,and I found the reason.When I use Spring Boot with Tomcat in my previous project,this plugin just work well.
However, my current project is using Spring Boot with Undertow,It throws this exception.

**Comment by BlackEragon** [comment]
I think Undertow plugin was needed,And I will try to implement it by myself.

**Comment by wu-sheng** [comment]
We still need your demo, even you are using undertow.

@ascrutae  Spring MVC should works well, independent on Tomcat.

**Comment by BlackEragon** [comment]
OK,Here is my test demo:https://github.com/BlackEragon/api-demo.git

**Comment by ascrutae** [comment]
This issue is that there isn't any `TraceContext` created before the spring interceptors invoked. because of the spring plugin store the `request` and the `response` object in `RuntimeContext` in `TraceContext`.

@wu-sheng Maybe we can't store  `request` and `response` in `RuntimeContext`. What do you think ?

**Comment by wu-sheng** [comment]
I think you overuse `RuntimeContext`. It is designed for across plugins communication only. Consider to use `TraceContext`.

**Comment by cloudgc** [comment]
it get me all day  and I  read all  code fund it was a bug in springboot ,WTF !!!

**Comment by cloudgc** [comment]
I use TomCat has the same error ,I use Spring Cloud Version : Dalston.SR3
and I  use ctripcorp/apollo as config server

**Comment by wu-sheng** [comment]
You shoud use master codes, it is fixed yesterday.
