### ISSUE TITLE
Enhance class com.mysql.jdbc.PreparedStatement error

### ISSUE THREAD

**Issue by qianshanding** [apache/incubator-skywalking#1430]
Please answer these questions before submitting your issue.

- Why do you submit this issue?
- [ ] Question or discussion
- [ ] Bug
- [ ] Requirement
- [ ] Feature or performance improvement

___
### Question
- What do you want to know?
DEBUG 2018-07-05 17:26:33 AbstractClassEnhancePluginDefine :  prepare to enhance class com.mysql.jdbc.PreparedStatement by org.apache.skywalking.apm.plugin.jdbc.mysql.define.PreparedStatementInstrumentation.
ERROR 2018-07-05 17:26:33 SkyWalkingAgent :  Enhance class com.mysql.jdbc.PreparedStatement error.
org.apache.skywalking.apm.agent.core.plugin.PluginException: Can't create InstanceMethodsAroundInterceptor.
        at org.apache.skywalking.apm.agent.core.plugin.interceptor.enhance.InstMethodsInter.<init>(InstMethodsInter.java:57)
        at org.apache.skywalking.apm.agent.core.plugin.interceptor.enhance.ClassEnhancePluginDefine.enhanceInstance(ClassEnhancePluginDefine.java:161)
        at org.apache.skywalking.apm.agent.core.plugin.interceptor.enhance.ClassEnhancePluginDefine.enhance(ClassEnhancePluginDefine.java:73)
        at org.apache.skywalking.apm.agent.core.plugin.AbstractClassEnhancePluginDefine.define(AbstractClassEnhancePluginDefine.java:75)
        at org.apache.skywalking.apm.agent.SkyWalkingAgent$Transformer.transform(SkyWalkingAgent.java:100)
        at org.apache.skywalking.apm.dependencies.net.bytebuddy.agent.builder.AgentBuilder$Transformer$Compound.transform(AgentBuilder.java:2335)
        at org.apache.skywalking.apm.dependencies.net.bytebuddy.agent.builder.AgentBuilder$Default$Transformation$Simple$Resolution.apply(AgentBuilder.java:8902)
        at org.apache.skywalking.apm.dependencies.net.bytebuddy.agent.builder.AgentBuilder$Default$ExecutingTransformer.doTransform(AgentBuilder.java:9306)
        at org.apache.skywalking.apm.dependencies.net.bytebuddy.agent.builder.AgentBuilder$Default$ExecutingTransformer.transform(AgentBuilder.java:9269)
        at org.apache.skywalking.apm.dependencies.net.bytebuddy.agent.builder.AgentBuilder$Default$ExecutingTransformer.access$1300(AgentBuilder.java:9047)
        at org.apache.skywalking.apm.dependencies.net.bytebuddy.agent.builder.AgentBuilder$Default$ExecutingTransformer$LegacyVmDispatcher.run(AgentBuilder.java:9625)
        at org.apache.skywalking.apm.dependencies.net.bytebuddy.agent.builder.AgentBuilder$Default$ExecutingTransformer$LegacyVmDispatcher.run(AgentBuilder.java:9575)
        at java.security.AccessController.doPrivileged(Native Method)
        at org.apache.skywalking.apm.dependencies.net.bytebuddy.agent.builder.AgentBuilder$Default$ExecutingTransformer.transform(AgentBuilder.java:9194)
        at sun.instrument.TransformerManager.transform(TransformerManager.java:188)
        at sun.instrument.InstrumentationImpl.transform(InstrumentationImpl.java:428)
        at java.lang.ClassLoader.defineClass1(Native Method)
        at java.lang.ClassLoader.defineClass(ClassLoader.java:763)
        at java.security.SecureClassLoader.defineClass(SecureClassLoader.java:142)
        at com.xxx.xxx.container.loader.AbstractCommonClassLoader.defineClass(AbstractCommonClassLoader.java:138)
        at com.xxx.xxx.container.loader.AbstractCommonClassLoader$1.run(AbstractCommonClassLoader.java:159)
        at com.xxx.xxx.container.loader.AbstractCommonClassLoader$1.run(AbstractCommonClassLoader.java:153)
        at java.security.AccessController.doPrivileged(Native Method)
        at com.xxx.xxx.container.loader.AbstractCommonClassLoader.findCustomClass(AbstractCommonClassLoader.java:152)
        at com.xxx.xxx.container.loader.AbstractCommonClassLoader.loadCustomClass(AbstractCommonClassLoader.java:193)
        at com.xxx.xxx.container.loader.AladdinClassLoader.loadClass(AladdinClassLoader.java:110)
        at java.lang.ClassLoader.loadClass(ClassLoader.java:357)
        at java.security.SecureClassLoader.defineClass(SecureClassLoader.java:142)
        at com.xxx.xxx.container.loader.AbstractCommonClassLoader.defineClass(AbstractCommonClassLoader.java:138)
        at com.xxx.xxx.container.loader.AbstractCommonClassLoader$1.run(AbstractCommonClassLoader.java:159)
        at com.xxx.xxx.container.loader.AbstractCommonClassLoader$1.run(AbstractCommonClassLoader.java:153)
        at java.security.AccessController.doPrivileged(Native Method)
        at com.xxx.xxx.container.loader.AbstractCommonClassLoader.findCustomClass(AbstractCommonClassLoader.java:152)
        at com.xxx.xxx.container.loader.AbstractCommonClassLoader.loadCustomClass(AbstractCommonClassLoader.java:193)
        at com.xxx.xxx.container.loader.AladdinClassLoader.loadClass(AladdinClassLoader.java:110)
        at java.lang.ClassLoader.loadClass(ClassLoader.java:357)
        at java.lang.Class.getDeclaredMethods0(Native Method)
        at java.lang.Class.privateGetDeclaredMethods(Class.java:2701)
        at java.lang.Class.privateGetMethodRecursive(Class.java:3048)
        at java.lang.Class.getMethod0(Class.java:3018)
        at java.lang.Class.getMethod(Class.java:1784)
        at com.alibaba.druid.pool.vendor.MySqlValidConnectionChecker.<init>(MySqlValidConnectionChecker.java:54)
        at com.alibaba.druid.pool.DruidDataSource.initValidConnectionChecker(DruidDataSource.java:1159)
        at com.alibaba.druid.pool.DruidDataSource.init(DruidDataSource.java:836)
        at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
        at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
        at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
        at java.lang.reflect.Method.invoke(Method.java:498)
        at org.springframework.beans.factory.support.AbstractAutowireCapableBeanFactory.invokeCustomInitMethod(AbstractAutowireCapableBeanFactory.java:1758)
        at org.springframework.beans.factory.support.AbstractAutowireCapableBeanFactory.invokeInitMethods(AbstractAutowireCapableBeanFactory.java:1695)
        at org.springframework.beans.factory.support.AbstractAutowireCapableBeanFactory.initializeBean(AbstractAutowireCapableBeanFactory.java:1624)
        at org.springframework.beans.factory.support.AbstractAutowireCapableBeanFactory.doCreateBean(AbstractAutowireCapableBeanFactory.java:555)
        at org.springframework.beans.factory.support.AbstractAutowireCapableBeanFactory.createBean(AbstractAutowireCapableBeanFactory.java:483)
        at org.springframework.beans.factory.support.AbstractBeanFactory$1.getObject(AbstractBeanFactory.java:306)
        at org.springframework.beans.factory.support.DefaultSingletonBeanRegistry.getSingleton(DefaultSingletonBeanRegistry.java:230)
        at org.springframework.beans.factory.support.AbstractBeanFactory.doGetBean(AbstractBeanFactory.java:302)
        at org.springframework.beans.factory.support.AbstractBeanFactory.getBean(AbstractBeanFactory.java:202)
        at org.springframework.beans.factory.config.DependencyDescriptor.resolveCandidate(DependencyDescriptor.java:208)
        at org.springframework.beans.factory.support.DefaultListableBeanFactory.doResolveDependency(DefaultListableBeanFactory.java:1138)
        at org.springframework.beans.factory.support.DefaultListableBeanFactory.resolveDependency(DefaultListableBeanFactory.java:1066)
        at org.springframework.beans.factory.support.ConstructorResolver.resolveAutowiredArgument(ConstructorResolver.java:835)
        at org.springframework.beans.factory.support.ConstructorResolver.createArgumentArray(ConstructorResolver.java:741)
       ....
       
![image](https://user-images.githubusercontent.com/26017939/42324011-88ee87c0-8094-11e8-9aae-0585b853da4a.png)

用了java.security.SecureClassLoader.defineClass

如果项目里面用了spring devtool或classloader，有办法可以解决吗？
___
### Bug
- Which version of SkyWalking, OS and JRE?
5.0.0-beta,linux,jdk8
- Which company or project?
company
- What happen?
If possible, provide a way for reproducing the error. e.g. demo application, component version.

___
### Requirement or improvement
- Please describe about your requirements or improvement suggestions.

**Comment by wu-sheng** [comment]
> 如果项目里面用了spring devtool或classloader，有办法可以解决吗？

This is the conflict if you are using Spring devtool. We have a very special mechanism for class loader work with the plugins. 

If you can provide more detail about how your classloader works? We can discuss. If you are using devtool, I don't think we need to fix this, devtool doesn't need in the product or test env, which is APM works.

**Comment by jackzhangsir** [comment]
OK

**Comment by lujiajing1126** [comment]
This incompatibility with devtool has been addressed by PR #6973.

You could try with the master branch or wait for the next release 8.6.0.

Feedback is welcome.
