### ISSUE TITLE
ModuleStartException Field named id in memory_pool_metric_month index not found.

### ISSUE THREAD

**Issue by liliang8858** [apache/incubator-skywalking#1453]
Please answer these questions before submitting your issue.

- Why do you submit this issue?
- [x] Question or discussion
- [ ] Bug
- [ ] Requirement
- [ ] Feature or performance improvement

___
### Question
- `2018-07-13 13:24:55,318 - org.apache.skywalking.apm.collector.boot.CollectorBootStartUp -10989 [main] ERROR [] - Field named id in memory_pool_metric_month index not found.
org.apache.skywalking.apm.collector.core.module.ModuleStartException: Field named id in memory_pool_metric_month index not found.
        at org.apache.skywalking.apm.collector.storage.es.StorageModuleEsProvider.start(StorageModuleEsProvider.java:300) ~[collector-storage-es-provider-5.0.0-beta.jar:5.0.0-beta]
        at org.apache.skywalking.apm.collector.core.module.BootstrapFlow.start(BootstrapFlow.java:61) ~[apm-collector-core-5.0.0-beta.jar:5.0.0-beta]
        at org.apache.skywalking.apm.collector.core.module.ModuleManager.init(ModuleManager.java:68) ~[apm-collector-core-5.0.0-beta.jar:5.0.0-beta]
        at org.apache.skywalking.apm.collector.boot.CollectorBootStartUp.main(CollectorBootStartUp.java:45) [apm-collector-boot-5.0.0-beta.jar:5.0.0-beta]
Caused by: org.apache.skywalking.apm.collector.storage.StorageInstallException: Field named id in memory_pool_metric_month index not found.
        at org.apache.skywalking.apm.collector.storage.es.base.define.ElasticSearchStorageInstaller.columnCheck(ElasticSearchStorageInstaller.java:72) ~[collector-storage-es-provider-5.0.0-beta.jar:5.0.0-beta]
        at org.apache.skywalking.apm.collector.storage.StorageInstaller.install(StorageInstaller.java:60) ~[collector-storage-define-5.0.0-beta.jar:5.0.0-beta]
        at org.apache.skywalking.apm.collector.storage.es.StorageModuleEsProvider.start(StorageModuleEsProvider.java:298) ~[collector-storage-es-provider-5.0.0-beta.jar:5.0.0-beta]
        ... 3 more
`

**Comment by liliang8858** [comment]
What is wrong

**Comment by wu-sheng** [comment]
Don't try to update SkyWalking without deleting the existed es tables.

Simple way, delete es data folder. All data will lose, agent need reboot.
