### ISSUE TITLE
Connect elasticsearch faild.

### ISSUE THREAD

**Issue by JaredTan95** [apache/incubator-skywalking#1458]
Please answer these questions before submitting your issue.

- Why do you submit this issue?
- [☑️] Question or discussion
- [ ] Bug
- [ ] Requirement
- [ ] Feature or performance improvement

___

 When I connect a different host of elasticsearch, always not connected, reported the following exception. But I was successful in using Elasticsearch client to test the connection alone.

```
2018-07-16 11:59:18,771 - org.apache.skywalking.apm.collector.core.data.StorageDefineLoader -37028 [main] INFO  [] - loaded storage definition class: org.apache.skywalking.apm.collector.storage.shardingjdbc.define.mpool.MemoryPoolMonthMetricShardingjdbcTableDefine
Exception in thread "main" NoNodeAvailableException[None of the configured nodes are available: [{#transport#-1}{Ve29DxVDSyCzPnx6-dSKrw}{192.168.2.96}{192.168.2.96:9300}]]
	at org.elasticsearch.client.transport.TransportClientNodesService.ensureNodesAreAvailable(TransportClientNodesService.java:347)
	at org.elasticsearch.client.transport.TransportClientNodesService.execute(TransportClientNodesService.java:245)
	at org.elasticsearch.client.transport.TransportProxyClient.execute(TransportProxyClient.java:59)
	at org.elasticsearch.client.transport.TransportClient.doExecute(TransportClient.java:363)
	at org.elasticsearch.client.support.AbstractClient.execute(AbstractClient.java:408)
	at org.elasticsearch.client.support.AbstractClient$IndicesAdmin.execute(AbstractClient.java:1256)
	at org.elasticsearch.action.ActionRequestBuilder.execute(ActionRequestBuilder.java:80)
	at org.elasticsearch.action.ActionRequestBuilder.execute(ActionRequestBuilder.java:54)
	at org.elasticsearch.action.ActionRequestBuilder.get(ActionRequestBuilder.java:62)
	at org.apache.skywalking.apm.collector.client.elasticsearch.ElasticSearchClient.isExistsIndex(ElasticSearchClient.java:145)
	at org.apache.skywalking.apm.collector.storage.es.base.define.ElasticSearchStorageInstaller.isExists(ElasticSearchStorageInstaller.java:151)
	at org.apache.skywalking.apm.collector.storage.StorageInstaller.install(StorageInstaller.java:52)
	at org.apache.skywalking.apm.collector.storage.es.StorageModuleEsProvider.start(StorageModuleEsProvider.java:125)
	at org.apache.skywalking.apm.collector.core.module.BootstrapFlow.start(BootstrapFlow.java:61)
	at org.apache.skywalking.apm.collector.core.module.ModuleManager.init(ModuleManager.java:68)
	at org.apache.skywalking.apm.collector.boot.CollectorBootStartUp.main(CollectorBootStartUp.java:45)
Disconnected from the target VM, address: '127.0.0.1:64300', transport: 'socket'

Process finished with exit code 1

```

IDE:idea
 Skywalking:5.0.0-RC-SNAPSHOT 、 5.0.0-beta2
OS:Macos
JRE: 1.8+
Elasticsearch:5.6.4

**Comment by wu-sheng** [comment]
Please follow ES documents.

**Comment by JaredTan95** [comment]
Elasticsearch client is the answer. I am using docker deployment es, you can refer to https://github.com/docker-library/elasticsearch/issues/162。If you are only one node, you must turn off the sniff feature.
.put("client.transport.sniff", false)
