### ISSUE TITLE
Exception on startup in beta2 version

### ISSUE THREAD

**Issue by asivanadi** [apache/incubator-skywalking#1461]
Please answer these questions before submitting your issue.

- Why do you submit this issue?
- [ ] Question or discussion
- [-] Bug
- [ ] Requirement
- [ ] Feature or performance improvement

___
### Question
- What do you want to know?

___
### Bug
- Which version of SkyWalking, OS and JRE?
   Skywalk - beta2
   OS - Ubuntu
   JRE - 8
- Which company or project?

- What happen?
If possible, provide a way for reproducing the error. e.g. demo application, component version.
2018-07-16 03:10:15,515 - org.apache.skywalking.apm.collector.analysis.segment.parser.provider.parser.SegmentParse -20788 [grpc-default-executor-2] ERROR [] - null
java.lang.NullPointerException: null
	at org.apache.skywalking.apm.collector.analysis.metric.provider.worker.segment.SegmentDurationSpanListener.build(SegmentDurationSpanListener.java:85) ~[metric-provider-5.0.0-beta2.jar:5.0.0-beta2]
	at java.lang.Iterable.forEach(Iterable.java:75) ~[?:1.8.0_171]
	at org.apache.skywalking.apm.collector.analysis.segment.parser.provider.parser.SegmentParse.notifyListenerToBuild(SegmentParse.java:187) ~[segment-parser-provider-5.0.0-beta2.jar:5.0.0-beta2]
	at org.apache.skywalking.apm.collector.analysis.segment.parser.provider.parser.SegmentParse.parse(SegmentParse.java:81) [segment-parser-provider-5.0.0-beta2.jar:5.0.0-beta2]
	at org.apache.skywalking.apm.collector.analysis.segment.parser.provider.service.SegmentParseService.parse(SegmentParseService.java:42) [segment-parser-provider-5.0.0-beta2.jar:5.0.0-beta2]
	at org.apache.skywalking.apm.collector.agent.grpc.provider.handler.TraceSegmentServiceHandler$1.onNext(TraceSegmentServiceHandler.java:51) [agent-grpc-provider-5.0.0-beta2.jar:5.0.0-beta2]
	at org.apache.skywalking.apm.collector.agent.grpc.provider.handler.TraceSegmentServiceHandler$1.onNext(TraceSegmentServiceHandler.java:45) [agent-grpc-provider-5.0.0-beta2.jar:5.0.0-beta2]
	at io.grpc.stub.ServerCalls$StreamingServerCallHandler$StreamingServerCallListener.onMessage(ServerCalls.java:248) [grpc-stub-1.10.0.jar:1.10.0]
	at io.grpc.internal.ServerCallImpl$ServerStreamListenerImpl.messagesAvailable(ServerCallImpl.java:252) [grpc-core-1.10.0.jar:1.10.0]
	at io.grpc.internal.ServerImpl$JumpToApplicationThreadServerStreamListener$1MessagesAvailable.runInContext(ServerImpl.java:629) [grpc-core-1.10.0.jar:1.10.0]
	at io.grpc.internal.ContextRunnable.run(ContextRunnable.java:37) [grpc-core-1.10.0.jar:1.10.0]
	at io.grpc.internal.SerializingExecutor.run(SerializingExecutor.java:123) [grpc-core-1.10.0.jar:1.10.0]
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149) [?:1.8.0_171]
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624) [?:1.8.0_171]
	at java.lang.Thread.run(Thread.java:748) [?:1.8.0_171]
~
___
### Requirement or improvement
- Please describe about your requirements or improvement suggestions.

**Comment by wu-sheng** [comment]
@peng-yongsheng Can't find out what is happening.

**Comment by ascrutae** [comment]
Sorry for the mistake. I fill the wrong issue id. ignore the the ref.

**Comment by wu-sheng** [comment]
I think this issue is caused by, you have remove all data in ElasticSearch, but don't remove the buffer files(in `/buffer` folder).
