### ISSUE TITLE
None data is show and heartbeat error occured after I restart skywalking

### ISSUE THREAD

**Issue by lovesea42** [apache/incubator-skywalking#1466]
### Bug
- Which version of SkyWalking, OS and JRE?
  5.0.0-beta2  CentOS 7.2   JRE 1.8

- What happen?
I cleared Es data and restart collector and agents.
After I restart,
"Exception while fetching data (/getTopNSlowService) : null" is show on the website.And error occurs in the log of Collector:

`2018-07-17 14:33:45,268 - org.apache.skywalking.apm.collector.analysis.worker.model.impl.MergePersistenceWorker -487126 [pool-2-thread-1] ERROR [] - Received an instance heart beat message under instance id= 29 , which doesn't exist.
org.apache.skywalking.apm.collector.core.UnexpectedException: Received an instance heart beat message under instance id= 29 , which doesn't exist.
	at org.apache.skywalking.apm.collector.storage.es.dao.InstanceHeartBeatEsPersistenceDAO.prepareBatchInsert(InstanceHeartBeatEsPersistenceDAO.java:65) ~[collector-storage-es-provider-5.0.0-beta2.jar:5.0.0-beta2]
	at org.apache.skywalking.apm.collector.storage.es.dao.InstanceHeartBeatEsPersistenceDAO.prepareBatchInsert(InstanceHeartBeatEsPersistenceDAO.java:38) ~[collector-storage-es-provider-5.0.0-beta2.jar:5.0.0-beta2]
	at org.apache.skywalking.apm.collector.analysis.worker.model.impl.MergePersistenceWorker.lambda$prepareBatch$0(MergePersistenceWorker.java:63) ~[analysis-worker-model-5.0.0-beta2.jar:5.0.0-beta2]
	at java.util.LinkedHashMap.forEach(LinkedHashMap.java:684) ~[?:1.8.0_161]
	at org.apache.skywalking.apm.collector.analysis.worker.model.impl.MergePersistenceWorker.prepareBatch(MergePersistenceWorker.java:50) ~[analysis-worker-model-5.0.0-beta2.jar:5.0.0-beta2]
	at org.apache.skywalking.apm.collector.analysis.worker.model.impl.MergePersistenceWorker.prepareBatch(MergePersistenceWorker.java:33) ~[analysis-worker-model-5.0.0-beta2.jar:5.0.0-beta2]
	at org.apache.skywalking.apm.collector.analysis.worker.model.impl.PersistenceWorker.buildBatchCollection(PersistenceWorker.java:91) ~[analysis-worker-model-5.0.0-beta2.jar:5.0.0-beta2]
	at org.apache.skywalking.apm.collector.analysis.worker.timer.PersistenceTimer.lambda$extractDataAndSave$2(PersistenceTimer.java:78) ~[analysis-worker-model-5.0.0-beta2.jar:5.0.0-beta2]
	at java.lang.Iterable.forEach(Iterable.java:75) ~[?:1.8.0_161]
	at org.apache.skywalking.apm.collector.analysis.worker.timer.PersistenceTimer.extractDataAndSave(PersistenceTimer.java:72) ~[analysis-worker-model-5.0.0-beta2.jar:5.0.0-beta2]
	at org.apache.skywalking.apm.collector.analysis.worker.timer.PersistenceTimer.lambda$start$0(PersistenceTimer.java:56) ~[analysis-worker-model-5.0.0-beta2.jar:5.0.0-beta2]
	at org.apache.skywalking.apm.util.RunnableWithExceptionProtection.run(RunnableWithExceptionProtection.java:36) [apm-util-5.0.0-beta2.jar:5.0.0-beta2]
	at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511) [?:1.8.0_161]
	at java.util.concurrent.FutureTask.runAndReset(FutureTask.java:308) [?:1.8.0_161]
	at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.access$301(ScheduledThreadPoolExecutor.java:180) [?:1.8.0_161]
	at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.run(ScheduledThreadPoolExecutor.java:294) [?:1.8.0_161]
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149) [?:1.8.0_161]
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624) [?:1.8.0_161]
	at java.lang.Thread.run(Thread.java:748) [?:1.8.0_161]`

___
### Requirement or improvement
- How to solve the problem "Exception while fetching data (/getTopNSlowService) : null" ?

**Comment by wu-sheng** [comment]
You didn't just reboot, you deleted data in storage. The system can't run in that way. You need to reboot agents too.

**Comment by lovesea42** [comment]
Thanks,I found after I reboot all the agents ,it works
