### ISSUE TITLE
Exception while fetching data (/getTopNApplicationThroughput) : null

### ISSUE THREAD

**Issue by liliang8858** [apache/incubator-skywalking#1474]
Please answer these questions before submitting your issue.

- Why do you submit this issue?
- [x] Question or discussion
- [ ] Bug
- [ ] Requirement
- [ ] Feature or performance improvement

___
### Question
- `2018-07-19 16:25:55,076 - graphql.execution.SimpleDataFetcherExceptionHandler -8079534 [qtp1771292895-186] WARN  [] - Exception while fetching data (/getTopNApplicationThroughput) : null
java.lang.NullPointerException: null
        at org.apache.skywalking.apm.collector.ui.service.ApplicationService.lambda$getTopNApplicationThroughput$11(ApplicationService.java:106) ~[collector-ui-jetty-provider-5.0.0-beta.jar:5.0.0-beta]
        at java.lang.Iterable.forEach(Iterable.java:75) ~[?:1.8.0_162]
        at org.apache.skywalking.apm.collector.ui.service.ApplicationService.getTopNApplicationThroughput(ApplicationService.java:105) ~[collector-ui-jetty-provider-5.0.0-beta.jar:5.0.0-beta]
        at org.apache.skywalking.apm.collector.ui.query.OverViewLayerQuery.getTopNApplicationThroughput(OverViewLayerQuery.java:147) ~[collector-ui-jetty-provider-5.0.0-beta.jar:5.0.0-beta]
        at org.apache.skywalking.apm.collector.ui.query.OverViewLayerQueryMethodAccess.invoke(Unknown Source) ~[reflectasm-1.11.3.jar:5.0.0-beta]
        at com.coxautodev.graphql.tools.MethodFieldResolverDataFetcher.get(MethodFieldResolver.kt:132) ~[graphql-java-tools-4.3.0.jar:?]
        at graphql.execution.ExecutionStrategy.fetchField(ExecutionStrategy.java:219) [graphql-java-6.0.jar:?]
        at graphql.execution.ExecutionStrategy.resolveField(ExecutionStrategy.java:165) [graphql-java-6.0.jar:?]
        at graphql.execution.AsyncExecutionStrategy.execute(AsyncExecutionStrategy.java:55) [graphql-java-6.0.jar:?]
        at graphql.execution.Execution.executeOperation(Execution.java:154) [graphql-java-6.0.jar:?]
        at graphql.execution.Execution.execute(Execution.java:98) [graphql-java-6.0.jar:?]
        at graphql.GraphQL.execute(GraphQL.java:546) [graphql-java-6.0.jar:?]
        at graphql.GraphQL.parseValidateAndExecute(GraphQL.java:488) [graphql-java-6.0.jar:?]
        at graphql.GraphQL.executeAsync(GraphQL.java:463) [graphql-java-6.0.jar:?]
        at graphql.GraphQL.execute(GraphQL.java:394) [graphql-java-6.0.jar:?]`

**Comment by wu-sheng** [comment]
Your collector didn't set up right. Follow documents and logs.

**Comment by liliang8858** [comment]
thanks
