### ISSUE TITLE
agent start error: java.nio.channels.UnresolvedAddressException

### ISSUE THREAD

**Issue by 70995781** [apache/incubator-skywalking#1476]
Please answer these questions before submitting your issue.

- Why do you submit this issue?
- [*] Question or discussion
___
### Question
agent logs has errors:

 `ERROR 2018-07-20 10:23:53 AppAndServiceRegisterClient :  AppAndServiceRegisterClient execute fail. 
org.apache.skywalking.apm.dependencies.io.grpc.StatusRuntimeException: UNKNOWN
        at org.apache.skywalking.apm.dependencies.io.grpc.stub.ClientCalls.toStatusRuntimeException(ClientCalls.java:221)
        at org.apache.skywalking.apm.dependencies.io.grpc.stub.ClientCalls.getUnchecked(ClientCalls.java:202)
        at org.apache.skywalking.apm.dependencies.io.grpc.stub.ClientCalls.blockingUnaryCall(ClientCalls.java:131)
        at org.apache.skywalking.apm.network.proto.ApplicationRegisterServiceGrpc$ApplicationRegisterServiceBlockingStub.applicationCodeRegister(ApplicationRegisterServiceGrpc.java:170)
        at org.apache.skywalking.apm.agent.core.remote.AppAndServiceRegisterClient.run(AppAndServiceRegisterClient.java:112)
        at org.apache.skywalking.apm.util.RunnableWithExceptionProtection.run(RunnableWithExceptionProtection.java:36)
        at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511)
        at java.util.concurrent.FutureTask.runAndReset(FutureTask.java:308)
        at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.access$301(ScheduledThreadPoolExecutor.java:180)
        at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.run(ScheduledThreadPoolExecutor.java:294)
        at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
        at java.lang.Thread.run(Thread.java:748)
**_Caused by: java.nio.channels.UnresolvedAddressException_**
        at sun.nio.ch.Net.checkAddress(Net.java:101)
        at sun.nio.ch.SocketChannelImpl.connect(SocketChannelImpl.java:622)
        at org.apache.skywalking.apm.dependencies.io.netty.util.internal.SocketUtils$3.run(SocketUtils.java:83)
        at org.apache.skywalking.apm.dependencies.io.netty.util.internal.SocketUtils$3.run(SocketUtils.java:80)
        at java.security.AccessController.doPrivileged(Native Method)
        at org.apache.skywalking.apm.dependencies.io.netty.util.internal.SocketUtils.connect(SocketUtils.java:80)
        at org.apache.skywalking.apm.dependencies.io.netty.channel.socket.nio.NioSocketChannel.doConnect(NioSocketChannel.java:308)
        at org.apache.skywalking.apm.dependencies.io.netty.channel.nio.AbstractNioChannel$AbstractNioUnsafe.connect(AbstractNioChannel.java:254)
        at org.apache.skywalking.apm.dependencies.io.netty.channel.DefaultChannelPipeline$HeadContext.connect(DefaultChannelPipeline.java:1291)
        at org.apache.skywalking.apm.dependencies.io.netty.channel.AbstractChannelHandlerContext.invokeConnect(AbstractChannelHandlerContext.java:545)
        at org.apache.skywalking.apm.dependencies.io.netty.channel.AbstractChannelHandlerContext.connect(AbstractChannelHandlerContext.java:530)
        at org.apache.skywalking.apm.dependencies.io.netty.channel.CombinedChannelDuplexHandler$DelegatingChannelHandlerContext.connect(CombinedChannelDuplexHandler.java:497)`

___

**Comment by wu-sheng** [comment]
This is an easy network error. Grpc connection can't establish. Check your setting, network, and firewall.

**Comment by 70995781** [comment]
my java command：
java -jar -Dapp.id=osmc-sms-service -Djava.ext.dirs=../agent/skywalking-agent.jar -Denv=DEV -Dserver.port=2225 -Ddev_meta=http://10.128.190.47:8080 -javaagent:../agent/skywalking-agent.jar -Dskywalking.agent.application_code=osmc-sms-service -Dskywalking.collector.servers=10.128.190.18:10800 -Dapollo.cluster=default target/osmc-sms-service.jar

**Comment by 70995781** [comment]
[root@ossdktest17 logs]# netstat -ano|grep 10800
tcp6       0      0 10.128.190.18:10800     :::*                    LISTEN      off (0.00/0/0)
tcp6       0      0 10.128.190.18:40996     10.128.190.18:10800     TIME_WAIT   timewait (30.41/0/0)
tcp6       0      0 10.128.190.18:40836     10.128.190.18:10800     TIME_WAIT   timewait (9.20/0/0)

**Comment by wu-sheng** [comment]
Are you using ipv6? That is totally a different thing in Java. I have no env to verify that. The easy way is, you use the grpc quick-start demo to test the network on your local machine.

**Comment by 70995781** [comment]
I find the reason：
I have default proxy env 。-DproxyHost=10.128.90.133 -DproxyPort=3122。
removed，it work ok！
