### ISSUE TITLE
elasticsearch 重启后，collector无法启动

### ISSUE THREAD

**Issue by shipengyan** [apache/incubator-skywalking#1489]
Please answer these questions before submitting your issue.

- Why do you submit this issue?
- [x] Question or discussion
- [ ] Bug
- [ ] Requirement
- [ ] Feature or performance improvement

___
### Question
- What do you want to know?
elasticsearch 重启后，collector启动就报错，无法启动了
___
### Bug
- Which version of SkyWalking, OS and JRE?
5.0.0-beta2.jar
centos
jdk8

- Which company or project?

- What happen?
If possible, provide a way for reproducing the error. e.g. demo application, component version.

___
### Requirement or improvement
- Please describe about your requirements or improvement suggestions.

`Field named mi in application_alarm_list_month index not found.` 这个不应该是弱依赖吗？

````
 loaded storage definition class: org.apache.skywalking.apm.collector.storage.es.define.smp.ServiceHourMetricEsTableDefine
2018-07-23 18:09:57,810 - org.apache.skywalking.apm.collector.core.define.DefinitionLoader -13200 [main] INFO  [] - definitionClass: org.apache.skywalking.apm.collector.storage.es.define.gc.GCMinuteMetricEsTableDefine
2018-07-23 18:09:57,810 - org.apache.skywalking.apm.collector.core.data.StorageDefineLoader -13200 [main] INFO  [] - loaded storage definition class: org.apache.skywalking.apm.collector.storage.es.define.gc.GCMinuteMetricEsTableDefine
2018-07-23 18:09:57,985 - org.apache.skywalking.apm.collector.boot.CollectorBootStartUp -13375 [main] ERROR [] - Field named mi in application_alarm_list_month index not found.
org.apache.skywalking.apm.collector.core.module.ModuleStartException: Field named mi in application_alarm_list_month index not found.
        at org.apache.skywalking.apm.collector.storage.es.StorageModuleEsProvider.start(StorageModuleEsProvider.java:127) ~[collector-storage-es-provider-5.0.0-beta2.jar:5.0.0-beta2]
        at org.apache.skywalking.apm.collector.core.module.BootstrapFlow.start(BootstrapFlow.java:61) ~[apm-collector-core-5.0.0-beta2.jar:5.0.0-beta2]
        at org.apache.skywalking.apm.collector.core.module.ModuleManager.init(ModuleManager.java:68) ~[apm-collector-core-5.0.0-beta2.jar:5.0.0-beta2]
        at org.apache.skywalking.apm.collector.boot.CollectorBootStartUp.main(CollectorBootStartUp.java:45) [apm-collector-boot-5.0.0-beta2.jar:5.0.0-beta2]
Caused by: org.apache.skywalking.apm.collector.storage.StorageInstallException: Field named mi in application_alarm_list_month index not found.
        at org.apache.skywalking.apm.collector.storage.es.base.define.ElasticSearchStorageInstaller.columnCheck(ElasticSearchStorageInstaller.java:72) ~[collector-storage-es-provider-5.0.0-beta2.jar:5.0.0-beta2]
        at org.apache.skywalking.apm.collector.storage.StorageInstaller.install(StorageInstaller.java:60) ~[collector-storage-define-5.0.0-beta2.jar:5.0.0-beta2]
        at org.apache.skywalking.apm.collector.storage.es.StorageModuleEsProvider.start(StorageModuleEsProvider.java:125) ~[collector-storage-es-provider-5.0.0-beta2.jar:5.0.0-beta2]
        ... 3 more
````

**Comment by wu-sheng** [comment]
You upgrade to new version, not reboot.
