### ISSUE TITLE
something wrong when running beta2 collector 

### ISSUE THREAD

**Issue by amoyf** [apache/incubator-skywalking#1492]
[ ] Question or discussion
___
### Question
I open the function of zikpin receiver n run the collectorService.sh ,but i found the log that printed show something wrong .how i can solve it.

Here is the message:

org.apache.skywalking.apm.collector.core.module.ModuleStartException: Field named rt in service_name index not found.
	at org.apache.skywalking.apm.collector.storage.es.StorageModuleEsProvider.start(StorageModuleEsProvider.java:127) ~[collector-storage-es-provider-5.0.0-beta2.jar:5.0.0-beta2]
	at org.apache.skywalking.apm.collector.core.module.BootstrapFlow.start(BootstrapFlow.java:61) ~[apm-collector-core-5.0.0-beta2.jar:5.0.0-beta2]
	at org.apache.skywalking.apm.collector.core.module.ModuleManager.init(ModuleManager.java:68) ~[apm-collector-core-5.0.0-beta2.jar:5.0.0-beta2]
	at org.apache.skywalking.apm.collector.boot.CollectorBootStartUp.main(CollectorBootStartUp.java:45) [apm-collector-boot-5.0.0-beta2.jar:5.0.0-beta2]
Caused by: org.apache.skywalking.apm.collector.storage.StorageInstallException: Field named rt in service_name index not found.
	at org.apache.skywalking.apm.collector.storage.es.base.define.ElasticSearchStorageInstaller.columnCheck(ElasticSearchStorageInstaller.java:72) ~[collector-storage-es-provider-5.0.0-beta2.jar:5.0.0-beta2]
	at org.apache.skywalking.apm.collector.storage.StorageInstaller.install(StorageInstaller.java:60) ~[collector-storage-define-5.0.0-beta2.jar:5.0.0-beta2]
	at org.apache.skywalking.apm.collector.storage.es.StorageModuleEsProvider.start(StorageModuleEsProvider.java:125) ~[collector-storage-es-provider-5.0.0-beta2.jar:5.0.0-beta2]
	... 3 more

**Comment by wu-sheng** [comment]
Remove your es data folder. Data structure changed.
