### ISSUE TITLE
RocketMQ NumberFormatException

### ISSUE THREAD

**Issue by Yuanxiangz** [apache/incubator-skywalking#1494]
Please answer these questions before submitting your issue.

- Why do you submit this issue?
- [ ] Question or discussion
- [ ] Bug
- [ ] Requirement
- [ ] Feature or performance improvement

___
### Question
- What do you want to know?

___
### Bug
- Which version of SkyWalking, OS and JRE?
skywalking 5.0.0.RC  rocketmq 4.2.4

- Which company or project?

- What happen?
ERROR 2018-07-24 20:38:27 InstMethodsInter :  class[class org.apache.rocketmq.client.consumer.ConsumerProxy$1] before method[consumeMessage] intercept failure 
java.lang.NumberFormatException: For input string: "OrderDiffQueue/Producer"
	at java.lang.NumberFormatException.forInputString(NumberFormatException.java:65)
	at java.lang.Integer.parseInt(Integer.java:580)
	at java.lang.Integer.parseInt(Integer.java:615)
	at org.apache.skywalking.apm.agent.core.context.trace.TraceSegmentRef.<init>(TraceSegmentRef.java:86)
	at org.apache.skywalking.apm.agent.core.context.TracingContext.extract(TracingContext.java:167)
	at org.apache.skywalking.apm.agent.core.context.ContextManager.createEntrySpan(ContextManager.java:99)
	at org.apache.skywalking.apm.plugin.rocketMQ.v4.AbstractMessageConsumeInterceptor.beforeMethod(AbstractMessageConsumeInterceptor.java:53)
	at org.apache.skywalking.apm.agent.core.plugin.interceptor.enhance.InstMethodsInter.intercept(InstMethodsInter.java:82)
	at org.apache.rocketmq.client.consumer.ConsumerProxy$1.consumeMessage(ConsumerProxy.java)
	at org.apache.rocketmq.client.impl.consumer.ConsumeMessageConcurrentlyService$ConsumeRequest.run(ConsumeMessageConcurrentlyService.java:421)
	at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511)
	at java.util.concurrent.FutureTask.run(FutureTask.java:266)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617)
	at java.lang.Thread.run(Thread.java:748)

___
### Requirement or improvement
- Please describe about your requirements or improvement suggestions.

**Comment by Yuanxiangz** [comment]
should we check and add '#' before entryOperationName  when deserialize text?

D:\Github\incubator-skywalking\apm-sniffer\apm-agent-core\src\main\java\org\apache\skywalking\apm\agent\core\context\ContextCarrier.java
    ContextCarrier deserialize(String text) {
        if (text != null) {
            String[] parts = text.split("\\|", 8);
            if (parts.length == 8) {
                try {
                    this.traceSegmentId = new ID(parts[0]);
                    this.spanId = Integer.parseInt(parts[1]);
                    this.parentApplicationInstanceId = Integer.parseInt(parts[2]);
                    this.entryApplicationInstanceId = Integer.parseInt(parts[3]);
                    this.peerHost = parts[4];
                    this.entryOperationName = parts[5];
                    this.parentOperationName = parts[6];
                    this.primaryDistributedTraceId = new PropagatedTraceId(parts[7]);
                } catch (NumberFormatException e) {

                }
            }
        }
        return this;
    }

**Comment by wu-sheng** [comment]
@Yuanxiangz I am not following. `entryOperationName` should have a `#` prefix in the header. But the carrier has already done this by `ContextCarrier#setParentOperationName`. Are you doing anything, which misses this method when process the header?

**Comment by Yuanxiangz** [comment]
Thanks sheng, I have found the error reason. it's not a skywalking issue. In our test env we use a prefix to tell the different. for the same rocketmq topic like OrderDiffQueue in our T2 env, the topic name will be "T2|OrderDiffQueue". in that case, when skywalking use "|" to split the text will get a wrong result. i will fix it in my private branch to replace "|" in topic to "/". For your question, I have thought the deserialize method's input, the parts[5] may be not start with "#" in some cases.

**Comment by ascrutae** [comment]
I use the `Message#UserProperty` to propagate the trace context. and we didn't change any property of the message in this plugin
