### ISSUE TITLE
InstanceReferenceMetricAlarmAssertWorker NullPointerException

### ISSUE THREAD

**Issue by Yuanxiangz** [apache/incubator-skywalking#1508]
In my collector, there are following errors persisted. It seems some alarms are not found. Should we check null here? Any idea about this? Thanks.

- Why do you submit this issue?
- [ ] Question or discussion
- [ ] Bug
- [ ] Requirement
- [ ] Feature or performance improvement

___
### Question
- What do you want to know?

___
### Bug
- Which version of SkyWalking, OS and JRE?
SkyWalking: 5.0.0.RC   OS: CentOS 6.9

- Which company or project?

- What happen?

2018-07-26 15:40:22,923 - org.apache.skywalking.apm.collector.storage.es.StorageModuleEsProvider -16872225 [pool-7-thread-1] INFO  [] - Current address d9b69998-f116-4205-a61c-dc9149eae234:0 isn't same with the selected first address is f8b17351-8f7c-46a9-b37b-61a206c5f6a9:0. Skip.
2018-07-26 15:42:01,157 - org.apache.skywalking.apm.collector.analysis.worker.model.base.LocalAsyncWorkerRef -16970459 [DataCarrier.Consumser.0.Thread] ERROR [] - null
java.lang.NullPointerException: null
	at org.apache.skywalking.apm.collector.analysis.alarm.provider.worker.instance.InstanceReferenceMetricAlarmAssertWorker.generateAlarmContent(InstanceReferenceMetricAlarmAssertWorker.java:71) ~[alarm-provider-5.0.0-RC-SNAPSHOT.jar:5.0.0-RC-SNAPSHOT]
	at org.apache.skywalking.apm.collector.analysis.alarm.provider.worker.instance.InstanceReferenceMetricAlarmAssertWorker.generateAlarmContent(InstanceReferenceMetricAlarmAssertWorker.java:41) ~[alarm-provider-5.0.0-RC-SNAPSHOT.jar:5.0.0-RC-SNAPSHOT]
	at org.apache.skywalking.apm.collector.analysis.alarm.provider.worker.AlarmAssertWorker.errorRateAlarmAssert(AlarmAssertWorker.java:80) ~[alarm-provider-5.0.0-RC-SNAPSHOT.jar:5.0.0-RC-SNAPSHOT]
	at org.apache.skywalking.apm.collector.analysis.alarm.provider.worker.AlarmAssertWorker.onWork(AlarmAssertWorker.java:46) ~[alarm-provider-5.0.0-RC-SNAPSHOT.jar:5.0.0-RC-SNAPSHOT]
	at org.apache.skywalking.apm.collector.analysis.alarm.provider.worker.AlarmAssertWorker.onWork(AlarmAssertWorker.java:37) ~[alarm-provider-5.0.0-RC-SNAPSHOT.jar:5.0.0-RC-SNAPSHOT]
	at org.apache.skywalking.apm.collector.analysis.worker.model.base.AbstractWorker.process(AbstractWorker.java:57) ~[analysis-worker-model-5.0.0-RC-SNAPSHOT.jar:5.0.0-RC-SNAPSHOT]
	at org.apache.skywalking.apm.collector.core.graph.Node.execute(Node.java:52) ~[apm-collector-core-5.0.0-RC-SNAPSHOT.jar:5.0.0-RC-SNAPSHOT]
	at org.apache.skywalking.apm.collector.core.graph.WayToNode.out(WayToNode.java:40) ~[apm-collector-core-5.0.0-RC-SNAPSHOT.jar:5.0.0-RC-SNAPSHOT]
	at org.apache.skywalking.apm.collector.analysis.worker.model.base.LocalAsyncWorkerRef.out(LocalAsyncWorkerRef.java:78) ~[analysis-worker-model-5.0.0-RC-SNAPSHOT.jar:5.0.0-RC-SNAPSHOT]
	at org.apache.skywalking.apm.collector.analysis.worker.model.base.LocalAsyncWorkerRef.consume(LocalAsyncWorkerRef.java:58) [analysis-worker-model-5.0.0-RC-SNAPSHOT.jar:5.0.0-RC-SNAPSHOT]
	at org.apache.skywalking.apm.commons.datacarrier.consumer.ConsumerThread.consume(ConsumerThread.java:101) [apm-datacarrier-5.0.0-RC-SNAPSHOT.jar:5.0.0-RC-SNAPSHOT]
	at org.apache.skywalking.apm.commons.datacarrier.consumer.ConsumerThread.run(ConsumerThread.java:68) [apm-datacarrier-5.0.0-RC-SNAPSHOT.jar:5.0.0-RC-SNAPSHOT]

___
### Requirement or improvement
- Please describe about your requirements or improvement suggestions.

**Comment by wu-sheng** [comment]
Fixed by #1558
