### ISSUE TITLE
Exception while fetching data (/getClusterTopology) : null

### ISSUE THREAD

**Issue by zyh5160** [apache/incubator-skywalking#1511]
Please answer these questions before submitting your issue.

### Question
**My ES server disk is full, all indexes become red.**
When I delete all the indexes and restart the application, skywalking cannot display the topology map.
When I look at the log, the skywalking-collector-server.log shows this exception.
I want to know how to deal with this problem, thanks to the master.

The following is the exception stack. FYI.
`
2018-08-01 16:41:03,746 - graphql.execution.SimpleDataFetcherExceptionHandler -1500704 [qtp1899433964-134] WARN  [] - Exception while fetching data (/getTopNSlowService) : null
java.lang.NullPointerException: null
        at org.apache.skywalking.apm.collector.ui.service.ServiceNameService.lambda$getSlowService$1(ServiceNameService.java:113) ~[collector-ui-jetty-provider-5.0.0-beta2.jar:5.0.0-beta2]
        at java.lang.Iterable.forEach(Iterable.java:75) ~[?:1.8.0_144]
        at org.apache.skywalking.apm.collector.ui.service.ServiceNameService.getSlowService(ServiceNameService.java:111) ~[collector-ui-jetty-provider-5.0.0-beta2.jar:5.0.0-beta2]
        at org.apache.skywalking.apm.collector.ui.query.OverViewLayerQuery.getTopNSlowService(OverViewLayerQuery.java:139) ~[collector-ui-jetty-provider-5.0.0-beta2.jar:5.0.0-beta2]
        at org.apache.skywalking.apm.collector.ui.query.OverViewLayerQueryMethodAccess.invoke(Unknown Source) ~[reflectasm-1.11.3.jar:5.0.0-beta2]
        at com.coxautodev.graphql.tools.MethodFieldResolverDataFetcher.get(MethodFieldResolver.kt:132) ~[graphql-java-tools-4.3.0.jar:?]
        at graphql.execution.ExecutionStrategy.fetchField(ExecutionStrategy.java:219) [graphql-java-6.0.jar:?]
        at graphql.execution.ExecutionStrategy.resolveField(ExecutionStrategy.java:165) [graphql-java-6.0.jar:?]
        at graphql.execution.AsyncExecutionStrategy.execute(AsyncExecutionStrategy.java:55) [graphql-java-6.0.jar:?]
        at graphql.execution.Execution.executeOperation(Execution.java:154) [graphql-java-6.0.jar:?]
        at graphql.execution.Execution.execute(Execution.java:98) [graphql-java-6.0.jar:?]
        at graphql.GraphQL.execute(GraphQL.java:546) [graphql-java-6.0.jar:?]
        at graphql.GraphQL.parseValidateAndExecute(GraphQL.java:488) [graphql-java-6.0.jar:?]
        at graphql.GraphQL.executeAsync(GraphQL.java:463) [graphql-java-6.0.jar:?]
        at graphql.GraphQL.execute(GraphQL.java:394) [graphql-java-6.0.jar:?]
        at org.apache.skywalking.apm.collector.ui.jetty.handler.GraphQLHandler.execute(GraphQLHandler.java:100) [collector-ui-jetty-provider-5.0.0-beta2.jar:5.0.0-beta2]
        at org.apache.skywalking.apm.collector.ui.jetty.handler.GraphQLHandler.doPost(GraphQLHandler.java:93) [collector-ui-jetty-provider-5.0.0-beta2.jar:5.0.0-beta2]
        at org.apache.skywalking.apm.collector.server.jetty.JettyJsonHandler.doPost(JettyJsonHandler.java:61) [server-component-5.0.0-beta2.jar:5.0.0-beta2]
        at javax.servlet.http.HttpServlet.service(HttpServlet.java:707) [javax.servlet-api-3.1.0.jar:3.1.0]
        at org.apache.skywalking.apm.collector.server.jetty.JettyJsonHandler.service(JettyJsonHandler.java:108) [server-component-5.0.0-beta2.jar:5.0.0-beta2]
        at javax.servlet.http.HttpServlet.service(HttpServlet.java:790) [javax.servlet-api-3.1.0.jar:3.1.0]
        at org.apache.skywalking.apm.collector.server.jetty.JettyJsonHandler.service(JettyJsonHandler.java:112) [server-component-5.0.0-beta2.jar:5.0.0-beta2]
        at org.eclipse.jetty.servlet.ServletHolder.handle(ServletHolder.java:841) [jetty-servlet-9.4.2.v20170220.jar:9.4.2.v20170220]
        at org.eclipse.jetty.servlet.ServletHandler.doHandle(ServletHandler.java:543) [jetty-servlet-9.4.2.v20170220.jar:9.4.2.v20170220]
        at org.eclipse.jetty.server.handler.ScopedHandler.nextHandle(ScopedHandler.java:188) [jetty-server-9.4.2.v20170220.jar:9.4.2.v20170220]
        at org.eclipse.jetty.server.handler.ContextHandler.doHandle(ContextHandler.java:1239) [jetty-server-9.4.2.v20170220.jar:9.4.2.v20170220]
        at org.eclipse.jetty.server.handler.ScopedHandler.nextScope(ScopedHandler.java:168) [jetty-server-9.4.2.v20170220.jar:9.4.2.v20170220]
        at org.eclipse.jetty.servlet.ServletHandler.doScope(ServletHandler.java:481) [jetty-servlet-9.4.2.v20170220.jar:9.4.2.v20170220]
        at org.eclipse.jetty.server.handler.ScopedHandler.nextScope(ScopedHandler.java:166) [jetty-server-9.4.2.v20170220.jar:9.4.2.v20170220]
        at org.eclipse.jetty.server.handler.ContextHandler.doScope(ContextHandler.java:1141) [jetty-server-9.4.2.v20170220.jar:9.4.2.v20170220]
        at org.eclipse.jetty.server.handler.ScopedHandler.handle(ScopedHandler.java:141) [jetty-server-9.4.2.v20170220.jar:9.4.2.v20170220]
        at org.eclipse.jetty.server.handler.HandlerWrapper.handle(HandlerWrapper.java:132) [jetty-server-9.4.2.v20170220.jar:9.4.2.v20170220]
        at org.eclipse.jetty.server.Server.handle(Server.java:564) [jetty-server-9.4.2.v20170220.jar:9.4.2.v20170220]
        at org.eclipse.jetty.server.HttpChannel.handle(HttpChannel.java:320) [jetty-server-9.4.2.v20170220.jar:9.4.2.v20170220]
        at org.eclipse.jetty.server.HttpConnection.onFillable(HttpConnection.java:251) [jetty-server-9.4.2.v20170220.jar:9.4.2.v20170220]
        at org.eclipse.jetty.io.AbstractConnection$ReadCallback.succeeded(AbstractConnection.java:279) [jetty-io-9.4.2.v20170220.jar:9.4.2.v20170220]
        at org.eclipse.jetty.io.FillInterest.fillable(FillInterest.java:110) [jetty-io-9.4.2.v20170220.jar:9.4.2.v20170220]
        at org.eclipse.jetty.io.ChannelEndPoint$2.run(ChannelEndPoint.java:124) [jetty-io-9.4.2.v20170220.jar:9.4.2.v20170220]
        at org.eclipse.jetty.util.thread.Invocable.invokePreferred(Invocable.java:122) [jetty-util-9.4.2.v20170220.jar:9.4.2.v20170220]
        at org.eclipse.jetty.util.thread.strategy.ExecutingExecutionStrategy.invoke(ExecutingExecutionStrategy.java:58) [jetty-util-9.4.2.v20170220.jar:9.4.2.v20170220]
        at org.eclipse.jetty.util.thread.strategy.ExecuteProduceConsume.produceConsume(ExecuteProduceConsume.java:201) [jetty-util-9.4.2.v20170220.jar:9.4.2.v20170220]
        at org.eclipse.jetty.util.thread.strategy.ExecuteProduceConsume.run(ExecuteProduceConsume.java:133) [jetty-util-9.4.2.v20170220.jar:9.4.2.v20170220]
        at org.eclipse.jetty.util.thread.QueuedThreadPool.runJob(QueuedThreadPool.java:672) [jetty-util-9.4.2.v20170220.jar:9.4.2.v20170220]
        at org.eclipse.jetty.util.thread.QueuedThreadPool$2.run(QueuedThreadPool.java:590) [jetty-util-9.4.2.v20170220.jar:9.4.2.v20170220]
`

**Comment by wu-sheng** [comment]
You need to reboot your application under monitoring. Not just collector.

**Comment by zyh5160** [comment]
thank you very much for your reply！
After I restarted all the applications, Tracing is OK, but when I open the dashboard, I still have this problem.
`Exception while fetching data (/getTopNApplicationThroughput) : null`. 

exceptions still exists.


`2018-08-01 17:25:48,873 - graphql.execution.SimpleDataFetcherExceptionHandler -739637 [qtp1899433964-137] WARN  [] - Exception while fetching data (/getTopNApplicationThroughput) : null
java.lang.NullPointerException: null
        at org.apache.skywalking.apm.collector.ui.service.ApplicationService.lambda$getTopNApplicationThroughput$2(ApplicationService.java:108) ~[collector-ui-jetty-provider-5.0.0-beta2.jar:5.0.0-beta2]
        at java.lang.Iterable.forEach(Iterable.java:75) ~[?:1.8.0_144]
        at org.apache.skywalking.apm.collector.ui.service.ApplicationService.getTopNApplicationThroughput(ApplicationService.java:107) ~[collector-ui-jetty-provider-5.0.0-beta2.jar:5.0.0-beta2]
        at org.apache.skywalking.apm.collector.ui.query.OverViewLayerQuery.getTopNApplicationThroughput(OverViewLayerQuery.java:147) ~[collector-ui-jetty-provider-5.0.0-beta2.jar:5.0.0-beta2]
        at org.apache.skywalking.apm.collector.ui.query.OverViewLayerQueryMethodAccess.invoke(Unknown Source) ~[reflectasm-1.11.3.jar:5.0.0-beta2]
        at com.coxautodev.graphql.tools.MethodFieldResolverDataFetcher.get(MethodFieldResolver.kt:132) ~[graphql-java-tools-4.3.0.jar:?]
        at graphql.execution.ExecutionStrategy.fetchField(ExecutionStrategy.java:219) [graphql-java-6.0.jar:?]
        at graphql.execution.ExecutionStrategy.resolveField(ExecutionStrategy.java:165) [graphql-java-6.0.jar:?]
        at graphql.execution.AsyncExecutionStrategy.execute(AsyncExecutionStrategy.java:55) [graphql-java-6.0.jar:?]
        at graphql.execution.Execution.executeOperation(Execution.java:154) [graphql-java-6.0.jar:?]
        at graphql.execution.Execution.execute(Execution.java:98) [graphql-java-6.0.jar:?]
        at graphql.GraphQL.execute(GraphQL.java:546) [graphql-java-6.0.jar:?]
        at graphql.GraphQL.parseValidateAndExecute(GraphQL.java:488) [graphql-java-6.0.jar:?]
        at graphql.GraphQL.executeAsync(GraphQL.java:463) [graphql-java-6.0.jar:?]
        at graphql.GraphQL.execute(GraphQL.java:394) [graphql-java-6.0.jar:?]`

Is it that I missed some steps?

Thank you again, master！
