### ISSUE TITLE
 apm-spring-annotation-plugin grpc exception

### ISSUE THREAD

**Issue by ylywyn** [apache/incubator-skywalking#1526]
Please answer these questions before submitting your issue.

- Why do you submit this issue?
- [ ] Question or discussion
- [ ] Bug
- [ ] Requirement
- [ ] Feature or performance improvement

___
### Question
- What do you want to know?
when not use everything is ok. After using this plugin apm-spring-annotation-plugin-5.0.0-RC-SNAPSHOT.jar,  exception. 
___
### Bug
- Which version of SkyWalking, OS and JRE?
SkyWalking: 5.0.0.RC 
CentOS 7

- Which company or project?

- What happen?
After using this plugin apm-spring-annotation-plugin-5.0.0-RC-SNAPSHOT.jar:
```
ERROR 2018-08-06 15:39:25 TraceSegmentServiceClient :  Send UpstreamSegment to collector fail with a grpc internal exception.
org.apache.skywalking.apm.dependencies.io.grpc.StatusRuntimeException: UNKNOWN
        at org.apache.skywalking.apm.dependencies.io.grpc.Status.asRuntimeException(Status.java:526)
        at org.apache.skywalking.apm.dependencies.io.grpc.stub.ClientCalls$StreamObserverToCallListenerAdapter.onClose(ClientCalls.java:419)
        at org.apache.skywalking.apm.dependencies.io.grpc.ForwardingClientCallListener.onClose(ForwardingClientCallListener.java:41)
        at org.apache.skywalking.apm.dependencies.io.grpc.internal.CensusStatsModule$StatsClientInterceptor$1$1.onClose(CensusStatsModule.java:684)
        at org.apache.skywalking.apm.dependencies.io.grpc.ForwardingClientCallListener.onClose(ForwardingClientCallListener.java:41)
        at org.apache.skywalking.apm.dependencies.io.grpc.internal.CensusTracingModule$TracingClientInterceptor$1$1.onClose(CensusTracingModule.java:391)
        at org.apache.skywalking.apm.dependencies.io.grpc.internal.ClientCallImpl.closeObserver(ClientCallImpl.java:475)
        at org.apache.skywalking.apm.dependencies.io.grpc.internal.ClientCallImpl.access$300(ClientCallImpl.java:63)
        at org.apache.skywalking.apm.dependencies.io.grpc.internal.ClientCallImpl$ClientStreamListenerImpl.close(ClientCallImpl.java:557)
        at org.apache.skywalking.apm.dependencies.io.grpc.internal.ClientCallImpl$ClientStreamListenerImpl.access$600(ClientCallImpl.java:478)
        at org.apache.skywalking.apm.dependencies.io.grpc.internal.ClientCallImpl$ClientStreamListenerImpl$1StreamClosed.runInContext(ClientCallImpl.java:590)
        at org.apache.skywalking.apm.dependencies.io.grpc.internal.ContextRunnable.run(ContextRunnable.java:37)
        at org.apache.skywalking.apm.dependencies.io.grpc.internal.SerializingExecutor.run(SerializingExecutor.java:123)
        at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142)
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617)
        at java.lang.Thread.run(Thread.java:745)
```
___
### Requirement or improvement
- Please describe about your requirements or improvement suggestions.

**Comment by wu-sheng** [comment]
This is nothing about the `apm-spring-annotation-plugin`. This exception means agent can't connect or uplink data to backend/collector.

**Comment by ylywyn** [comment]
may be apm-spring-annotation-plugin  create much more spans. I have tried it many times，remove this  plugin everything is ok,    after adding  exceptions will occur

**Comment by wu-sheng** [comment]
> may be apm-spring-annotation-plugin create much more spans. I have tried it many times，remove this plugin everything is ok, after adding exceptions will occur

No. I am pretty sure, this error is nothing about the plugin. If spans trigger something wrong, should have collector side's log or memory related error.

gRPC transports bytes to backend, even don't know the span concept.

**Comment by ylywyn** [comment]
adding this plugin there is another exception when  start  app with agent:
`WARN  TracingContext :  More than 300 spans required to create
java.lang.RuntimeException: Shadow tracing context. Thread dump
        at org.apache.skywalking.apm.agent.core.context.TracingContext.isLimitMechanismWorking(TracingContext.java:515)
        at org.apache.skywalking.apm.agent.core.context.TracingContext.createLocalSpan(TracingContext.java:290)
        at org.apache.skywalking.apm.agent.core.context.ContextManager.createLocalSpan(ContextManager.java:110)
        at org.apache.skywalking.apm.plugin.spring.annotations.SpringAnnotationInterceptor.beforeMethod(SpringAnnotationInterceptor.java:32)
        at org.apache.skywalking.apm.agent.core.plugin.interceptor.enhance.InstMethodsInter.intercept(InstMethodsInter.java:89)
        at springfox.documentation.schema.property.ObjectMapperBeanPropertyNamingStrategy.nameForDeserialization(ObjectMapperBeanPropertyNamingStrategy.java)
        at springfox.documentation.schema.property.BeanPropertyDefinitions.name(BeanPropertyDefinitions.java:48)
        at springfox.documentation.schema.property.OptimizedModelPropertiesProvider.beanModelProperty(OptimizedModelPropertiesProvider.java:281)
        at springfox.documentation.schema.property.OptimizedModelPropertiesProvider.access$200(OptimizedModelPropertiesProvider.java:79)
        at springfox.documentation.schema.property.OptimizedModelPropertiesProvider$2.apply(OptimizedModelPropertiesProvider.java:163)
        at springfox.documentation.schema.property.OptimizedModelPropertiesProvider$2.apply(OptimizedModelPropertiesProvider.java:155)
        at com.google.common.base.Present.transform(Present.java:79)`

**Comment by wu-sheng** [comment]
That [warn] means you are trying to create over 300 spans in a single segment. I wonder this is your real purpose. It is very dangerous for your memory.

**Comment by ylywyn** [comment]
These are automatically generated. what should I do?

**Comment by wu-sheng** [comment]
> These are automatically generated. what should I do?

I don't know what does your application do, and why do you have so many spans in a single request. Only you or your team can say this is reasonable or some incompatible bug. I don't know, sorry.
