### ISSUE TITLE
Use mysql as storage failure.

### ISSUE THREAD

**Issue by spy1988** [apache/incubator-skywalking#1529]
Please answer these questions before submitting your issue.

- Why do you submit this issue?
- [x] Question or discussion
- [x] Bug
- [ ] Requirement
- [ ] Feature or performance improvement

___
### Question
- What do you want to know?
使用mysql作为存储层

___
### Bug
- Which version of SkyWalking, OS and JRE?
5.0.0-beta2

- Which company or project?

- What happen?
If possible, provide a way for reproducing the error. e.g. demo application, component version.

___
### Requirement or improvement
- Please describe about your requirements or improvement suggestions.

````
2018-08-07 14:37:03,389 - org.apache.skywalking.apm.collector.boot.CollectorBootStartUp -2323 [main] ERROR [] - Service:org.apache.skywalking.apm.collector.storage.ttl.ITTLConfigService not provided
org.apache.skywalking.apm.collector.core.module.ServiceNotProvidedException: Service:org.apache.skywalking.apm.collector.storage.ttl.ITTLConfigService not provided
        at org.apache.skywalking.apm.collector.core.module.ModuleProvider.requiredCheck(ModuleProvider.java:110) ~[apm-collector-core-5.0.0-beta2.jar:5.0.0-beta2]
        at org.apache.skywalking.apm.collector.core.module.BootstrapFlow.start(BootstrapFlow.java:59) ~[apm-collector-core-5.0.0-beta2.jar:5.0.0-beta2]
        at org.apache.skywalking.apm.collector.core.module.ModuleManager.init(ModuleManager.java:68) ~[apm-collector-core-5.0.0-beta2.jar:5.0.0-beta2]
        at org.apache.skywalking.apm.collector.boot.CollectorBootStartUp.main(CollectorBootStartUp.java:45) [apm-collector-boot-5.0.0-beta2.jar:5.0.0-beta2]
2018-08-07 14:43:49,413 - org.apache.skywalking.apm.collector.boot.config.ApplicationConfigLoader -1263 [main] INFO  [] - Get a module define from application.yml, mo
````

**Comment by wu-sheng** [comment]
We don't include MySQL storage provider. What do you mean?

**Comment by wu-sheng** [comment]
@shipengyan You could try to fix this by adding a new service.

@chidaodezhongsheng This may be caused by your contributions. Could you please help to fix that? 

FYI @terrymanum

**Comment by chenyi19851209** [comment]
hello, skywalking 5.0.0-GA version can support shardingjdbc storage ? have related docs ? thank you for you answer.

**Comment by chenyi19851209** [comment]
你好。skywalking 5.0.0-GA按照这个文档https://github.com/apache/incubator-skywalking/blob/5.x/docs/cn/Use-ShardingJDBC-as-storage-implementor-CN.md 配置，会出现以下报错，请问有办法解决吗？

2018-10-23 11:22:10,099 - org.apache.skywalking.apm.collector.boot.CollectorBootStartUp -1193 [main] ERROR [] - Service:org.apache.skywalking.apm.collector.storage.ttl.ITTLConfigService not provided
org.apache.skywalking.apm.collector.core.module.ServiceNotProvidedException: Service:org.apache.skywalking.apm.collector.storage.ttl.ITTLConfigService not provided
        at org.apache.skywalking.apm.collector.core.module.ModuleProvider.requiredCheck(ModuleProvider.java:110) ~[apm-collector-core-5.0.0-GA.jar:5.0.0-GA]
        at org.apache.skywalking.apm.collector.core.module.BootstrapFlow.start(BootstrapFlow.java:59) ~[apm-collector-core-5.0.0-GA.jar:5.0.0-GA]
        at org.apache.skywalking.apm.collector.core.module.ModuleManager.init(ModuleManager.java:68) ~[apm-collector-core-5.0.0-GA.jar:5.0.0-GA]
        at org.apache.skywalking.apm.collector.boot.CollectorBootStartUp.main(CollectorBootStartUp.java:45) [apm-collector-boot-5.0.0-GA.jar:5.0.0-GA]

**Comment by chenyi19851209** [comment]
@chidaodezhongsheng

**Comment by wu-sheng** [comment]
Yes, @chidaodezhongsheng is the one taking responsibilities for this feature. 

From the log, look like he missed a required service to provide. Need to add the missing one.

**Comment by mackwan84** [comment]
I met the same issue with Sharding JDBC storage.

**Comment by wu-sheng** [comment]
Ping @terrymanu @tristaZero @tuohai666

I just ping the Sharding-Sphere committers, hope they could provide helps. As I said, the codes for this storage solution, it may not be ready.

**Comment by terrymanu** [comment]
any error log about sharding-jdbc? Maybe I can find some hints.

**Comment by wu-sheng** [comment]
> any error log about sharding-jdbc? Maybe I can find some hints.

I doubt these is sharding jdbc 's bug. This most likely because the sharding jdbc storage implementor can't work.

**Comment by terrymanu** [comment]
ok, I will have a look

**Comment by tuohai666** [comment]
@spy1988 @chenyi19851209 
hi, which version of Sharding-Sphere?

**Comment by chidaodezhongsheng** [comment]
I have added the ttl config service and fix the bug.Thanks a lot @chenyi19851209

**Comment by wu-sheng** [comment]
@chidaodezhongsheng Your PR target is incorrect. Please send to 5.x branch.

**Comment by wu-sheng** [comment]
@spy1988 Try the latest `5.x` branch codes. Submit new if there are new bugs showing up.

**Comment by nadirakdag** [comment]
Hello, I am trying to use 5.0 GA version with mysql but getting exception which is bellow, can you guys help me ?

2018-12-25 15:47:15,818 - org.apache.skywalking.apm.collector.boot.CollectorBootStartUp -1017 [main] ERROR [] - Service:org.apache.skywalking.apm.collector.storage.ttl.ITTLConfigService not provided
org.apache.skywalking.apm.collector.core.module.ServiceNotProvidedException: Service:org.apache.skywalking.apm.collector.storage.ttl.ITTLConfigService not provided
	at org.apache.skywalking.apm.collector.core.module.ModuleProvider.requiredCheck(ModuleProvider.java:110) ~[apm-collector-core-5.0.0-GA.jar:5.0.0-GA]
	at org.apache.skywalking.apm.collector.core.module.BootstrapFlow.start(BootstrapFlow.java:59) ~[apm-collector-core-5.0.0-GA.jar:5.0.0-GA]
	at org.apache.skywalking.apm.collector.core.module.ModuleManager.init(ModuleManager.java:68) ~[apm-collector-core-5.0.0-GA.jar:5.0.0-GA]
	at org.apache.skywalking.apm.collector.boot.CollectorBootStartUp.main(CollectorBootStartUp.java:45) [apm-collector-boot-5.0.0-GA.jar:5.0.0-GA]

**Comment by wu-sheng** [comment]
@nadirakdag Only 6.x supports MySQL as storage. Please try 6.0.0beta release.
