### ISSUE TITLE
exception occurred

### ISSUE THREAD

**Issue by Fly-fly-bibiQ** [apache/incubator-skywalking#1561]
Please answer these questions before submitting your issue.

- Why do you submit this issue?
- [√ ] Question or discussion
- [ ] Bug
- [ ] Requirement
- [ ] Feature or performance improvement

___
### Question
- What do you want to know?
Something unusual has happened, but I don't know what's wrong. Can I get your help?
org.apache.skywalking.apm.collector.core.module.ModuleStartException: Field named ac in application index not found.
	at org.apache.skywalking.apm.collector.storage.es.StorageModuleEsProvider.start(StorageModuleEsProvider.java:127) ~[collector-storage-es-provider-5.0.0-beta2.jar:5.0.0-beta2]
	at org.apache.skywalking.apm.collector.core.module.BootstrapFlow.start(BootstrapFlow.java:61) ~[apm-collector-core-5.0.0-beta2.jar:5.0.0-beta2]
	at org.apache.skywalking.apm.collector.core.module.ModuleManager.init(ModuleManager.java:68) ~[apm-collector-core-5.0.0-beta2.jar:5.0.0-beta2]
	at org.apache.skywalking.apm.collector.boot.CollectorBootStartUp.main(CollectorBootStartUp.java:45) [apm-collector-boot-5.0.0-beta2.jar:5.0.0-beta2]
Caused by: org.apache.skywalking.apm.collector.storage.StorageInstallException: Field named ac in application index not found.
	at org.apache.skywalking.apm.collector.storage.es.base.define.ElasticSearchStorageInstaller.columnCheck(ElasticSearchStorageInstaller.java:72) ~[collector-storage-es-provider-5.0.0-beta2.jar:5.0.0-beta2]
	at org.apache.skywalking.apm.collector.storage.StorageInstaller.install(StorageInstaller.java:60) ~[collector-storage-define-5.0.0-beta2.jar:5.0.0-beta2]
	at org.apache.skywalking.apm.collector.storage.es.StorageModuleEsProvider.start(StorageModuleEsProvider.java:125) ~[collector-storage-es-provider-5.0.0-beta2.jar:5.0.0-beta2]

- Please describe about your requirements or improvement suggestions.

**Comment by wu-sheng** [comment]
You upgrade backend, ElasticSearch should be reset. You could remove data folder.
