### ISSUE TITLE
DubboInterceptor

### ISSUE THREAD

**Issue by IanCao** [apache/incubator-skywalking#1579]
Version 5.0.0-beta2
- Why do you submit this issue?
- [ ] Bug

ERROR 2018-08-21 10:58:30 InstMethodsInter :  class[class com.alibaba.dubbo.monitor.support.MonitorFilter] after method[invoke] intercept failure 
java.lang.NullPointerException
	at org.apache.skywalking.apm.agent.core.context.ContextManager.activeSpan(ContextManager.java:155)
	at org.apache.skywalking.apm.agent.core.context.ContextManager.stopSpan(ContextManager.java:159)
	at org.apache.skywalking.apm.plugin.dubbo.DubboInterceptor.afterMethod(DubboInterceptor.java:101)
	at org.apache.skywalking.apm.agent.core.plugin.interceptor.enhance.InstMethodsInter.intercept(InstMethodsInter.java:105)
	at com.alibaba.dubbo.monitor.support.MonitorFilter.invoke(MonitorFilter.java)
	at com.alibaba.dubbo.rpc.protocol.ProtocolFilterWrapper$1.invoke(ProtocolFilterWrapper.java:68)
	at com.alibaba.dubbo.rpc.protocol.dubbo.filter.TraceFilter.invoke(TraceFilter.java:78)
	at com.alibaba.dubbo.rpc.protocol.ProtocolFilterWrapper$1.invoke(ProtocolFilterWrapper.java:68)
	at com.lianjia.trace.filter.ProviderFilter.invoke(ProviderFilter.java:38)
	at com.alibaba.dubbo.rpc.protocol.ProtocolFilterWrapper$1.invoke(ProtocolFilterWrapper.java:68)
	at com.alibaba.dubbo.rpc.filter.ContextFilter.invoke$dkimi$impl(ContextFilter.java:60)
	at com.alibaba.dubbo.rpc.filter.ContextFilter.invoke(ContextFilter.java)
	at com.alibaba.dubbo.rpc.protocol.ProtocolFilterWrapper$1.invoke(ProtocolFilterWrapper.java:68)
	at com.alibaba.dubbo.rpc.filter.GenericFilter.invoke(GenericFilter.java:132)
	at com.alibaba.dubbo.rpc.protocol.ProtocolFilterWrapper$1.invoke(ProtocolFilterWrapper.java:68)
	at com.alibaba.dubbo.rpc.filter.ClassLoaderFilter.invoke(ClassLoaderFilter.java:38)
	at com.alibaba.dubbo.rpc.protocol.ProtocolFilterWrapper$1.invoke(ProtocolFilterWrapper.java:68)
	at com.alibaba.dubbo.rpc.filter.EchoFilter.invoke(EchoFilter.java:38)
	at com.alibaba.dubbo.rpc.protocol.ProtocolFilterWrapper$1.invoke(ProtocolFilterWrapper.java:68)
	at com.alibaba.dubbo.rpc.protocol.dubbo.DubboProtocol$1.reply(DubboProtocol.java:108)
	at com.alibaba.dubbo.remoting.exchange.support.header.HeaderExchangeHandler.handleRequest(HeaderExchangeHandler.java:84)
	at com.alibaba.dubbo.remoting.exchange.support.header.HeaderExchangeHandler.received(HeaderExchangeHandler.java:170)
	at com.alibaba.dubbo.remoting.transport.DecodeHandler.received(DecodeHandler.java:52)
	at com.alibaba.dubbo.remoting.transport.dispatcher.ChannelEventRunnable.run(ChannelEventRunnable.java:82)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1145)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:615)
	at java.lang.Thread.run(Thread.java:745)

**Comment by wu-sheng** [comment]
Which dubbo version?

**Comment by IanCao** [comment]
1.0.1.0, but i still can not understand why.....  there is no error log in beforeMethod and the span should  be put into threadLocal.

**Comment by wu-sheng** [comment]
Dubbo 1.0? Really have this version?

**Comment by IanCao** [comment]
im sorry.. the dubbo version is 2.5.4 ... the 1.0.1.0 is a private packaged dubbo based on 2.5.4 ......

**Comment by wu-sheng** [comment]
Dubbo 2.5.4 passed from our automatically daily test report. You can find it here: https://github.com/SkywalkingTest/agent-integration-test-report#dubbo All cases are open sourced too, https://github.com/SkywalkingTest/skywalking-agent-testcases/tree/master/dubbo-scenario

You need to provide more things, I suggest you compare your codes with our cases, may find a clue?

**Comment by IanCao** [comment]
ok  i'll find more info to solve this NPE
