### ISSUE TITLE
InstanceMetricAlarmAssertWorker NullPointerException

### ISSUE THREAD

**Issue by Yuanxiangz** [apache/incubator-skywalking#1598]
Please answer these questions before submitting your issue.

- Why do you submit this issue?
- [ ] Question or discussion
- [ ] Bug
- [ ] Requirement
- [ ] Feature or performance improvement

___
### Question
- What do you want to know?

___
### Bug
- Which version of SkyWalking, OS and JRE?
skywalking 5.0.0.RC

- Which company or project?

- What happen?
If possible, provide a way for reproducing the error. e.g. demo application, component version.
a similar issue like #1508

2018-08-28 20:04:03,201 - org.apache.skywalking.apm.collector.analysis.worker.model.base.LocalAsyncWorkerRef -86292978 [DataCarrier.Consumser.0.Thread] ERROR [] - null
java.lang.NullPointerException: null
	at org.apache.skywalking.apm.collector.analysis.alarm.provider.worker.instance.InstanceMetricAlarmAssertWorker.generateAlarmContent(InstanceMetricAlarmAssertWorker.java:69) ~[alarm-provider-5.0.0-RC-SNAPSHOT.jar:5.0.0-RC-SNAPSHOT]
	at org.apache.skywalking.apm.collector.analysis.alarm.provider.worker.instance.InstanceMetricAlarmAssertWorker.generateAlarmContent(InstanceMetricAlarmAssertWorker.java:41) ~[alarm-provider-5.0.0-RC-SNAPSHOT.jar:5.0.0-RC-SNAPSHOT]
	at org.apache.skywalking.apm.collector.analysis.alarm.provider.worker.AlarmAssertWorker.errorRateAlarmAssert(AlarmAssertWorker.java:80) ~[alarm-provider-5.0.0-RC-SNAPSHOT.jar:5.0.0-RC-SNAPSHOT]
	at org.apache.skywalking.apm.collector.analysis.alarm.provider.worker.AlarmAssertWorker.onWork(AlarmAssertWorker.java:46) ~[alarm-provider-5.0.0-RC-SNAPSHOT.jar:5.0.0-RC-SNAPSHOT]
	at org.apache.skywalking.apm.collector.analysis.alarm.provider.worker.AlarmAssertWorker.onWork(AlarmAssertWorker.java:37) ~[alarm-provider-5.0.0-RC-SNAPSHOT.jar:5.0.0-RC-SNAPSHOT]
	at org.apache.skywalking.apm.collector.analysis.worker.model.base.AbstractWorker.process(AbstractWorker.java:57) ~[analysis-worker-model-5.0.0-RC-SNAPSHOT.jar:5.0.0-RC-SNAPSHOT]
	at org.apache.skywalking.apm.collector.core.graph.Node.execute(Node.java:52) ~[apm-collector-core-5.0.0-RC-SNAPSHOT.jar:5.0.0-RC-SNAPSHOT]
	at org.apache.skywalking.apm.collector.core.graph.WayToNode.out(WayToNode.java:40) ~[apm-collector-core-5.0.0-RC-SNAPSHOT.jar:5.0.0-RC-SNAPSHOT]
	at org.apache.skywalking.apm.collector.analysis.worker.model.base.LocalAsyncWorkerRef.out(LocalAsyncWorkerRef.java:78) ~[analysis-worker-model-5.0.0-RC-SNAPSHOT.jar:5.0.0-RC-SNAPSHOT]
	at org.apache.skywalking.apm.collector.analysis.worker.model.base.LocalAsyncWorkerRef.consume(LocalAsyncWorkerRef.java:58) [analysis-worker-model-5.0.0-RC-SNAPSHOT.jar:5.0.0-RC-SNAPSHOT]
	at org.apache.skywalking.apm.commons.datacarrier.consumer.ConsumerThread.consume(ConsumerThread.java:101) [apm-datacarrier-5.0.0-RC-SNAPSHOT.jar:5.0.0-RC-SNAPSHOT]
	at org.apache.skywalking.apm.commons.datacarrier.consumer.ConsumerThread.run(ConsumerThread.java:68) [apm-datacarrier-5.0.0-RC-SNAPSHOT.jar:5.0.0-RC-SNAPSHOT]
2018-08-28 20:04:08,186 - org.apache.skywalking.apm.collector.analysis.worker.model.base.LocalAsyncWorkerRef -86297963 [DataCarrier.Consumser.0.Thread] ERROR [] - null
java.lang.NullPointerException: null
	at org.apache.skywalking.apm.collector.analysis.alarm.provider.worker.instance.InstanceMetricAlarmAssertWorker.generateAlarmContent(InstanceMetricAlarmAssertWorker.java:69) ~[alarm-provider-5.0.0-RC-SNAPSHOT.jar:5.0.0-RC-SNAPSHOT]
	at org.apache.skywalking.apm.collector.analysis.alarm.provider.worker.instance.InstanceMetricAlarmAssertWorker.generateAlarmContent(InstanceMetricAlarmAssertWorker.java:41) ~[alarm-provider-5.0.0-RC-SNAPSHOT.jar:5.0.0-RC-SNAPSHOT]
	at org.apache.skywalking.apm.collector.analysis.alarm.provider.worker.AlarmAssertWorker.averageResponseTimeAlarmAssert(AlarmAssertWorker.java:116) ~[alarm-provider-5.0.0-RC-SNAPSHOT.jar:5.0.0-RC-SNAPSHOT]
	at org.apache.skywalking.apm.collector.analysis.alarm.provider.worker.AlarmAssertWorker.onWork(AlarmAssertWorker.java:47) ~[alarm-provider-5.0.0-RC-SNAPSHOT.jar:5.0.0-RC-SNAPSHOT]
	at org.apache.skywalking.apm.collector.analysis.alarm.provider.worker.AlarmAssertWorker.onWork(AlarmAssertWorker.java:37) ~[alarm-provider-5.0.0-RC-SNAPSHOT.jar:5.0.0-RC-SNAPSHOT]
	at org.apache.skywalking.apm.collector.analysis.worker.model.base.AbstractWorker.process(AbstractWorker.java:57) ~[analysis-worker-model-5.0.0-RC-SNAPSHOT.jar:5.0.0-RC-SNAPSHOT]
	at org.apache.skywalking.apm.collector.core.graph.Node.execute(Node.java:52) ~[apm-collector-core-5.0.0-RC-SNAPSHOT.jar:5.0.0-RC-SNAPSHOT]
	at org.apache.skywalking.apm.collector.core.graph.WayToNode.out(WayToNode.java:40) ~[apm-collector-core-5.0.0-RC-SNAPSHOT.jar:5.0.0-RC-SNAPSHOT]
	at org.apache.skywalking.apm.collector.analysis.worker.model.base.LocalAsyncWorkerRef.out(LocalAsyncWorkerRef.java:78) ~[analysis-worker-model-5.0.0-RC-SNAPSHOT.jar:5.0.0-RC-SNAPSHOT]
	at org.apache.skywalking.apm.collector.analysis.worker.model.base.LocalAsyncWorkerRef.consume(LocalAsyncWorkerRef.java:58) [analysis-worker-model-5.0.0-RC-SNAPSHOT.jar:5.0.0-RC-SNAPSHOT]
	at org.apache.skywalking.apm.commons.datacarrier.consumer.ConsumerThread.consume(ConsumerThread.java:101) [apm-datacarrier-5.0.0-RC-SNAPSHOT.jar:5.0.0-RC-SNAPSHOT]
	at org.apache.skywalking.apm.commons.datacarrier.consumer.ConsumerThread.run(ConsumerThread.java:68) [apm-datacarrier-5.0.0-RC-SNAPSHOT.jar:5.0.0-RC-SNAPSHOT]

___
### Requirement or improvement
- Please describe about your requirements or improvement suggestions.

**Comment by wu-sheng** [comment]
#1508 fixed in RC. Try RC release.

**Comment by Yuanxiangz** [comment]
@wu-sheng   #1508 fixed part of it.  following file also need to be changed
alarm-provider/src/main/java/org/apache/skywalking/apm/collector/analysis/alarm/provider/worker/instance/InstanceMetricAlarmAssertWorker.java

**Comment by wu-sheng** [comment]
@Yuanxiangz If current master codes are still not right, don't hesitate, send the PR.

**Comment by wu-sheng** [comment]
Sorry, not master codes, 5.x branch codes.

**Comment by Yuanxiangz** [comment]
@wu-sheng  I found it fixed in #1614 after checked out the latest code.

**Comment by wu-sheng** [comment]
Yes. New release happens next week. I hope.
