### ISSUE TITLE
collector.log  Exception in thread "main" java.lang.NullPointerException

### ISSUE THREAD

**Issue by liliang8858** [apache/incubator-skywalking#1599]
Please answer these questions before submitting your issue.

- Why do you submit this issue?
- [x] Question or discussion
- [ ] Bug
- [ ] Requirement
- [ ] Feature or performance improvement

___
### Question
- What do you want to know?
`Exception in thread "main" java.lang.NullPointerException
        at org.apache.skywalking.apm.collector.analysis.segment.parser.provider.buffer.Offset.deserialize(Offset.java:42)
        at org.apache.skywalking.apm.collector.analysis.segment.parser.provider.buffer.OffsetManager.initialize(OffsetManager.java:71)
        at org.apache.skywalking.apm.collector.analysis.segment.parser.provider.buffer.SegmentBufferManager.initialize(SegmentBufferManager.java:42)
        at org.apache.skywalking.apm.collector.analysis.segment.parser.provider.parser.standardization.SegmentStandardizationWorker.<init>(SegmentStandardizationWorker.java:42)
        at org.apache.skywalking.apm.collector.analysis.segment.parser.provider.parser.standardization.SegmentStandardizationWorker.<init>(SegmentStandardizationWorker.java:36)
        at org.apache.skywalking.apm.collector.analysis.segment.parser.provider.parser.standardization.SegmentStandardizationWorker$Factory.workerInstance(SegmentStandardizationWorker.java:64)
        at org.apache.skywalking.apm.collector.analysis.segment.parser.provider.parser.standardization.SegmentStandardizationWorker$Factory.workerInstance(SegmentStandardizationWorker.java:57)
        at org.apache.skywalking.apm.collector.analysis.worker.model.base.AbstractLocalAsyncWorkerProvider.create(AbstractLocalAsyncWorkerProvider.java:38)
        at org.apache.skywalking.apm.collector.analysis.segment.parser.provider.parser.standardization.SegmentStandardizationGraph.create(SegmentStandardizationGraph.java:41)
        at org.apache.skywalking.apm.collector.analysis.segment.parser.provider.AnalysisSegmentParserModuleProvider.graphCreate(AnalysisSegmentParserModuleProvider.java:89)
        at org.apache.skywalking.apm.collector.analysis.segment.parser.provider.AnalysisSegmentParserModuleProvider.start(AnalysisSegmentParserModuleProvider.java:73)
        at org.apache.skywalking.apm.collector.core.module.BootstrapFlow.start(BootstrapFlow.java:61)
        at org.apache.skywalking.apm.collector.core.module.ModuleManager.init(ModuleManager.java:68)
        at org.apache.skywalking.apm.collector.boot.CollectorBootStartUp.main(CollectorBootStartUp.java:45)`
___

**Comment by liliang8858** [comment]
elasticsearch-6.4.0
skywalking  newest

**Comment by wu-sheng** [comment]
First of all, es 6 is not supported. Then, why do you env have buffer data?

**Comment by wu-sheng** [comment]
I said, if you are new, why do you have buffer files? If you don't know, try to clear the `buffer` folder, then reboot.
