### ISSUE TITLE
java.lang.StackOverflowError with skywalking SpringAnnotationInterceptor

### ISSUE THREAD

**Issue by voidmanun** [apache/incubator-skywalking#1613]
Please answer these questions before submitting your issue.

- Why do you submit this issue?
- [ ] Question or discussion
- [X] Bug
- [ ] Requirement
- [ ] Feature or performance improvement

___
### Bug
- Which version of SkyWalking, OS and JRE?
5.0.0-RC-SNAPSHOT
- Which company or project?
here is the demo project 
[demo.zip](https://github.com/apache/incubator-skywalking/files/2338600/demo.zip)
run the UnitTest DemoServiceTest
- What happen?
If possible, provide a way for reproducing the error. e.g. demo application, component version.

*** java.lang.instrument ASSERTION FAILED ***: "!errorOutstanding" with message transform method call failed at JPLISAgent.c line: 844

java.lang.StackOverflowError
	at org.apache.skywalking.apm.agent.core.logging.core.EasyLogger.format(EasyLogger.java:79)
	at org.apache.skywalking.apm.agent.core.logging.core.EasyLogger.format(EasyLogger.java:73)
	at org.apache.skywalking.apm.agent.core.logging.core.EasyLogger.logger(EasyLogger.java:46)
	at org.apache.skywalking.apm.agent.core.logging.core.EasyLogger.error(EasyLogger.java:123)
	at org.apache.skywalking.apm.agent.core.plugin.interceptor.enhance.InstMethodsInter.intercept(InstMethodsInter.java:100)
	at com.yunxiao.apm.demo.DemoService.process(DemoService.java)
	at com.yunxiao.apm.demo.SuperDemoService.process(SuperDemoService.java)
	at com.yunxiao.apm.demo.DemoService.process$accessor$lcM0Ri93(DemoService.java)
	at com.yunxiao.apm.demo.DemoService$auxiliary$kFixME2T.call(Unknown Source)
	at org.apache.skywalking.apm.agent.core.plugin.interceptor.enhance.InstMethodsInter.intercept(InstMethodsInter.java:93)
	at com.yunxiao.apm.demo.DemoService.process(DemoService.java)
	at com.yunxiao.apm.demo.SuperDemoService.process(SuperDemoService.java)
	at com.yunxiao.apm.demo.DemoService.process$accessor$lcM0Ri93(DemoService.java)
	at com.yunxiao.apm.demo.DemoService$auxiliary$kFixME2T.call(Unknown Source)
	at org.apache.skywalking.apm.agent.core.plugin.interceptor.enhance.InstMethodsInter.intercept(InstMethodsInter.java:93)
	at com.yunxiao.apm.demo.DemoService.process(DemoService.java)
	at com.yunxiao.apm.demo.SuperDemoService.process(SuperDemoService.java)
	at com.yunxiao.apm.demo.DemoService.process$accessor$lcM0Ri93(DemoService.java)
	at com.yunxiao.apm.demo.DemoService$auxiliary$kFixME2T.call(Unknown Source)
	at org.apache.skywalking.apm.agent.core.plugin.interceptor.enhance.InstMethodsInter.intercept(InstMethodsInter.java:93)
	at com.yunxiao.apm.demo.DemoService.process(DemoService.java)
	at com.yunxiao.apm.demo.SuperDemoService.process(SuperDemoService.java)
	at com.yunxiao.apm.demo.DemoService.process$accessor$lcM0Ri93(DemoService.java)
	at com.yunxiao.apm.demo.DemoService$auxiliary$kFixME2T.call(Unknown Source)
	at org.apache.skywalking.apm.agent.core.plugin.interceptor.enhance.InstMethodsInter.intercept(InstMethodsInter.java:93)
	at com.yunxiao.apm.demo.DemoService.process(DemoService.java)
	at com.yunxiao.apm.demo.SuperDemoService.process(SuperDemoService.java)
	at com.yunxiao.apm.demo.DemoService.process$accessor$lcM0Ri93(DemoService.java)
	at com.yunxiao.apm.demo.DemoService$auxiliary$kFixME2T.call(Unknown Source)
	at org.apache.skywalking.apm.agent.core.plugin.interceptor.enhance.InstMethodsInter.intercept(InstMethodsInter.java:93)
	at com.yunxiao.apm.demo.DemoService.process(DemoService.java)
	at com.yunxiao.apm.demo.SuperDemoService.process(SuperDemoService.java)
	at com.yunxiao.apm.demo.DemoService.process$accessor$lcM0Ri93(DemoService.java)
	at com.yunxiao.apm.demo.DemoService$auxiliary$kFixME2T.call(Unknown Source)
	at org.apache.skywalking.apm.agent.core.plugin.interceptor.enhance.InstMethodsInter.intercept(InstMethodsInter.java:93)
	at com.yunxiao.apm.demo.DemoService.process(DemoService.java)
	at com.yunxiao.apm.demo.SuperDemoService.process(SuperDemoService.java)
	at com.yunxiao.apm.demo.DemoService.process$accessor$lcM0Ri93(DemoService.java)
	at com.yunxiao.apm.demo.DemoService$auxiliary$kFixME2T.call(Unknown Source)
	at org.apache.skywalking.apm.agent.core.plugin.interceptor.enhance.InstMethodsInter.intercept(InstMethodsInter.java:93)
	at com.yunxiao.apm.demo.DemoService.process(DemoService.java)
	at com.yunxiao.apm.demo.SuperDemoService.process(SuperDemoService.java)
	at com.yunxiao.apm.demo.DemoService.process$accessor$lcM0Ri93(DemoService.java)
	at com.yunxiao.apm.demo.DemoService$auxiliary$kFixME2T.call(Unknown Source)
	at org.apache.skywalking.apm.agent.core.plugin.interceptor.enhance.InstMethodsInter.intercept(InstMethodsInter.java:93)
	at com.yunxiao.apm.demo.DemoService.process(DemoService.java)
	at com.yunxiao.apm.demo.SuperDemoService.process(SuperDemoService.java)
	at com.yunxiao.apm.demo.DemoService.process$accessor$lcM0Ri93(DemoService.java)
	at com.yunxiao.apm.demo.DemoService$auxiliary$kFixME2T.call(Unknown Source)
	at org.apache.skywalking.apm.agent.core.plugin.interceptor.enhance.InstMethodsInter.intercept(InstMethodsInter.java:93)
	at com.yunxiao.apm.demo.DemoService.process(DemoService.java)
	at com.yunxiao.apm.demo.SuperDemoService.process(SuperDemoService.java)
	at com.yunxiao.apm.demo.DemoService.process$accessor$lcM0Ri93(DemoService.java)
	at com.yunxiao.apm.demo.DemoService$auxiliary$kFixME2T.call(Unknown Source)
	at org.apache.skywalking.apm.agent.core.plugin.interceptor.enhance.InstMethodsInter.intercept(InstMethodsInter.java:93)
	at com.yunxiao.apm.demo.DemoService.process(DemoService.java)
	at com.yunxiao.apm.demo.SuperDemoService.process(SuperDemoService.java)
	at com.yunxiao.apm.demo.DemoService.process$accessor$lcM0Ri93(DemoService.java)
	at com.yunxiao.apm.demo.DemoService$auxiliary$kFixME2T.call(Unknown Source)
	at org.apache.skywalking.apm.agent.core.plugin.interceptor.enhance.InstMethodsInter.intercept(InstMethodsInter.java:93)
	at com.yunxiao.apm.demo.DemoService.process(DemoService.java)
	at com.yunxiao.apm.demo.SuperDemoService.process(SuperDemoService.java)
	at com.yunxiao.apm.demo.DemoService.process$accessor$lcM0Ri93(DemoService.java)
	at com.yunxiao.apm.demo.DemoService$auxiliary$kFixME2T.call(Unknown Source)
	at org.apache.skywalking.apm.agent.core.plugin.interceptor.enhance.InstMethodsInter.intercept(InstMethodsInter.java:93)
	at com.yunxiao.apm.demo.DemoService.process(DemoService.java)
	at com.yunxiao.apm.demo.SuperDemoService.process(SuperDemoService.java)
	at com.yunxiao.apm.demo.DemoService.process$accessor$lcM0Ri93(DemoService.java)
	at com.yunxiao.apm.demo.DemoService$auxiliary$kFixME2T.call(Unknown Source)
	at org.apache.skywalking.apm.agent.core.plugin.interceptor.enhance.InstMethodsInter.intercept(InstMethodsInter.java:93)
	at com.yunxiao.apm.demo.DemoService.process(DemoService.java)
	at com.yunxiao.apm.demo.SuperDemoService.process(SuperDemoService.java)
	at com.yunxiao.apm.demo.DemoService.process$accessor$lcM0Ri93(DemoService.java)
	at com.yunxiao.apm.demo.DemoService$auxiliary$kFixME2T.call(Unknown Source)
	at org.apache.skywalking.apm.agent.core.plugin.interceptor.enhance.InstMethodsInter.intercept(InstMethodsInter.java:93)
	at com.yunxiao.apm.demo.DemoService.process(DemoService.java)
	at com.yunxiao.apm.demo.SuperDemoService.process(SuperDemoService.java)
	at com.yunxiao.apm.demo.DemoService.process$accessor$lcM0Ri93(DemoService.java)
	at com.yunxiao.apm.demo.DemoService$auxiliary$kFixME2T.call(Unknown Source)
	at org.apache.skywalking.apm.agent.core.plugin.interceptor.enhance.InstMethodsInter.intercept(InstMethodsInter.java:93)
	at com.yunxiao.apm.demo.DemoService.process(DemoService.java)
	at com.yunxiao.apm.demo.SuperDemoService.process(SuperDemoService.java)
	at com.yunxiao.apm.demo.DemoService.process$accessor$lcM0Ri93(DemoService.java)
	at com.yunxiao.apm.demo.DemoService$auxiliary$kFixME2T.call(Unknown Source)
	at org.apache.skywalking.apm.agent.core.plugin.interceptor.enhance.InstMethodsInter.intercept(InstMethodsInter.java:93)
	at com.yunxiao.apm.demo.DemoService.process(DemoService.java)
	at com.yunxiao.apm.demo.SuperDemoService.process(SuperDemoService.java)
	at com.yunxiao.apm.demo.DemoService.process$accessor$lcM0Ri93(DemoService.java)
	at com.yunxiao.apm.demo.DemoService$auxiliary$kFixME2T.call(Unknown Source)
	at org.apache.skywalking.apm.agent.core.plugin.interceptor.enhance.InstMethodsInter.intercept(InstMethodsInter.java:93)
	at com.yunxiao.apm.demo.DemoService.process(DemoService.java)
	at com.yunxiao.apm.demo.SuperDemoService.process(SuperDemoService.java)

___
### Requirement or improvement
- Please describe about your requirements or improvement suggestions.

**Comment by voidmanun** [comment]
`public abstract class AriesAbstractProcessor<T> {

    public void process(T context) throws Exception {
            System.err.println("-----" + this.toString());
            doProcess(context);
    }

    protected abstract void doProcess(T context) throws Exception;
}`

if without T ,it process ok

**Comment by wu-sheng** [comment]
I am not sure. Why intercept this method? I haven't done that before.

**Comment by voidmanun** [comment]
```
@Service
public class SuperDemoService extends AriesAbstractProcessor<UseCaseFrameContext> {
    @Override
    protected void doProcess(UseCaseFrameContext context) throws Exception {
        System.out.println("SuperDemoService doProcess");
    }
}
```
intercept this method

**Comment by voidmanun** [comment]
[Demo.zip](https://github.com/apache/incubator-skywalking/files/2338600/demo.zip)
a simple springboot project for this case
run the UT

**Comment by wu-sheng** [comment]
@ascrutae consider to have to try?

**Comment by ascrutae** [comment]
I have try this demoI with the latest agent , and I can't reproduce this issue. 

I had add an Controller to call `demoService.process` method and Here is the sample data:
```
segmentItems:
- applicationCode: test-demo
  segmentSize: 1
  segments:
  - segmentId: 1.46.15377571935560000
    spans:
    - operationName: /test
      operationId: 0
      parentSpanId: -1
      spanId: 0
      spanLayer: Http
      startTime: 1537757193560
      endTime: 1537757193676
      componentId: 14
      componentName: ''
      isError: false
      spanType: Entry
      peer: ''
      peerId: 0
      tags:
      - {key: url, value: 'http://localhost:8080/test'}
      - {key: http.method, value: GET}
```

**Comment by wu-sheng** [comment]
Remove milestone for now. Wait for any updates. Thanks @ascrutae

**Comment by voidmanun** [comment]
@ascrutae witch version of agent？
