### ISSUE TITLE
Field named rt in service_name index not found.

### ISSUE THREAD

**Issue by ranmao** [apache/incubator-skywalking#1656]
2018-09-11 14:58:27,416 - org.apache.skywalking.apm.collector.boot.CollectorBootStartUp -21342 [main] ERROR [] - Field named rt in service_name index not found.
org.apache.skywalking.apm.collector.core.module.ModuleStartException: Field named rt in service_name index not found.
	at org.apache.skywalking.apm.collector.storage.es.StorageModuleEsProvider.start(StorageModuleEsProvider.java:127) ~[collector-storage-es-provider-5.0.0-beta2.jar:5.0.0-beta2]
	at org.apache.skywalking.apm.collector.core.module.BootstrapFlow.start(BootstrapFlow.java:61) ~[apm-collector-core-5.0.0-beta2.jar:5.0.0-beta2]
	at org.apache.skywalking.apm.collector.core.module.ModuleManager.init(ModuleManager.java:68) ~[apm-collector-core-5.0.0-beta2.jar:5.0.0-beta2]
	at org.apache.skywalking.apm.collector.boot.CollectorBootStartUp.main(CollectorBootStartUp.java:45) [apm-collector-boot-5.0.0-beta2.jar:5.0.0-beta2]
Caused by: org.apache.skywalking.apm.collector.storage.StorageInstallException: Field named rt in service_name index not found.
	at org.apache.skywalking.apm.collector.storage.es.base.define.ElasticSearchStorageInstaller.columnCheck(ElasticSearchStorageInstaller.java:72) ~[collector-storage-es-provider-5.0.0-beta2.jar:5.0.0-beta2]
	at org.apache.skywalking.apm.collector.storage.StorageInstaller.install(StorageInstaller.java:60) ~[collector-storage-define-5.0.0-beta2.jar:5.0.0-beta2]
	at org.apache.skywalking.apm.collector.storage.es.StorageModuleEsProvider.start(StorageModuleEsProvider.java:125) ~[collector-storage-es-provider-5.0.0-beta2.jar:5.0.0-beta2]
	... 3 more

**Comment by wu-sheng** [comment]
If you do upgrade, es need to rebuild. Please reset your es.
