### ISSUE TITLE
got a problem

### ISSUE THREAD

**Issue by chtel** [apache/incubator-skywalking#1689]
Please answer these questions before submitting your issue.

- Why do you submit this issue?
- [x] Question or discussion
- [ ] Bug
- [ ] Requirement
- [ ] Feature or performance improvement

___
### Question
- What do you want to know?

___
### Bug
- Which version of SkyWalking, OS and JRE?

- Which company or project?

- What happen?
If possible, provide a way for reproducing the error. e.g. demo application, component version.
I got a problem :
DEBUG 2018-09-21 16:46:12:844 AppAndServiceRegisterClient :  AppAndServiceRegisterClient running, status:DISCONNECT.
DEBUG 2018-09-21 16:46:15:844 AppAndServiceRegisterClient :  AppAndServiceRegisterClient running, status:DISCONNECT.
DEBUG 2018-09-21 16:46:18:844 AppAndServiceRegisterClient :  AppAndServiceRegisterClient running, status:DISCONNECT.
DEBUG 2018-09-21 16:46:21:844 AppAndServiceRegisterClient :  AppAndServiceRegisterClient running, status:DISCONNECT.
DEBUG 2018-09-21 16:46:24:844 AppAndServiceRegisterClient :  AppAndServiceRegisterClient running, status:DISCONNECT.
DEBUG 2018-09-21 16:46:27:844 AppAndServiceRegisterClient :  AppAndServiceRegisterClient running, status:DISCONNECT.
DEBUG 2018-09-21 16:46:30:844 AppAndServiceRegisterClient :  AppAndServiceRegisterClient running, status:DISCONNECT.
DEBUG 2018-09-21 16:46:33:835 GRPCChannelManager :  Selected collector grpc service running, reconnect:true.
DEBUG 2018-09-21 16:46:33:835 GRPCChannelManager :  Selected collector grpc service is not available. Wait 30 seconds to retry
ERROR 2018-09-21 16:46:33:840 DiscoveryRestServiceClient :  Find server list fail.
org.apache.skywalking.apm.dependencies.org.apache.http.conn.HttpHostConnectException: Connect to 127.0.0.1:10800 [/127.0.0.1] failed: Connection refused (Connection refused)
        at org.apache.skywalking.apm.dependencies.org.apache.http.impl.conn.DefaultHttpClientConnectionOperator.connect(DefaultHttpClientConnectionOperator.java:159)
        at org.apache.skywalking.apm.dependencies.org.apache.http.impl.conn.PoolingHttpClientConnectionManager.connect(PoolingHttpClientConnectionManager.java:359)
        at org.apache.skywalking.apm.dependencies.org.apache.http.impl.execchain.MainClientExec.establishRoute(MainClientExec.java:381)
        at org.apache.skywalking.apm.dependencies.org.apache.http.impl.execchain.MainClientExec.execute(MainClientExec.java:237)
        at org.apache.skywalking.apm.dependencies.org.apache.http.impl.execchain.ProtocolExec.execute(ProtocolExec.java:185)
        at org.apache.skywalking.apm.dependencies.org.apache.http.impl.execchain.RetryExec.execute(RetryExec.java:89)
        at org.apache.skywalking.apm.dependencies.org.apache.http.impl.execchain.RedirectExec.execute(RedirectExec.java:111)
        at org.apache.skywalking.apm.dependencies.org.apache.http.impl.client.InternalHttpClient.doExecute(InternalHttpClient.java:185)
        at org.apache.skywalking.apm.dependencies.org.apache.http.impl.client.CloseableHttpClient.execute(CloseableHttpClient.java:83)
        at org.apache.skywalking.apm.dependencies.org.apache.http.impl.client.CloseableHttpClient.execute(CloseableHttpClient.java:108)
        at org.apache.skywalking.apm.agent.core.remote.DiscoveryRestServiceClient.findServerList(DiscoveryRestServiceClient.java:88)
        at org.apache.skywalking.apm.agent.core.remote.DiscoveryRestServiceClient.run(DiscoveryRestServiceClient.java:77)
        at org.apache.skywalking.apm.util.RunnableWithExceptionProtection.run(RunnableWithExceptionProtection.java:36)
        at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511)
        at java.util.concurrent.FutureTask.runAndReset(FutureTask.java:308)
        at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.access$301(ScheduledThreadPoolExecutor.java:180)
        at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.run(ScheduledThreadPoolExecutor.java:294)
        at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
        at java.lang.Thread.run(Thread.java:748)
Caused by: java.net.ConnectException: Connection refused (Connection refused)
        at java.net.PlainSocketImpl.socketConnect(Native Method)
        at java.net.AbstractPlainSocketImpl.doConnect(AbstractPlainSocketImpl.java:350)
        at java.net.AbstractPlainSocketImpl.connectToAddress(AbstractPlainSocketImpl.java:206)
        at java.net.AbstractPlainSocketImpl.connect(AbstractPlainSocketImpl.java:188)
        at java.net.SocksSocketImpl.connect(SocksSocketImpl.java:392)
        at java.net.Socket.connect(Socket.java:589)
        at org.apache.skywalking.apm.dependencies.org.apache.http.conn.socket.PlainConnectionSocketFactory.connectSocket(PlainConnectionSocketFactory.java:75)
        at org.apache.skywalking.apm.dependencies.org.apache.http.impl.conn.DefaultHttpClientConnectionOperator.connect(DefaultHttpClientConnectionOperator.java:142)
        ... 19 more

DEBUG 2018-09-21 16:46:33:844 AppAndServiceRegisterClient :  AppAndServiceRegisterClient running, status:DISCONNECT.
DEBUG 2018-09-21 16:46:36:844 AppAndServiceRegisterClient :  AppAndServiceRegisterClient running, status:DISCONNECT.
DEBUG 2018-09-21 16:46:39:844 AppAndServiceRegisterClient :  AppAndServiceRegisterClient running, status:DISCONNECT.
DEBUG 2018-09-21 16:46:42:844 AppAndServiceRegisterClient :  AppAndServiceRegisterClient running, status:DISCONNECT.
DEBUG 2018-09-21 16:46:45:844 AppAndServiceRegisterClient :  AppAndServiceRegisterClient running, status:DISCONNECT.
DEBUG 2018-09-21 16:46:48:844 AppAndServiceRegisterClient :  AppAndServiceRegisterClient running, status:DISCONNECT.
DEBUG 2018-09-21 16:46:51:844 AppAndServiceRegisterClient :  AppAndServiceRegisterClient running, status:DISCONNECT.
DEBUG 2018-09-21 16:46:54:844 AppAndServiceRegisterClient :  AppAndServiceRegisterClient running, status:DISCONNECT.
DEBUG 2018-09-21 16:46:57:844 AppAndServiceRegisterClient :  AppAndServiceRegisterClient running, status:DISCONNECT.
DEBUG 2018-09-21 16:47:00:844 AppAndServiceRegisterClient :  AppAndServiceRegisterClient running, status:DISCONNECT.
DEBUG 2018-09-21 16:47:03:835 GRPCChannelManager :  Selected collector grpc service running, reconnect:true.
DEBUG 2018-09-21 16:47:03:835 GRPCChannelManager :  Selected collector grpc service is not available. Wait 30 seconds to retry
DEBUG 2018-09-21 16:47:03:844 AppAndServiceRegisterClient :  AppAndServiceRegisterClient running, status:DISCONNECT.
DEBUG 2018-09-21 16:47:06:844 AppAndServiceRegisterClient :  AppAndServiceRegisterClient running, status:DISCONNECT.
DEBUG 2018-09-21 16:47:09:844 AppAndServiceRegisterClient :  AppAndServiceRegisterClient running, status:DISCONNECT.

---------------------------------------------------------------------------
INFO 2018-09-21 16:48:04:397 AgentClassLoader :  /usr/local/test/walk/sw/agent/activations/apm-toolkit-log4j-1.x-activation-5.0.0-RC2.jar loaded.
INFO 2018-09-21 16:48:04:398 AgentClassLoader :  /usr/local/test/walk/sw/agent/activations/apm-toolkit-log4j-2.x-activation-5.0.0-RC2.jar loaded.
INFO 2018-09-21 16:48:04:400 AgentClassLoader :  /usr/local/test/walk/sw/agent/activations/apm-toolkit-logback-1.x-activation-5.0.0-RC2.jar loaded.
INFO 2018-09-21 16:48:04:400 AgentClassLoader :  /usr/local/test/walk/sw/agent/activations/apm-toolkit-opentracing-activation-5.0.0-RC2.jar loaded.
INFO 2018-09-21 16:48:04:401 AgentClassLoader :  /usr/local/test/walk/sw/agent/activations/apm-toolkit-trace-activation-5.0.0-RC2.jar loaded.
DEBUG 2018-09-21 16:48:04:419 AbstractClassEnhancePluginDefine :  enhance class org.springframework.beans.factory.annotation.AutowiredAnnotationBeanPostProcessor by org.apache.skywalking.apm                                               .plugin.spring.patch.define.AutowiredAnnotationProcessorInstrumentation completely.
DEBUG 2018-09-21 16:48:04:427 SkyWalkingAgent :  Finish the prepare stage for org.springframework.beans.factory.annotation.AutowiredAnnotationBeanPostProcessor.
DEBUG 2018-09-21 16:48:05:173 SkyWalkingAgent :  On Transformation class org.springframework.beans.factory.annotation.AutowiredAnnotationBeanPostProcessor.
ERROR 2018-09-21 16:48:05:569 AppAndServiceRegisterClient :  AppAndServiceRegisterClient execute fail.
org.apache.skywalking.apm.dependencies.io.grpc.StatusRuntimeException: UNAVAILABLE: io exception
        at org.apache.skywalking.apm.dependencies.io.grpc.stub.ClientCalls.toStatusRuntimeException(ClientCalls.java:222)
        at org.apache.skywalking.apm.dependencies.io.grpc.stub.ClientCalls.getUnchecked(ClientCalls.java:203)
        at org.apache.skywalking.apm.dependencies.io.grpc.stub.ClientCalls.blockingUnaryCall(ClientCalls.java:132)
        at org.apache.skywalking.apm.network.proto.ApplicationRegisterServiceGrpc$ApplicationRegisterServiceBlockingStub.applicationCodeRegister(ApplicationRegisterServiceGrpc.java:170)
        at org.apache.skywalking.apm.agent.core.remote.AppAndServiceRegisterClient.run(AppAndServiceRegisterClient.java:112)
        at org.apache.skywalking.apm.util.RunnableWithExceptionProtection.run(RunnableWithExceptionProtection.java:36)
        at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511)
        at java.util.concurrent.FutureTask.runAndReset(FutureTask.java:308)
        at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.access$301(ScheduledThreadPoolExecutor.java:180)
        at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.run(ScheduledThreadPoolExecutor.java:294)
        at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
        at java.lang.Thread.run(Thread.java:748)
Caused by: org.apache.skywalking.apm.dependencies.io.netty.channel.AbstractChannel$AnnotatedConnectException: Connection refused: /127.0.0.1:11800
        at sun.nio.ch.SocketChannelImpl.checkConnect(Native Method)
        at sun.nio.ch.SocketChannelImpl.finishConnect(SocketChannelImpl.java:717)
        at org.apache.skywalking.apm.dependencies.io.netty.channel.socket.nio.NioSocketChannel.doFinishConnect(NioSocketChannel.java:325)
        at org.apache.skywalking.apm.dependencies.io.netty.channel.nio.AbstractNioChannel$AbstractNioUnsafe.finishConnect(AbstractNioChannel.java:340)
        at org.apache.skywalking.apm.dependencies.io.netty.channel.nio.NioEventLoop.processSelectedKey(NioEventLoop.java:634)
        at org.apache.skywalking.apm.dependencies.io.netty.channel.nio.NioEventLoop.processSelectedKeysOptimized(NioEventLoop.java:581)
        at org.apache.skywalking.apm.dependencies.io.netty.channel.nio.NioEventLoop.processSelectedKeys(NioEventLoop.java:498)
        at org.apache.skywalking.apm.dependencies.io.netty.channel.nio.NioEventLoop.run(NioEventLoop.java:460)
        at org.apache.skywalking.apm.dependencies.io.netty.util.concurrent.SingleThreadEventExecutor$5.run(SingleThreadEventExecutor.java:884)
        at org.apache.skywalking.apm.dependencies.io.netty.util.concurrent.FastThreadLocalRunnable.run(FastThreadLocalRunnable.java:30)
        ... 1 more
Caused by: java.net.ConnectException: Connection refused
        ... 11 more

DEBUG 2018-09-21 16:48:05:989 AbstractClassEnhancePluginDefine :  prepare to enhance class org.springframework.beans.BeanWrapperImpl by org.apache.skywalking.apm.plugin.spring.patch.define.B                                               eanWrapperImplInstrumentation.
DEBUG 2018-09-21 16:48:05:998 AbstractClassEnhancePluginDefine :  enhance class org.springframework.beans.BeanWrapperImpl by org.apache.skywalking.apm.plugin.spring.patch.define.BeanWrapperI                                               mplInstrumentation completely.
DEBUG 2018-09-21 16:48:06:002 SkyWalkingAgent :  Finish the prepare stage for org.springframework.beans.BeanWrapperImpl.
DEBUG 2018-09-21 16:48:06:129 SkyWalkingAgent :  On Transformation class org.springframework.beans.BeanWrapperImpl.
DEBUG 2018-09-21 16:48:06:844 AbstractClassEnhancePluginDefine :  prepare to enhance class org.springframework.web.client.RestTemplate by org.apache.skywalking.apm.plugin.spring.resttemplate                                               .sync.define.RestTemplateInstrumentation.
DEBUG 2018-09-21 16:48:06:855 AbstractClassEnhancePluginDefine :  enhance class org.springframework.web.client.RestTemplate by org.apache.skywalking.apm.plugin.spring.resttemplate.sync.defin                                               e.RestTemplateInstrumentation completely.
DEBUG 2018-09-21 16:48:06:858 SkyWalkingAgent :  Finish the prepare stage for org.springframework.web.client.RestTemplate.
DEBUG 2018-09-21 16:48:06:934 AppAndServiceRegisterClient :  AppAndServiceRegisterClient running, status:CONNECTED.
ERROR 2018-09-21 16:48:06:935 AppAndServiceRegisterClient :  AppAndServiceRegisterClient execute fail.
org.apache.skywalking.apm.dependencies.io.grpc.StatusRuntimeException: UNAVAILABLE: io exception

___
### Requirement or improvement
- Please describe about your requirements or improvement suggestions.
centos 7 
jdk 1.8
es5.6.10
skywalking5 rc2

**Comment by wu-sheng** [comment]
Grpc service is no available. Or ip binding is not correct.

**Comment by tongfaithian** [comment]
similar issue, still not solved

**Comment by tongfaithian** [comment]
DEBUG 2019-12-08 21:46:24:895 SkywalkingAgent-4-ServiceAndEndpointRegisterClient-0 ServiceAndEndpointRegisterClient :  ServiceAndEndpointRegisterClient running, status:CONNECTED. 
ERROR 2019-12-08 21:46:24:895 SkywalkingAgent-4-ServiceAndEndpointRegisterClient-0 ServiceAndEndpointRegisterClient :  ServiceAndEndpointRegisterClient execute fail. 
org.apache.skywalking.apm.dependencies.io.grpc.StatusRuntimeException: UNAVAILABLE: io exception
	at org.apache.skywalking.apm.dependencies.io.grpc.stub.ClientCalls.toStatusRuntimeException(ClientCalls.java:222)
	at org.apache.skywalking.apm.dependencies.io.grpc.stub.ClientCalls.getUnchecked(ClientCalls.java:203)
	at org.apache.skywalking.apm.dependencies.io.grpc.stub.ClientCalls.blockingUnaryCall(ClientCalls.java:132)
	at org.apache.skywalking.apm.network.register.v2.RegisterGrpc$RegisterBlockingStub.doServiceRegister(RegisterGrpc.java:386)
	at org.apache.skywalking.apm.agent.core.remote.ServiceAndEndpointRegisterClient.run(ServiceAndEndpointRegisterClient.java:115)
	at org.apache.skywalking.apm.util.RunnableWithExceptionProtection.run(RunnableWithExceptionProtection.java:36)
	at java.base/java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:515)
	at java.base/java.util.concurrent.FutureTask.runAndReset(FutureTask.java:305)
	at java.base/java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.run(ScheduledThreadPoolExecutor.java:305)
	at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1128)
	at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:628)
	at java.base/java.lang.Thread.run(Thread.java:834)
Caused by: org.apache.skywalking.apm.dependencies.io.netty.channel.AbstractChannel$AnnotatedConnectException: Connection refused: /127.0.0.1:11800
	at java.base/sun.nio.ch.SocketChannelImpl.checkConnect(Native Method)
	at java.base/sun.nio.ch.SocketChannelImpl.finishConnect(SocketChannelImpl.java:779)
	at org.apache.skywalking.apm.dependencies.io.netty.channel.socket.nio.NioSocketChannel.doFinishConnect(NioSocketChannel.java:325)
	at org.apache.skywalking.apm.dependencies.io.netty.channel.nio.AbstractNioChannel$AbstractNioUnsafe.finishConnect(AbstractNioChannel.java:340)
	at org.apache.skywalking.apm.dependencies.io.netty.channel.nio.NioEventLoop.processSelectedKey(NioEventLoop.java:634)
	at org.apache.skywalking.apm.dependencies.io.netty.channel.nio.NioEventLoop.processSelectedKeysPlain(NioEventLoop.java:546)
	at org.apache.skywalking.apm.dependencies.io.netty.channel.nio.NioEventLoop.processSelectedKeys(NioEventLoop.java:500)
	at org.apache.skywalking.apm.dependencies.io.netty.channel.nio.NioEventLoop.run(NioEventLoop.java:460)
	at org.apache.skywalking.apm.dependencies.io.netty.util.concurrent.SingleThreadEventExecutor$5.run(SingleThreadEventExecutor.java:884)
	at org.apache.skywalking.apm.dependencies.io.netty.util.concurrent.FastThreadLocalRunnable.run(FastThreadLocalRunnable.java:30)
	... 1 more
Caused by: java.net.ConnectException: Connection refused
	... 11 more

**Comment by xasnow** [comment]
Hello, has this problem been solved？
I also had this problem when running on windows
