### ISSUE TITLE
H2单机部署采集器启动报错

### ISSUE THREAD

**Issue by pzhangmiao** [apache/incubator-skywalking#1704]
2018-09-26 15:50:29,132 - org.apache.skywalking.apm.collector.boot.CollectorBootStartUp -1829 [main] ERROR [] - Service:org.apache.skywalking.apm.collector.storage.ttl.ITTLConfigService not provided
org.apache.skywalking.apm.collector.core.module.ServiceNotProvidedException: Service:org.apache.skywalking.apm.collector.storage.ttl.ITTLConfigService not provided
	at org.apache.skywalking.apm.collector.core.module.ModuleProvider.requiredCheck(ModuleProvider.java:110) ~[apm-collector-core-5.0.0-RC2.jar:5.0.0-RC2]
	at org.apache.skywalking.apm.collector.core.module.BootstrapFlow.start(BootstrapFlow.java:59) ~[apm-collector-core-5.0.0-RC2.jar:5.0.0-RC2]
	at org.apache.skywalking.apm.collector.core.module.ModuleManager.init(ModuleManager.java:68) ~[apm-collector-core-5.0.0-RC2.jar:5.0.0-RC2]
	at org.apache.skywalking.apm.collector.boot.CollectorBootStartUp.main(CollectorBootStartUp.java:45) [apm-collector-boot-5.0.0-RC2.jar:5.0.0-RC2]

public class StorageModule extends ModuleDefine {

    public static final String NAME = "storage";

    @Override public String name() {
        return NAME;
    }

    @Override public Class[] services() {
        List<Class> classes = new ArrayList<>();
        classes.add(IBatchDAO.class);

        classes.add(ITTLConfigService.class);

        addCacheDAO(classes);
        addRegisterDAO(classes);
        addPersistenceDAO(classes);
        addUiDAO(classes);
        addAlarmDAO(classes);

        return classes.toArray(new Class[] {});
    }

H2中没有注册这个ITTLConfigService

**Comment by wu-sheng** [comment]
No H2 storage supported in 5.x. Will provide that again in 6.x

**Comment by wu-sheng** [comment]
English only, thanks.

**Comment by llmjxx** [comment]
> No H2 storage supported in 5.x. Will provide that again in 6.x

This message is very usefull for me.By the way,I saw some configuration for H2 in application.yml of version 5.x. I think it can mislead users and that is the mistake i made.

**Comment by wu-sheng** [comment]
Yes. I maybe. 6 GA is on release process. We recommend user upgrade to 6.0.0 GA
