### ISSUE TITLE
A little problem in skywalking-5.0.0-RC2 

### ISSUE THREAD

**Issue by wangxiang5050** [apache/incubator-skywalking#1715]
Hi, i am using skywalking-5.0.0-RC2, and encounter a little bug in class AlarmService. Here is the exception:
`java.lang.NullPointerException: null
	at org.apache.skywalking.apm.collector.ui.service.AlarmService.buildServerName(AlarmService.java:178) ~[collector-ui-jetty-provider-5.0.0-RC2.jar:5.0.0-RC2]
	at org.apache.skywalking.apm.collector.ui.service.AlarmService.lambda$loadInstanceAlarmList$3(AlarmService.java:114) ~[collector-ui-jetty-provider-5.0.0-RC2.jar:5.0.0-RC2]
	at java.lang.Iterable.forEach(Iterable.java:75) ~[?:1.8.0_172]
	at org.apache.skywalking.apm.collector.ui.service.AlarmService.loadInstanceAlarmList(AlarmService.java:111) ~[collector-ui-jetty-provider-5.0.0-RC2.jar:5.0.0-RC2]
	at org.apache.skywalking.apm.collector.ui.query.AlarmQuery.loadAlarmList(AlarmQuery.java:61) ~[collector-ui-jetty-provider-5.0.0-RC2.jar:5.0.0-RC2]
	at org.apache.skywalking.apm.collector.ui.query.AlarmQueryMethodAccess.invoke(Unknown Source) ~[reflectasm-1.11.3.jar:5.0.0-RC2]
	at com.coxautodev.graphql.tools.MethodFieldResolverDataFetcher.get(MethodFieldResolver.kt:132) ~[graphql-java-tools-4.3.0.jar:?]
	at graphql.execution.ExecutionStrategy.fetchField(ExecutionStrategy.java:219) [graphql-java-6.0.jar:?]
	at graphql.execution.ExecutionStrategy.resolveField(ExecutionStrategy.java:165) [graphql-java-6.0.jar:?]
	at graphql.execution.AsyncExecutionStrategy.execute(AsyncExecutionStrategy.java:55) [graphql-java-6.0.jar:?]
	at graphql.execution.Execution.executeOperation(Execution.java:154) [graphql-java-6.0.jar:?]
	at graphql.execution.Execution.execute(Execution.java:98) [graphql-java-6.0.jar:?]
	at graphql.GraphQL.execute(GraphQL.java:546) [graphql-java-6.0.jar:?]
	at graphql.GraphQL.parseValidateAndExecute(GraphQL.java:488) [graphql-java-6.0.jar:?]
	at graphql.GraphQL.executeAsync(GraphQL.java:463) [graphql-java-6.0.jar:?]
	at graphql.GraphQL.execute(GraphQL.java:394) [graphql-java-6.0.jar:?]
	at org.apache.skywalking.apm.collector.ui.jetty.handler.GraphQLHandler.execute(GraphQLHandler.java:100) [collector-ui-jetty-provider-5.0.0-RC2.jar:5.0.0-RC2]
	at org.apache.skywalking.apm.collector.ui.jetty.handler.GraphQLHandler.doPost(GraphQLHandler.java:93) [collector-ui-jetty-provider-5.0.0-RC2.jar:5.0.0-RC2]
	at org.apache.skywalking.apm.collector.server.jetty.JettyJsonHandler.doPost(JettyJsonHandler.java:61) [server-component-5.0.0-RC2.jar:5.0.0-RC2]
	at javax.servlet.http.HttpServlet.service(HttpServlet.java:707) [javax.servlet-api-3.1.0.jar:3.1.0]`

This bug make server label in Alarm List page unavailable. I have fixed that.But the latested code which i forked doesn't contain that class, so i am a little confused whether i should report things like this?

**Comment by wu-sheng** [comment]
This should be fixed in GA already. Please recheck after our RC release passed.
