### ISSUE TITLE
Collector cant connect to elasticsearch

### ISSUE THREAD

**Issue by Mor-Walkme** [apache/incubator-skywalking#1730]
Hey,
I am trying to setup local skywalking environment on my laptop, contains UI + Collector + ElasticSearch, and i cant make the collector work with elastic.

The error i am getting in collector.log:
`Exception in thread "main" NoNodeAvailableException[None of the configured nodes are available: [{#transport#-1}{UZP-ChuRSg25DF3ymCgniw}{localhost}{127.0.0.1:9300}]]
	at org.elasticsearch.client.transport.TransportClientNodesService.ensureNodesAreAvailable(TransportClientNodesService.java:347)
	at org.elasticsearch.client.transport.TransportClientNodesService.execute(TransportClientNodesService.java:245)
	at org.elasticsearch.client.transport.TransportProxyClient.execute(TransportProxyClient.java:59)
	at org.elasticsearch.client.transport.TransportClient.doExecute(TransportClient.java:363)
	at org.elasticsearch.client.support.AbstractClient.execute(AbstractClient.java:408)
	at org.elasticsearch.client.support.AbstractClient$IndicesAdmin.execute(AbstractClient.java:1256)
	at org.elasticsearch.action.ActionRequestBuilder.execute(ActionRequestBuilder.java:80)
	at org.elasticsearch.action.ActionRequestBuilder.execute(ActionRequestBuilder.java:54)
	at org.elasticsearch.action.ActionRequestBuilder.get(ActionRequestBuilder.java:62)
	at org.apache.skywalking.apm.collector.client.elasticsearch.ElasticSearchClient.isExistsIndex(ElasticSearchClient.java:145)
	at org.apache.skywalking.apm.collector.storage.es.base.define.ElasticSearchStorageInstaller.isExists(ElasticSearchStorageInstaller.java:151)
	at org.apache.skywalking.apm.collector.storage.StorageInstaller.install(StorageInstaller.java:52)
	at org.apache.skywalking.apm.collector.storage.es.StorageModuleEsProvider.start(StorageModuleEsProvider.java:125)
	at org.apache.skywalking.apm.collector.core.module.BootstrapFlow.start(BootstrapFlow.java:61)
	at org.apache.skywalking.apm.collector.core.module.ModuleManager.init(ModuleManager.java:68)
	at org.apache.skywalking.apm.collector.boot.CollectorBootStartUp.main(CollectorBootStartUp.java:45)`

I am running local elasticsearch using docker container. here is my elasticsearch.yml:
http.host: 0.0.0.0
cluster.name: CollectorDBCluster
node.name: TestNode
thread_pool.bulk.queue_size: 1000
discovery.type: single-node

ElasticSearch version: 5.5
How i run the container locally: docker run -p 9200:9200 -p 9300:9300 elasticsearch:5.5

Skywalking version: apache-skywalking-apm-incubating-5.0.0-RC2.tar.gz

Here is my skywalking configuration file application.yml:
storage:
  elasticsearch:
    clusterName: CollectorDBCluster
    clusterTransportSniffer: false
    clusterNodes: localhost:9300
    indexShardsNumber: 2
    indexReplicasNumber: 0
    highPerformanceMode: true
    # Batch process setting, refer to https://www.elastic.co/guide/en/elasticsearch/client/java-api/5.5/java-docs-bulk-processor.html
    bulkActions: 2000 # Execute the bulk every 2000 requests
    bulkSize: 20 # flush the bulk every 20mb
    flushInterval: 10 # flush the bulk every 10 seconds whatever the number of requests
    concurrentRequests: 2 # the number of concurrent requests
    # Set a timeout on metric data. After the timeout has expired, the metric data will automatically be deleted.
    traceDataTTL: 90 # Unit is minute
    minuteMetricDataTTL: 90 # Unit is minute
    hourMetricDataTTL: 36 # Unit is hour
    dayMetricDataTTL: 45 # Unit is day
    monthMetricDataTTL: 18 # Unit is month

Do you know what have i missed to make it work?

Thanks,
Mor.

**Comment by wu-sheng** [comment]
You should set your setting in correct markdown format. Your issue is very hard to understand.

The requirements are
- Add settings in es we suggested
- Make sure ES binding right. You set 127.0.01, is your es at local?
- Make sure you connect TCP port of es.

**Comment by Mor-Walkme** [comment]
Thanks, I hope now its more readable.

- I added the ES as recommended in the documentation.
- I run ES on my local computer using docker listening to ports 9300 and 9200
- I run skywalking on my local computer as well
