### ISSUE TITLE
grpc  throws java.lang.NoClassDefFoundError: com/google/common/collect/Maps

### ISSUE THREAD

**Issue by juaiahu** [apache/incubator-skywalking#1800]
### I got an execption when I started a springBoot based application in this way:
   
java -javaagent:/Users/syswin/work/agent/skywalking-agent.jar -Dloader.path=./libs -jar app-xxx.jar**

the followig is exception trace:
org.springframework.boot.SpringApplication.reportFailure(SpringApplication.java:863) - Application run failed
java.lang.NoClassDefFoundError: com/google/common/collect/Maps
	at io.opencensus.stats.NoopStats$NoopViewManager.<init>(NoopStats.java:156) ~[skywalking-agent.jar:5.0.0-RC-SNAPSHOT]
	at io.opencensus.stats.NoopStats$NoopViewManager.<init>(NoopStats.java:152) ~[skywalking-agent.jar:5.0.0-RC-SNAPSHOT]
	at io.opencensus.stats.NoopStats.newNoopViewManager(NoopStats.java:86) ~[skywalking-agent.jar:5.0.0-RC-SNAPSHOT]
	at io.opencensus.stats.NoopStats$NoopStatsComponent.<init>(NoopStats.java:91) ~[skywalking-agent.jar:5.0.0-RC-SNAPSHOT]
	at io.opencensus.stats.NoopStats$NoopStatsComponent.<init>(NoopStats.java:90) ~[skywalking-agent.jar:5.0.0-RC-SNAPSHOT]
	at io.opencensus.stats.NoopStats.newNoopStatsComponent(NoopStats.java:57) ~[skywalking-agent.jar:5.0.0-RC-SNAPSHOT]
	at io.opencensus.stats.Stats.loadStatsComponent(Stats.java:104) ~[skywalking-agent.jar:5.0.0-RC-SNAPSHOT]
	at io.opencensus.stats.Stats.<clinit>(Stats.java:30) ~[skywalking-agent.jar:5.0.0-RC-SNAPSHOT]
	at io.grpc.internal.CensusStatsModule.<init>(CensusStatsModule.java:87) ~[grpc-core-1.15.0.jar!/:1.15.0]
	at io.grpc.internal.AbstractServerImplBuilder.getTracerFactories(AbstractServerImplBuilder.java:267) ~[grpc-core-1.15.0.jar!/:1.15.0]
	at io.grpc.internal.AbstractServerImplBuilder.build(AbstractServerImplBuilder.java:252) ~[grpc-core-1.15.0.jar!/:1.15.0]
	at com.syswin.temail.channel.grpc.servers.GrpcServerStarter.start(GrpcServerStarter.java:31) ~[classes!/:1.0.0-SNAPSHOT]
	at com.syswin.temail.channel.grpc.servers.GrpcServerManager.run(GrpcServerManager.java:24) ~[classes!/:1.0.0-SNAPSHOT]
	at org.springframework.boot.SpringApplication.callRunner(SpringApplication.java:809) [spring-boot-2.0.5.RELEASE.jar!/:2.0.5.RELEASE]
	at org.springframework.boot.SpringApplication.callRunners(SpringApplication.java:799) [spring-boot-2.0.5.RELEASE.jar!/:2.0.5.RELEASE]
	at org.springframework.boot.SpringApplication.run(SpringApplication.java:341) [spring-boot-2.0.5.RELEASE.jar!/:2.0.5.RELEASE]
	at org.springframework.boot.SpringApplication.run(SpringApplication.java:1277) [spring-boot-2.0.5.RELEASE.jar!/:2.0.5.RELEASE]
	at org.springframework.boot.SpringApplication.run(SpringApplication.java:1265) [spring-boot-2.0.5.RELEASE.jar!/:2.0.5.RELEASE]
	at com.syswin.temail.channel.TemailChannelApplication.main(TemailChannelApplication.java:9) [classes!/:1.0.0-SNAPSHOT]
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method) ~[?:1.8.0_181]
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62) ~[?:1.8.0_181]
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43) ~[?:1.8.0_181]
	at java.lang.reflect.Method.invoke(Method.java:498) ~[?:1.8.0_181]
	at org.springframework.boot.loader.MainMethodRunner.run(MainMethodRunner.java:48) [temail-channel-registry-server.jar:1.0.0-SNAPSHOT]
	at org.springframework.boot.loader.Launcher.launch(Launcher.java:87) [temail-channel-registry-server.jar:1.0.0-SNAPSHOT]
	at org.springframework.boot.loader.Launcher.launch(Launcher.java:50) [temail-channel-registry-server.jar:1.0.0-SNAPSHOT]
	at org.springframework.boot.loader.PropertiesLauncher.main(PropertiesLauncher.java:593) [temail-channel-registry-server.jar:1.0.0-SNAPSHOT]
Caused by: java.lang.ClassNotFoundException: com.google.common.collect.Maps
	at java.net.URLClassLoader.findClass(URLClassLoader.java:381) ~[?:1.8.0_181]
	at java.lang.ClassLoader.loadClass(ClassLoader.java:424) ~[?:1.8.0_181]
	at sun.misc.Launcher$AppClassLoader.loadClass(Launcher.java:349) ~[?:1.8.0_181]
	at java.lang.ClassLoader.loadClass(ClassLoader.java:357) ~[?:1.8.0_181]
	... 27 more

### but when start it in another way:

 $JAVA_HOME/bin/java -javaagent:/home/java/jarServer/apmAgent/agent/skywalking-agent.jar -Dfile.encoding=UTF-8 -classpath $JAVA_HOME/jre/lib/charsets.jar:$JAVA_HOME/jre/lib/deploy.jar:$JAVA_HOME/jre/lib/ext/cldrdat.jar:$JAVA_HOME/jre/lib/ext/dnsns.jar:$JAVA_HOME/jre/lib/ext/jaccess.jar:$JAVA_HOME/jre/lib/ext/jfxr.jar:$JAVA_HOME/jre/lib/ext/localedata.jar:$JAVA_HOME/jre/lib/ext/nashorn.jar:$JAVA_HOME/jre/lib/ext/sune.jar:$JAVA_HOME/jre/lib/ext/sunjce_provider.jar:$JAVA_HOME/jre/lib/ext/sunpkcs11.jar:$JAVA_HOME/jre/lib/ext/zipf.jar:$JAVA_HOME/jre/lib/javaws.jar:$JAVA_HOME/jre/lib/jce.jar:$JAVA_HOME/jre/lib/jfr.jar:$JAVA_HOME/jre/lib/jfxsw.jar:$JAVA_HOME/jre/lib/jsse.jar:$JAVA_HOME/jre/lib/management-agent.jar:$JAVA_HOME/jre/lib/plugin.jar:$JAVA_HOME/jre/lib/resource.jar:$JAVA_HOME/jre/lib/rt.jar:$JAVA_HOME/lib/ant-javafx.jar:$JAVA_HOME/lib/dt.jar:$JAVA_HOME/lib/javafx-m.jar:$JAVA_HOME/lib/jconsole.jar:$JAVA_HOME/lib/packager.jar:$JAVA_HOME/lib/sa-jdi.jar:$JAVA_HOME/lib/tools.jar:/home/java/jarServer/classes:/home/java/jarServer/libs/activation-1.1.jar:/home/java/jarServer/libs/animal-sniffer-annotations-1.17.jar:/home/java/jarServer/libs/aspectjtools-1.8.13.jar:/home/java/jarServer/libs/classmate-1.3.4.jar:/home/java/jarServer/libs/commons-codec-1.11.jar:/home/java/jarServer/libs/commons-io-2.5.jar:/home/java/jarServer/libs/commons-lang3-3.7.jar:/home/java/jarServer/libs/disconf-client-2.6.36.jar:/home/java/jarServer/libs/disconf-core-2.6.36.jar:/home/java/jarServer/libs/disconf-spring-boot-starter-1.0.0.jar:/home/java/jarServer/libs/dom4j-1.6.1.jar:/home/java/jarServer/libs/error_prone_annotations-2.2.0.jar:/home/java/jarServer/libs/google-auth-library-credentials-0.9.0.jar:/home/java/jarServer/libs/google-auth-library-oauth2-http-0.9.0.jar:/home/java/jarServer/libs/google-http-client-1.19.0.jar:/home/java/jarServer/libs/google-http-client-jackson2-1.19.0.jar:/home/java/jarServer/libs/grpc-alts-1.15.0.jar:/home/java/jarServer/libs/grpc-auth-1.15.0.jar:/home/java/jarServer/libs/grpc-context-1.15.0.jar:/home/java/jarServer/libs/grpc-core-1.15.0.jar:/home/java/jarServer/libs/grpc-netty-1.15.0.jar:/home/java/jarServer/libs/grpc-netty-shaded-1.15.0.jar:/home/java/jarServer/libs/grpc-protobuf-1.15.0.jar:/home/java/jarServer/libs/grpc-protobuf-lite-1.15.0.jar:/home/java/jarServer/libs/grpc-stub-1.15.0.jar:/home/java/jarServer/libs/gson-2.8.0.jar:/home/java/jarServer/libs/guava-20.0.jar:/home/java/jarServer/libs/hamcrest-core-1.3.jar:/home/java/jarServer/libs/hibernate-validator-6.0.12.Final.jar:/home/java/jarServer/libs/httpclient-4.5.6.jar:/home/java/jarServer/libs/httpcore-4.4.10.jar:/home/java/jarServer/libs/jackson-annotations-2.9.0.jar:/home/java/jarServer/libs/jackson-core-2.9.6.jar:/home/java/jarServer/libs/jackson-databind-2.9.6.jar:/home/java/jarServer/libs/jackson-dataformat-yaml-2.9.6.jar:/home/java/jarServer/libs/jackson-datatype-jdk8-2.9.6.jar:/home/java/jarServer/libs/jackson-datatype-jsr310-2.9.6.jar:/home/java/jarServer/libs/jackson-module-parameter-names-2.9.6.jar:/home/java/jarServer/libs/javassist-3.21.0-GA.jar:/home/java/jarServer/libs/javax.annotation-api-1.3.2.jar:/home/java/jarServer/libs/jboss-logging-3.3.2.Final.jar:/home/java/jarServer/libs/jcl-over-slf4j-1.7.25.jar:/home/java/jarServer/libs/jline-0.9.94.jar:/home/java/jarServer/libs/jsr305-2.0.2.jar:/home/java/jarServer/libs/jul-to-slf4j-1.7.25.jar:/home/java/jarServer/libs/junit-4.12.jar:/home/java/jarServer/libs/lettuce-core-5.0.5.RELEASE.jar:/home/java/jarServer/libs/log4j-1.2.15.jar:/home/java/jarServer/libs/log4j-api-2.10.0.jar:/home/java/jarServer/libs/log4j-core-2.10.0.jar:/home/java/jarServer/libs/log4j-jul-2.10.0.jar:/home/java/jarServer/libs/log4j-slf4j-impl-2.10.0.jar:/home/java/jarServer/libs/lombok-1.16.22.jar:/home/java/jarServer/libs/mail-1.5.0-b01.jar:/home/java/jarServer/libs/netty-all-4.1.29.Final.jar:/home/java/jarServer/libs/netty-buffer-4.1.29.Final.jar:/home/java/jarServer/libs/netty-codec-4.1.29.Final.jar:/home/java/jarServer/libs/netty-codec-http2-4.1.29.Final.jar:/home/java/jarServer/libs/netty-codec-http-4.1.29.Final.jar:/home/java/jarServer/libs/netty-codec-socks-4.1.29.Final.jar:/home/java/jarServer/libs/netty-common-4.1.29.Final.jar:/home/java/jarServer/libs/netty-handler-4.1.29.Final.jar:/home/java/jarServer/libs/netty-handler-proxy-4.1.29.Final.jar:/home/java/jarServer/libs/netty-resolver-4.1.29.Final.jar:/home/java/jarServer/libs/netty-tcnative-boringssl-static-2.0.7.Final.jar:/home/java/jarServer/libs/netty-transport-4.1.29.Final.jar:/home/java/jarServer/libs/opencensus-api-0.12.3.jar:/home/java/jarServer/libs/opencensus-contrib-grpc-metrics-0.12.3.jar:/home/java/jarServer/libs/protobuf-java-3.5.1.jar:/home/java/jarServer/libs/protobuf-java-format-1.2.jar:/home/java/jarServer/libs/protobuf-java-util-3.5.1.jar:/home/java/jarServer/libs/proto-google-common-protos-1.0.0.jar:/home/java/jarServer/libs/reactive-streams-1.0.2.jar:/home/java/jarServer/libs/reactor-core-3.1.9.RELEASE.jar:/home/java/jarServer/libs/reflections-0.9.9-RC1.jar:/home/java/jarServer/libs/slf4j-api-1.7.25.jar:/home/java/jarServer/libs/snakeyaml-1.19.jar:/home/java/jarServer/libs/spring-aop-5.0.9.RELEASE.jar:/home/java/jarServer/libs/spring-beans-5.0.9.RELEASE.jar:/home/java/jarServer/libs/spring-boot-2.0.5.RELEASE.jar:/home/java/jarServer/libs/spring-boot-autoconfigure-2.0.5.RELEASE.jar:/home/java/jarServer/libs/spring-boot-configuration-processor-2.0.5.RELEASE.jar:/home/java/jarServer/libs/spring-boot-starter-2.0.5.RELEASE.jar:/home/java/jarServer/libs/spring-boot-starter-data-redis-2.0.5.RELEASE.jar:/home/java/jarServer/libs/spring-boot-starter-json-2.0.5.RELEASE.jar:/home/java/jarServer/libs/spring-boot-starter-log4j2-2.0.5.RELEASE.jar:/home/java/jarServer/libs/spring-boot-starter-tomcat-2.0.5.RELEASE.jar:/home/java/jarServer/libs/spring-boot-starter-web-2.0.5.RELEASE.jar:/home/java/jarServer/libs/spring-context-5.0.9.RELEASE.jar:/home/java/jarServer/libs/spring-context-support-5.0.9.RELEASE.jar:/home/java/jarServer/libs/spring-core-5.0.9.RELEASE.jar:/home/java/jarServer/libs/spring-data-commons-2.0.10.RELEASE.jar:/home/java/jarServer/libs/spring-data-keyvalue-2.0.10.RELEASE.jar:/home/java/jarServer/libs/spring-data-redis-2.0.10.RELEASE.jar:/home/java/jarServer/libs/spring-expression-5.0.9.RELEASE.jar:/home/java/jarServer/libs/spring-jcl-5.0.9.RELEASE.jar:/home/java/jarServer/libs/spring-oxm-5.0.9.RELEASE.jar:/home/java/jarServer/libs/spring-tx-5.0.9.RELEASE.jar:/home/java/jarServer/libs/spring-web-5.0.9.RELEASE.jar:/home/java/jarServer/libs/spring-webmvc-5.0.9.RELEASE.jar:/home/java/jarServer/libs/temail-channel-common-1.0.0-SNAPSHOT.jar:/home/java/jarServer/libs/tomcat-embed-core-8.5.34.jar:/home/java/jarServer/libs/tomcat-embed-el-8.5.34.jar:/home/java/jarServer/libs/tomcat-embed-websocket-8.5.34.jar:/home/java/jarServer/libs/validation-api-2.0.1.Final.jar:/home/java/jarServer/libs/xml-apis-1.4.01.jar:/home/java/jarServer/libs/zookeeper-3.3.6.jar com.syswin.temail.channel.TemailChannelApplication 2>&1|tee ./log/current_run.log > ./log/$logfileName &  

**then it works well ,  I checked so many times and I am make sure we do have the guava.jar in the libs dir , but the first way just not work.**

**Comment by wu-sheng** [comment]
I am not sure why is this happening, in SkyWalking agent, all dependencies including opencensus have been shade(package name changes). Need you to recheck and find out what is happening.

**Comment by seanyinx** [comment]
We found the solution. The issue was caused by repackaging of `spring-boot-maven-plugin` . Replacing this plugin with `maven-jar-plugin` fixed this issue.
