### ISSUE TITLE
rest protocol of dubbo not supported

### ISSUE THREAD

**Issue by blakesu** [apache/incubator-skywalking#1804]
### Bug
- Which version of SkyWalking, OS and JRE?
skywalking-agent.jar:5.0.0-GA
linux
JRE 8

- Which company or project?
SF Express

- What happen?
exception throwed while calling dubbo service through rest protocol. 

Caused by: javax.ws.rs.ProcessingException: java.lang.IllegalArgumentException: The attachments of RpcContext must not contain ',' or '=' when using rest protocol
	at org.jboss.resteasy.client.jaxrs.internal.ClientInvocation.invoke(ClientInvocation.java:401) ~[resteasy-client-3.0.7.Final.jar:na]
	at org.jboss.resteasy.client.jaxrs.internal.proxy.ClientInvoker.invoke(ClientInvoker.java:102) ~[resteasy-client-3.0.7.Final.jar:na]
	at org.jboss.resteasy.client.jaxrs.internal.proxy.ClientProxy.invoke(ClientProxy.java:62) ~[resteasy-client-3.0.7.Final.jar:na]
	at com.sun.proxy.$Proxy105.batchConvertLineCargoByCondition(Unknown Source) ~[na:na]
	at com.alibaba.dubbo.common.bytecode.Wrapper1.invokeMethod(Wrapper1.java) ~[dubbo-sf.2.0.4.jar:sf.2.0.4]
	at com.alibaba.dubbo.rpc.proxy.javassist.JavassistProxyFactory$1.doInvoke(JavassistProxyFactory.java:46) [dubbo-sf.2.0.4.jar:sf.2.0.4]
	at com.alibaba.dubbo.rpc.proxy.AbstractProxyInvoker.invoke(AbstractProxyInvoker.java:72) [dubbo-sf.2.0.4.jar:sf.2.0.4]
	at com.alibaba.dubbo.rpc.protocol.AbstractProxyProtocol$2.doInvoke(AbstractProxyProtocol.java:93) ~[dubbo-sf.2.0.4.jar:sf.2.0.4]
	at com.alibaba.dubbo.rpc.protocol.AbstractInvoker.invoke(AbstractInvoker.java:144) ~[dubbo-sf.2.0.4.jar:sf.2.0.4]
	at com.sf.fvp.data.server.service.hystrix.dubbo.HystrixFilter.invoke(HystrixFilter.java:22) ~[classes/:na]
	at com.alibaba.dubbo.rpc.protocol.ProtocolFilterWrapper$1.invoke(ProtocolFilterWrapper.java:91) [dubbo-sf.2.0.4.jar:sf.2.0.4]
	at com.alibaba.dubbo.monitor.support.MonitorFilter.invoke$original$QYY8CEkQ(MonitorFilter.java:75) [dubbo-sf.2.0.4.jar:sf.2.0.4]
	at com.alibaba.dubbo.monitor.support.MonitorFilter.invoke$original$QYY8CEkQ$accessor$38j0IATe(MonitorFilter.java) [dubbo-sf.2.0.4.jar:sf.2.0.4]
	at com.alibaba.dubbo.monitor.support.MonitorFilter$auxiliary$7KnCMtHH.call(Unknown Source) [dubbo-sf.2.0.4.jar:sf.2.0.4]
	at org.apache.skywalking.apm.agent.core.plugin.interceptor.enhance.InstMethodsInter.intercept(InstMethodsInter.java:93) [skywalking-agent.jar:5.0.0-GA]
	at com.alibaba.dubbo.monitor.support.MonitorFilter.invoke(MonitorFilter.java) [dubbo-sf.2.0.4.jar:sf.2.0.4]
	at com.alibaba.dubbo.rpc.protocol.ProtocolFilterWrapper$1.invoke(ProtocolFilterWrapper.java:91) [dubbo-sf.2.0.4.jar:sf.2.0.4]
	at com.alibaba.dubbo.rpc.protocol.dubbo.filter.FutureFilter.invoke(FutureFilter.java:53) ~[dubbo-sf.2.0.4.jar:sf.2.0.4]
	at com.alibaba.dubbo.rpc.protocol.ProtocolFilterWrapper$1.invoke(ProtocolFilterWrapper.java:91) [dubbo-sf.2.0.4.jar:sf.2.0.4]
	at com.alibaba.dubbo.rpc.filter.ConsumerContextFilter.invoke(ConsumerContextFilter.java:48) ~[dubbo-sf.2.0.4.jar:sf.2.0.4]
	at com.alibaba.dubbo.rpc.protocol.ProtocolFilterWrapper$1.invoke(ProtocolFilterWrapper.java:91) [dubbo-sf.2.0.4.jar:sf.2.0.4]
	at com.alibaba.dubbo.rpc.listener.ListenerInvokerWrapper.invoke(ListenerInvokerWrapper.java:74) ~[dubbo-sf.2.0.4.jar:sf.2.0.4]
	at com.alibaba.dubbo.rpc.protocol.InvokerWrapper.invoke(InvokerWrapper.java:53) [dubbo-sf.2.0.4.jar:sf.2.0.4]
	at com.alibaba.dubbo.rpc.cluster.support.FailoverClusterInvoker.doInvoke(FailoverClusterInvoker.java:77) ~[dubbo-sf.2.0.4.jar:sf.2.0.4]
	... 72 common frames omitted
Caused by: java.lang.IllegalArgumentException: The attachments of RpcContext must not contain ',' or '=' when using rest protocol
	at com.alibaba.dubbo.rpc.protocol.rest.RpcContextFilter.filter(RpcContextFilter.java:74) ~[dubbo-sf.2.0.4.jar:sf.2.0.4]
	at org.jboss.resteasy.client.jaxrs.internal.ClientInvocation.invoke(ClientInvocation.java:384) ~[resteasy-client-3.0.7.Final.jar:na]
	... 95 common frames omitted

**Comment by blakesu** [comment]
as a new user of SW, need some time to dig into the code.  :)

**Comment by wu-sheng** [comment]
> as a new user of SW, need some time to dig into the code. :)

That is not in hurry. Just I want to know what happens to the header. It is a possible bug, but don't show up before.

**Comment by blakesu** [comment]
The header just like below, it only happended while calling dubbo service from dubbo consumer through rest protocol, dubbo protocol is OK.

36.181.15417549869400000|2|36|36|7|#services/com.sf.fvp.data.server.service.IVehicleLoadUnloadTaskRestService.queryVehicleloadUnloadTasksByLineRequireId(long,int,String)|#services/com.sf.fvp.data.server.service.IVehicleLoadUnloadTaskRestService.queryVehicleloadUnloadTasksByLineRequireId(long,int,String)|36.181.15417549869400001

**Comment by wu-sheng** [comment]
Why dubbo rest block this? sw6 header in 6.0.0 has base64 encoding, could avoid this. But next release only.

**Comment by blakesu** [comment]
guess the reason is HTTP procotol，dubbo added this extra limitation for it.

**Comment by wu-sheng** [comment]
Anyway, see https://github.com/apache/incubator-skywalking/pull/1894 for new header. Should avoid this.
