### ISSUE TITLE
Service:org.apache.skywalking.apm.collector.storage.ttl.ITTLConfigService not provided

### ISSUE THREAD

**Issue by xiaoxing598** [apache/incubator-skywalking#1868]
After I started in stand-alone deployment mode, I found an error message in the log. Is there any problem?

```
2018-11-02 13:51:14,352 - org.apache.skywalking.apm.collector.boot.CollectorBootStartUp -2702 [main] ERROR [] - Service:org.apache.skywalking.apm.collector.storage.ttl.ITTLConfigService not provided
org.apache.skywalking.apm.collector.core.module.ServiceNotProvidedException: Service:org.apache.skywalking.apm.collector.storage.ttl.ITTLConfigService not provided
	at org.apache.skywalking.apm.collector.core.module.ModuleProvider.requiredCheck(ModuleProvider.java:110) ~[apm-collector-core-5.0.0-GA.jar:5.0.0-GA]
	at org.apache.skywalking.apm.collector.core.module.BootstrapFlow.start(BootstrapFlow.java:59) ~[apm-collector-core-5.0.0-GA.jar:5.0.0-GA]
	at org.apache.skywalking.apm.collector.core.module.ModuleManager.init(ModuleManager.java:68) ~[apm-collector-core-5.0.0-GA.jar:5.0.0-GA]
	at org.apache.skywalking.apm.collector.boot.CollectorBootStartUp.main(CollectorBootStartUp.java:45) [apm-collector-boot-5.0.0-GA.jar:5.0.0-GA]
```

**Comment by xiaoxing598** [comment]
Yes, on the Windows platform, I got the installation package from the download page.

**Comment by wu-sheng** [comment]
Because of the first issue, you backend starts up failure. So UI is meaningless.

**Comment by wu-sheng** [comment]
I just download and run the release on my laptop, nothing wrong. If you are in windows, please make sure you unzip file right. We have received a lot times, windows block unzip with long file path or file name, so you will miss some jar file. Check your collector-libs folder, should have 159 jar files in it.

**Comment by xiaoxing598** [comment]
I have tested it in the CentOS environment and found the same problem in the logs.

![skywalking](https://user-images.githubusercontent.com/5615719/47900040-7ac5d600-deb6-11e8-9632-74cc459d3f82.png)

**Comment by xiaoxing598** [comment]
[root@oms-java-dev /home/apache-skywalking-apm-incubating]# cd collector-libs/
[root@oms-java-dev /home/apache-skywalking-apm-incubating/collector-libs]#  ls -l | grep "^-" | wc -l
159

**Comment by wu-sheng** [comment]
This interface has been implmented in `org.apache.skywalking.apm.collector.storage.es.StorageModuleEsProvider#prepare`

> this.registerServiceImplementation(ITTLConfigService.class, new TTLConfigService(config));

**Comment by xiaoxing598** [comment]
Due to stand-alone deployment, I chose to use H2DB
![skywalking](https://user-images.githubusercontent.com/5615719/47900626-78fd1200-deb8-11e8-9a0f-3d9b839a7dd0.png)

**Comment by wu-sheng** [comment]
You should read the document. H2 storage is not provided in 5.x. No one contributes that feature.

**Comment by jackzhangsir** [comment]
got it
