### ISSUE TITLE
Bug java.lang.ArithmeticException: / by zero

### ISSUE THREAD

**Issue by Johnson-Jia** [apache/incubator-skywalking#1948]
v6.0.0-alpha
=============
org.apache.skywalking.oap.server.core.remote.selector.HashCodeSelector#select

select(List<RemoteClient> clients, StreamData streamData) {
        int size = clients.size();
        int selectIndex = Math.abs(streamData.remoteHashCode()) % size;
        return clients.get(selectIndex);
    }

`2018-11-22 18:53:26,301 - org.apache.skywalking.oap.server.core.analysis.worker.IndicatorRemoteWorker -7699 [DataCarrier.IndicatorAggregateWorker.instance_jvm_memory_heap.Consumser.0.Thread] ERROR [] - / by zero
java.lang.ArithmeticException: / by zero
	at org.apache.skywalking.oap.server.core.remote.selector.HashCodeSelector.select(HashCodeSelector.java:32) ~[server-core-6.0.0-alpha.jar:6.0.0-alpha]
	at org.apache.skywalking.oap.server.core.remote.RemoteSenderService.send(RemoteSenderService.java:50) ~[server-core-6.0.0-alpha.jar:6.0.0-alpha]
	at org.apache.skywalking.oap.server.core.analysis.worker.IndicatorRemoteWorker.in(IndicatorRemoteWorker.java:51) ~[server-core-6.0.0-alpha.jar:6.0.0-alpha]
	at org.apache.skywalking.oap.server.core.analysis.worker.IndicatorRemoteWorker.in(IndicatorRemoteWorker.java:33) ~[server-core-6.0.0-alpha.jar:6.0.0-alpha]
	at org.apache.skywalking.oap.server.core.analysis.worker.IndicatorAggregateWorker.lambda$sendToNext$0(IndicatorAggregateWorker.java:84) ~[server-core-6.0.0-alpha.jar:6.0.0-alpha]
	at java.util.HashMap$Values.forEach(HashMap.java:981) [?:1.8.0_161]
`

**Comment by peng-yongsheng** [comment]
@Johnson-Jia This bug was fixed. Thanks for your question.

**Comment by 1248912240** [comment]
2019-02-25 07:36:01,315 - org.apache.skywalking.oap.server.core.analysis.worker.IndicatorRemoteWorker - 53 [DataCarrier.IndicatorAggregateWorker.instance_jvm_memory_noheap_max.Consumser.0.Thread] ERROR [] - / by zero
java.lang.ArithmeticException: / by zero
        at org.apache.skywalking.oap.server.core.remote.selector.HashCodeSelector.select(HashCodeSelector.java:32) ~[server-core-6.0.0-GA.jar:6.0.0-GA]
        at org.apache.skywalking.oap.server.core.remote.RemoteSenderService.send(RemoteSenderService.java:50) ~[server-core-6.0.0-GA.jar:6.0.0-GA]
        at org.apache.skywalking.oap.server.core.analysis.worker.IndicatorRemoteWorker.in(IndicatorRemoteWorker.java:51) ~[server-core-6.0.0-GA.jar:6.0.0-GA]
        at org.apache.skywalking.oap.server.core.analysis.worker.IndicatorRemoteWorker.in(IndicatorRemoteWorker.java:33) ~[server-core-6.0.0-GA.jar:6.0.0-GA]
        at org.apache.skywalking.oap.server.core.analysis.worker.IndicatorAggregateWorker.lambda$sendToNext$0(IndicatorAggregateWorker.java:93) ~[server-core-6.0.0-GA.jar:6.0.0-GA]
        at java.util.HashMap$Values.forEach(HashMap.java:981) [?:1.8.0_201]
        at org.apache.skywalking.oap.server.core.analysis.worker.IndicatorAggregateWorker.sendToNext(IndicatorAggregateWorker.java:88) [server-core-6.0.0-GA.jar:6.0.0-GA]
        at org.apache.skywalking.oap.server.core.analysis.worker.IndicatorAggregateWorker.onWork(IndicatorAggregateWorker.java:73) [server-core-6.0.0-GA.jar:6.0.0-GA]
        at org.apache.skywalking.oap.server.core.analysis.worker.IndicatorAggregateWorker.access$100(IndicatorAggregateWorker.java:38) [server-core-6.0.0-GA.jar:6.0.0-GA]
        at org.apache.skywalking.oap.server.core.analysis.worker.IndicatorAggregateWorker$AggregatorConsumer.consume(IndicatorAggregateWorker.java:131) [server-core-6.0.0-GA.jar:6.0.0-GA]
        at org.apache.skywalking.apm.commons.datacarrier.consumer.ConsumerThread.consume(ConsumerThread.java:101) [apm-datacarrier-6.0.0-GA.jar:6.0.0-GA]
        at org.apache.skywalking.apm.commons.datacarrier.consumer.ConsumerThread.run(ConsumerThread.java:68) [apm-datacarrier-6.0.0-GA.jar:6.0.0-GA]

**Comment by 1248912240** [comment]
i run it in a docker linux, it appeares again
