### ISSUE TITLE
Exception::TracingContext :  More than 300 spans required to create java.lang.RuntimeEception: Shadow tracing context

### ISSUE THREAD

**Issue by ychandu** [apache/incubator-skywalking#1950]
WARN 2018-11-22 14:28:34:690 TracingContext :  More than 300 spans required to create
java.lang.RuntimeEception: Shadow tracing context. Thread dump
        at org.apache.skywalking.apm.agent.core.context.TracingContext.isLimitMechanismWorking(TracingContext.java:515)
        at org.apache.skywalking.apm.agent.core.context.TracingContext.createLocalSpan(TracingContext.java:290)
        at org.apache.skywalking.apm.agent.core.context.ContextManager.createLocalSpan(ContextManager.java:110)
        at org.apache.skywalking.apm.plugin.spring.annotations.SpringAnnotationInterceptor.beforeMethod(SpringAnnotationInterceptor.java:32)
        at org.apache.skywalking.apm.agent.core.plugin.interceptor.enhance.InstMethodsInter.intercept(InstMethodsInter.java:82)
        at xxx.RedisService.getTemplate(RedisService.java)

========================

WARN 2018-11-22 14:29:21:363 TracingContext :  More than 300 spans required to create
java.lang.RuntimeException: Shadow tracing context. Thread dump
        at org.apache.skywalking.apm.agent.core.context.TracingContext.isLimitMechanismWorking(TracingContext.java:515)
        at org.apache.skywalking.apm.agent.core.context.TracingContext.createLocalSpan(TracingContext.java:290)
        at org.apache.skywalking.apm.agent.core.context.ContextManager.createLocalSpan(ContextManager.java:110)
        at org.apache.skywalking.apm.plugin.spring.annotations.SpringAnnotationInterceptor.beforeMethod(SpringAnnotationInterceptor.java:32)
        at org.apache.skywalking.apm.agent.core.plugin.interceptor.enhance.InstMethodsInter.intercept(InstMethodsInter.java:82)

=======

I got so many such Warning after adding the optional plugin "spring annotation plugin".

I am using skywalking 6.0.0-apha

**Comment by wu-sheng** [comment]
Do you really try to trace so many spans in a single request? And if no this plugin, do you trace report and visualize right?

**Comment by wu-sheng** [comment]
This warning based on setting in Config.java. Could be override by agent.config. For each request, the segment should include less than 300 spans. The segment is a part of trace in a single thread per request.

**Comment by wu-sheng** [comment]
If you still want `trim` happens, which is good for memory, then, you could set log level to `error` :P Sorry. It is not a perfect solution, but works.
