### ISSUE TITLE
setSkyWalkingDynamicField(java.lang.Object) not found

### ISSUE THREAD

**Issue by yanghongge** [apache/incubator-skywalking#1955]
Please answer these questions before submitting your issue.

- Why do you submit this issue?
- [- ] Question or discussion
- [ ] Bug
- [ ] Requirement
- [ ] Feature or performance improvement

___
### Question
- use Spring bean plugin  with Dubbo, It can't work.

- What happen?
Service has been setSkyWalkingDynamicField by Spring bean plugin first, javassist in Dubbo :
java.lang.RuntimeException: [source error] setSkyWalkingDynamicField(java.lang.Object) not found in com.xx.services.Test4
	at com.alibaba.dubbo.common.bytecode.ClassGenerator.toClass(ClassGenerator.java:301)
	at com.alibaba.dubbo.common.bytecode.ClassGenerator.toClass(ClassGenerator.java:255)
	at com.alibaba.dubbo.common.bytecode.Wrapper.makeWrapper(Wrapper.java:237)
	at com.alibaba.dubbo.common.bytecode.Wrapper.getWrapper(Wrapper.java:99)
	at com.alibaba.dubbo.rpc.proxy.javassist.JavassistProxyFactory.getInvoker(JavassistProxyFactory.java:39)
	at com.alibaba.dubbo.rpc.proxy.wrapper.StubProxyFactoryWrapper.getInvoker(StubProxyFactoryWrapper.java:103)
	at com.alibaba.dubbo.rpc.ProxyFactory$Adaptive.getInvoker(ProxyFactory$Adaptive.java)
	at com.alibaba.dubbo.config.ServiceConfig.exportLocal(ServiceConfig.java:528)
	at com.alibaba.dubbo.config.ServiceConfig.doExportUrlsFor1Protocol(ServiceConfig.java:485)
	at com.alibaba.dubbo.config.ServiceConfig.doExportUrls(ServiceConfig.java:357)
	at com.alibaba.dubbo.config.ServiceConfig.doExport(ServiceConfig.java:316)
	at com.alibaba.dubbo.config.ServiceConfig.export(ServiceConfig.java:215)
	at com.alibaba.dubbo.config.spring.ServiceBean.onApplicationEvent(ServiceBean.java:121)
	at com.alibaba.dubbo.config.spring.ServiceBean.onApplicationEvent(ServiceBean.java:50)
	at org.springframework.context.event.SimpleApplicationEventMulticaster.invokeListener(SimpleApplicationEventMulticaster.java:166)
	at org.springframework.context.event.SimpleApplicationEventMulticaster.multicastEvent(SimpleApplicationEventMulticaster.java:138)
	at org.springframework.context.support.AbstractApplicationContext.publishEvent(AbstractApplicationContext.java:383)
	at org.springframework.context.support.AbstractApplicationContext.publishEvent(AbstractApplicationContext.java:337)
	at org.springframework.context.support.AbstractApplicationContext.finishRefresh(AbstractApplicationContext.java:882)
	at org.springframework.boot.context.embedded.EmbeddedWebApplicationContext.finishRefresh(EmbeddedWebApplicationContext.java:144)
	at org.springframework.context.support.AbstractApplicationContext.refresh(AbstractApplicationContext.java:545)
	at org.springframework.boot.context.embedded.EmbeddedWebApplicationContext.refresh(EmbeddedWebApplicationContext.java:122)
	at org.springframework.boot.SpringApplication.refresh(SpringApplication.java:761)
	at org.springframework.boot.SpringApplication.refreshContext(SpringApplication.java:371)
	at org.springframework.boot.SpringApplication.run(SpringApplication.java:315)
	at org.springframework.boot.SpringApplication.run(SpringApplication.java:1186)
	at org.springframework.boot.SpringApplication.run(SpringApplication.java:1175)

___
### Requirement or improvement
- Spring boot 1.4.3.RELEASE  Dubbo 2.6.0 skywalking5/6 .

Please take a look at my question.

**Comment by wu-sheng** [comment]
Ref to https://github.com/apache/incubator-skywalking/issues/1769 Look like 2.6.5 should work. Could you verify again? 

And, it is still no working in 2.6.5 for you, which had verified by others, then we need your demo app to reproduce this. Thanks.

**Comment by wu-sheng** [comment]
Why the @service class is also in dubbo controlled? Which scenario are you?

**Comment by yanghongge** [comment]
public interface T1 {public void test1();}
@Service
public class Test1 implements T1 {}

<dubbo:service registry="x1" protocol="dubbo" interface="com.kaishustory.services.T1" ref="test1"/>

by this scenario  @wu-sheng

**Comment by wu-sheng** [comment]
You need to report to Dubbo community, and link to this issue. We need their help to see what is happening. 

I highly recommend don't use in this way. Which either service or dubbo.

**Comment by wu-sheng** [comment]
This is really like dubbo can't survive from skywalking's dynamic class.

**Comment by yanghongge** [comment]
Ok,I'll report it to Dubbo community, and find a solution, thank you for your reply.

**Comment by wu-sheng** [comment]
Thanks. Please link this issue to them. If anything we could help, please let us known

**Comment by ascrutae** [comment]
Ref #2064

**Comment by wu-sheng** [comment]
Closing, PR is going to merge soon.
