### ISSUE TITLE
The Collector has an exception when querying Trace data.

### ISSUE THREAD

**Issue by ascrutae** [apache/incubator-skywalking#1968]
Please answer these questions before submitting your issue.

- Why do you submit this issue?
- [ ] Question or discussion
- [x] Bug
- [ ] Requirement
- [ ] Feature or performance improvement

Here is the stack:
```
2018-11-27 20:50:29,145 - graphql.execution.SimpleDataFetcherExceptionHandler -1058296774 [qtp831654622-3135] WARN  [] - Exception while fetching data (/queryBasicTraces) : Elasticsearch exception [type=search_phase_execution_exception, reason=all shards failed]
org.elasticsearch.ElasticsearchStatusException: Elasticsearch exception [type=search_phase_execution_exception, reason=all shards failed]
        at org.elasticsearch.rest.BytesRestResponse.errorFromXContent(BytesRestResponse.java:177) ~[elasticsearch-6.3.2.jar:6.3.2]
        at org.elasticsearch.client.RestHighLevelClient.parseEntity(RestHighLevelClient.java:653) ~[elasticsearch-rest-high-level-client-6.3.2.jar:6.3.2]
        at org.elasticsearch.client.RestHighLevelClient.parseResponseException(RestHighLevelClient.java:628) ~[elasticsearch-rest-high-level-client-6.3.2.jar:6.3.2]
        at org.elasticsearch.client.RestHighLevelClient.performRequest(RestHighLevelClient.java:535) ~[elasticsearch-rest-high-level-client-6.3.2.jar:6.3.2]
        at org.elasticsearch.client.RestHighLevelClient.performRequestAndParseEntity(RestHighLevelClient.java:508) ~[elasticsearch-rest-high-level-client-6.3.2.jar:6.3.2]
        at org.elasticsearch.client.RestHighLevelClient.search(RestHighLevelClient.java:404) ~[elasticsearch-rest-high-level-client-6.3.2.jar:6.3.2]
        at org.apache.skywalking.oap.server.library.client.elasticsearch.ElasticSearchClient.search(ElasticSearchClient.java:122) ~[library-client-6.0.0-alpha-SNAPSHOT.jar:6.0.0-alpha-SNAPSHOT]
        at org.apache.skywalking.oap.server.storage.plugin.elasticsearch.query.TraceQueryEsDAO.queryBasicTraces(TraceQueryEsDAO.java:99) ~[storage-elasticsearch-plugin-6.0.0-alpha-SNAPSHOT.jar:6.0.0-alpha-SNAPSHOT]
        at org.apache.skywalking.oap.server.core.query.TraceQueryService.queryBasicTraces(TraceQueryService.java:95) ~[server-core-6.0.0-alpha-SNAPSHOT.jar:6.0.0-alpha-SNAPSHOT]
        at org.apache.skywalking.oap.query.graphql.resolver.TraceQuery.queryBasicTraces(TraceQuery.java:74) ~[query-graphql-plugin-6.0.0-alpha-SNAPSHOT.jar:6.0.0-alpha-SNAPSHOT]
        at org.apache.skywalking.oap.query.graphql.resolver.TraceQueryMethodAccess.invoke(Unknown Source) ~[reflectasm-1.11.7.jar:6.0.0-alpha-SNAPSHOT]
        at com.coxautodev.graphql.tools.MethodFieldResolverDataFetcher.get(MethodFieldResolver.kt:147) ~[graphql-java-tools-5.2.3.jar:?]
        at graphql.execution.ExecutionStrategy.fetchField(ExecutionStrategy.java:227) [graphql-java-8.0.jar:?]
        at graphql.execution.ExecutionStrategy.resolveField(ExecutionStrategy.java:170) [graphql-java-8.0.jar:?]
        at graphql.execution.AsyncExecutionStrategy.execute(AsyncExecutionStrategy.java:59) [graphql-java-8.0.jar:?]
        at graphql.execution.Execution.executeOperation(Execution.java:158) [graphql-java-8.0.jar:?]
        at graphql.execution.Execution.execute(Execution.java:100) [graphql-java-8.0.jar:?]
        at graphql.GraphQL.execute(GraphQL.java:558) [graphql-java-8.0.jar:?]
        at graphql.GraphQL.parseValidateAndExecute(GraphQL.java:500) [graphql-java-8.0.jar:?]
        at graphql.GraphQL.executeAsync(GraphQL.java:470) [graphql-java-8.0.jar:?]
        at graphql.GraphQL.execute(GraphQL.java:401) [graphql-java-8.0.jar:?]
....
 Caused by: org.elasticsearch.client.ResponseException: method [POST], host [http://192.168.10.17:9200], URI [/segment/type/_search?typed_keys=true&ignore_unavailable=false&expand_wildcards=open&allow_no_indices=true&search_type=query_then_fetch&batched_reduce_size=512], status line [HTTP/1.1 500 Internal Server Error]
{"error":{"root_cause":[{"type":"query_phase_execution_exception","reason":"Result window is too large, from + size must be less than or equal to: [10000] but was [1220020]. See the scroll api for a more efficient way to request large data sets. This limit can be set by changing the [index.max_result_window] index level setting."}],"type":"search_phase_execution_exception","reason":"all shards failed","phase":"query","grouped":true,"failed_shards":[{"shard":0,"index":"segment","node":"FIjl8em3RomnhSuSckWMzw","reason":{"type":"query_phase_execution_exception","reason":"Result window is too large, from + size must be less than or equal to: [10000] but was [1220020]. See the scroll api for a more efficient way to request large data sets. This limit can be set by changing the [index.max_result_window] index level setting."}}]},"status":500}
                at org.elasticsearch.client.RestClient$1.completed(RestClient.java:377) ~[elasticsearch-rest-client-6.3.2.jar:6.3.2]
                at org.elasticsearch.client.RestClient$1.completed(RestClient.java:366) ~[elasticsearch-rest-client-6.3.2.jar:6.3.2]
                at org.apache.http.concurrent.BasicFuture.completed(BasicFuture.java:119) ~[httpcore-4.4.5.jar:4.4.5]
                at org.apache.http.impl.nio.client.DefaultClientExchangeHandlerImpl.responseCompleted(DefaultClientExchangeHandlerImpl.java:177) ~[httpasyncclient-4.1.2.jar:4.1.2]
                at org.apache.http.nio.protocol.HttpAsyncRequestExecutor.processResponse(HttpAsyncRequestExecutor.java:436) ~[httpcore-nio-4.4.5.jar:4.4.5]
                at org.apache.http.nio.protocol.HttpAsyncRequestExecutor.inputReady(HttpAsyncRequestExecutor.java:326) ~[httpcore-nio-4.4.5.jar:4.4.5]
                at org.apache.http.impl.nio.DefaultNHttpClientConnection.consumeInput(DefaultNHttpClientConnection.java:265) ~[httpcore-nio-4.4.5.jar:4.4.5]
                at org.apache.http.impl.nio.client.InternalIODispatch.onInputReady(InternalIODispatch.java:81) ~[httpasyncclient-4.1.2.jar:4.1.2]
                at org.apache.http.impl.nio.client.InternalIODispatch.onInputReady(InternalIODispatch.java:39) ~[httpasyncclient-4.1.2.jar:4.1.2]
                at org.apache.http.impl.nio.reactor.AbstractIODispatch.inputReady(AbstractIODispatch.java:114) ~[httpcore-nio-4.4.5.jar:4.4.5]
                at org.apache.http.impl.nio.reactor.BaseIOReactor.readable(BaseIOReactor.java:162) ~[httpcore-nio-4.4.5.jar:4.4.5]
                at org.apache.http.impl.nio.reactor.AbstractIOReactor.processEvent(AbstractIOReactor.java:337) ~[httpcore-nio-4.4.5.jar:4.4.5]
                at org.apache.http.impl.nio.reactor.AbstractIOReactor.processEvents(AbstractIOReactor.java:315) ~[httpcore-nio-4.4.5.jar:4.4.5]
                at org.apache.http.impl.nio.reactor.AbstractIOReactor.execute(AbstractIOReactor.java:276) ~[httpcore-nio-4.4.5.jar:4.4.5]
                at org.apache.http.impl.nio.reactor.BaseIOReactor.execute(BaseIOReactor.java:104) ~[httpcore-nio-4.4.5.jar:4.4.5]
                at org.apache.http.impl.nio.reactor.AbstractMultiworkerIOReactor$Worker.run(AbstractMultiworkerIOReactor.java:588) ~[httpcore-nio-4.4.5.jar:4.4.5]
                ... 1 more
```

**Comment by peng-yongsheng** [comment]
The paging query in every database are similar.  It gets slower and slower as you page down too much.
Although, the elasticsearch notice us to use scroll search to request large data. But, I suggest we can add a limit size in UI and add other search conditions to make it easier for users to search for desired results.

**Comment by wu-sheng** [comment]
I agree. 

FYI @hanahmily

**Comment by wu-sheng** [comment]
@TinyAllen We need to set a paging condition, no matter which page size the user choose, don't let user go to more than 10000 rows.
- 20 rows per page, than set max page number to 500
- 50 rows per page, max page 200
- .....

Also give user a tip, `Don't allow to query rows after 10000, please change your query conditions.`
