### ISSUE TITLE
HystrixGatewayFilterFactory java.lang.ClassCastException

### ISSUE THREAD

**Issue by ppboyhai** [apache/incubator-skywalking#2008]
Please answer these questions before submitting your issue.

- Why do you submit this issue?
- [ √] Question or discussion
- [ √] Bug
- [ ] Requirement
- [ ] Feature or performance improvement

___
### Question
- What do you want to know?

___
### Bug
- Which version of SkyWalking, OS and JRE?
 SkyWalking6.0 alpha 、windows10、JDK1.8
- Which company or project?

- What happen?
环境及场景如下
1.通过本地idea启动spring boot2 编写的服务并加入了skywalking的vm参数
2.本地项目是分布式服务，使用了spring eureka、 spring config、 spring cloud gateway
3.项目启动均正常，但是在调用服务的时候，网管服务报错如下：,所有对外接口均不能正常调用
`java.lang.ClassCastException: org.springframework.cloud.gateway.filter.factory.HystrixGatewayFilterFactory$RouteHystrixCommand cannot be cast to org.apache.skywalking.apm.agent.core.plugin.interceptor.enhance.EnhancedInstance
	at org.apache.skywalking.apm.plugin.hystrix.v1.SWExecutionHookWrapper.onStart(SWExecutionHookWrapper.java:42)
	at com.netflix.hystrix.AbstractCommand$ExecutionHookDeprecationWrapper.onStart(AbstractCommand.java:2134)
	at com.netflix.hystrix.AbstractCommand.applyHystrixSemantics(AbstractCommand.java:520)
	at com.netflix.hystrix.AbstractCommand.access$200(AbstractCommand.java:60)
	at com.netflix.hystrix.AbstractCommand$4.call(AbstractCommand.java:419)
	at com.netflix.hystrix.AbstractCommand$4.call(AbstractCommand.java:413)
	at rx.internal.operators.OnSubscribeDefer.call(OnSubscribeDefer.java:46)
	at rx.internal.operators.OnSubscribeDefer.call(OnSubscribeDefer.java:35)
	at rx.Observable.unsafeSubscribe(Observable.java:10327)
	at rx.internal.operators.OnSubscribeMap.call(OnSubscribeMap.java:48)
	at rx.internal.operators.OnSubscribeMap.call(OnSubscribeMap.java:33)
	at rx.Observable.unsafeSubscribe(Observable.java:10327)
	at rx.internal.operators.OnSubscribeDoOnEach.call(OnSubscribeDoOnEach.java:41)
	at rx.internal.operators.OnSubscribeDoOnEach.call(OnSubscribeDoOnEach.java:30)
	at rx.internal.operators.OnSubscribeLift.call(OnSubscribeLift.java:48)
	at rx.internal.operators.OnSubscribeLift.call(OnSubscribeLift.java:30)
	at rx.Observable.unsafeSubscribe(Observable.java:10327)
	at rx.internal.operators.OnSubscribeDoOnEach.call(OnSubscribeDoOnEach.java:41)
	at rx.internal.operators.OnSubscribeDoOnEach.call(OnSubscribeDoOnEach.java:30)
	at rx.Observable.unsafeSubscribe(Observable.java:10327)
	at rx.internal.operators.OnSubscribeDefer.call(OnSubscribeDefer.java:51)
	at rx.internal.operators.OnSubscribeDefer.call(OnSubscribeDefer.java:35)
	at rx.Observable.subscribe(Observable.java:10423)
	at rx.Observable.subscribe(Observable.java:10390)
	at rx.Observable.subscribe(Observable.java:10271)
	at org.springframework.cloud.gateway.filter.factory.HystrixGatewayFilterFactory.lambda$null$0(HystrixGatewayFilterFactory.java:99)
	at org.springframework.cloud.gateway.filter.factory.HystrixGatewayFilterFactory$$Lambda$926/1681626645.accept(Unknown Source)
	at reactor.core.publisher.MonoCreate.subscribe(MonoCreate.java:54)
	at reactor.core.publisher.MonoOnErrorResume.subscribe(MonoOnErrorResume.java:44)
	at reactor.core.publisher.Mono.subscribe(Mono.java:3080)
	at reactor.core.publisher.MonoIgnorePublisher.subscribe(MonoIgnorePublisher.java:41)
	at reactor.core.publisher.MonoDefer.subscribe(MonoDefer.java:53)
	at reactor.core.publisher.MonoDefer.subscribe(MonoDefer.java:53)
	at reactor.core.publisher.MonoFlatMap$FlatMapMain.onNext(MonoFlatMap.java:150)
	at reactor.core.publisher.FluxMapFuseable$MapFuseableSubscriber.onNext(FluxMapFuseable.java:115)
	at reactor.core.publisher.Operators$MonoSubscriber.complete(Operators.java:1083)
	at reactor.core.publisher.MonoReduceSeed$ReduceSeedSubscriber.onComplete(MonoReduceSeed.java:150)
	at reactor.core.publisher.Operators$MultiSubscriptionSubscriber.onComplete(Operators.java:1318)
	at reactor.core.publisher.FluxDoFinally$DoFinallySubscriber.onComplete(FluxDoFinally.java:138)
	at reactor.core.publisher.FluxMap$MapSubscriber.onComplete(FluxMap.java:130)
	at reactor.core.publisher.Operators$MultiSubscriptionSubscriber.onComplete(Operators.java:1318)
	at reactor.core.publisher.FluxConcatMap$ConcatMapImmediate.drain(FluxConcatMap.java:349)
	at reactor.core.publisher.FluxConcatMap$ConcatMapImmediate.onComplete(FluxConcatMap.java:265)
	at reactor.core.publisher.Operators$MultiSubscriptionSubscriber.onComplete(Operators.java:1318)
	at reactor.core.publisher.MonoFlatMapMany$FlatMapManyInner.onComplete(MonoFlatMapMany.java:248)
	at io.lettuce.core.RedisPublisher$State.onAllDataRead(RedisPublisher.java:646)
	at io.lettuce.core.RedisPublisher$RedisSubscription.onAllDataRead(RedisPublisher.java:298)
	at io.lettuce.core.RedisPublisher$SubscriptionCommand.complete(RedisPublisher.java:729)
	at io.lettuce.core.protocol.CommandWrapper.complete(CommandWrapper.java:57)
	at io.lettuce.core.protocol.CommandHandler.complete(CommandHandler.java:598)
	at io.lettuce.core.protocol.CommandHandler.decode(CommandHandler.java:556)
	at io.lettuce.core.protocol.CommandHandler.channelRead(CommandHandler.java:508)
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:362)
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:348)
	at io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:340)
	at io.netty.channel.ChannelInboundHandlerAdapter.channelRead(ChannelInboundHandlerAdapter.java:86)
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:362)
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:348)
	at io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:340)
	at io.netty.channel.ChannelInboundHandlerAdapter.channelRead(ChannelInboundHandlerAdapter.java:86)
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:362)
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:348)
	at io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:340)
	at io.netty.channel.DefaultChannelPipeline$HeadContext.channelRead(DefaultChannelPipeline.java:1434)
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:362)
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:348)
	at io.netty.channel.DefaultChannelPipeline.fireChannelRead(DefaultChannelPipeline.java:965)
	at io.netty.channel.nio.AbstractNioByteChannel$NioByteUnsafe.read(AbstractNioByteChannel.java:163)
	at io.netty.channel.nio.NioEventLoop.processSelectedKey(NioEventLoop.java:647)
	at io.netty.channel.nio.NioEventLoop.processSelectedKeysOptimized(NioEventLoop.java:582)
	at io.netty.channel.nio.NioEventLoop.processSelectedKeys(NioEventLoop.java:499)
	at io.netty.channel.nio.NioEventLoop.run(NioEventLoop.java:461)
	at io.netty.util.concurrent.SingleThreadEventExecutor$5.run(SingleThreadEventExecutor.java:884)
	at io.netty.util.concurrent.FastThreadLocalRunnable.run(FastThreadLocalRunnable.java:30)
	at java.lang.Thread.run(Thread.java:745)`
___
### Requirement or improvement
- Please describe about your requirements or improvement suggestions.

**Comment by github24518** [comment]
我也遇到这个问题！！
Whitelabel Error Page
This application has no configured error view, so you are seeing this as a fallback.

Thu Dec 06 17:51:29 CST 2018
There was an unexpected error (type=Internal Server Error, status=500).
**org.springframework.cloud.gateway.filter.factory.HystrixGatewayFilterFactory$RouteHystrixCommand cannot be cast to org.apache.skywalking.apm.agent.core.plugin.interceptor.enhance.EnhancedInstance**

**Comment by github24518** [comment]
使用springcloud gateway代理转发的时候，出现异常
Whitelabel Error Page
This application has no configured error view, so you are seeing this as a fallback.

Thu Dec 06 17:51:29 CST 2018
There was an unexpected error (type=Internal Server Error, status=500).
**org.springframework.cloud.gateway.filter.factory.HystrixGatewayFilterFactory$RouteHystrixCommand cannot be cast to org.apache.skywalking.apm.agent.core.plugin.interceptor.enhance.EnhancedInstance**

**Comment by wu-sheng** [comment]
Need your demo codes.

**Comment by github24518** [comment]
> o
就是一个普通代理转发项目哇，启动时候指定skywalking-agent.jar。

**Comment by wu-sheng** [comment]
ClassCastException has been fixed, follow #2126 to support gateway
