### ISSUE TITLE
DiscoveryRestServiceClient :  Find server list fail

### ISSUE THREAD

**Issue by xiaoxing598** [apache/incubator-skywalking#2065]
Please answer these questions before submitting your issue.

- Why do you submit this issue?
- [x] Question or discussion
- [ ] Bug
- [ ] Requirement
- [ ] Feature or performance improvement

___
### Question
- What do you want to know?
Configuring the collection server failed
___
### Bug
- Which version of SkyWalking, OS and JRE?
6.0.0
- Which company or project?

- What happen?

1. I completed the SkyWalking deployment on a server, which can be verified from the three ports that were launched.
2. I started the application on another server and expect to send the data to the server through the proxy. But unfortunately the following error has occurred:
```
ERROR 2018-12-18 19:40:50:358 DiscoveryRestServiceClient :  Find server list fail. 
org.apache.skywalking.apm.agent.core.remote.RESTResponseStatusError: Unexpected service response code: 404
	at org.apache.skywalking.apm.agent.core.remote.DiscoveryRestServiceClient.findServerList(DiscoveryRestServiceClient.java:92)
	at org.apache.skywalking.apm.agent.core.remote.DiscoveryRestServiceClient.run(DiscoveryRestServiceClient.java:77)
	at org.apache.skywalking.apm.util.RunnableWithExceptionProtection.run(RunnableWithExceptionProtection.java:36)
	at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511)
	at java.util.concurrent.FutureTask.runAndReset(FutureTask.java:308)
	at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.access$301(ScheduledThreadPoolExecutor.java:180)
	at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.run(ScheduledThreadPoolExecutor.java:294)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
	at java.lang.Thread.run(Thread.java:748)
```
3. I started to detect if I could connect to the other end on this server. The answer is yes. I can verify this problem with TELNET.
```
[root@dev /www/test-service]# telnet 10.0.0.0 11800
Trying 10.0.0.0...
Connected to 10.0.0.0.
Escape character is '^]'.
```
4. Since the target port is connectable, why doesn't SkyWalking think so?
```
collector.servers=10.0.0.0:11800
```

**Comment by wu-sheng** [comment]
No service discovery in 6.x. Are you using 5.x agent to connect 6's backend?

**Comment by xiaoxing598** [comment]
Yes, the version of the agent I use is 5.x. Is it normal after upgrading to 6.x?

**Comment by wu-sheng** [comment]
For considering cloud native, the load balance is not skywalking agent responsibility. Please removed in 6.x. If you want to use 6.x backend, please upgrade the agents. No big change in agent core.

**Comment by xiaoxing598** [comment]
Can work normally, thank you.
