### ISSUE TITLE
One trace segment has been abandoned, cause by buffer is full

### ISSUE THREAD

**Issue by WentHao** [apache/incubator-skywalking#2066]
Please answer these questions before submitting your issue.

- Why do you submit this issue?
- [X] Question or discussion

___
### Question
- What do you want to know?

my project has too many "One trace segment has been abandoned, cause by buffer is full".
I tried to make larger thread(from 1 to 20) & lower consumeCycle (from 20 to 2) ,not work. 
can you help me?
___

**Comment by wu-sheng** [comment]
That depends on your backend performance. This is a memory fail safe mechanism. Don't extend thread or reduce the consume cycle. Not helpful.

**Comment by foxracle** [comment]
we have the same issues when we add more services to be traced. what do you mean the backend? is it the server that the sw agent on or the server that sw collector service on? we find no performance's issue on both side.

**Comment by wu-sheng** [comment]
How do you know you haven't performance issue at backend side? I doubt about this conclusion. Because you mentioned this happens when you add more services, this means more payloads to the backend.

**Comment by foxracle** [comment]
you are right, we only use cpu load and cpu utilization to check the performance of the whole server that backend on, we have not find any hint messages  in the backend's log. any other hints about the backend service performance's bottleneck we can find?

**Comment by wu-sheng** [comment]
If you are using default settings, please recheck the memory settings of JVM. Default is only 512M

**Comment by WentHao** [comment]
I use the version 5.0.0-GA. 
For me，the point is collector's performance. I rewrite the load balance rule.

**Comment by wu-sheng** [comment]
Yes. Load balance is recommended between agent and collector cluster. That is why naming is removed permanently

**Comment by foxracle** [comment]
two questions:
1: if we plan to use three backend as a cluster by using consul, the agent's collector.backend_service setting is still one of the collector's IP, right?
2: Is it still necessary to use LB between agent and collector when use a collector cluster? why? if it's called cluster, it is strange that no embeded route service to dispatch requests to all collector service evenly.

**Comment by tinytigerchaos** [comment]
we have the same issues , and i fix it by adding several es nodes to es cluster .
i thought es cluster need more resources to process the trace data than opa server.

**Comment by wu-sheng** [comment]
> we have the same issues , and i fix it by adding several es nodes to es cluster .
i thought es cluster need more resources to process the trace data than opa server.

If some cases, yes.

**Comment by karott** [comment]
i encountered  this problem too...and i saw some es about threads blocked on BulkProcessor,it's lock is  hold by another thread which waits for a BulkRequestHandler#semaphore.acquire(),the semaphore can't acquire

![image](https://user-images.githubusercontent.com/3212080/59485998-716c0580-8eaa-11e9-95c3-f3faa784cb64.png)

![image](https://user-images.githubusercontent.com/3212080/59486009-792baa00-8eaa-11e9-813b-dd5f75b63dd4.png)

**Comment by weiqiang333** [comment]
> > we have the same issues , and i fix it by adding several es nodes to es cluster .
> > i thought es cluster need more resources to process the trace data than opa server.
> 
> If some cases, yes.

I also encountered ES bottleneck, OAP CPU overflow

**Comment by wujun8** [comment]
Actually, this bottleneck is just in  agent side.
You can config like this:
```
buffer.channel_size=10
buffer.buffer_size=10000
```
Notify that it will cost more resources.

And OAP server bottleneck is something like this:

```
ERROR 2019-09-26 10:30:25:165 grpc-default-executor-1 TraceSegmentServiceClient :  Send UpstreamSegment to collector fail with a grpc internal exception.
org.apache.skywalking.apm.dependencies.io.grpc.StatusRuntimeException: DEADLINE_EXCEEDED: deadline exceeded after 9999621000ns
	at org.apache.skywalking.apm.dependencies.io.grpc.Status.asRuntimeException(Status.java:526)
	at org.apache.skywalking.apm.dependencies.io.grpc.stub.ClientCalls$StreamObserverToCallListenerAdapter.onClose(ClientCalls.java:420)
	at org.apache.skywalking.apm.dependencies.io.grpc.PartialForwardingClientCallListener.onClose(PartialForwardingClientCallListener.java:39)
	at org.apache.skywalking.apm.dependencies.io.grpc.ForwardingClientCallListener.onClose(ForwardingClientCallListener.java:23)
	at org.apache.skywalking.apm.dependencies.io.grpc.ForwardingClientCallListener$SimpleForwardingClientCallListener.onClose(ForwardingClientCallListener.java:40)
	at org.apache.skywalking.apm.dependencies.io.grpc.internal.CensusStatsModule$StatsClientInterceptor$1$1.onClose(CensusStatsModule.java:684)
	at org.apache.skywalking.apm.dependencies.io.grpc.PartialForwardingClientCallListener.onClose(PartialForwardingClientCallListener.java:39)
	at org.apache.skywalking.apm.dependencies.io.grpc.ForwardingClientCallListener.onClose(ForwardingClientCallListener.java:23)
	at org.apache.skywalking.apm.dependencies.io.grpc.ForwardingClientCallListener$SimpleForwardingClientCallListener.onClose(ForwardingClientCallListener.java:40)
	at org.apache.skywalking.apm.dependencies.io.grpc.internal.CensusTracingModule$TracingClientInterceptor$1$1.onClose(CensusTracingModule.java:403)
	at org.apache.skywalking.apm.dependencies.io.grpc.internal.ClientCallImpl.closeObserver(ClientCallImpl.java:459)
	at org.apache.skywalking.apm.dependencies.io.grpc.internal.ClientCallImpl.access$300(ClientCallImpl.java:63)
	at org.apache.skywalking.apm.dependencies.io.grpc.internal.ClientCallImpl$ClientStreamListenerImpl.close(ClientCallImpl.java:546)
	at org.apache.skywalking.apm.dependencies.io.grpc.internal.ClientCallImpl$ClientStreamListenerImpl.access$600(ClientCallImpl.java:467)
	at org.apache.skywalking.apm.dependencies.io.grpc.internal.ClientCallImpl$ClientStreamListenerImpl$1StreamClosed.runInContext(ClientCallImpl.java:584)
	at org.apache.skywalking.apm.dependencies.io.grpc.internal.ContextRunnable.run(ContextRunnable.java:37)
	at org.apache.skywalking.apm.dependencies.io.grpc.internal.SerializingExecutor.run(SerializingExecutor.java:123)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1145)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:615)
	at java.lang.Thread.run(Thread.java:745)
```

**Comment by wangchengguo** [comment]
> 两个问题：
> 1：如果计划通过使用领事将三个后端用作群集，则代理的collector.backend_service设置仍然是收集器的IP之一，对吗？
> 2：使用收集器集群时，是否仍需要在代理和收集器之间使用LB？为什么？如果称为集群，那么很奇怪，没有嵌入的路由服务可以将请求平均分配给所有收集器服务。

Do you have answers to these two questions

**Comment by wangchengguo** [comment]
> two questions:
> 1: if we plan to use three backend as a cluster by using consul, the agent's collector.backend_service setting is still one of the collector's IP, right?
> 2: Is it still necessary to use LB between agent and collector when use a collector cluster? why? if it's called cluster, it is strange that no embeded route service to dispatch requests to all collector service evenly.

Do you have answers to these two questions
