### ISSUE TITLE
Bug java.lang.ArithmeticException

### ISSUE THREAD

**Issue by zhuoran** [apache/incubator-skywalking#2079]
v6.0.0-alpha  

org.apache.skywalking.oap.server.core.analysis.worker.IndicatorRemoteWorker -5694 [DataCarrier.IndicatorAggregateWorker.instance_jvm_memory_noheap.Consumser.0.Thread] ERROR [] - /
 by zero
java.lang.ArithmeticException: / by zero
	at org.apache.skywalking.oap.server.core.remote.selector.HashCodeSelector.select(HashCodeSelector.java:32) ~[server-core-6.0.0-alpha.jar:6.0.0-alpha]
	at org.apache.skywalking.oap.server.core.remote.RemoteSenderService.send(RemoteSenderService.java:50) ~[server-core-6.0.0-alpha.jar:6.0.0-alpha]
	at org.apache.skywalking.oap.server.core.analysis.worker.IndicatorRemoteWorker.in(IndicatorRemoteWorker.java:51) ~[server-core-6.0.0-alpha.jar:6.0.0-alpha]
	at org.apache.skywalking.oap.server.core.analysis.worker.IndicatorRemoteWorker.in(IndicatorRemoteWorker.java:33) ~[server-core-6.0.0-alpha.jar:6.0.0-alpha]
	at org.apache.skywalking.oap.server.core.analysis.worker.IndicatorAggregateWorker.lambda$sendToNext$0(IndicatorAggregateWorker.java:84) ~[server-core-6.0.0-alpha.jar:6.0.0-alpha]
	at java.util.HashMap$Values.forEach(HashMap.java:980) [?:1.8.0_121]
	at org.apache.skywalking.oap.server.core.analysis.worker.IndicatorAggregateWorker.sendToNext(IndicatorAggregateWorker.java:79) [server-core-6.0.0-alpha.jar:6.0.0-alpha]
	at org.apache.skywalking.oap.server.core.analysis.worker.IndicatorAggregateWorker.onWork(IndicatorAggregateWorker.java:64) [server-core-6.0.0-alpha.jar:6.0.0-alpha]
	at org.apache.skywalking.oap.server.core.analysis.worker.IndicatorAggregateWorker.access$100(IndicatorAggregateWorker.java:35) [server-core-6.0.0-alpha.jar:6.0.0-alpha]
	at org.apache.skywalking.oap.server.core.analysis.worker.IndicatorAggregateWorker$AggregatorConsumer.consume(IndicatorAggregateWorker.java:122) [server-core-6.0.0-alpha.jar:6.0.0-alpha]
	at org.apache.skywalking.apm.commons.datacarrier.consumer.ConsumerThread.consume(ConsumerThread.java:101) [apm-datacarrier-6.0.0-alpha.jar:6.0.0-alpha]
	at org.apache.skywalking.apm.commons.datacarrier.consumer.ConsumerThread.run(ConsumerThread.java:68) [apm-datacarrier-6.0.0-alpha.jar:6.0.0-alpha]
2018-12-21 14:32:18,165 - org.apache.skyw

**Comment by wu-sheng** [comment]
@peng-yongsheng I remember this should be fixed in beta release, right?

**Comment by wu-sheng** [comment]
Fixed in beta release, please try.
