### ISSUE TITLE
logs/oap.log： Exception in thread "main" java.lang.NullPointerException

### ISSUE THREAD

**Issue by liliang8858** [apache/incubator-skywalking#2085]
Please answer these questions before submitting your issue.

- Why do you submit this issue?
- [1] Question or discussion
- [ ] Bug
- [ ] Requirement
- [ ] Feature or performance improvement

___
### Question
- What do you want to know?
Exception in thread "main" java.lang.NullPointerException
        at org.apache.skywalking.oap.server.library.client.elasticsearch.ElasticSearchClient.parseClusterNodes(ElasticSearchClient.java:79)
        at org.apache.skywalking.oap.server.library.client.elasticsearch.ElasticSearchClient.connect(ElasticSearchClient.java:62)
        at org.apache.skywalking.oap.server.storage.plugin.elasticsearch.StorageModuleElasticsearchProvider.start(StorageModuleElasticsearchProvider.java:87)
        at org.apache.skywalking.oap.server.library.module.BootstrapFlow.start(BootstrapFlow.java:57)
        at org.apache.skywalking.oap.server.library.module.ModuleManager.init(ModuleManager.java:65)
        at org.apache.skywalking.oap.server.starter.OAPServerStartUp.main(OAPServerStartUp.java:37)
___
### Bug
- Which version of SkyWalking, OS and JRE?

- Which company or project?

- What happen?
If possible, provide a way for reproducing the error. e.g. demo application, component version.

___
### Requirement or improvement
- Please describe about your requirements or improvement suggestions.

**Comment by wu-sheng** [comment]
If you didn't set the ElaticSearch connection IPs, this happens.
