### ISSUE TITLE
Oracle JDBC error

### ISSUE THREAD

**Issue by langyan1022** [apache/incubator-skywalking#2098]
Please answer these questions before submitting your issue.

- Why do you submit this issue?
- [X] Question or discussion
- [X] Bug
- [ ] Requirement
- [ ] Feature or performance improvement

___
### Question
- What do you want to know?
Whether Oracle jdbc supports, which version is supported by the highest.
I find apm-oracle-10.x-plugin-1.0.0 .
If I use it, do I have to delete jdbc-common-plugin.
___
### Bug
- Which version of SkyWalking, OS and JRE?
SkyWalking Version:6.0.0-beta
OS:linux
JRE:oracle 1.8
- Which company or project?

- What happen?
I can't see the DB information again on the Dashboard.
<img width="472" alt="image" src="https://user-images.githubusercontent.com/5259422/50531903-ff963e80-0b4b-11e9-8c3d-a9e3140b1b21.png">

And can't trace any SQL statement information.

When I see the log of agent(skywalking-api.log),I found this error log:

`InstMethodsInter :  class[class oracle.jdbc.OracleDriver] after method[connect] intercept failure
java.lang.ClassCastException: oracle.jdbc.driver.T4CConnection cannot be cast to org.apache.skywalking.apm.agent.core.plugin.interceptor.enhance.EnhancedInstance
        at org.apache.skywalking.apm.plugin.jdbc.JDBCDriverInterceptor.afterMethod(JDBCDriverInterceptor.java:45)
        at org.apache.skywalking.apm.agent.core.plugin.interceptor.enhance.InstMethodsInter.intercept(InstMethodsInter.java:105)
        at oracle.jdbc.driver.OracleDriver.connect(OracleDriver.java)
        at com.alibaba.druid.filter.FilterChainImpl.connection_connect(FilterChainImpl.java:156)
        at com.alibaba.druid.filter.stat.StatFilter.connection_connect(StatFilter.java:218)
        at com.alibaba.druid.filter.FilterChainImpl.connection_connect(FilterChainImpl.java:150)
        at com.alibaba.druid.filter.FilterAdapter.connection_connect(FilterAdapter.java:786)
        at com.alibaba.druid.filter.FilterChainImpl.connection_connect(FilterChainImpl.java:150)
        at com.alibaba.druid.pool.DruidAbstractDataSource.createPhysicalConnection(DruidAbstractDataSource.java:1560)
        at com.alibaba.druid.pool.DruidAbstractDataSource.createPhysicalConnection(DruidAbstractDataSource.java:1623)
        at com.alibaba.druid.pool.DruidDataSource$CreateConnectionThread.run(DruidDataSource.java:2468)`

**Comment by wu-sheng** [comment]
Please submit oracle plugin issue to 
https://github.com/OpenSkywalking/java-plugin-extensions

**Comment by wu-sheng** [comment]
FYI @ascrutae
