### ISSUE TITLE
Field named sdb in segment index not found

### ISSUE THREAD

**Issue by wangsz05** [apache/incubator-skywalking#2100]
Please answer these questions before submitting your issue.

- Why do you submit this issue?
- [ ] Question or discussion

___
### Question
- What do you want to know?
how can I solve the issue?
___
### Bug
- Which version of SkyWalking, OS and JRE?

 SkyWalking 5.0GA   + elasticsearch-5.6.14

HI  when I start the collectorService.sh ,I meet the "Field named sdb in segment index not found". the collector start fail

the trace is like this:

2018-12-29 11:26:28,885 - org.apache.skywalking.apm.collector.boot.CollectorBootStartUp -3476 [main] ERROR [] - Field named sdb in segment index not found.
org.apache.skywalking.apm.collector.core.module.ModuleStartException: Field named sdb in segment index not found.
        at org.apache.skywalking.apm.collector.storage.es.StorageModuleEsProvider.start(StorageModuleEsProvider.java:127) ~[collector-storage-es-provider-5.0.0-GA.jar:5.0.0-GA]
        at org.apache.skywalking.apm.collector.core.module.BootstrapFlow.start(BootstrapFlow.java:61) ~[apm-collector-core-5.0.0-GA.jar:5.0.0-GA]
        at org.apache.skywalking.apm.collector.core.module.ModuleManager.init(ModuleManager.java:68) ~[apm-collector-core-5.0.0-GA.jar:5.0.0-GA]
        at org.apache.skywalking.apm.collector.boot.CollectorBootStartUp.main(CollectorBootStartUp.java:45) [apm-collector-boot-5.0.0-GA.jar:5.0.0-GA]
Caused by: org.apache.skywalking.apm.collector.storage.StorageInstallException: Field named sdb in segment index not found.
        at org.apache.skywalking.apm.collector.storage.es.base.define.ElasticSearchStorageInstaller.columnCheck(ElasticSearchStorageInstaller.java:72) ~[collector-storage-es-provider-5.0.0-GA.jar:5.0.0-GA]
        at org.apache.skywalking.apm.collector.storage.StorageInstaller.install(StorageInstaller.java:60) ~[collector-storage-define-5.0.0-GA.jar:5.0.0-GA]
        at org.apache.skywalking.apm.collector.storage.es.StorageModuleEsProvider.start(StorageModuleEsProvider.java:125) ~[collector-storage-es-provider-5.0.0-GA.jar:5.0.0-GA]
        ... 3 more
"skywalking-collector-server.log" 585L, 133930C

**Comment by wu-sheng** [comment]
6.0 ga is not compatible with old version. So you need to reset the whole env including elasticsearch.

**Comment by jackzhangsir** [comment]
多谢，是需要删除表，还是把表的数据清空就行？

**Comment by wu-sheng** [comment]
Delete index or table.

**Comment by jackzhangsir** [comment]
多谢晟哥
