### ISSUE TITLE
Collector Exception :: Too Many Request Exception rejected by ES

### ISSUE THREAD

**Issue by ychandu** [apache/incubator-skywalking#2103]
`9608c%2FProducer_1/_update?refresh=true&timeout=1m], status line [HTTP/1.1 429 Too Many Requests]
{"error":{"root_cause":[{"type":"remote_transport_exception","reason":"[L-Llj8_][172.31.40.119:9300][indices:data/write/update[s]]"}],"type":"es_rejected_execution_exception","reason":"rejected execution of processing of [140631286][indices:data/write/bulk[s][p]]: request: BulkShardRequest [[endpoint_inventory][0]] containing [index {[endpoint_inventory][type][8_RabbitMQ/Topic/bravo-Platform-Events-ExchangeQueue/92:ORDER:39481770-0cc4-11e9-89bc-0a3b2ae9608c/Producer_1], source[{\"sequence\":19115,\"heartbeat_time\":1546237256866,\"service_id\":8,\"name\":\"RabbitMQ/Topic/bravo-Platform-Events-ExchangeQueue/92:ORDER:39481770-0cc4-11e9-89bc-0a3b2ae9608c/Producer\",\"detect_point\":1,\"register_time\":1546237252743}]}] and a refresh, target allocation id: 3ZnZK2L6R2uBlvmDl8zjMw, primary term: 1 on EsThreadPoolExecutor[name = L-Llj8_/write, queue capacity = 200, org.elasticsearch.common.util.concurrent.EsThreadPoolExecutor@6ac019e8[Running, pool size = 4, active threads = 4, queued tasks = 200, completed tasks = 4341962]]"},"status":429}
		at org.elasticsearch.client.RestClient$SyncResponseListener.get(RestClient.java:705) ~[elasticsearch-rest-client-6.3.2.jar:6.3.2]
		at org.elasticsearch.client.RestClient.performRequest(RestClient.java:235) ~[elasticsearch-rest-client-6.3.2.jar:6.3.2]
		at org.elasticsearch.client.RestClient.performRequest(RestClient.java:198) ~[elasticsearch-rest-client-6.3.2.jar:6.3.2]
		at org.elasticsearch.client.RestHighLevelClient.performRequest(RestHighLevelClient.java:522) ~[elasticsearch-rest-high-level-client-6.3.2.jar:6.3.2]
		at org.elasticsearch.client.RestHighLevelClient.performRequestAndParseEntity(RestHighLevelClient.java:508) ~[elasticsearch-rest-high-level-client-6.3.2.jar:6.3.2]
		at org.elasticsearch.client.RestHighLevelClient.update(RestHighLevelClient.java:366) ~[elasticsearch-rest-high-level-client-6.3.2.jar:6.3.2]
		at org.apache.skywalking.oap.server.library.client.elasticsearch.ElasticSearchClient.forceUpdate(ElasticSearchClient.java:153) ~[library-client-6.0.0-beta.jar:6.0.0-beta]
		at org.apache.skywalking.oap.server.storage.plugin.elasticsearch.base.RegisterEsDAO.forceUpdate(RegisterEsDAO.java:78) ~[storage-elasticsearch-plugin-6.0.0-beta.jar:6.0.0-beta]
		at org.apache.skywalking.oap.server.core.register.worker.RegisterPersistentWorker.lambda$onWork$0(RegisterPersistentWorker.java:79) ~[server-core-6.0.0-beta.jar:6.0.0-beta]
		at java.util.HashMap$Values.forEach(HashMap.java:981) [?:1.8.0_191]
		at org.apache.skywalking.oap.server.core.register.worker.RegisterPersistentWorker.onWork(RegisterPersistentWorker.java:74) [server-core-6.0.0-beta.jar:6.0.0-beta]
		at org.apache.skywalking.oap.server.core.register.worker.RegisterPersistentWorker.access$100(RegisterPersistentWorker.java:35) [server-core-6.0.0-beta.jar:6.0.0-beta]
		at org.apache.skywalking.oap.server.core.register.worker.RegisterPersistentWorker$PersistentConsumer.consume(RegisterPersistentWorker.java:120) [server-core-6.0.0-beta.jar:6.0.0-beta]
		at org.apache.skywalking.apm.commons.datacarrier.consumer.ConsumerThread.consume(ConsumerThread.java:101) [apm-datacarrier-6.0.0-beta.jar:6.0.0-beta]
		at org.apache.skywalking.apm.commons.datacarrier.consumer.ConsumerThread.run(ConsumerThread.java:68) [apm-datacarrier-6.0.0-beta.jar:6.0.0-beta]
	Caused by: org.elasticsearch.client.ResponseException: method [POST], host [http://localhost:9200], URI [/endpoint_inventory/type/8_RabbitMQ%2FTopic%2Fbravo-Platform-Events-ExchangeQueue%2F92:ORDER:39481770-0cc4-11e9-89bc-0a3b2ae9608c%2FProducer_1/_update?refresh=true&timeout=1m], status line [HTTP/1.1 429 Too Many Requests]
{"error":{"root_cause":[{"type":"remote_transport_exception","reason":"[L-Llj8_][172.31.40.119:9300][indices:data/write/update[s]]"}],"type":"es_rejected_execution_exception","reason":"rejected execution of processing of [140631286][indices:data/write/bulk[s][p]]: request: BulkShardRequest [[endpoint_inventory][0]] containing [index {[endpoint_inventory][type][8_RabbitMQ/Topic/bravo-Platform-Events-ExchangeQueue/92:ORDER:39481770-0cc4-11e9-89bc-0a3b2ae9608c/Producer_1], source[{\"sequence\":19115,\"heartbeat_time\":1546237256866,\"service_id\":8,\"name\":\"RabbitMQ/Topic/bravo-Platform-Events-ExchangeQueue/92:ORDER:39481770-0cc4-11e9-89bc-0a3b2ae9608c/Producer\",\"detect_point\":1,\"register_time\":1546237252743}]}] and a refresh, target allocation id: 3ZnZK2L6R2uBlvmDl8zjMw, primary term: 1 on EsThreadPoolExecutor[name = L-Llj8_/write, queue capacity = 200, org.elasticsearch.common.util.concurrent.EsThreadPoolExecutor@6ac019e8[Running, pool size = 4, active threads = 4, queued tasks = 200, completed tasks = 4341962]]"},"status":429}
		at org.elasticsearch.client.RestClient$1.completed(RestClient.java:377) ~[elasticsearch-rest-client-6.3.2.jar:6.3.2]
		at org.elasticsearch.client.RestClient$1.completed(RestClient.java:366) ~[elasticsearch-rest-client-6.3.2.jar:6.3.2]
		at org.apache.http.concurrent.BasicFuture.completed(BasicFuture.java:119) ~[httpcore-4.4.5.jar:4.4.5]
		at org.apache.http.impl.nio.client.DefaultClientExchangeHandlerImpl.responseCompleted(DefaultClientExchangeHandlerImpl.java:177) ~[httpasyncclient-4.1.2.jar:4.1.2]
		at org.apache.http.nio.protocol.HttpAsyncRequestExecutor.processResponse(HttpAsyncRequestExecutor.java:436) ~[httpcore-nio-4.4.5.jar:4.4.5]
		at org.apache.http.nio.protocol.HttpAsyncRequestExecutor.inputReady(HttpAsyncRequestExecutor.java:326) ~[httpcore-nio-4.4.5.jar:4.4.5]
		at org.apache.http.impl.nio.DefaultNHttpClientConnection.consumeInput(DefaultNHttpClientConnection.java:265) ~[httpcore-nio-4.4.5.jar:4.4.5]
		at org.apache.http.impl.nio.client.InternalIODispatch.onInputReady(InternalIODispatch.java:81) ~[httpasyncclient-4.1.2.jar:4.1.2]
		at org.apache.http.impl.nio.client.InternalIODispatch.onInputReady(InternalIODispatch.java:39) ~[httpasyncclient-4.1.2.jar:4.1.2]
		at org.apache.http.impl.nio.reactor.AbstractIODispatch.inputReady(AbstractIODispatch.java:114) ~[httpcore-nio-4.4.5.jar:4.4.5]
		at org.apache.http.impl.nio.reactor.BaseIOReactor.readable(BaseIOReactor.java:162) ~[httpcore-nio-4.4.5.jar:4.4.5]
		at org.apache.http.impl.nio.reactor.AbstractIOReactor.processEvent(AbstractIOReactor.java:337) ~[httpcore-nio-4.4.5.jar:4.4.5]
		at org.apache.http.impl.nio.reactor.AbstractIOReactor.processEvents(AbstractIOReactor.java:315) ~[httpcore-nio-4.4.5.jar:4.4.5]
		at org.apache.http.impl.nio.reactor.AbstractIOReactor.execute(AbstractIOReactor.java:276) ~[httpcore-nio-4.4.5.jar:4.4.5]
		at org.apache.http.impl.nio.reactor.BaseIOReactor.execute(BaseIOReactor.java:104) ~[httpcore-nio-4.4.5.jar:4.4.5]
		at org.apache.http.impl.nio.reactor.AbstractMultiworkerIOReactor$Worker.run(AbstractMultiworkerIOReactor.java:588) ~[httpcore-nio-4.4.5.jar:4.4.5]`

**Comment by peng-yongsheng** [comment]
@ychandu The default queue size of elasticsearch is 200, set the queue size larger. 

Add this configuration item to the end of elasticsearch.yml.
```
thread_pool.bulk.queue_size: xxxxxx
```
