### ISSUE TITLE
org.apache.skywalking.apm.collector.analysis.segment.parser.provider.parser.SegmentParse:java.lang.NullPointerException: null

### ISSUE THREAD

**Issue by woshijay7788** [apache/incubator-skywalking#2131]
2019-01-08 11:50:19,398 - org.apache.skywalking.apm.collector.analysis.worker.model.base.LocalAsyncWorkerRef -671334 [DataCarrier.Consumser.0.Thread] ERROR [] - null
java.lang.NullPointerException: null
	at org.apache.skywalking.apm.collector.analysis.alarm.provider.worker.service.ServiceReferenceMetricAlarmAssertWorker.generateAlarmContent(ServiceReferenceMetricAlarmAssertWorker.java:75) ~[alarm-provider-5.0.0-GA.jar:5.0.0-GA]
	at org.apache.skywalking.apm.collector.analysis.alarm.provider.worker.service.ServiceReferenceMetricAlarmAssertWorker.generateAlarmContent(ServiceReferenceMetricAlarmAssertWorker.java:39) ~[alarm-provider-5.0.0-GA.jar:5.0.0-GA]
	at org.apache.skywalking.apm.collector.analysis.alarm.provider.worker.AlarmAssertWorker.errorRateAlarmAssert(AlarmAssertWorker.java:69) ~[alarm-provider-5.0.0-GA.jar:5.0.0-GA]
	at org.apache.skywalking.apm.collector.analysis.alarm.provider.worker.AlarmAssertWorker.onWork(AlarmAssertWorker.java:46) ~[alarm-provider-5.0.0-GA.jar:5.0.0-GA]
	at org.apache.skywalking.apm.collector.analysis.alarm.provider.worker.AlarmAssertWorker.onWork(AlarmAssertWorker.java:37) ~[alarm-provider-5.0.0-GA.jar:5.0.0-GA]
	at org.apache.skywalking.apm.collector.analysis.worker.model.base.AbstractWorker.process(AbstractWorker.java:57) ~[analysis-worker-model-5.0.0-GA.jar:5.0.0-GA]
	at org.apache.skywalking.apm.collector.core.graph.Node.execute(Node.java:52) ~[apm-collector-core-5.0.0-GA.jar:5.0.0-GA]
	at org.apache.skywalking.apm.collector.core.graph.WayToNode.out(WayToNode.java:40) ~[apm-collector-core-5.0.0-GA.jar:5.0.0-GA]
	at org.apache.skywalking.apm.collector.analysis.worker.model.base.LocalAsyncWorkerRef.out(LocalAsyncWorkerRef.java:78) ~[analysis-worker-model-5.0.0-GA.jar:5.0.0-GA]
	at org.apache.skywalking.apm.collector.analysis.worker.model.base.LocalAsyncWorkerRef.consume(LocalAsyncWorkerRef.java:58) [analysis-worker-model-5.0.0-GA.jar:5.0.0-GA]
	at org.apache.skywalking.apm.commons.datacarrier.consumer.ConsumerThread.consume(ConsumerThread.java:101) [apm-datacarrier-5.0.0-GA.jar:5.0.0-GA]
	at org.apache.skywalking.apm.commons.datacarrier.consumer.ConsumerThread.run(ConsumerThread.java:68) [apm-datacarrier-5.0.0-GA.jar:5.0.0-GA]
2019-01-08 11:50:19,400 - org.apache.skywalking.apm.collector.analysis.segment.parser.provider.parser.SegmentParse -671336 [grpc-default-executor-39] ERROR [] - null
java.lang.NullPointerException: null
2019-01-08 11:50:19,401 - org.apache.skywalking.apm.collector.analysis.segment.parser.provider.parser.SegmentParse -671337 [grpc-default-executor-43] ERROR [] - null
java.lang.NullPointerException: null
2019-01-08 11:50:19,407 - org.apache.skywalking.apm.collector.analysis.segment.parser.provider.parser.SegmentParse -671343 [grpc-default-executor-48] ERROR [] - null
java.lang.NullPointerException: null
2019-01-08 11:50:19,411 - org.apache.skywalking.apm.collector.analysis.segment.parser.provider.parser.SegmentParse -671347 [grpc-default-executor-2] ERROR [] - null

I use version 5.0.0-RC and deleted service_name index from es, could you tell me what happened?

**Comment by wu-sheng** [comment]
Look like you delete the inventory data in storage, but don't reboot agent.

**Comment by woshijay7788** [comment]
I have more than 40 application， reboot agent is unreality
