### ISSUE TITLE
After I started the Skywalking, the skywalking-oap-server.log file always reported NullPointerException, 

### ISSUE THREAD

**Issue by liyongfa0311** [apache/incubator-skywalking#2144]
Please answer these questions before submitting your issue.
Bug
- Why do you submit this issue?
- [ ] Question or discussion
- [ ] Bug
- [ ] Requirement
- [ ] Feature or performance improvement

___
### Question
- What do you want to know?
Solve my problem
___
### Bug
- Which version of SkyWalking, OS and JRE?
Skywalking version: 6.0.0-beta   OS:centos 6.5  JRE: JDK1.8.0_131
- Which company or project?

- What happen?
If possible, provide a way for reproducing the error. e.g. demo application, component version.
After I started the Skywalking, the skywalking-oap-server.log file always reported NullPointerException, and the file quickly reached 100M.

2019-01-10 21:26:45,011 - org.apache.skywalking.oap.server.receiver.trace.provider.parser.SegmentParse - 98 [grpc-default-executor-1] ERROR [] - null
java.lang.NullPointerException: null
	at org.apache.skywalking.oap.server.receiver.trace.provider.parser.listener.endpoint.MultiScopesSpanListener.parseExit(MultiScopesSpanListener.java:138) ~[skywalking-trace-receiver-plugin-6.0.0-beta.jar:6.0.0-beta]
	at org.apache.skywalking.oap.server.receiver.trace.provider.parser.SegmentParse.lambda$notifyExitListener$0(SegmentParse.java:193) ~[skywalking-trace-receiver-plugin-6.0.0-beta.jar:6.0.0-beta]
	at java.lang.Iterable.forEach(Iterable.java:75) ~[?:1.8.0_131]
	at org.apache.skywalking.oap.server.receiver.trace.provider.parser.SegmentParse.notifyExitListener(SegmentParse.java:191) ~[skywalking-trace-receiver-plugin-6.0.0-beta.jar:6.0.0-beta]
	at org.apache.skywalking.oap.server.receiver.trace.provider.parser.SegmentParse.preBuild(SegmentParse.java:162) ~[skywalking-trace-receiver-plugin-6.0.0-beta.jar:6.0.0-beta]
	at org.apache.skywalking.oap.server.receiver.trace.provider.parser.SegmentParse.parse(SegmentParse.java:81) [skywalking-trace-receiver-plugin-6.0.0-beta.jar:6.0.0-beta]
	at org.apache.skywalking.oap.server.receiver.trace.provider.parser.SegmentParse$Producer.send(SegmentParse.java:252) [skywalking-trace-receiver-plugin-6.0.0-beta.jar:6.0.0-beta]
	at org.apache.skywalking.oap.server.receiver.trace.provider.handler.v5.grpc.TraceSegmentServiceHandler$1.onNext(TraceSegmentServiceHandler.java:49) [skywalking-trace-receiver-plugin-6.0.0-beta.jar:6.0.0-beta]
	at org.apache.skywalking.oap.server.receiver.trace.provider.handler.v5.grpc.TraceSegmentServiceHandler$1.onNext(TraceSegmentServiceHandler.java:43) [skywalking-trace-receiver-plugin-6.0.0-beta.jar:6.0.0-beta]
	at io.grpc.stub.ServerCalls$StreamingServerCallHandler$StreamingServerCallListener.onMessage(ServerCalls.java:248) [grpc-stub-1.15.1.jar:1.15.1]
	at io.grpc.internal.ServerCallImpl$ServerStreamListenerImpl.messagesAvailable(ServerCallImpl.java:263) [grpc-core-1.15.1.jar:1.15.1]
	at io.grpc.internal.ServerImpl$JumpToApplicationThreadServerStreamListener$1MessagesAvailable.runInContext(ServerImpl.java:683) [grpc-core-1.15.1.jar:1.15.1]
	at io.grpc.internal.ContextRunnable.run(ContextRunnable.java:37) [grpc-core-1.15.1.jar:1.15.1]
	at io.grpc.internal.SerializingExecutor.run(SerializingExecutor.java:123) [grpc-core-1.15.1.jar:1.15.1]
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142) [?:1.8.0_131]
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617) [?:1.8.0_131]
	at java.lang.Thread.run(Thread.java:748) [?:1.8.0_131]
2019-01-10 21:26:45,450 - org.apache.skywalking.oap.server.receiver.trace.provider.parser.SegmentParse - 98 [grpc-default-executor-1] ERROR [] - null
java.lang.NullPointerException: null
	at org.apache.skywalking.oap.server.receiver.trace.provider.parser.listener.endpoint.MultiScopesSpanListener.parseExit(MultiScopesSpanListener.java:138) ~[skywalking-trace-receiver-plugin-6.0.0-beta.jar:6.0.0-beta]
	at org.apache.skywalking.oap.server.receiver.trace.provider.parser.SegmentParse.lambda$notifyExitListener$0(SegmentParse.java:193) ~[skywalking-trace-receiver-plugin-6.0.0-beta.jar:6.0.0-beta]
	at java.lang.Iterable.forEach(Iterable.java:75) ~[?:1.8.0_131]
	at org.apache.skywalking.oap.server.receiver.trace.provider.parser.SegmentParse.notifyExitListener(SegmentParse.java:191) ~[skywalking-trace-receiver-plugin-6.0.0-beta.jar:6.0.0-beta]
	at org.apache.skywalking.oap.server.receiver.trace.provider.parser.SegmentParse.preBuild(SegmentParse.java:162) ~[skywalking-trace-receiver-plugin-6.0.0-beta.jar:6.0.0-beta]
	at org.apache.skywalking.oap.server.receiver.trace.provider.parser.SegmentParse.parse(SegmentParse.java:81) [skywalking-trace-receiver-plugin-6.0.0-beta.jar:6.0.0-beta]
	at org.apache.skywalking.oap.server.receiver.trace.provider.parser.SegmentParse$Producer.send(SegmentParse.java:252) [skywalking-trace-receiver-plugin-6.0.0-beta.jar:6.0.0-beta]
	at org.apache.skywalking.oap.server.receiver.trace.provider.handler.v5.grpc.TraceSegmentServiceHandler$1.onNext(TraceSegmentServiceHandler.java:49) [skywalking-trace-receiver-plugin-6.0.0-beta.jar:6.0.0-beta]
	at org.apache.skywalking.oap.server.receiver.trace.provider.handler.v5.grpc.TraceSegmentServiceHandler$1.onNext(TraceSegmentServiceHandler.java:43) [skywalking-trace-receiver-plugin-6.0.0-beta.jar:6.0.0-beta]
	at io.grpc.stub.ServerCalls$StreamingServerCallHandler$StreamingServerCallListener.onMessage(ServerCalls.java:248) [grpc-stub-1.15.1.jar:1.15.1]
	at io.grpc.internal.ServerCallImpl$ServerStreamListenerImpl.messagesAvailable(ServerCallImpl.java:263) [grpc-core-1.15.1.jar:1.15.1]
	at io.grpc.internal.ServerImpl$JumpToApplicationThreadServerStreamListener$1MessagesAvailable.runInContext(ServerImpl.java:683) [grpc-core-1.15.1.jar:1.15.1]
	at io.grpc.internal.ContextRunnable.run(ContextRunnable.java:37) [grpc-core-1.15.1.jar:1.15.1]
	at io.grpc.internal.SerializingExecutor.run(SerializingExecutor.java:123) [grpc-core-1.15.1.jar:1.15.1]
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142) [?:1.8.0_131]
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617) [?:1.8.0_131]
	at java.lang.Thread.run(Thread.java:748) [?:1.8.0_131]
__
### Requirement or improvement
- Please describe about your requirements or improvement suggestions.
Thank you for you help me solving this error.

**Comment by wu-sheng** [comment]
That means, you remove the storage(ElaticSearch maybe), and haven't rebooted the agents.
