### ISSUE TITLE
ServiceAndEndpointRegisterClient execute fail. 

### ISSUE THREAD

**Issue by sanxun0325** [apache/incubator-skywalking#2163]
The following problems were encountered when starting the agent：

INFO 2019-01-15 19:46:16:175 AgentClassLoader :  C:\apache-skywalking-apm-incubating\agent_bbz_build\plugins\tomcat-7.x-8.x-plugin-6.0.0-GA-SNAPSHOT.jar loaded. 
INFO 2019-01-15 19:46:16:176 AgentClassLoader :  C:\apache-skywalking-apm-incubating\agent_bbz_build\activations\apm-toolkit-log4j-1.x-activation-6.0.0-GA-SNAPSHOT.jar loaded. 
INFO 2019-01-15 19:46:16:176 AgentClassLoader :  C:\apache-skywalking-apm-incubating\agent_bbz_build\activations\apm-toolkit-log4j-2.x-activation-6.0.0-GA-SNAPSHOT.jar loaded. 
INFO 2019-01-15 19:46:16:176 AgentClassLoader :  C:\apache-skywalking-apm-incubating\agent_bbz_build\activations\apm-toolkit-logback-1.x-activation-6.0.0-GA-SNAPSHOT.jar loaded. 
INFO 2019-01-15 19:46:16:176 AgentClassLoader :  C:\apache-skywalking-apm-incubating\agent_bbz_build\activations\apm-toolkit-opentracing-activation-6.0.0-GA-SNAPSHOT.jar loaded. 
INFO 2019-01-15 19:46:16:177 AgentClassLoader :  C:\apache-skywalking-apm-incubating\agent_bbz_build\activations\apm-toolkit-trace-activation-6.0.0-GA-SNAPSHOT.jar loaded. 
DEBUG 2019-01-15 19:46:16:185 AbstractClassEnhancePluginDefine :  enhance class org.apache.catalina.core.StandardHostValve by org.apache.skywalking.apm.plugin.tomcat78x.define.TomcatInstrumentation completely. 
DEBUG 2019-01-15 19:46:16:185 SkyWalkingAgent :  Finish the prepare stage for org.apache.catalina.core.StandardHostValve. 
DEBUG 2019-01-15 19:46:16:397 SkyWalkingAgent :  On Transformation class org.apache.catalina.core.StandardHostValve. 
DEBUG 2019-01-15 19:46:18:074 ServiceAndEndpointRegisterClient :  ServiceAndEndpointRegisterClient running, status:CONNECTED. 
### **_ERROR 2019-01-15 19:46:18:784 ServiceAndEndpointRegisterClient :  ServiceAndEndpointRegisterClient execute fail. 
org.apache.skywalking.apm.dependencies.io.grpc.StatusRuntimeException: UNIMPLEMENTED: Method not found: Register/doServiceRegister_**
	at org.apache.skywalking.apm.dependencies.io.grpc.stub.ClientCalls.toStatusRuntimeException(ClientCalls.java:222)
	at org.apache.skywalking.apm.dependencies.io.grpc.stub.ClientCalls.getUnchecked(ClientCalls.java:203)
	at org.apache.skywalking.apm.dependencies.io.grpc.stub.ClientCalls.blockingUnaryCall(ClientCalls.java:132)
	at org.apache.skywalking.apm.network.register.v2.RegisterGrpc$RegisterBlockingStub.doServiceRegister(RegisterGrpc.java:386)
	at org.apache.skywalking.apm.agent.core.remote.ServiceAndEndpointRegisterClient.run(ServiceAndEndpointRegisterClient.java:111)
	at org.apache.skywalking.apm.util.RunnableWithExceptionProtection.run(RunnableWithExceptionProtection.java:36)
	at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511)
	at java.util.concurrent.FutureTask.runAndReset(FutureTask.java:308)
	at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.access$301(ScheduledThreadPoolExecutor.java:180)
	at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.run(ScheduledThreadPoolExecutor.java:294)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617)
	at java.lang.Thread.run(Thread.java:748)

DEBUG 2019-01-15 19:46:21:072 ServiceAndEndpointRegisterClient :  ServiceAndEndpointRegisterClient running, status:CONNECTED. 
ERROR 2019-01-15 19:46:21:078 ServiceAndEndpointRegisterClient :  ServiceAndEndpointRegisterClient execute fail. 
org.apache.skywalking.apm.dependencies.io.grpc.StatusRuntimeException: UNIMPLEMENTED: Method not found: Register/doServiceRegister
	at org.apache.skywalking.apm.dependencies.io.grpc.stub.ClientCalls.toStatusRuntimeException(ClientCalls.java:222)
	at org.apache.skywalking.apm.dependencies.io.grpc.stub.ClientCalls.getUnchecked(ClientCalls.java:203)
	at org.apache.skywalking.apm.dependencies.io.grpc.stub.ClientCalls.blockingUnaryCall(ClientCalls.java:132)
	at org.apache.skywalking.apm.network.register.v2.RegisterGrpc$RegisterBlockingStub.doServiceRegister(RegisterGrpc.java:386)
	at org.apache.skywalking.apm.agent.core.remote.ServiceAndEndpointRegisterClient.run(ServiceAndEndpointRegisterClient.java:111)
	at org.apache.skywalking.apm.util.RunnableWithExceptionProtection.run(RunnableWithExceptionProtection.java:36)
	at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511)
	at java.util.concurrent.FutureTask.runAndReset(FutureTask.java:308)
	at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.access$301(ScheduledThreadPoolExecutor.java:180)
	at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.run(ScheduledThreadPoolExecutor.java:294)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617)
	at java.lang.Thread.run(Thread.java:748)###

**Comment by wu-sheng** [comment]
Do you set to grpc port? And are you using the backend with same version? It is a very easy error, the codes don't match.

**Comment by alvinwangs** [comment]
Hi @wu-sheng , I also get this issue, 
Skywalking version: 7.0.0
Skywalking oap docker image: apache/skywalking-oap-server:7.0.0-es6
log as below:
`DEBUG 2020-05-11 07:24:40:526 SkywalkingAgent-8-ServiceAndEndpointRegisterClient-0 ServiceAndEndpointRegisterClient : ServiceAndEndpointRegisterClient running, status:CONNECTED. 
ERROR 2020-05-11 07:24:40:530 SkywalkingAgent-8-ServiceAndEndpointRegisterClient-0 ServiceAndEndpointRegisterClient : ServiceAndEndpointRegisterClient execute fail. 
org.apache.skywalking.apm.dependencies.io.grpc.StatusRuntimeException: UNIMPLEMENTED: Method not found: Register/doServiceRegister
	at org.apache.skywalking.apm.dependencies.io.grpc.stub.ClientCalls.toStatusRuntimeException(ClientCalls.java:240)
	at org.apache.skywalking.apm.dependencies.io.grpc.stub.ClientCalls.getUnchecked(ClientCalls.java:221)
	at org.apache.skywalking.apm.dependencies.io.grpc.stub.ClientCalls.blockingUnaryCall(ClientCalls.java:140)
	at org.apache.skywalking.apm.network.register.v2.RegisterGrpc$RegisterBlockingStub.doServiceRegister(RegisterGrpc.java:386)
	at org.apache.skywalking.apm.agent.core.remote.ServiceAndEndpointRegisterClient.run(ServiceAndEndpointRegisterClient.java:147)
	at org.apache.skywalking.apm.util.RunnableWithExceptionProtection.run(RunnableWithExceptionProtection.java:33)
	at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511)
	at java.util.concurrent.FutureTask.runAndReset(FutureTask.java:308)
	at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.access$301(ScheduledThreadPoolExecutor.java:180)
	at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.run(ScheduledThreadPoolExecutor.java:294)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
	at java.lang.Thread.run(Thread.java:748)`

Log at Skywalking Oap:
`2020-05-11 07:34:56,339 - io.grpc.netty.NettyServerHandler -243415 [grpc-nio-worker-ELG-3-2] DEBUG [] - [id: 0xd2b6a500, L:/10.2.4.37:11800 - R:/10.2.6.87:60828] INBOUND HEADERS: streamId=133 headers=GrpcHttp2RequestHeaders[:path: /Register/doServiceRegister, :authority: skywalking-oap-service:11800, :method: POST, :scheme: http, te: trailers, content-type: application/grpc, user-agent: grpc-java-netty/1.26.0, agent-version: 7.0.0, grpc-accept-encoding: gzip, grpc-timeout: 29999864u] streamDependency=0 weight=16 exclusive=false padding=0 endStream=false

2020-05-11 07:34:56,340 - io.grpc.netty.NettyServerHandler -243416 [grpc-nio-worker-ELG-3-2] DEBUG [] - [id: 0xd2b6a500, L:/10.2.4.37:11800 - R:/10.2.6.87:60828] OUTBOUND HEADERS: streamId=133 headers=GrpcHttp2OutboundHeaders[:status: 200, content-type: application/grpc, grpc-status: 12, grpc-message: Method not found: Register/doServiceRegister] streamDependency=0 weight=16 exclusive=false padding=0 endStream=true

2020-05-11 07:34:56,342 - io.grpc.netty.NettyServerHandler -243418 [grpc-nio-worker-ELG-3-2] DEBUG [] - [id: 0xd2b6a500, L:/10.2.4.37:11800 - R:/10.2.6.87:60828] INBOUND RST_STREAM: streamId=133 errorCode=8
`

You can see the version at OAP log,it shows that the skywalking version is 7.0.0

**Comment by wu-sheng** [comment]
Don't know what you are doing. This service exists in 7.0, but not in master and 8.0. So, make sure you are using the right codebase.

**Comment by alvinwangs** [comment]
> Don't know what you are doing. This service exists in 7.0, but not in master and 8.0. So, make sure you are using the right codebase.

How to confirm is version 8.0? 
I donwload the binary from http://skywalking.apache.org/downloads/  ,on the donwload page no 8.0 for download.

And i verify the signature ,the result as below:
`AlvindeMacBook-Pro-5:Downloads alvinwang$ gpg --verify apache-skywalking-apm-7.0.0.tar.gz.asc apache-skywalking-apm-7.0.0.tar.gz
Warning: Failed to set locale category LC_NUMERIC to en_CN.
Warning: Failed to set locale category LC_TIME to en_CN.
Warning: Failed to set locale category LC_COLLATE to en_CN.
Warning: Failed to set locale category LC_MONETARY to en_CN.
Warning: Failed to set locale category LC_MESSAGES to en_CN.
gpg: Signature made Thu Mar 19 00:02:21 2020 CST
gpg:                using RSA key E8608938DB25E06B
gpg: key E8608938DB25E06B: public key "Sheng Wu <wusheng@apache.org>" imported
gpg: Total number processed: 1
gpg:               imported: 1
gpg: Good signature from "Sheng Wu <wusheng@apache.org>" [unknown]
gpg: WARNING: This key is not certified with a trusted signature!
gpg:          There is no indication that the signature belongs to the owner.
Primary key fingerprint: D360 AB2A B20B 2840 3270  E2CB E860 8938 DB25 E06B`

![image](https://user-images.githubusercontent.com/43318274/81544233-d1647800-93a9-11ea-8f8f-a9fe20cdb9d1.png)

**Comment by wu-sheng** [comment]
There is no download for 8.0.0, so, the version is right. Do you set up any proxy between agent and backend?

**Comment by alvinwangs** [comment]
no proxy.

**Comment by wu-sheng** [comment]
Don't know what happens, it should relate to your local env only. Every commit of SkyWalking has been checked in e2e about metrics and trace generated. Releases have more checks. And we have many users in the 7.0.0 already. 

Don't know any setting could make this happens.

**Comment by alvinwangs** [comment]
Ok, we will check our env. 
Any way, Tks.
