### ISSUE TITLE
The locking mechanism for inventory registration is not valid when the brain is split.

### ISSUE THREAD

**Issue by peng-yongsheng** [apache/incubator-skywalking#2183]
Please answer these questions before submitting your issue.

- Why do you submit this issue?
- [ ] Question or discussion
- [X] Bug
- [ ] Requirement
- [ ] Feature or performance improvement

___
### Bug
- Which version of SkyWalking, OS and JRE?
All the versions of 6.0.0

- What happen?
If possible, provide a way for reproducing the error. e.g. demo application, component version.

A small amount of endpoint inventories had the same sequence value after OAP server received excess  segments.

**Comment by JaredTan95** [comment]
Is the following error the same as this bug? When i tested in mysql storage:

```
the cache of service inventory, service id: 9, mapping service id: 2
2019-01-19 14:52:22,473 - org.apache.skywalking.oap.server.storage.plugin.jdbc.h2.dao.H2BatchDAO - 58 [pool-16-thread-1] ERROR [] - Duplicate entry '20190119145221_1_5_0' for key 'PRIMARY'
java.sql.SQLIntegrityConstraintViolationException: Duplicate entry '20190119145221_1_5_0' for key 'PRIMARY'
        at com.mysql.cj.jdbc.exceptions.SQLError.createSQLException(SQLError.java:117) ~[mysql-connector-java-8.0.13.jar:8.0.13]
        at com.mysql.cj.jdbc.exceptions.SQLError.createSQLException(SQLError.java:97) ~[mysql-connector-java-8.0.13.jar:8.0.13]
        at com.mysql.cj.jdbc.exceptions.SQLExceptionsMapping.translateException(SQLExceptionsMapping.java:122) ~[mysql-connector-java-8.0.13.jar:8.0.13]
        at com.mysql.cj.jdbc.ClientPreparedStatement.executeInternal(ClientPreparedStatement.java:974) ~[mysql-connector-java-8.0.13.jar:8.0.13]
        at com.mysql.cj.jdbc.ClientPreparedStatement.execute(ClientPreparedStatement.java:391) ~[mysql-connector-java-8.0.13.jar:8.0.13]
        at com.zaxxer.hikari.pool.ProxyPreparedStatement.execute(ProxyPreparedStatement.java:44) ~[HikariCP-3.1.0.jar:?]
        at com.zaxxer.hikari.pool.HikariProxyPreparedStatement.execute(HikariProxyPreparedStatement.java) ~[HikariCP-3.1.0.jar:?]
        at org.apache.skywalking.oap.server.storage.plugin.jdbc.SQLExecutor.invoke(SQLExecutor.java:52) ~[storage-jdbc-hikaricp-plugin-6.1.0-SNAPSHOT.jar:6.1.0-SNAPSHOT]
        at org.apache.skywalking.oap.server.storage.plugin.jdbc.h2.dao.H2BatchDAO.batchPersistence(H2BatchDAO.java:55) ~[storage-jdbc-hikaricp-plugin-6.1.0-SNAPSHOT.jar:6.1.0-SNAPSHOT]
        at org.apache.skywalking.oap.server.core.storage.PersistenceTimer.extractDataAndSave(PersistenceTimer.java:112) ~[server-core-6.1.0-SNAPSHOT.jar:6.1.0-SNAPSHOT]
        at org.apache.skywalking.oap.server.core.storage.PersistenceTimer.lambda$start$0(PersistenceTimer.java:65) ~[server-core-6.1.0-SNAPSHOT.jar:6.1.0-SNAPSHOT]
        at org.apache.skywalking.apm.util.RunnableWithExceptionProtection.run(RunnableWithExceptionProtection.java:36) [apm-util-6.1.0-SNAPSHOT.jar:6.1.0-SNAPSHOT]
        at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511) [?:1.8.0_191]
        at java.util.concurrent.FutureTask.runAndReset(FutureTask.java:308) [?:1.8.0_191]
        at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.access$301(ScheduledThreadPoolExecutor.java:180) [?:1.8.0_191]
        at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.run(ScheduledThreadPoolExecutor.java:294) [?:1.8.0_191]
        at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149) [?:1.8.0_191]
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624) [?:1.8.0_191]
        at java.lang.Thread.run(Thread.java:748) [?:1.8.0_191]
2019-01-19 14:52:24,786 - org.apache.skywalking.oap.server.core.cache.CacheUpdateTimer - 61 [pool-18-thread-1] INFO  [] - Update mapping service id in the cache of service inventory, service id: 10, mapping service id: 3
```

**Comment by wu-sheng** [comment]
No. This isn't. That bug only happens in ElasticSearch lock mechanism. I am still trying to figure this MySQL bug out. Right now, look like the data committed by one transaction, can't be read immediately by another connection.

**Comment by wu-sheng** [comment]
We need another pr to improve. Right now, the IDs are used too quickly, because update op(heartbeat mostly) requires ID, but don't use.
