### ISSUE TITLE
listener timeout after waiting for [30000] ms java.io.IOException: listener timeout after waiting for [30000] ms

### ISSUE THREAD

**Issue by jular6759** [apache/incubator-skywalking#2191]
Please answer these questions before submitting your issue.

- Why do you submit this issue?
- [x] Question or discussion
- [ ] Bug
- [ ] Requirement
- [ ] Feature or performance improvement

___
### Question
- What do you want to know?
  When I start up collector server, I get "listener timeout after waiting for [30000] ms
java.io.IOException: listener timeout after waiting for [30000] ms" error every five minute.Can I config some thing to avoid it? Thanks. The detail error messge as follow:

2019-01-21 18:40:43,387 - org.apache.skywalking.oap.server.core.storage.ttl.DataTTLKeeperTimer - 122 [pool-11-thread-1] WARN  [] - History of segment delete failure, time bucket 20190121171009
2019-01-21 18:40:43,387 - org.apache.skywalking.oap.server.core.storage.ttl.DataTTLKeeperTimer - 123 [pool-11-thread-1] ERROR [] - listener timeout after waiting for [30000] ms
java.io.IOException: listener timeout after waiting for [30000] ms
        at org.elasticsearch.client.RestClient$SyncResponseListener.get(RestClient.java:684) ~[elasticsearch-rest-client-6.3.2.jar:6.3.2]
        at org.elasticsearch.client.RestClient.performRequest(RestClient.java:235) ~[elasticsearch-rest-client-6.3.2.jar:6.3.2]
        at org.elasticsearch.client.RestClient.performRequest(RestClient.java:198) ~[elasticsearch-rest-client-6.3.2.jar:6.3.2]
        at org.apache.skywalking.oap.server.library.client.elasticsearch.ElasticSearchClient.delete(ElasticSearchClient.java:179) ~[library-client-6.0.0-beta.jar:6.0.0-beta]
        at org.apache.skywalking.oap.server.storage.plugin.elasticsearch.base.HistoryDeleteEsDAO.deleteHistory(HistoryDeleteEsDAO.java:40) ~[storage-elasticsearch-plugin-6.0.0-beta.jar:6.0.0-beta]
        at org.apache.skywalking.oap.server.core.storage.ttl.DataTTLKeeperTimer.execute(DataTTLKeeperTimer.java:119) ~[server-core-6.0.0-beta.jar:6.0.0-beta]
        at org.apache.skywalking.oap.server.core.storage.ttl.DataTTLKeeperTimer.lambda$delete$1(DataTTLKeeperTimer.java:99) ~[server-core-6.0.0-beta.jar:6.0.0-beta]
        at java.lang.Iterable.forEach(Iterable.java:75) ~[?:1.8.0_92]
        at org.apache.skywalking.oap.server.core.storage.ttl.DataTTLKeeperTimer.delete(DataTTLKeeperTimer.java:85) ~[server-core-6.0.0-beta.jar:6.0.0-beta]
        at org.apache.skywalking.apm.util.RunnableWithExceptionProtection.run(RunnableWithExceptionProtection.java:36) [apm-util-6.0.0-beta.jar:6.0.0-beta]
        at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511) [?:1.8.0_92]
        at java.util.concurrent.FutureTask.runAndReset(FutureTask.java:308) [?:1.8.0_92]
        at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.access$301(ScheduledThreadPoolExecutor.java:180) [?:1.8.0_92]
        at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.run(ScheduledThreadPoolExecutor.java:294) [?:1.8.0_92]
        at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142) [?:1.8.0_92]
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617) [?:1.8.0_92]
        at java.lang.Thread.run(Thread.java:745) [?:1.8.0_92]
___
### Bug
- Which version of SkyWalking, OS and JRE?
  SkyWalking v6.0.0-beta, SUSE Linux Enterprise Server 11 (x86_64), java version "1.8.0_92"
- Which company or project?

- What happen?
If possible, provide a way for reproducing the error. e.g. demo application, component version.

___
### Requirement or improvement
- Please describe about your requirements or improvement suggestions.

**Comment by wu-sheng** [comment]
That based on elasticsearch performance. Deleting is high payload.

**Comment by lestchun** [comment]
when I user cammond 
curl  http://192.168.7.62:9200
return 
{
  "name" : "testcdh",
  "cluster_name" : "elasticsearch",
  "cluster_uuid" : "_na_",
  "version" : {
    "number" : "7.1.1",
    "build_flavor" : "default",
    "build_type" : "rpm",
    "build_hash" : "7a013de",
    "build_date" : "2019-05-23T14:04:00.380842Z",
    "build_snapshot" : false,
    "lucene_version" : "8.0.0",
    "minimum_wire_compatibility_version" : "6.8.0",
    "minimum_index_compatibility_version" : "6.0.0-beta1"
  },
  "tagline" : "You Know, for Search"
}
but when I invoke  startup.sh  fail
here are the log 
2019-06-03 20:04:08,712 - org.apache.skywalking.oap.server.library.module.BootstrapFlow - 54 [main] INFO  [] - start the provider default in alarm module.
2019-06-03 20:04:08,712 - org.apache.skywalking.oap.server.library.module.BootstrapFlow - 54 [main] INFO  [] - start the provider elasticsearch in storage module.
2019-06-03 20:04:08,712 - org.apache.skywalking.oap.server.library.client.elasticsearch.ElasticSearchClient - 90 [main] INFO  [] - elasticsearch cluster nodes: 192.168.7.62:9200
2019-06-03 20:04:32,999 - org.apache.skywalking.oap.server.starter.OAPServerStartUp - 55 [main] ERROR [] - listener timeout after waiting for [30000] ms
org.apache.skywalking.oap.server.library.module.ModuleStartException: listener timeout after waiting for [30000] ms
	at org.apache.skywalking.oap.server.storage.plugin.elasticsearch.StorageModuleElasticsearchProvider.start(StorageModuleElasticsearchProvider.java:137) ~[storage-elasticsearch-plugin-6.1.0.jar:6.1.0]
	at org.apache.skywalking.oap.server.library.module.BootstrapFlow.start(BootstrapFlow.java:57) ~[library-module-6.1.0.jar:6.1.0]
	at org.apache.skywalking.oap.server.library.module.ModuleManager.init(ModuleManager.java:65) ~[library-module-6.1.0.jar:6.1.0]
	at org.apache.skywalking.oap.server.starter.OAPServerStartUp.main(OAPServerStartUp.java:43) [server-starter-6.1.0.jar:6.1.0]
Caused by: org.apache.skywalking.oap.server.core.storage.StorageException: listener timeout after waiting for [30000] ms
	at org.apache.skywalking.oap.server.storage.plugin.elasticsearch.base.StorageEsInstaller.isExists(StorageEsInstaller.java:53) ~[storage-elasticsearch-plugin-6.1.0.jar:6.1.0]
	at org.apache.skywalking.oap.server.core.storage.model.ModelInstaller.install(ModelInstaller.java:77) ~[server-core-6.1.0.jar:6.1.0]
	at org.apache.skywalking.oap.server.storage.plugin.elasticsearch.StorageModuleElasticsearchProvider.start(StorageModuleElasticsearchProvider.java:132) ~[storage-elasticsearch-plugin-6.1.0.jar:6.1.0]
	... 3 more
2019-06-03 20:04:39,459 - org.apache.skywalking.oap.server.starter.OAPServerStartUp - 55 [main] ERROR [] - listener timeout after waiting for [30000] ms
org.apache.skywalking.oap.server.library.module.ModuleStartException: listener timeout after waiting for [30000] ms
	at org.apache.skywalking.oap.server.storage.plugin.elasticsearch.StorageModuleElasticsearchProvider.start(StorageModuleElasticsearchProvider.java:137) ~[storage-elasticsearch-plugin-6.1.0.jar:6.1.0]
	at org.apache.skywalking.oap.server.library.module.BootstrapFlow.start(BootstrapFlow.java:57) ~[library-module-6.1.0.jar:6.1.0]
	at org.apache.skywalking.oap.server.library.module.ModuleManager.init(ModuleManager.java:65) ~[library-module-6.1.0.jar:6.1.0]
	at org.apache.skywalking.oap.server.starter.OAPServerStartUp.main(OAPServerStartUp.java:43) [server-starter-6.1.0.jar:6.1.0]
Caused by: org.apache.skywalking.oap.server.core.storage.StorageException: listener timeout after waiting for [30000] ms
	at org.apache.skywalking.oap.server.storage.plugin.elasticsearch.base.StorageEsInstaller.isExists(StorageEsInstaller.java:53) ~[storage-elasticsearch-plugin-6.1.0.jar:6.1.0]
	at org.apache.skywalking.oap.server.core.storage.model.ModelInstaller.install(ModelInstaller.java:77) ~[server-core-6.1.0.jar:6.1.0]
	at org.apache.skywalking.oap.server.storage.plugin.elasticsearch.StorageModuleElasticsearchProvider.start(StorageModuleElasticsearchProvider.java:132) ~[storage-elasticsearch-plugin-6.1.0.jar:6.1.0]
	... 3 more
