### ISSUE TITLE
I have some problems,when i use docker to build skywalking

### ISSUE THREAD

**Issue by xukuitao** [apache/incubator-skywalking#2220]
Question
- i have build  elasticsearch  successed . 
 here is the  command 
`docker run -p 9200:9200 -p 9300:9300 -e cluster.name=elasticsearch -e xpack.security.enabled=false --name=elasticsearch --restart=always -d wutang/elasticsearch-shanghai-zone`

- curl  localhost:9200  was  successed.

- but when i build Skywalking-Docker ,there was something wrong
   the command is
`docker run -p 8080:8080 -p 10800:10800 -p 11800:11800 -p 12800:12800 -e ES_JAVA_OPTS="-Xms512m -Xmx512m" --name sky -e ES_CLUSTER_NAME=elasticsearch -e ES_ADDRESSES=172.17.0.2:9300 -d wutang/skywalking-docker:5.x`

there war an error `Address already in use `

- **the skywalking-collector-server.log  ：**

`2019-01-29 13:32:56,994 - org.apache.skywalking.apm.collector.server.jetty.JettyServer -21265 [main] INFO  [] - start server, host: 0.0.0.0, port: 12800
2019-01-29 13:32:56,994 - org.apache.skywalking.apm.collector.server.jetty.JettyServer -21265 [main] INFO  [] - jetty servlet mappings: [/graphql] register by org.apache.skywalking.apm.collector.ui.jetty.handler.GraphQLHandler-6568f998
2019-01-29 13:32:56,998 - org.eclipse.jetty.server.Server -21269 [main] INFO  [] - jetty-9.4.2.v20170220
2019-01-29 13:32:57,122 - org.eclipse.jetty.server.handler.ContextHandler -21393 [main] INFO  [] - Started o.e.j.s.ServletContextHandler@44bbb7c6{/,null,AVAILABLE}
2019-01-29 13:32:57,153 - org.eclipse.jetty.server.AbstractConnector -21424 [main] INFO  [] - Started ServerConnector@177c345e{HTTP/1.1,[http/1.1]}{0.0.0.0:12800}
2019-01-29 13:32:57,160 - org.eclipse.jetty.server.Server -21431 [main] INFO  [] - Started @21465ms
2019-01-29 13:32:57,160 - org.apache.skywalking.apm.collector.server.jetty.JettyServer -21431 [main] INFO  [] - start server, host: localhost, port: 10800
2019-01-29 13:32:57,160 - org.apache.skywalking.apm.collector.server.jetty.JettyServer -21431 [main] INFO  [] - jetty servlet mappings: [/agent/jetty] register by org.apache.skywalking.apm.collector.agent.jetty.provider.handler.naming.AgentJettyNamingHandler-603cabc4
2019-01-29 13:32:57,160 - org.apache.skywalking.apm.collector.server.jetty.JettyServer -21431 [main] INFO  [] - jetty servlet mappings: [/ui/jetty] register by org.apache.skywalking.apm.collector.ui.jetty.handler.naming.UIJettyNamingHandler-422ab737
2019-01-29 13:32:57,161 - org.apache.skywalking.apm.collector.server.jetty.JettyServer -21432 [main] INFO  [] - jetty servlet mappings: [/agent/gRPC] register by org.apache.skywalking.apm.collector.agent.grpc.provider.handler.naming.AgentGRPCNamingHandler-2f4d01b6
2019-01-29 13:32:57,161 - org.eclipse.jetty.server.Server -21432 [main] INFO  [] - jetty-9.4.2.v20170220
2019-01-29 13:32:57,177 - org.eclipse.jetty.server.handler.ContextHandler -21448 [main] INFO  [] - Started o.e.j.s.ServletContextHandler@33a47707{/,null,AVAILABLE}
2019-01-29 13:32:57,182 - org.eclipse.jetty.server.AbstractConnector -21453 [main] INFO  [] - Started ServerConnector@4bc60503{HTTP/1.1,[http/1.1]}{localhost:10800}
2019-01-29 13:32:57,182 - org.eclipse.jetty.server.Server -21453 [main] INFO  [] - Started @21488ms
2019-01-29 13:32:57,182 - org.apache.skywalking.apm.collector.server.jetty.JettyServer -21453 [main] INFO  [] - start server, host: localhost, port: 12800
2019-01-29 13:32:57,182 - org.apache.skywalking.apm.collector.server.jetty.JettyServer -21453 [main] INFO  [] - jetty servlet mappings: [/segments] register by org.apache.skywalking.apm.collector.agent.jetty.provider.handler.TraceSegmentServletHandler-2e5e6fc4
2019-01-29 13:32:57,182 - org.apache.skywalking.apm.collector.server.jetty.JettyServer -21453 [main] INFO  [] - jetty servlet mappings: [/application/register] register by org.apache.skywalking.apm.collector.agent.jetty.provider.handler.ApplicationRegisterServletHandler-348137e8
2019-01-29 13:32:57,182 - org.apache.skywalking.apm.collector.server.jetty.JettyServer -21453 [main] INFO  [] - jetty servlet mappings: [/instance/register] register by org.apache.skywalking.apm.collector.agent.jetty.provider.handler.InstanceDiscoveryServletHandler-412c5e8b
2019-01-29 13:32:57,182 - org.apache.skywalking.apm.collector.server.jetty.JettyServer -21453 [main] INFO  [] - jetty servlet mappings: [/instance/heartbeat] register by org.apache.skywalking.apm.collector.agent.jetty.provider.handler.InstanceHeartBeatServletHandler-637791d
2019-01-29 13:32:57,183 - org.apache.skywalking.apm.collector.server.jetty.JettyServer -21454 [main] INFO  [] - jetty servlet mappings: [/servicename/discovery] register by org.apache.skywalking.apm.collector.agent.jetty.provider.handler.ServiceNameDiscoveryServiceHandler-3b0c3951
2019-01-29 13:32:57,183 - org.apache.skywalking.apm.collector.server.jetty.JettyServer -21454 [main] INFO  [] - jetty servlet mappings: [/networkAddress/register] register by org.apache.skywalking.apm.collector.agent.jetty.provider.handler.NetworkAddressRegisterServletHandler-60f77af
2019-01-29 13:32:57,183 - org.eclipse.jetty.server.Server -21454 [main] INFO  [] - jetty-9.4.2.v20170220
2019-01-29 13:32:57,194 - org.eclipse.jetty.server.handler.ContextHandler -21465 [main] INFO  [] - Started o.e.j.s.ServletContextHandler@d28c214{/,null,AVAILABLE}
2019-01-29 13:32:57,200 - org.apache.skywalking.apm.collector.jetty.manager.JettyManagerProvider _**_-21471 [main] ERROR [] - Address already in use
org.apache.skywalking.apm.collector.server.jetty.JettyServerException: Address already in use
	at org.apache.skywalking.apm.collector.server.jetty.JettyServer.start(JettyServer.java:96) ~[server-component-5.0.0-GA.jar:5.0.0-GA]
org.apache.skywalking.apm.collector.jetty.manager.JettyManagerProvider.lambda$notifyAfterCompleted$0(JettyManagerProvider.java:68) ~[collector-jetty-manager-provider-5.0.0-GA.jar:5.0.0-GA]
	at java.util.HashMap$Values.forEach(HashMap.java:980) [?:1.8.0_111]
org.apache.skywalking.apm.collector.jetty.manager.JettyManagerProvider.notifyAfterCompleted(JettyManagerProvider.java:66) [collector-jetty-manager-provider-5.0.0-GA.jar:5.0.0-GA]
org.apache.skywalking.apm.collector.core.module.BootstrapFlow.notifyAfterCompleted(BootstrapFlow.java:67)
	at org.apache.skywalking.apm.collector.core.module.ModuleManager.init(ModuleManager.java:69) 
org.apache.skywalking.apm.collector.boot.CollectorBootStartUp.main(CollectorBootStartUp.java:45) [apm-collector-boot-5.0.0-GA.jar:5.0.0-GA]
Caused by: java.net.BindException: Address already in use
	at sun.nio.ch.Net.bind0(Native Method) ~[?:1.8.0_111]
	at sun.nio.ch.Net.bind(Net.java:433) ~[?:1.8.0_111]
	at sun.nio.ch.Net.bind(Net.java:425) ~[?:1.8.0_111]
	at sun.nio.ch.ServerSocketChannelImpl.bind(ServerSocketChannelImpl.java:223) ~[?:1.8.0_111]
	at sun.nio.ch.ServerSocketAdaptor.bind(ServerSocketAdaptor.java:74) ~[?:1.8.0_111]
	at org.eclipse.jetty.server.ServerConnector.open(ServerConnector.java:298) ~[jetty-server-9.4.2.v20170220.jar:9.4.2.v20170220]
	at org.eclipse.jetty.server.AbstractNetworkConnector.doStart(AbstractNetworkConnector.java:80) ~
	at org.eclipse.jetty.server.ServerConnector.doStart(ServerConnector.java:236)
	at org.eclipse.jetty.util.component.AbstractLifeCycle.start(AbstractLifeCycle.java:68)
	at org.eclipse.jetty.server.Server.doStart(Server.java:431) ~[jetty-server-
	at org.eclipse.jetty.util.component.AbstractLifeCycle.start(AbstractLifeCycle.java:68) ~[jetty-util-
	at org.apache.skywalking.apm.collector.server.jetty.JettyServer.start(JettyServer.java:94) ~[server-component-5.0.0-GA.jar:5.0.0-GA]
	... 6 more_**_
2019-01-29 13:33:57,289 - org.apache.skywalking.apm.collector.storage.es.StorageModuleEsProvider -81560 [pool-7-thread-1] INFO  [] - Beginning to remove expired metrics from the storage.
2019-01-29 13:33:57,289 - org.apache.skywalking.apm.collector.storage.es.StorageModuleEsProvider -81560 [pool-7-thread-1] INFO  [] - Metrics in minute dimension before 201901291203, are going to be removed.
2019-01-29 13:33:57,289 - org.apache.skywalking.apm.collector.storage.es.StorageModuleEsProvider -81560 [pool-7-thread-1] INFO  [] - Metrics in hour dimension before 2019012801, are going to be removed.
2019-01-29 13:33:57,289 - org.apache.skywalking.apm.collector.storage.es.StorageModuleEsProvider -81560 [pool-7-thread-1] INFO  [] - Metrics in day dimension before 20181215, are going to be removed.
2019-01-29 13:33:57,289 - org.apache.skywalking.apm.collector.storage.es.StorageModuleEsProvider -81560 [pool-7-thread-1] INFO  [] - Metrics in month dimension before 201707, are going to be removed.
2019-01-29 13:33:57,309 - org.apache.skywalking.apm.collector.storage.es.base.dao.AbstractPersistenceEsDAO -81580 [pool-7-thread-1] INFO  [] - Delete 0 rows history from cpu_metric_minute index.
2019-01-29 13:33:57,311 - org.apache.skywalking.apm.collector.storage.es.base.dao.AbstractPersistenceEsDAO -81582 [pool-7-thread-1] INFO  [] - Delete 0 rows history from cpu_metric_hour index.
`

- **the  webapp.log** 

```
2019-01-29 13:34:12.406  INFO 69 --- [http-nio-8080-exec-6] c.netflix.config.ChainedDynamicProperty  : Flipping property: collector.ribbon.ActiveConnectionsLimit to use NEXT property: niws.loadbalancer.availabilityFilteringRule.activeConnectionsLimit = 2147483647
2019-01-29 13:34:12.808  INFO 69 --- [http-nio-8080-exec-6] c.netflix.loadbalancer.BaseLoadBalancer  : Client: collector instantiated a LoadBalancer: DynamicServerListLoadBalancer:{NFLoadBalancer:name=collector,current list of Servers=[],Load balancer stats=Zone stats: {},Server stats: []}ServerList:null
2019-01-29 13:34:12.842  INFO 69 --- [http-nio-8080-exec-6] c.n.l.DynamicServerListLoadBalancer      : Using serverListUpdater PollingServerListUpdater
2019-01-29 13:34:12.849  WARN 69 --- [http-nio-8080-exec-6] o.a.s.a.w.proxy.CollectorServerList      : none agentstream server return available grpc server.
2019-01-29 13:34:12.849  INFO 69 --- [http-nio-8080-exec-6] c.n.l.DynamicServerListLoadBalancer      : DynamicServerListLoadBalancer for client collector initialized: DynamicServerListLoadBalancer:{NFLoadBalancer:name=collector,current list of Servers=[],Load balancer stats=Zone stats: {},Server stats: []}ServerList:org.apache.skywalking.apm.webapp.proxy.CollectorServerList@69b5cc92
2019-01-29 13:34:13.520  WARN 69 --- [http-nio-8080-exec-6] o.s.c.n.z.filters.post.SendErrorFilter   : Error during filtering com.netflix.zuul.exception.ZuulException: Forwarding error at org.springframework.cloud.netflix.zuul.filters.route.RibbonRoutingFilter.handleException(RibbonRoutingFilter.java:189) at org.springframework.cloud.netflix.zuul.filters.route.RibbonRoutingFilter.forward(RibbonRoutingFilter.java:164) at org.springframework.cloud.netflix.zuul.filters.route.RibbonRoutingFilter.run(RibbonRoutingFilter.java:111)
	at com.netflix.zuul.ZuulFilter.runFilter(ZuulFilter.java:112)
	at com.netflix.zuul.FilterProcessor.processZuulFilter(FilterProcessor.java:193)
	at com.netflix.zuul.FilterProcessor.runFilters(FilterProcessor.java:157)
	at com.netflix.zuul.FilterProcessor.route(FilterProcessor.java:118)
	at com.netflix.zuul.ZuulRunner.route(ZuulRunner.java:96)
	at com.netflix.zuul.http.ZuulServlet.route(ZuulServlet.java:116)
	at com.netflix.zuul.http.ZuulServlet.service(ZuulServlet.java:81)
	at org.springframework.web.servlet.mvc.ServletWrappingController.handleRequestInternal(ServletWrappingController.java:157) at org.springframework.cloud.netflix.zuul.web.ZuulController.handleRequest(ZuulController.java:44) at org.springframework.web.servlet.mvc.SimpleControllerHandlerAdapter.handle(SimpleControllerHandlerAdapter.java:50)
	at org.springframework.web.servlet.DispatcherServlet.doDispatch(DispatcherServlet.java:967)
	at org.springframework.web.servlet.DispatcherServlet.doService(DispatcherServlet.java:901)
	at org.springframework.web.servlet.FrameworkServlet.processRequest(FrameworkServlet.java:970)
	at org.springframework.web.servlet.FrameworkServlet.doPost(FrameworkServlet.java:872)
	at javax.servlet.http.HttpServlet.service(HttpServlet.java:661)
	at org.springframework.web.servlet.FrameworkServlet.service(FrameworkServlet.java:846)
	at javax.servlet.http.HttpServlet.service(HttpServlet.java:742)
	at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:231)
	at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:166)
	at org.apache.tomcat.websocket.server.WsFilter.doFilter(WsFilter.java:52)
	at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:193)
	at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:166)
	at org.springframework.boot.web.filter.ApplicationContextHeaderFilter.doFilterInternal(ApplicationContextHeaderFilter.java:55)
	at org.springframework.web.filter.OncePerRequestFilter.doFilter(OncePerRequestFilter.java:107)
	at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:193)
	at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:166)
	at org.springframework.boot.actuate.trace.WebRequestTraceFilter.doFilterInternal(WebRequestTraceFilter.java:111)
	at org.springframework.web.filter.OncePerRequestFilter.doFilter(OncePerRequestFilter.java:107)
	at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:193)
	at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:166)
	at org.springframework.web.filter.RequestContextFilter.doFilterInternal(RequestContextFilter.java:99)
	at org.springframework.web.filter.OncePerRequestFilter.doFilter(OncePerRequestFilter.java:107)
	at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:193)
	at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:166)
	at org.springframework.web.filter.HttpPutFormContentFilter.doFilterInternal(HttpPutFormContentFilter.java:109)
	at org.springframework.web.filter.OncePerRequestFilter.doFilter(OncePerRequestFilter.java:107)
	at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:193)
	at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:166)
	at org.springframework.web.filter.HiddenHttpMethodFilter.doFilterInternal(HiddenHttpMethodFilter.java:81)
	at org.springframework.web.filter.OncePerRequestFilter.doFilter(OncePerRequestFilter.java:107)
	at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:193)
	at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:166)
	at org.springframework.web.filter.CharacterEncodingFilter.doFilterInternal(CharacterEncodingFilter.java:197)
	at org.springframework.web.filter.OncePerRequestFilter.doFilter(OncePerRequestFilter.java:107)
	at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:193)
	at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:166)
	at org.springframework.boot.actuate.autoconfigure.MetricsFilter.doFilterInternal(MetricsFilter.java:106)
	at org.springframework.web.filter.OncePerRequestFilter.doFilter(OncePerRequestFilter.java:107)
	at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:193)
	at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:166)
	at org.apache.catalina.core.StandardWrapperValve.invoke(StandardWrapperValve.java:198)
	at org.apache.catalina.core.StandardContextValve.invoke(StandardContextValve.java:96)
	at org.apache.catalina.authenticator.AuthenticatorBase.invoke(AuthenticatorBase.java:496)
	at org.apache.catalina.core.StandardHostValve.invoke(StandardHostValve.java:140)
	at org.apache.catalina.valves.ErrorReportValve.invoke(ErrorReportValve.java:81)
	at org.apache.catalina.core.StandardEngineValve.invoke(StandardEngineValve.java:87)
	at org.apache.catalina.connector.CoyoteAdapter.service(CoyoteAdapter.java:342)
	at org.apache.coyote.http11.Http11Processor.service(Http11Processor.java:803)
	at org.apache.coyote.AbstractProcessorLight.process(AbstractProcessorLight.java:66)
	at org.apache.coyote.AbstractProtocol$ConnectionHandler.process(AbstractProtocol.java:790)
	at org.apache.tomcat.util.net.NioEndpoint$SocketProcessor.doRun(NioEndpoint.java:1459)
	at org.apache.tomcat.util.net.SocketProcessorBase.run(SocketProcessorBase.java:49)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617)
	at org.apache.tomcat.util.threads.TaskThread$WrappingRunnable.run(TaskThread.java:61)
	at java.lang.Thread.run(Thread.java:745)
Caused by: com.netflix.client.ClientException: Load balancer does not have available server for client: collector
	at com.netflix.loadbalancer.LoadBalancerContext.getServerFromLoadBalancer(LoadBalancerContext.java:483)
	at com.netflix.loadbalancer.reactive.LoadBalancerCommand$1.call(LoadBalancerCommand.java:184)
	at com.netflix.loadbalancer.reactive.LoadBalancerCommand$1.call(LoadBalancerCommand.java:180)
	at rx.Observable.unsafeSubscribe(Observable.java:10151)
	at rx.internal.operators.OnSubscribeConcatMap.call(OnSubscribeConcatMap.java:94)
	at rx.internal.operators.OnSubscribeConcatMap.call(OnSubscribeConcatMap.java:42)
	at rx.Observable.unsafeSubscribe(Observable.java:10151)
	at rx.internal.operators.OperatorRetryWithPredicate$SourceSubscriber$1.call(OperatorRetryWithPredicate.java:127)
	at rx.internal.schedulers.TrampolineScheduler$InnerCurrentThreadScheduler.enqueue(TrampolineScheduler.java:73)
	at rx.internal.schedulers.TrampolineScheduler$InnerCurrentThreadScheduler.schedule(TrampolineScheduler.java:52)
	at rx.internal.operators.OperatorRetryWithPredicate$SourceSubscriber.onNext(OperatorRetryWithPredicate.java:79)
	at rx.internal.operators.OperatorRetryWithPredicate$SourceSubscriber.onNext(OperatorRetryWithPredicate.java:45)
	at rx.internal.util.ScalarSynchronousObservable$WeakSingleProducer.request(ScalarSynchronousObservable.java:276)
	at rx.Subscriber.setProducer(Subscriber.java:209)
	at rx.internal.util.ScalarSynchronousObservable$JustOnSubscribe.call(ScalarSynchronousObservable.java:138)
	at rx.internal.util.ScalarSynchronousObservable$JustOnSubscribe.call(ScalarSynchronousObservable.java:129)
	at rx.internal.operators.OnSubscribeLift.call(OnSubscribeLift.java:48)
	at rx.internal.operators.OnSubscribeLift.call(OnSubscribeLift.java:30)
	at rx.internal.operators.OnSubscribeLift.call(OnSubscribeLift.java:48)
	at rx.internal.operators.OnSubscribeLift.call(OnSubscribeLift.java:30)
	at rx.internal.operators.OnSubscribeLift.call(OnSubscribeLift.java:48)
	at rx.internal.operators.OnSubscribeLift.call(OnSubscribeLift.java:30)
	at rx.Observable.subscribe(Observable.java:10247)
	at rx.Observable.subscribe(Observable.java:10214)
	at rx.observables.BlockingObservable.blockForSingle(BlockingObservable.java:444)
	at rx.observables.BlockingObservable.single(BlockingObservable.java:341)
	at com.netflix.client.AbstractLoadBalancerAwareClient.executeWithLoadBalancer(AbstractLoadBalancerAwareClient.java:112)
	at org.springframework.cloud.netflix.zuul.filters.route.support.AbstractRibbonCommand.run(AbstractRibbonCommand.java:152)
	at org.springframework.cloud.netflix.zuul.filters.route.support.AbstractRibbonCommand.run(AbstractRibbonCommand.java:49)
	at com.netflix.hystrix.HystrixCommand$2.call(HystrixCommand.java:302)
	at com.netflix.hystrix.HystrixCommand$2.call(HystrixCommand.java:298)
	at rx.internal.operators.OnSubscribeDefer.call(OnSubscribeDefer.java:46)
	at rx.internal.operators.OnSubscribeDefer.call(OnSubscribeDefer.java:35)
	at rx.internal.operators.OnSubscribeLift.call(OnSubscribeLift.java:48)
	at rx.internal.operators.OnSubscribeLift.call(OnSubscribeLift.java:30)
	at rx.internal.operators.OnSubscribeLift.call(OnSubscribeLift.java:48)
	at rx.internal.operators.OnSubscribeLift.call(OnSubscribeLift.java:30)
	at rx.internal.operators.OnSubscribeLift.call(OnSubscribeLift.java:48)
	at rx.internal.operators.OnSubscribeLift.call(OnSubscribeLift.java:30)
	at rx.Observable.unsafeSubscribe(Observable.java:10151)
	at rx.internal.operators.OnSubscribeDefer.call(OnSubscribeDefer.java:51)
	at rx.internal.operators.OnSubscribeDefer.call(OnSubscribeDefer.java:35)
	at rx.internal.operators.OnSubscribeLift.call(OnSubscribeLift.java:48)
	at rx.internal.operators.OnSubscribeLift.call(OnSubscribeLift.java:30)
	at rx.Observable.unsafeSubscribe(Observable.java:10151)
	at rx.internal.operators.OnSubscribeDoOnEach.call(OnSubscribeDoOnEach.java:41)
	at rx.internal.operators.OnSubscribeDoOnEach.call(OnSubscribeDoOnEach.java:30)
	at rx.Observable.unsafeSubscribe(Observable.java:10151)
	at rx.internal.operators.OnSubscribeDoOnEach.call(OnSubscribeDoOnEach.java:41)
	at rx.internal.operators.OnSubscribeDoOnEach.call(OnSubscribeDoOnEach.java:30)
	at rx.internal.operators.OnSubscribeLift.call(OnSubscribeLift.java:48)
	at rx.internal.operators.OnSubscribeLift.call(OnSubscribeLift.java:30)
	at rx.Observable.unsafeSubscribe(Observable.java:10151)
	at rx.internal.operators.OnSubscribeDoOnEach.call(OnSubscribeDoOnEach.java:41)
	at rx.internal.operators.OnSubscribeDoOnEach.call(OnSubscribeDoOnEach.java:30)
	at rx.Observable.unsafeSubscribe(Observable.java:10151)
	at rx.internal.operators.OnSubscribeDoOnEach.call(OnSubscribeDoOnEach.java:41)
	at rx.internal.operators.OnSubscribeDoOnEach.call(OnSubscribeDoOnEach.java:30)
	at rx.Observable.unsafeSubscribe(Observable.java:10151)
	at rx.internal.operators.OnSubscribeDoOnEach.call(OnSubscribeDoOnEach.java:41)
	at rx.internal.operators.OnSubscribeDoOnEach.call(OnSubscribeDoOnEach.java:30)
	at rx.internal.operators.OnSubscribeLift.call(OnSubscribeLift.java:48)
	at rx.internal.operators.OnSubscribeLift.call(OnSubscribeLift.java:30)
	at rx.Observable.unsafeSubscribe(Observable.java:10151)
	at rx.internal.operators.OnSubscribeDefer.call(OnSubscribeDefer.java:51)
	at rx.internal.operators.OnSubscribeDefer.call(OnSubscribeDefer.java:35)
	at rx.Observable.unsafeSubscribe(Observable.java:10151)
	at rx.internal.operators.OnSubscribeMap.call(OnSubscribeMap.java:48)
	at rx.internal.operators.OnSubscribeMap.call(OnSubscribeMap.java:33)
	at rx.Observable.unsafeSubscribe(Observable.java:10151)
	at rx.internal.operators.OnSubscribeDoOnEach.call(OnSubscribeDoOnEach.java:41)
	at rx.internal.operators.OnSubscribeDoOnEach.call(OnSubscribeDoOnEach.java:30)
	at rx.internal.operators.OnSubscribeLift.call(OnSubscribeLift.java:48)
	at rx.internal.operators.OnSubscribeLift.call(OnSubscribeLift.java:30)
	at rx.Observable.unsafeSubscribe(Observable.java:10151)
	at rx.internal.operators.OnSubscribeDoOnEach.call(OnSubscribeDoOnEach.java:41)
	at rx.internal.operators.OnSubscribeDoOnEach.call(OnSubscribeDoOnEach.java:30)
	at rx.Observable.unsafeSubscribe(Observable.java:10151)
	at rx.internal.operators.OnSubscribeDefer.call(OnSubscribeDefer.java:51)
	at rx.internal.operators.OnSubscribeDefer.call(OnSubscribeDefer.java:35)
	at rx.internal.operators.OnSubscribeLift.call(OnSubscribeLift.java:48)
	at rx.internal.operators.OnSubscribeLift.call(OnSubscribeLift.java:30)
	at rx.Observable.subscribe(Observable.java:10247)
	at rx.Observable.subscribe(Observable.java:10214)
	at rx.internal.operators.BlockingOperatorToFuture.toFuture(BlockingOperatorToFuture.java:51)
	at rx.observables.BlockingObservable.toFuture(BlockingObservable.java:411)
	at com.netflix.hystrix.HystrixCommand.queue(HystrixCommand.java:378)
	at com.netflix.hystrix.HystrixCommand.execute(HystrixCommand.java:344)
	at org.springframework.cloud.netflix.zuul.filters.route.RibbonRoutingFilter.forward(RibbonRoutingFilter.java:158)
	... 67 common frames omitted

2019-01-29 13:34:13.846  WARN 69 --- [PollingServerListUpdater-0] o.a.s.a.w.proxy.CollectorServerList      : none agentstream server return available grpc server.
2019-01-29 13:34:43.847  WARN 69 --- [PollingServerListUpdater-0] o.a.s.a.w.proxy.CollectorServerList      : none agentstream server return available grpc server.
2019-01-29 13:35:13.848  WARN 69 --- [PollingServerListUpdater-0] o.a.s.a.w.proxy.CollectorServerList      : none agentstream server return available grpc server.`
```

**I can log into the UI successfully with  localhost:8080 ,but there was  an error  code ' 500 '**

So, how can i do  with that !

**Comment by JaredTan95** [comment]
This image is not provided by skywalking.

**Comment by wu-sheng** [comment]
+1 This is not our image. Please post the issue for the one providing this image.
