### ISSUE TITLE
During the use of skywalking5.X, the business function appears "No active span" error

### ISSUE THREAD

**Issue by littlehuihui** [apache/incubator-skywalking#2240]
Hi~When I use skywalking, one of our business scenarios has the following error, and the error disappears after closing the skywalking-agent. What is the possible reason for this? Thank you!

`Error - 2019/2/12 11:51:00 - Microsoft.EntityFrameworkCore.Database.Command - 114805-5065 - INSERT INTO Testtccmainlog0 (id, createdtime, lastupdatetime, registers, retrycount, rootid, serviceunit, status)
VALUES (@p0, @p1, @p2, @p3, @p4, @p5, @p6, @p7);
Error - 2019/2/12 11:51:00 - Communication - 114805-5065 - [CommunicationTag,Caf,developer] One or more errors occurred. (One or more errors occurred. (Exception has been thrown by the target of an invocation.)) {System.AggregateException: One or more errors occurred. (One or more errors occurred. (Exception has been thrown by the target of an invocation.)) 
---> System.AggregateException: One or more errors occurred. (Exception has been thrown by the target of an invocation.) ---> System.Reflection.TargetInvocationException: Exception has been thrown by the target of an invocation. ---> Microsoft.EntityFrameworkCore.DbUpdateException: An error occurred while updating the entries. See the inner exception for details. ---> System.Reflection.TargetInvocationException: Exception has been thrown by the target of an invocation. ---> System.InvalidOperationException: No active span.
   at SkyWalking.Context.TracingContext.InternalActiveSpan()
   at SkyWalking.Diagnostics.EntityFrameworkCore.EntityFrameworkCoreDiagnosticProcessor.CommandError(CommandErrorEventData eventData)
   --- End of inner exception stack trace ---
   at System.RuntimeMethodHandle.InvokeMethod(Object target, Object[] arguments, Signature sig, Boolean constructor, Boolean wrapExceptions)
   at System.Reflection.RuntimeMethodInfo.Invoke(Object obj, BindingFlags invokeAttr, Binder binder, Object[] parameters, CultureInfo culture)
   at SkyWalking.Diagnostics.TracingDiagnosticMethod.Invoke(String diagnosticName, Object value)
   at SkyWalking.Diagnostics.TracingDiagnosticObserver.OnNext(KeyValuePair`2 value)
   at System.Diagnostics.DiagnosticListener.Write(String name, Object value)
   at Microsoft.EntityFrameworkCore.Internal.RelationalLoggerExtensions.CommandError(IDiagnosticsLogger`1 diagnostics, DbCommand command, DbCommandMethod executeMethod, Guid commandId, Guid connectionId, Exception exception, Boolean async, DateTimeOffset startTime, TimeSpan duration)
   at Microsoft.EntityFrameworkCore.Storage.Internal.RelationalCommand.Execute(IRelationalConnection connection, DbCommandMethod executeMethod, IReadOnlyDictionary`2 parameterValues)
   at Microsoft.EntityFrameworkCore.Storage.Internal.RelationalCommand.ExecuteReader(IRelationalConnection connection, IReadOnlyDictionary`2 parameterValues)
   at Microsoft.EntityFrameworkCore.Update.ReaderModificationCommandBatch.Execute(IRelationalConnection connection)`

**Comment by wu-sheng** [comment]
This is not SkyWalking issue. Please move to https://github.com/SkyAPM/SkyAPM-dotnet/issues . .NET agent is part of SkyWalking ecosystem, but the issue should be tracked at their own repo.
