### ISSUE TITLE
agent can not work after upgrade from 6.0.0-beta to 6.0.0-GA

### ISSUE THREAD

**Issue by foxracle** [apache/incubator-skywalking#2248]
Please answer these questions before submitting your issue.

- Why do you submit this issue?
- [x] Question or discussion
- [ ] Bug
- [ ] Requirement
- [ ] Feature or performance improvement

___
### Question
- What do you want to know?
sw agent can not work after upgrade from 6.0.0-beta to 6.0.0-GA (we have upgraded all agents, oap and webapp service). they all worked before upgraded.

here is the agent's log:
DEBUG 2019-02-15 17:49:15:828 ServiceAndEndpointRegisterClient :  ServiceAndEndpointRegisterClient running, status:CONNECTED.
ERROR 2019-02-15 17:49:15:833 ServiceAndEndpointRegisterClient :  ServiceAndEndpointRegisterClient execute fail.
org.apache.skywalking.apm.dependencies.io.grpc.StatusRuntimeException: UNKNOWN
	at org.apache.skywalking.apm.dependencies.io.grpc.stub.ClientCalls.toStatusRuntimeException(ClientCalls.java:222)
	at org.apache.skywalking.apm.dependencies.io.grpc.stub.ClientCalls.getUnchecked(ClientCalls.java:203)
	at org.apache.skywalking.apm.dependencies.io.grpc.stub.ClientCalls.blockingUnaryCall(ClientCalls.java:132)
	at org.apache.skywalking.apm.network.register.v2.RegisterGrpc$RegisterBlockingStub.doServiceInstanceRegister(RegisterGrpc.java:393)
	at org.apache.skywalking.apm.agent.core.remote.ServiceAndEndpointRegisterClient.run(ServiceAndEndpointRegisterClient.java:126)
	at org.apache.skywalking.apm.util.RunnableWithExceptionProtection.run(RunnableWithExceptionProtection.java:36)
	at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511)
	at java.util.concurrent.FutureTask.runAndReset(FutureTask.java:308)
	at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.access$301(ScheduledThreadPoolExecutor.java:180)
	at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.run(ScheduledThreadPoolExecutor.java:294)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617)
	at java.lang.Thread.run(Thread.java:745)

**Comment by wu-sheng** [comment]
This error looks no related to version update. More likely, your backend does not startup right. The models of backend have been changed, so recheck your backend.

**Comment by foxracle** [comment]
3q
this is the backend's log:

2019-02-15 18:56:53,801 - org.apache.skywalking.oap.server.storage.plugin.elasticsearch.lock.RegisterLockDAOImpl - 71 [DataCarrier.IndicatorPersistentWorker.endpoint_inventory.Consumser.0.Thread] WARN  [] - Try to lock the row with the id 16 failure, error message: null
2019-02-15 18:56:53,812 - org.apache.skywalking.oap.server.core.register.worker.RegisterPersistentWorker - 98 [DataCarrier.IndicatorPersistentWorker.endpoint_inventory.Consumser.0.Thread] INFO  [] - EndpointInventory inventory register try lock and increment sequence failure.
2019-02-15 18:56:53,810 - org.apache.skywalking.oap.server.storage.plugin.elasticsearch.cache.ServiceInventoryCacheEsDAO - 86 [grpc-default-executor-4] ERROR [] - null
java.lang.NullPointerException: null
        at org.apache.skywalking.oap.server.core.register.ServiceInventory$Builder.map2Data(ServiceInventory.java:207) ~[server-core-6.0.0-GA.jar:6.0.0-GA]
        at org.apache.skywalking.oap.server.storage.plugin.elasticsearch.cache.ServiceInventoryCacheEsDAO.get(ServiceInventoryCacheEsDAO.java:81) [storage-elasticsearch-plugin-6.0.0-GA.jar:6.0.0-GA]
        at org.apache.skywalking.oap.server.core.cache.ServiceInventoryCache.get(ServiceInventoryCache.java:100) [server-core-6.0.0-GA.jar:6.0.0-GA]
        at org.apache.skywalking.oap.server.core.register.service.ServiceInventoryRegister.heartbeat(ServiceInventoryRegister.java:111) [server-core-6.0.0-GA.jar:6.0.0-GA]
        at org.apache.skywalking.oap.server.receiver.register.provider.handler.v6.grpc.ServiceInstancePingServiceHandler.doPing(ServiceInstancePingServiceHandler.java:59) [skywalking-register-receiver-plugin-6.0.0-GA.jar:6.0.0-GA]
        at org.apache.skywalking.apm.network.register.v2.ServiceInstancePingGrpc$MethodHandlers.invoke(ServiceInstancePingGrpc.java:210) [apm-network-6.0.0-GA.jar:6.0.0-GA]
        at io.grpc.stub.ServerCalls$UnaryServerCallHandler$UnaryServerCallListener.onHalfClose(ServerCalls.java:171) [grpc-stub-1.15.1.jar:1.15.1]
        at io.grpc.internal.ServerCallImpl$ServerStreamListenerImpl.halfClosed(ServerCallImpl.java:283) [grpc-core-1.15.1.jar:1.15.1]
        at io.grpc.internal.ServerImpl$JumpToApplicationThreadServerStreamListener$1HalfClosed.runInContext(ServerImpl.java:707) [grpc-core-1.15.1.jar:1.15.1]
        at io.grpc.internal.ContextRunnable.run(ContextRunnable.java:37) [grpc-core-1.15.1.jar:1.15.1]
        at io.grpc.internal.SerializingExecutor.run(SerializingExecutor.java:123) [grpc-core-1.15.1.jar:1.15.1]
        at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149) [?:1.8.0_181]
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624) [?:1.8.0_181]
        at java.lang.Thread.run(Thread.java:748) [?:1.8.0_181]
2019-02-15 18:56:53,812 - org.apache.skywalking.oap.server.core.register.service.ServiceInventoryRegister - 118 [grpc-default-executor-4] WARN  [] - Service 9 heartbeat, but not found in storage.
2019-02-15 18:56:53,813 - org.apache.skywalking.oap.server.storage.plugin.elasticsearch.lock.RegisterLockDAOImpl - 71 [DataCarrier.IndicatorPersistentWorker.endpoint_inventory.Consumser.0.Thread] WARN  [] - Try to lock the row with the id 16 failure, error message: null
2019-02-15 18:56:53,813 - org.apache.skywalking.oap.server.core.register.worker.RegisterPersistentWorker - 98 [DataCarrier.IndicatorPersistentWorker.endpoint_inventory.Consumser.0.Thread] INFO  [] - EndpointInventory inventory register try lock and increment sequence failure.
2019-02-15 18:56:53,814 - org.apache.skywalking.oap.server.storage.plugin.elasticsearch.lock.RegisterLockDAOImpl - 71 [DataCarrier.IndicatorPersistentWorker.endpoint_inventory.Consumser.0.Thread] WARN  [] - Try to lock the row with the id 16 failure, error message: null
2019-02-15 18:56:53,814 - org.apache.skywalking.oap.server.core.register.worker.RegisterPersistentWorker - 98 [DataCarrier.IndicatorPersistentWorker.endpoint_inventory.Consumser.0.Thread] INFO  [] - EndpointInventory inventory register try lock and increment sequence failure.

**Comment by foxracle** [comment]
it seems that the problem related to es, any hints? during the upgrade and restart, we did not change anything for es

**Comment by wu-sheng** [comment]
The es models changes. You need to change that manually, or use a new empty es.

**Comment by foxracle** [comment]
after delete all old indexes of es, it works. thank you.
Is there any document for upgrade?
here is my upgrade procedure for upgrading from 6.0.0-beta to 6.0.0-GA(it may not be the best practice)
1: stop all backend servers
2: delete all old indexes of sw(you can delete all indexes that starting with the value of storage.elasticsearch.nameSpace)
3: upgrade all backend servers
4: upgrade all agent and restart all application that start with javaagent (I used sw for java app)
5: start all backend servers

**Comment by wu-sheng** [comment]
You could do update in this way. But we don't have this document.
