### ISSUE TITLE
java.lang.ArrayIndexOutOfBoundsException

### ISSUE THREAD

**Issue by liuzhengyang** [apache/incubator-skywalking#2283]
Please answer these questions before submitting your issue.

- Why do you submit this issue?
- [x] Bug

___
### Bug
In latest 6.1.0-SNAPSHOT version, when we called `net.spy.memcached.MemcachedClient.getStats()`.
```
java.lang.ArrayIndexOutOfBoundsException: 0
  at org.apache.skywalking.apm.plugin.spymemcached.v2.MemcachedMethodInterceptor.beforeMethod(MemcachedMethodInterceptor.java:44)
  at org.apache.skywalking.apm.agent.core.plugin.interceptor.enhance.InstMethodsInter.intercept(InstMethodsInter.java:82)
  at net.spy.memcached.MemcachedClient.getStats(MemcachedClient.java)
```

**Comment by wu-sheng** [comment]
PR merged. Thanks for the contribution.
