### ISSUE TITLE
服务启动报错，我哪里配置错了么?

### ISSUE THREAD

**Issue by dejdong** [apache/incubator-skywalking#2312]
1.启动日志
2019-03-04 01:17:47,926 - org.apache.skywalking.oap.server.starter.config.ApplicationConfigLoader - 62 [main] INFO  [] - Get a module define from application.yml, module name: naming
2019-03-04 01:17:47,942 - org.apache.skywalking.oap.server.starter.config.ApplicationConfigLoader - 65 [main] INFO  [] - Get a provider define belong to naming module, provider name: jetty
2019-03-04 01:17:47,956 - org.apache.skywalking.oap.server.starter.config.ApplicationConfigLoader - 73 [main] INFO  [] - The property with key: host, value: localhost, in jetty provider
2019-03-04 01:17:47,956 - org.apache.skywalking.oap.server.starter.config.ApplicationConfigLoader - 73 [main] INFO  [] - The property with key: port, value: 10800, in jetty provider
2019-03-04 01:17:47,957 - org.apache.skywalking.oap.server.starter.config.ApplicationConfigLoader - 73 [main] INFO  [] - The property with key: contextPath, value: /, in jetty provider
2019-03-04 01:17:47,958 - org.apache.skywalking.oap.server.starter.config.ApplicationConfigLoader - 62 [main] INFO  [] - Get a module define from application.yml, module name: remote
2019-03-04 01:17:47,958 - org.apache.skywalking.oap.server.starter.config.ApplicationConfigLoader - 65 [main] INFO  [] - Get a provider `define` belong to remote module, provider name: gRPC
2019-03-04 01:17:47,958 - org.apache.skywalking.oap.server.starter.config.ApplicationConfigLoader - 73 [main] INFO  [] - The property with key: host, value: 0.0.0.0, in gRPC provider
2019-03-04 01:17:47,959 - org.apache.skywalking.oap.server.starter.config.ApplicationConfigLoader - 73 [main] INFO  [] - The property with key: port, value: 11800, in gRPC provider
2019-03-04 01:17:47,959 - org.apache.skywalking.oap.server.starter.config.ApplicationConfigLoader - 62 [main] INFO  [] - Get a module define from application.yml, module name: agent_gRPC
2019-03-04 01:17:47,959 - org.apache.skywalking.oap.server.starter.config.ApplicationConfigLoader - 65 [main] INFO  [] - Get a provider define belong to agent_gRPC module, provider name: gRPC
2019-03-04 01:17:47,959 - org.apache.skywalking.oap.server.starter.config.ApplicationConfigLoader - 73 [main] INFO  [] - The property with key: host, value: 0.0.0.0, in gRPC provider
2019-03-04 01:17:47,959 - org.apache.skywalking.oap.server.starter.config.ApplicationConfigLoader - 73 [main] INFO  [] - The property with key: port, value: 11800, in gRPC provider
2019-03-04 01:17:47,959 - org.apache.skywalking.oap.server.starter.config.ApplicationConfigLoader - 62 [main] INFO  [] - Get a module define from application.yml, module name: agent_jetty
2019-03-04 01:17:47,959 - org.apache.skywalking.oap.server.starter.config.ApplicationConfigLoader - 65 [main] INFO  [] - Get a provider define belong to agent_jetty module, provider name: jetty
2019-03-04 01:17:47,960 - org.apache.skywalking.oap.server.starter.config.ApplicationConfigLoader - 73 [main] INFO  [] - The property with key: host, value: 0.0.0.0, in jetty provider
2019-03-04 01:17:47,960 - org.apache.skywalking.oap.server.starter.config.ApplicationConfigLoader - 73 [main] INFO  [] - The property with key: port, value: 12800, in jetty provider
2019-03-04 01:17:47,960 - org.apache.skywalking.oap.server.starter.config.ApplicationConfigLoader - 73 [main] INFO  [] - The property with key: contextPath, value: /, in jetty provider
2019-03-04 01:17:47,960 - org.apache.skywalking.oap.server.starter.config.ApplicationConfigLoader - 62 [main] INFO  [] - Get a module define from application.yml, module name: analysis_register
2019-03-04 01:17:47,960 - org.apache.skywalking.oap.server.starter.config.ApplicationConfigLoader - 65 [main] INFO  [] - Get a provider define belong to analysis_register module, provider name: default
2019-03-04 01:17:47,960 - org.apache.skywalking.oap.server.starter.config.ApplicationConfigLoader - 62 [main] INFO  [] - Get a module define from application.yml, module name: analysis_jvm
2019-03-04 01:17:47,960 - org.apache.skywalking.oap.server.starter.config.ApplicationConfigLoader - 65 [main] INFO  [] - Get a provider define belong to analysis_jvm module, provider name: default
2019-03-04 01:17:47,960 - org.apache.skywalking.oap.server.starter.config.ApplicationConfigLoader - 62 [main] INFO  [] - Get a module define from application.yml, module name: analysis_segment_parser
2019-03-04 01:17:47,961 - org.apache.skywalking.oap.server.starter.config.ApplicationConfigLoader - 65 [main] INFO  [] - Get a provider define belong to analysis_segment_parser module, provider name: default
2019-03-04 01:17:47,961 - org.apache.skywalking.oap.server.starter.config.ApplicationConfigLoader - 73 [main] INFO  [] - The property with key: bufferFilePath, value: ../buffer/, in default provider
2019-03-04 01:17:47,961 - org.apache.skywalking.oap.server.starter.config.ApplicationConfigLoader - 73 [main] INFO  [] - The property with key: bufferOffsetMaxFileSize, value: 10M, in default provider
2019-03-04 01:17:47,961 - org.apache.skywalking.oap.server.starter.config.ApplicationConfigLoader - 73 [main] INFO  [] - The property with key: bufferSegmentMaxFileSize, value: 500M, in default provider
2019-03-04 01:17:47,961 - org.apache.skywalking.oap.server.starter.config.ApplicationConfigLoader - 62 [main] INFO  [] - Get a module define from application.yml, module name: ui
2019-03-04 01:17:47,962 - org.apache.skywalking.oap.server.starter.config.ApplicationConfigLoader - 65 [main] INFO  [] - Get a provider define belong to ui module, provider name: jetty
2019-03-04 01:17:47,962 - org.apache.skywalking.oap.server.starter.config.ApplicationConfigLoader - 73 [main] INFO  [] - The property with key: host, value: 127.0.0.1, in jetty provider
2019-03-04 01:17:47,963 - org.apache.skywalking.oap.server.starter.config.ApplicationConfigLoader - 73 [main] INFO  [] - The property with key: port, value: 12800, in jetty provider
2019-03-04 01:17:47,964 - org.apache.skywalking.oap.server.starter.config.ApplicationConfigLoader - 73 [main] INFO  [] - The property with key: contextPath, value: /, in jetty provider
2019-03-04 01:17:47,964 - org.apache.skywalking.oap.server.starter.config.ApplicationConfigLoader - 62 [main] INFO  [] - Get a module define from application.yml, module name: storage
2019-03-04 01:17:47,964 - org.apache.skywalking.oap.server.starter.config.ApplicationConfigLoader - 65 [main] INFO  [] - Get a provider define belong to storage module, provider name: elasticsearch
2019-03-04 01:17:47,965 - org.apache.skywalking.oap.server.starter.config.ApplicationConfigLoader - 73 [main] INFO  [] - The property with key: clusterName, value: CollectorDBCluster, in elasticsearch provider
2019-03-04 01:17:47,965 - org.apache.skywalking.oap.server.starter.config.ApplicationConfigLoader - 73 [main] INFO  [] - The property with key: clusterTransportSniffer, value: true, in elasticsearch provider
2019-03-04 01:17:47,966 - org.apache.skywalking.oap.server.starter.config.ApplicationConfigLoader - 73 [main] INFO  [] - The property with key: clusterNodes, value: 192.168.1.121:9300, in elasticsearch provider
2019-03-04 01:17:47,966 - org.apache.skywalking.oap.server.starter.config.ApplicationConfigLoader - 73 [main] INFO  [] - The property with key: indexShardsNumber, value: 2, in elasticsearch provider
2019-03-04 01:17:47,967 - org.apache.skywalking.oap.server.starter.config.ApplicationConfigLoader - 73 [main] INFO  [] - The property with key: indexReplicasNumber, value: 0, in elasticsearch provider
2019-03-04 01:17:47,967 - org.apache.skywalking.oap.server.starter.config.ApplicationConfigLoader - 73 [main] INFO  [] - The property with key: highPerformanceMode, value: true, in elasticsearch provider
2019-03-04 01:17:47,967 - org.apache.skywalking.oap.server.starter.config.ApplicationConfigLoader - 73 [main] INFO  [] - The property with key: traceDataTTL, value: 90, in elasticsearch provider
2019-03-04 01:17:47,967 - org.apache.skywalking.oap.server.starter.config.ApplicationConfigLoader - 73 [main] INFO  [] - The property with key: minuteMetricDataTTL, value: 45, in elasticsearch provider
2019-03-04 01:17:47,968 - org.apache.skywalking.oap.server.starter.config.ApplicationConfigLoader - 73 [main] INFO  [] - The property with key: hourMetricDataTTL, value: 36, in elasticsearch provider
2019-03-04 01:17:47,968 - org.apache.skywalking.oap.server.starter.config.ApplicationConfigLoader - 73 [main] INFO  [] - The property with key: dayMetricDataTTL, value: 45, in elasticsearch provider
2019-03-04 01:17:47,968 - org.apache.skywalking.oap.server.starter.config.ApplicationConfigLoader - 73 [main] INFO  [] - The property with key: monthMetricDataTTL, value: 18, in elasticsearch provider
2019-03-04 01:17:47,968 - org.apache.skywalking.oap.server.starter.config.ApplicationConfigLoader - 62 [main] INFO  [] - Get a module define from application.yml, module name: configuration
2019-03-04 01:17:47,969 - org.apache.skywalking.oap.server.starter.config.ApplicationConfigLoader - 65 [main] INFO  [] - Get a provider define belong to configuration module, provider name: default
2019-03-04 01:17:47,969 - org.apache.skywalking.oap.server.starter.config.ApplicationConfigLoader - 73 [main] INFO  [] - The property with key: applicationApdexThreshold, value: 2000, in default provider
2019-03-04 01:17:47,969 - org.apache.skywalking.oap.server.starter.config.ApplicationConfigLoader - 73 [main] INFO  [] - The property with key: serviceErrorRateThreshold, value: 10.0, in default provider
2019-03-04 01:17:47,969 - org.apache.skywalking.oap.server.starter.config.ApplicationConfigLoader - 73 [main] INFO  [] - The property with key: serviceAverageResponseTimeThreshold, value: 2000, in default provider
2019-03-04 01:17:47,969 - org.apache.skywalking.oap.server.starter.config.ApplicationConfigLoader - 73 [main] INFO  [] - The property with key: instanceErrorRateThreshold, value: 10.0, in default provider
2019-03-04 01:17:47,970 - org.apache.skywalking.oap.server.starter.config.ApplicationConfigLoader - 73 [main] INFO  [] - The property with key: instanceAverageResponseTimeThreshold, value: 2000, in default provider
2019-03-04 01:17:47,970 - org.apache.skywalking.oap.server.starter.config.ApplicationConfigLoader - 73 [main] INFO  [] - The property with key: applicationErrorRateThreshold, value: 10.0, in default provider
2019-03-04 01:17:47,970 - org.apache.skywalking.oap.server.starter.config.ApplicationConfigLoader - 73 [main] INFO  [] - The property with key: applicationAverageResponseTimeThreshold, value: 2000, in default provider
2019-03-04 01:17:47,970 - org.apache.skywalking.oap.server.starter.config.ApplicationConfigLoader - 73 [main] INFO  [] - The property with key: thermodynamicResponseTimeStep, value: 50, in default provider
2019-03-04 01:17:47,971 - org.apache.skywalking.oap.server.starter.config.ApplicationConfigLoader - 73 [main] INFO  [] - The property with key: thermodynamicCountOfResponseTimeSteps, value: 40, in default provider
2019-03-04 01:17:48,228 - org.apache.skywalking.oap.server.library.module.ModuleDefine - 89 [main] INFO  [] - Prepare the elasticsearch provider in storage module.
2019-03-04 01:17:48,229 - org.apache.skywalking.oap.server.library.module.ModuleDefine - 114 [main] WARN  [] - clusterTransportSniffer setting is not supported in elasticsearch provider of storage module
2019-03-04 01:17:48,230 - org.apache.skywalking.oap.server.library.module.ModuleDefine - 114 [main] WARN  [] - clusterName setting is not supported in elasticsearch provider of storage module
2019-03-04 01:17:48,346 - org.apache.skywalking.oap.server.starter.OAPServerStartUp - 45 [main] ERROR [] - [analysis_register, analysis_segment_parser, ui, agent_gRPC, configuration, naming, remote, agent_jetty, analysis_jvm] missing.
org.apache.skywalking.oap.server.library.module.ModuleNotFoundException: [analysis_register, analysis_segment_parser, ui, agent_gRPC, configuration, naming, remote, agent_jetty, analysis_jvm] missing.
	at org.apache.skywalking.oap.server.library.module.ModuleManager.init(ModuleManager.java:60) ~[library-module-6.0.0-beta.jar:6.0.0-beta]
	at org.apache.skywalking.oap.server.starter.OAPServerStartUp.main(OAPServerStartUp.java:37) [server-starter-6.0.0-beta.jar:6.0.0-beta]

2.配置文件 application.yml
#cluster:
# The Zookeeper cluster for collector cluster management.
#  zookeeper:
#    hostPort: 192.168.1.120:2181
#    sessionTimeout: 100000
naming:
# Host and port used for agent config
  jetty:  
    # 配置agent发现collector集群,host必须要系统真实网络ip地址. agent --(HTTP)--> collector
    host: localhost 
    port: 10800
    contextPath: /
remote:
  gRPC:
    # 配置collector节点在集群中相互通信,host必须要系统真实网络ip地址. collectorN --(gRPC) --> collectorM
    host: 0.0.0.0 
    port: 11800
agent_gRPC:
  gRPC:
    # 配置agent上传(链路跟踪和指标)数据到collector,host必须要系统真实网络ip地址. agent--(gRPC)--> collector
    host: 0.0.0.0 
    port: 11800
agent_jetty:
  jetty:  
    # 配置agent上传(链路跟踪和指标)数据到collector,host必须要系统真实网络ip地址. agent--(HTTP)--> collector
    # SkyWalking native Java/.Net/node.js agents don't use this.
    # Open this for other implementor.
    host: 0.0.0.0 
    port: 12800
    contextPath: /
analysis_register:
  default:
analysis_jvm:
  default:
analysis_segment_parser:
  default:
    bufferFilePath: ../buffer/
    bufferOffsetMaxFileSize: 10M
    bufferSegmentMaxFileSize: 500M
ui:
  jetty:  
    # 配置UI访问collector,host必须要系统真实网络ip地址. 
    host: 127.0.0.1
    port: 12800
    contextPath: /
# 配置Elasticsearch 集群连接信息
storage:
  elasticsearch:
    clusterName: CollectorDBCluster
    clusterTransportSniffer: true
    clusterNodes: 192.168.1.121:9300
    indexShardsNumber: 2
    indexReplicasNumber: 0
    highPerformanceMode: true
    # 设置统计指标数据的失效时间，当指标数据失效时系统将数据自动删除.

**Comment by wu-sheng** [comment]
English only. And look like you changed the application.yml a lot, and remove many required modules.

**Comment by dejdong** [comment]
thank you!
