### ISSUE TITLE
org.apache.skywalking.oap.server.receiver.register.provider.handler.v6.grpc.ServiceInstancePingServiceHandler - 61 [grpc-default-executor-23] WARN  [] - Can't found service by service instance id from cache, service instance id is: 20 2019-03-12 12:26:16,302 - org.apache.skywalking.oap.server.core.register.service.ServiceInstanceInventoryRegister - 108 [grpc-default-executor-23] WARN  [] - Service instance 17 heartbeat, but not found in storage.

### ISSUE THREAD

**Issue by lvzhekang** [apache/incubator-skywalking#2349]
Please answer these questions before submitting your issue.

- Why do you submit this issue?
- [x] Question or discussion
- [ ] Bug
- [ ] Requirement
- [ ] Feature or performance improvement

___
### Question
- What do you want to know?

___
### Bug
- Which version of SkyWalking, OS and JRE?

- Which company or project?

- What happen?
If possible, provide a way for reproducing the error. e.g. demo application, component version.

___
### Requirement or improvement
- Please describe about your requirements or improvement suggestions.

**Comment by lvzhekang** [comment]
2019-03-12 12:19:59,761 - org.apache.skywalking.oap.server.receiver.register.provider.handler.v6.grpc.ServiceInstancePingServiceHandler - 61 [grpc-default-executor-21] WARN  [] - Can't found service by service instance id from cache, service instance id is: 28
2019-03-12 12:19:59,799 - org.apache.skywalking.oap.server.core.register.service.ServiceInstanceInventoryRegister - 108 [grpc-default-executor-21] WARN  [] - Service instance 17 heartbeat, but not found in storage.
2019-03-12 12:19:59,800 - org.apache.skywalking.oap.server.receiver.register.provider.handler.v6.grpc.ServiceInstancePingServiceHandler - 61 [grpc-default-executor-21] WARN  [] - Can't found service by service instance id from cache, service instance id is: 17
2019-03-12 12:20:00,011 - org.apache.skywalking.oap.server.receiver.trace.provider.parser.SegmentParseV2 - 111 [grpc-default-executor-21] ERROR [] - null
java.lang.NullPointerException: null
	at org.apache.skywalking.oap.server.receiver.trace.provider.parser.standardization.SpanIdExchanger.exchange(SpanIdExchanger.java:119) ~[skywalking-trace-receiver-plugin-6.0.0-GA.jar:6.0.0-GA]
	at org.apache.skywalking.oap.server.receiver.trace.provider.parser.SegmentParseV2.preBuild(SegmentParseV2.java:146) ~[skywalking-trace-receiver-plugin-6.0.0-GA.jar:6.0.0-GA]
	at org.apache.skywalking.oap.server.receiver.trace.provider.parser.SegmentParseV2.parse(SegmentParseV2.java:89) [skywalking-trace-receiver-plugin-6.0.0-GA.jar:6.0.0-GA]
	at org.apache.skywalking.oap.server.receiver.trace.provider.parser.SegmentParseV2$Producer.send(SegmentParseV2.java:265) [skywalking-trace-receiver-plugin-6.0.0-GA.jar:6.0.0-GA]
	at org.apache.skywalking.oap.server.receiver.trace.provider.handler.v6.grpc.TraceSegmentReportServiceHandler$1.onNext(TraceSegmentReportServiceHandler.java:58) [skywalking-trace-receiver-plugin-6.0.0-GA.jar:6.0.0-GA]
	at org.apache.skywalking.oap.server.receiver.trace.provider.handler.v6.grpc.TraceSegmentReportServiceHandler$1.onNext(TraceSegmentReportServiceHandler.java:50) [skywalking-trace-receiver-plugin-6.0.0-GA.jar:6.0.0-GA]
	at io.grpc.stub.ServerCalls$StreamingServerCallHandler$StreamingServerCallListener.onMessage(ServerCalls.java:248) [grpc-stub-1.15.1.jar:1.15.1]
	at io.grpc.internal.ServerCallImpl$ServerStreamListenerImpl.messagesAvailable(ServerCallImpl.java:263) [grpc-core-1.15.1.jar:1.15.1]
	at io.grpc.internal.ServerImpl$JumpToApplicationThreadServerStreamListener$1MessagesAvailable.runInContext(ServerImpl.java:683) [grpc-core-1.15.1.jar:1.15.1]
	at io.grpc.internal.ContextRunnable.run(ContextRunnable.java:37) [grpc-core-1.15.1.jar:1.15.1]
	at io.grpc.internal.SerializingExecutor.run(SerializingExecutor.java:123) [grpc-core-1.15.1.jar:1.15.1]
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142) [?:1.8.0_121]
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617) [?:1.8.0_121]
	at java.lang.Thread.run(Thread.java:745) [?:1.8.0_121]
2019-03-12 12:20:00,014 - org.apache.skywalking.oap.server.receiver.trace.provider.parser.SegmentParseV2 - 111 [grpc-default-executor-21] ERROR [] - null
java.lang.NullPointerException: null
	at org.apache.skywalking.oap.server.receiver.trace.provider.parser.standardization.SpanIdExchanger.exchange(SpanIdExchanger.java:119) ~[skywalking-trace-receiver-plugin-6.0.0-GA.jar:6.0.0-GA]
	at org.apache.skywalking.oap.server.receiver.trace.provider.parser.SegmentParseV2.preBuild(SegmentParseV2.java:146) ~[skywalking-trace-receiver-plugin-6.0.0-GA.jar:6.0.0-GA]
	at org.apache.skywalking.oap.server.receiver.trace.provider.parser.SegmentParseV2.parse(SegmentParseV2.java:89) [skywalking-trace-receiver-plugin-6.0.0-GA.jar:6.0.0-GA]
	at org.apache.skywalking.oap.server.receiver.trace.provider.parser.SegmentParseV2$Producer.send(SegmentParseV2.java:265) [skywalking-trace-receiver-plugin-6.0.0-GA.jar:6.0.0-GA]
	at org.apache.skywalking.oap.server.receiver.trace.provider.handler.v6.grpc.TraceSegmentReportServiceHandler$1.onNext(TraceSegmentReportServiceHandler.java:58) [skywalking-trace-receiver-plugin-6.0.0-GA.jar:6.0.0-GA]
	at org.apache.skywalking.oap.server.receiver.trace.provider.handler.v6.grpc.TraceSegmentReportServiceHandler$1.onNext(TraceSegmentReportServiceHandler.java:50) [skywalking-trace-receiver-plugin-6.0.0-GA.jar:6.0.0-GA]
	at io.grpc.stub.ServerCalls$StreamingServerCallHandler$StreamingServerCallListener.onMessage(ServerCalls.java:248) [grpc-stub-1.15.1.jar:1.15.1]
	at io.grpc.internal.ServerCallImpl$ServerStreamListenerImpl.messagesAvailable(ServerCallImpl.java:263) [grpc-core-1.15.1.jar:1.15.1]
	at io.grpc.internal.ServerImpl$JumpToApplicationThreadServerStreamListener$1MessagesAvailable.runInContext(ServerImpl.java:683) [grpc-core-1.15.1.jar:1.15.1]
	at io.grpc.internal.ContextRunnable.run(ContextRunnable.java:37) [grpc-core-1.15.1.jar:1.15.1]
	at io.grpc.internal.SerializingExecutor.run(SerializingExecutor.java:123) [grpc-core-1.15.1.jar:1.15.1]
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142) [?:1.8.0_121]
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617) [?:1.8.0_121]
	at java.lang.Thread.run(Thread.java:745) [?:1.8.0_121]
2019-03-12 12:20:00,026 - org.apache.skywalking.oap.server.core.register.service.ServiceInstanceInventoryRegister - 108 [grpc-default-executor-21] WARN  [] - Service instance 22 heartbeat, but not found in storage.
2019-03-12 12:20:00,027 - org.apache.skywalking.oap.server.receiver.register.provider.handler.v6.grpc.ServiceInstancePingServiceHandler - 61 [grpc-default-executor-21] WARN  [] - Can't found service by service instance id from cache, service instance id is: 22
2019-03-12 12:20:00,469 - org.apache.skywalking.oap.server.core.register.service.ServiceInstanceInventoryRegister - 108 [grpc-default-executor-21] WARN  [] - Service instance 27 heartbeat, but not found in storage.
2019-03-12 12:20:00,470 - org.apache.skywalking.oap.server.receiver.register.provider.handler.v6.grpc.ServiceInstancePingServiceHandler - 61 [grpc-default-executor-21] WARN  [] - Can't found service by service instance id from cache, service instance id is: 27
2019-03-12 12:20:00,621 - org.apache.skywalking.oap.server.core.register.service.ServiceInstanceInventoryRegister - 108 [grpc-default-executor-21] WARN  [] - Service instance 32 heartbeat, but not found in storage.

**Comment by wu-sheng** [comment]
You reset the elasticsearch, so agent must reboot too.

**Comment by seasonouc** [comment]
![image](https://user-images.githubusercontent.com/5309752/59318241-e0096180-8cf8-11e9-9607-e49030bb2c95.png)
I use docker ,and change the config use h2,still have the problem

**Comment by urtop** [comment]
I have the same issues,using K8S

**Comment by wu-sheng** [comment]
There is nothing k8s or VM. That is caused by your storage deleted. So reboot the agent and delete trace-cache folder. There is pointless to say having an issue, but not follow the suggestions.

**Comment by monkeyAlwaysWin** [comment]
where is trace-cache folder
