### ISSUE TITLE
关于使用中的几个问题

### ISSUE THREAD

**Issue by lelence** [apache/incubator-skywalking#2376]
你好， 我在使用 `6.0.0-GA` 版本, 最下面是我的docker-compose.yml, 我想搭建一个多 `OAP`的 APM 环境,  发现了几个问题<br/>

1. 两个`OAP`的时候, 总会有一个报错的, 是不是 这里不可以对 `OAP` 做 高可用的配置, 或者是我的配置不对, 这里应该是执行重复了

> org.elasticsearch.client.ResponseException: method [PUT], host [http://elasticsearch:9200], URI [/all_heatmap_hour?master_timeout=30s&timeout=30s], status line [HTTP/1.1 400 Bad Request]
{"error":{"root_cause":[{"type":"resource_already_exists_exception","reason":"index [all_heatmap_hour/4n3lxsqIQUGiXOeJixPC2A] already exists","index_uuid":"4n3lxsqIQUGiXOeJixPC2A","index":"all_heatmap_hour"}],"type":"resource_already_exists_exception","reason":"index [all_heatmap_hour/4n3lxsqIQUGiXOeJixPC2A] already exists","index_uuid":"4n3lxsqIQUGiXOeJixPC2A","index":"all_heatmap_hour"},"status":400}

2. 如果有一个 `OAP` 宕机之后, `UI` 的 zuul + ribbon 总是 不能 及时响应, 总会出现下面的错误, 我也试着修改了相关参数, 还是会出现下面的情况

> com.netflix.zuul.exception.ZuulException: Forwarding error
	at org.springframework.cloud.netflix.zuul.filters.route.RibbonRoutingFilter.handleException(RibbonRoutingFilter.java:189)
	at java.lang.Thread.run(Thread.java:748)
Caused by: com.netflix.client.ClientException: null
	at com.netflix.client.AbstractLoadBalancerAwareClient.executeWithLoadBalancer(AbstractLoadBalancerAwareClient.java:118)
	... 67 common frames omitted
Caused by: java.lang.RuntimeException: org.apache.http.conn.HttpHostConnectException: Connect to oap1:12800 [oap1/172.27.0.4] failed: Connection refused (Connection refused)

3. 还有就是会出现下面的问题

> 2019-03-18 21:23:58,559 - org.apache.skywalking.oap.server.core.register.worker.RegisterRemoteWorker -26138 [DataCarrier.default.Consumser.0.Thread] ERROR [] - Index: 0, Size: 0
java.lang.IndexOutOfBoundsException: Index: 0, Size: 0
	at java.util.LinkedList.checkElementIndex(LinkedList.java:555) ~[?:1.8.0_181]
	at java.util.LinkedList.get(LinkedList.java:476) ~[?:1.8.0_181]
	at org.apache.skywalking.oap.server.core.remote.selector.ForeverFirstSelector.select(ForeverFirstSelector.java:37) ~[server-core-6.0.0-GA.jar:6.0.0-GA]
	at org.apache.skywalking.oap.server.core.remote.RemoteSenderService.send(RemoteSenderService.java:58) ~[server-core-6.0.0-GA.jar:6.0.0-GA]
	at org.apache.skywalking.oap.server.core.register.worker.RegisterRemoteWorker.in(RegisterRemoteWorker.java:47) ~[server-core-6.0.0-GA.jar:6.0.0-GA]
	at org.apache.skywalking.oap.server.core.register.worker.RegisterRemoteWorker.in(RegisterRemoteWorker.java:32) ~[server-core-6.0.0-GA.jar:6.0.0-GA]
	at java.util.HashMap$Values.forEach(HashMap.java:981) [?:1.8.0_181]

```xml
version: '3.3'
services:

  elasticsearch:
    image: wutang/elasticsearch-shanghai-zone:6.3.2
    container_name: apm-elasticsearch
    environment:
      - cluster.name=elasticsearch
      - xpack.security.enabled=false
    ports:
      - 9200:9200
    networks:
      - simple-net

  oap_zoo:
    image: zookeeper:3.5.4-beta
    container_name: amp-oap_zoo
    restart: always
    networks:
      - simple-net

  oap1:
    build:
      context: ../../apm-oap/
    image: apm-oap:1.0
    container_name: apm-oap-1
    restart: always
    depends_on:
      - oap_zoo
      - elasticsearch
    environment:
      - SW_STORAGE_ES_CLUSTER_NODES=elasticsearch:9200
      - SW_CORE_REST_HOST=oap1
      - SW_CORE_GRPC_HOST=oap1
      - SW_CLUSTER_ZK_HOST_PORT=oap_zoo:2181
    volumes:
      - ./build/config:/skywalking/config:ro
    networks:
      - simple-net

  oap2:
    build:
      context: ../../apm-oap/
    image: apm-oap:1.0
    container_name: apm-oap-2
    restart: always
    depends_on:
      - oap1
      - oap_zoo
      - elasticsearch
    environment:
      - SW_STORAGE_ES_CLUSTER_NODES=elasticsearch:9200
      - SW_CORE_REST_HOST=oap2
      - SW_CORE_GRPC_HOST=oap2
      - SW_CLUSTER_ZK_HOST_PORT=oap_zoo:2181
    volumes:
      - ./build/config:/skywalking/config:ro
    networks:
      - simple-net

  ui:
    build:
      context: ../../apm-ui/
    image: apm-ui:1.0
    container_name: apm-ui
    depends_on:
      - oap1
      - oap2
    restart: always
    ports:
      - 9730:8080
    environment:
      - zuul.retryable=true
      - ribbon.ConnectTimeout=250
      - ribbon.ReadTimeout=1000
      - ribbon.OkToRetryOnAllOperations=true
      - ribbon.MaxAutoRetriesNextServer=2
      - ribbon.MaxAutoRetries=1
  
      - collector.ribbon.listOfServers=oap1:12800,oap2:12800
    networks:
      - simple-net

volumes:
  agent-data:

networks:
  simple-net:
```

**Comment by wu-sheng** [comment]
English only.

docker-compose.yml should only be used for demo and preview. We recommend you to read our [k8s repo](https://github.com/apache/incubator-skywalking-kubernetes) to understand how oap work as the cluster.

How to deploy as a cluster, we provide a detailed document to guide, please read it.

**Comment by lelence** [comment]
Thanks
