### ISSUE TITLE
A question about IndexOutOfBoundsException 

### ISSUE THREAD

**Issue by Remember-Forever** [apache/incubator-skywalking#2378]
Please answer these questions before submitting your issue.

- Why do you submit this issue?
- [√ ] Question or discussion
- [ ] Bug
- [ ] Requirement
- [ ] Feature or performance improvement

I build skywalking and elasticsearch on openshift, and run a demo(springboot project) on my pc.
Then I try to find my endpoint on skywalking-ui, but the oap-server's log shows error, and ui can't get my project.
If I don't mount the oap-config, the endpoint will appear.

Skywalking version is 6.0.0-GA, and my jre is 1.8.0_161.

The log detail:

`2019-03-19 02:59:01,480 - org.apache.skywalking.oap.server.core.register.worker.RegisterRemoteWorker -1783846 [DataCarrier.default.Consumser.0.Thread] ERROR [] - Index: 0, Size: 0
java.lang.IndexOutOfBoundsException: Index: 0, Size: 0
at java.util.LinkedList.checkElementIndex(LinkedList.java:555) ~[?:1.8.0_181]
at java.util.LinkedList.get(LinkedList.java:476) ~[?:1.8.0_181]
at org.apache.skywalking.oap.server.core.remote.selector.ForeverFirstSelector.select(ForeverFirstSelector.java:37) ~[server-core-6.0.0-GA.jar:6.0.0-GA]
at org.apache.skywalking.oap.server.core.remote.RemoteSenderService.send(RemoteSenderService.java:58) ~[server-core-6.0.0-GA.jar:6.0.0-GA]
at org.apache.skywalking.oap.server.core.register.worker.RegisterRemoteWorker.in(RegisterRemoteWorker.java:47) ~[server-core-6.0.0-GA.jar:6.0.0-GA]
at org.apache.skywalking.oap.server.core.register.worker.RegisterRemoteWorker.in(RegisterRemoteWorker.java:32) ~[server-core-6.0.0-GA.jar:6.0.0-GA]
at java.util.HashMap$Values.forEach(HashMap.java:981) [?:1.8.0_181]
at org.apache.skywalking.oap.server.core.register.worker.RegisterDistinctWorker.onWork(RegisterDistinctWorker.java:64) [server-core-6.0.0-GA.jar:6.0.0-GA]
at org.apache.skywalking.oap.server.core.register.worker.RegisterDistinctWorker.access$100(RegisterDistinctWorker.java:32) [server-core-6.0.0-GA.jar:6.0.0-GA]
at org.apache.skywalking.oap.server.core.register.worker.RegisterDistinctWorker$AggregatorConsumer.consume(RegisterDistinctWorker.java:91) [server-core-6.0.0-GA.jar:6.0.0-GA]
at org.apache.skywalking.apm.commons.datacarrier.consumer.ConsumerThread.consume(ConsumerThread.java:101) [apm-datacarrier-6.0.0-GA.jar:6.0.0-GA]
at org.apache.skywalking.apm.commons.datacarrier.consumer.ConsumerThread.run(ConsumerThread.java:68) [apm-datacarrier-6.0.0-GA.jar:6.0.0-GA]`

**Comment by wu-sheng** [comment]
This log means, you somehow run oap in cluster mode, but cluster module implementor can't find the cluster inform. The reason is based on which cluster implementor, and whether is it compatible with its server side? Such as Zookeeper auth.

**Comment by Remember-Forever** [comment]
Auth? It seems never used in my skywalking environment.

**Comment by wu-sheng** [comment]
I don't it is related to auth or not. But im theory, your cluster module doesn't work well.

**Comment by Remember-Forever** [comment]
I resolve this problem when I rebuild my oap-server... -.-

But now I get another problem, es, oap and ui are all in CST timezone like 'Tue, 02 Apr 2019 14:05:37 +0800' while I use the command 'date -R'.

If I choose UTC on UI, trace will appear. And if I use Asia/shanghai, I need select the range earlier than 8h.

**Comment by wu-sheng** [comment]
Then your server still run in utc time. Not +8

**Comment by Remember-Forever** [comment]
Thx. I resolved it

**Comment by mark0614** [comment]
> 
> 
> I resolve this problem when I rebuild my oap-server... -.-
> 
> But now I get another problem, es, oap and ui are all in CST timezone like 'Tue, 02 Apr 2019 14:05:37 +0800' while I use the command 'date -R'.
> 
> If I choose UTC on UI, trace will appear. And if I use Asia/shanghai, I need select the range earlier than 8h.

I got the same problem, and I used docker-compose to deploy the elasticsearch oap and ui.  How did you solve this problem？
