### ISSUE TITLE
Exception while fetching data (/getApplicationTopology) : null

### ISSUE THREAD

**Issue by LiuZeng520** [apache/incubator-skywalking#2414]
Please answer these questions before submitting your issue.

- Why do you submit this issue?
org.apache.skywalking.apm.collector.analysis.segment.parser.provider.parser.SegmentParse -1623927 [grpc-default-executor-36] ERROR [] - null
java.lang.NullPointerException: null
2019-03-28 15:06:07,833 - org.apache.skywalking.apm.collector.analysis.worker.model.impl.MergePersistenceWorker -1624787 [pool-2-thread-1] ERROR [] - Received an instance heart beat message under instance id= 3123 , which doesn't exist.
org.apache.skywalking.apm.collector.core.UnexpectedException: Received an instance heart beat message under instance id= 3123 , which doesn't exist.
        at org.apache.skywalking.apm.collector.storage.es.dao.InstanceHeartBeatEsPersistenceDAO.prepareBatchInsert(InstanceHeartBeatEsPersistenceDAO.java:65) ~[collector-storage-es-provider-5.0.0-GA.jar:5.0.0-GA]
        at org.apache.skywalking.apm.collector.storage.es.dao.InstanceHeartBeatEsPersistenceDAO.prepareBatchInsert(InstanceHeartBeatEsPersistenceDAO.java:38) ~[collector-storage-es-provider-5.0.0-GA.jar:5.0.0-GA]
        at org.apache.skywalking.apm.collector.analysis.worker.model.impl.MergePersistenceWorker.lambda$prepareBatch$0(MergePersistenceWorker.java:63) ~[analysis-worker-model-5.0.0-GA.jar:5.0.0-GA]
        at java.util.LinkedHashMap.forEach(LinkedHashMap.java:684) ~[?:1.8.0_191]
        at org.apache.skywalking.apm.collector.analysis.worker.model.impl.MergePersistenceWorker.prepareBatch(MergePersistenceWorker.java:50) ~[analysis-worker-model-5.0.0-GA.jar:5.0.0-GA]
        at org.apache.skywalking.apm.collector.analysis.worker.model.impl.MergePersistenceWorker.prepareBatch(MergePersistenceWorker.java:33) ~[analysis-worker-model-5.0.0-GA.jar:5.0.0-GA]
        at org.apache.skywalking.apm.collector.analysis.worker.model.impl.PersistenceWorker.buildBatchCollection(PersistenceWorker.java:91) ~[analysis-worker-model-5.0.0-GA.jar:5.0.0-GA]
        at org.apache.skywalking.apm.collector.analysis.worker.timer.PersistenceTimer.lambda$extractDataAndSave$2(PersistenceTimer.java:78) ~[analysis-worker-model-5.0.0-GA.jar:5.0.0-GA]
        at java.lang.Iterable.forEach(Iterable.java:75) ~[?:1.8.0_191]
        at org.apache.skywalking.apm.collector.analysis.worker.timer.PersistenceTimer.extractDataAndSave(PersistenceTimer.java:72) ~[analysis-worker-model-5.0.0-GA.jar:5.0.0-GA]
        at org.apache.skywalking.apm.collector.analysis.worker.timer.PersistenceTimer.lambda$start$0(PersistenceTimer.java:56) ~[analysis-worker-model-5.0.0-GA.jar:5.0.0-GA]
        at org.apache.skywalking.apm.util.RunnableWithExceptionProtection.run(RunnableWithExceptionProtection.java:36) [apm-util-5.0.0-GA.jar:5.0.0-GA]
        at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511) [?:1.8.0_191]
        at java.util.concurrent.FutureTask.runAndReset(FutureTask.java:308) [?:1.8.0_191]
        at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.access$301(ScheduledThreadPoolExecutor.java:180) [?:1.8.0_191]
        at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.run(ScheduledThreadPoolExecutor.java:294) [?:1.8.0_191]
        at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149) [?:1.8.0_191]
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624) [?:1.8.0_191]
        at java.lang.Thread.run(Thread.java:748) [?:1.8.0_191]

**Comment by LiuZeng520** [comment]
客户端报错：
Caused by: org.apache.skywalking.apm.dependencies.io.netty.channel.AbstractChannel$AnnotatedConnectException: Connection refused: /$IP:11800
