### ISSUE TITLE
print stack trace Continuously: uri [/network_address_inventory/type] and method [GET], allowed: [POST]"

### ISSUE THREAD

**Issue by ldcsaa** [apache/incubator-skywalking#2417]
version: skywalking-apm-incubating-6.0.0-GA 

My storage is elasticsearch 6.5.4  

while running, skywalking-oap-server.log print the following stack trace log continuously:  

`2019-03-28 20:40:27,823 - org.apache.skywalking.oap.server.core.register.worker.RegisterPersistentWorker - 102 [DataCarrier.IndicatorPersistentWorker.network_address_inventory.Consumser.0.Thread] ERROR [] - Elasticsearch exception [type=exception, reason=Incorrect HTTP method for uri [/network_address_inventory/type] and method [GET], allowed: [POST]]
org.elasticsearch.ElasticsearchStatusException: Elasticsearch exception [type=exception, reason=Incorrect HTTP method for uri [/network_address_inventory/type] and method [GET], allowed: [POST]]
	at org.elasticsearch.rest.BytesRestResponse.errorFromXContent(BytesRestResponse.java:177) ~[elasticsearch-6.3.2.jar:6.3.2]
	at org.elasticsearch.client.RestHighLevelClient.parseEntity(RestHighLevelClient.java:653) ~[elasticsearch-rest-high-level-client-6.3.2.jar:6.3.2]
	at org.elasticsearch.client.RestHighLevelClient.parseResponseException(RestHighLevelClient.java:628) ~[elasticsearch-rest-high-level-client-6.3.2.jar:6.3.2]
	at org.elasticsearch.client.RestHighLevelClient.performRequest(RestHighLevelClient.java:535) ~[elasticsearch-rest-high-level-client-6.3.2.jar:6.3.2]
	at org.elasticsearch.client.RestHighLevelClient.performRequestAndParseEntity(RestHighLevelClient.java:508) ~[elasticsearch-rest-high-level-client-6.3.2.jar:6.3.2]
	at org.elasticsearch.client.RestHighLevelClient.get(RestHighLevelClient.java:293) ~[elasticsearch-rest-high-level-client-6.3.2.jar:6.3.2]
	at org.apache.skywalking.oap.server.library.client.elasticsearch.ElasticSearchClient.get(ElasticSearchClient.java:146) ~[library-client-6.0.0-GA.jar:6.0.0-GA]
	at org.apache.skywalking.oap.server.storage.plugin.elasticsearch.base.RegisterEsDAO.get(RegisterEsDAO.java:45) ~[storage-elasticsearch-plugin-6.0.0-GA.jar:6.0.0-GA]
	at org.apache.skywalking.oap.server.core.register.worker.RegisterPersistentWorker.lambda$onWork$0(RegisterPersistentWorker.java:74) ~[server-core-6.0.0-GA.jar:6.0.0-GA]
	at java.util.HashMap$Values.forEach(HashMap.java:972) [?:1.8.0_74]
	at org.apache.skywalking.oap.server.core.register.worker.RegisterPersistentWorker.onWork(RegisterPersistentWorker.java:72) [server-core-6.0.0-GA.jar:6.0.0-GA]
	at org.apache.skywalking.oap.server.core.register.worker.RegisterPersistentWorker.access$100(RegisterPersistentWorker.java:36) [server-core-6.0.0-GA.jar:6.0.0-GA]
	at org.apache.skywalking.oap.server.core.register.worker.RegisterPersistentWorker$PersistentConsumer.consume(RegisterPersistentWorker.java:131) [server-core-6.0.0-GA.jar:6.0.0-GA]
	at org.apache.skywalking.apm.commons.datacarrier.consumer.ConsumerThread.consume(ConsumerThread.java:101) [apm-datacarrier-6.0.0-GA.jar:6.0.0-GA]
	at org.apache.skywalking.apm.commons.datacarrier.consumer.ConsumerThread.run(ConsumerThread.java:68) [apm-datacarrier-6.0.0-GA.jar:6.0.0-GA]
	Suppressed: org.elasticsearch.client.ResponseException: method [GET], host [http://elk.client.kaka.cn:9200], URI [/network_address_inventory/type], status line [HTTP/1.1 405 Method Not Allowed]
{"error":"Incorrect HTTP method for uri [/network_address_inventory/type] and method [GET], allowed: [POST]","status":405}
		at org.elasticsearch.client.RestClient$SyncResponseListener.get(RestClient.java:705) ~[elasticsearch-rest-client-6.3.2.jar:6.3.2]
		at org.elasticsearch.client.RestClient.performRequest(RestClient.java:235) ~[elasticsearch-rest-client-6.3.2.jar:6.3.2]
		at org.elasticsearch.client.RestClient.performRequest(RestClient.java:198) ~[elasticsearch-rest-client-6.3.2.jar:6.3.2]
		at org.elasticsearch.client.RestHighLevelClient.performRequest(RestHighLevelClient.java:522) ~[elasticsearch-rest-high-level-client-6.3.2.jar:6.3.2]
		at org.elasticsearch.client.RestHighLevelClient.performRequestAndParseEntity(RestHighLevelClient.java:508) ~[elasticsearch-rest-high-level-client-6.3.2.jar:6.3.2]
		at org.elasticsearch.client.RestHighLevelClient.get(RestHighLevelClient.java:293) ~[elasticsearch-rest-high-level-client-6.3.2.jar:6.3.2]
		at org.apache.skywalking.oap.server.library.client.elasticsearch.ElasticSearchClient.get(ElasticSearchClient.java:146) ~[library-client-6.0.0-GA.jar:6.0.0-GA]
		at org.apache.skywalking.oap.server.storage.plugin.elasticsearch.base.RegisterEsDAO.get(RegisterEsDAO.java:45) ~[storage-elasticsearch-plugin-6.0.0-GA.jar:6.0.0-GA]
		at org.apache.skywalking.oap.server.core.register.worker.RegisterPersistentWorker.lambda$onWork$0(RegisterPersistentWorker.java:74) ~[server-core-6.0.0-GA.jar:6.0.0-GA]
		at java.util.HashMap$Values.forEach(HashMap.java:972) [?:1.8.0_74]
		at org.apache.skywalking.oap.server.core.register.worker.RegisterPersistentWorker.onWork(RegisterPersistentWorker.java:72) [server-core-6.0.0-GA.jar:6.0.0-GA]
		at org.apache.skywalking.oap.server.core.register.worker.RegisterPersistentWorker.access$100(RegisterPersistentWorker.java:36) [server-core-6.0.0-GA.jar:6.0.0-GA]
		at org.apache.skywalking.oap.server.core.register.worker.RegisterPersistentWorker$PersistentConsumer.consume(RegisterPersistentWorker.java:131) [server-core-6.0.0-GA.jar:6.0.0-GA]
		at org.apache.skywalking.apm.commons.datacarrier.consumer.ConsumerThread.consume(ConsumerThread.java:101) [apm-datacarrier-6.0.0-GA.jar:6.0.0-GA]
		at org.apache.skywalking.apm.commons.datacarrier.consumer.ConsumerThread.run(ConsumerThread.java:68) [apm-datacarrier-6.0.0-GA.jar:6.0.0-GA]
	Caused by: org.elasticsearch.client.ResponseException: method [GET], host [http://elk.client.kaka.cn:9200], URI [/network_address_inventory/type], status line [HTTP/1.1 405 Method Not Allowed]
{"error":"Incorrect HTTP method for uri [/network_address_inventory/type] and method [GET], allowed: [POST]","status":405}
		at org.elasticsearch.client.RestClient$1.completed(RestClient.java:377) ~[elasticsearch-rest-client-6.3.2.jar:6.3.2]
		at org.elasticsearch.client.RestClient$1.completed(RestClient.java:366) ~[elasticsearch-rest-client-6.3.2.jar:6.3.2]
		at org.apache.http.concurrent.BasicFuture.completed(BasicFuture.java:119) ~[httpcore-4.4.5.jar:4.4.5]
		at org.apache.http.impl.nio.client.DefaultClientExchangeHandlerImpl.responseCompleted(DefaultClientExchangeHandlerImpl.java:177) ~[httpasyncclient-4.1.2.jar:4.1.2]
		at org.apache.http.nio.protocol.HttpAsyncRequestExecutor.processResponse(HttpAsyncRequestExecutor.java:436) ~[httpcore-nio-4.4.5.jar:4.4.5]
		at org.apache.http.nio.protocol.HttpAsyncRequestExecutor.inputReady(HttpAsyncRequestExecutor.java:326) ~[httpcore-nio-4.4.5.jar:4.4.5]
		at org.apache.http.impl.nio.DefaultNHttpClientConnection.consumeInput(DefaultNHttpClientConnection.java:265) ~[httpcore-nio-4.4.5.jar:4.4.5]
		at org.apache.http.impl.nio.client.InternalIODispatch.onInputReady(InternalIODispatch.java:81) ~[httpasyncclient-4.1.2.jar:4.1.2]
		at org.apache.http.impl.nio.client.InternalIODispatch.onInputReady(InternalIODispatch.java:39) ~[httpasyncclient-4.1.2.jar:4.1.2]
		at org.apache.http.impl.nio.reactor.AbstractIODispatch.inputReady(AbstractIODispatch.java:114) ~[httpcore-nio-4.4.5.jar:4.4.5]
		at org.apache.http.impl.nio.reactor.BaseIOReactor.readable(BaseIOReactor.java:162) ~[httpcore-nio-4.4.5.jar:4.4.5]
		at org.apache.http.impl.nio.reactor.AbstractIOReactor.processEvent(AbstractIOReactor.java:337) ~[httpcore-nio-4.4.5.jar:4.4.5]
		at org.apache.http.impl.nio.reactor.AbstractIOReactor.processEvents(AbstractIOReactor.java:315) ~[httpcore-nio-4.4.5.jar:4.4.5]
		at org.apache.http.impl.nio.reactor.AbstractIOReactor.execute(AbstractIOReactor.java:276) ~[httpcore-nio-4.4.5.jar:4.4.5]
		at org.apache.http.impl.nio.reactor.BaseIOReactor.execute(BaseIOReactor.java:104) ~[httpcore-nio-4.4.5.jar:4.4.5]
		at org.apache.http.impl.nio.reactor.AbstractMultiworkerIOReactor$Worker.run(AbstractMultiworkerIOReactor.java:588) ~[httpcore-nio-4.4.5.jar:4.4.5]
		at java.lang.Thread.run(Thread.java:745) ~[?:1.8.0_74]
`

**Comment by wu-sheng** [comment]
This is a simple ElasticSearch exception, `ElasticsearchStatusException`.

**Comment by kevinLuan** [comment]
I have the same problem，This is not an ES problem。
Look at this method code：
```java
//When indexName is: [network_address_inventory], the id is always passed empty, causing the es to report an error
public GetResponse get(String indexName, String id) throws IOException {
        indexName = formatIndexName(indexName);
        GetRequest request = new GetRequest(indexName, TYPE, id);
        return client.get(request);
    }
```
Skywalking version: 6.0.0-alpha, 6.0.0-ga both have this problem
@wu-sheng

**Comment by wu-sheng** [comment]
We have nearly 100 users in product environment, connecting elasticsearch. So make sure you are using right version, and don't open auth(such as xpack, basic auth)

**Comment by kevinLuan** [comment]
Elasticsearch 6.3.2 and 6.7.1 versions have this imagined.
And no ES auth is turned on.

**Comment by ldcsaa** [comment]
6.1.0 has the same problem !!!
