### ISSUE TITLE
print error while startup: "java.lang.ArithmeticException: / by zero"

### ISSUE THREAD

**Issue by ldcsaa** [apache/incubator-skywalking#2418]
version: skywalking-apm-incubating-6.0.0-GA

My storage is elasticsearch 6.5.4

`2019-03-28 18:34:22,241 - org.apache.skywalking.oap.server.core.analysis.worker.IndicatorRemoteWorker - 53 [DataCarrier.IndicatorAggregateWorker.instance_jvm_memory_noheap_max.Consumser.0.Thread] ERROR [] - / by zero
java.lang.ArithmeticException: / by zero
        at org.apache.skywalking.oap.server.core.remote.selector.HashCodeSelector.select(HashCodeSelector.java:32) ~[server-core-6.0.0-GA.jar:6.0.0-GA]
        at org.apache.skywalking.oap.server.core.remote.RemoteSenderService.send(RemoteSenderService.java:50) ~[server-core-6.0.0-GA.jar:6.0.0-GA]
        at org.apache.skywalking.oap.server.core.analysis.worker.IndicatorRemoteWorker.in(IndicatorRemoteWorker.java:51) ~[server-core-6.0.0-GA.jar:6.0.0-GA]
        at org.apache.skywalking.oap.server.core.analysis.worker.IndicatorRemoteWorker.in(IndicatorRemoteWorker.java:33) ~[server-core-6.0.0-GA.jar:6.0.0-GA]
        at org.apache.skywalking.oap.server.core.analysis.worker.IndicatorAggregateWorker.lambda$sendToNext$0(IndicatorAggregateWorker.java:93) ~[server-core-6.0.0-GA.jar:6.0.0-GA]
        at java.util.HashMap$Values.forEach(HashMap.java:972) [?:1.8.0_74]
        at org.apache.skywalking.oap.server.core.analysis.worker.IndicatorAggregateWorker.sendToNext(IndicatorAggregateWorker.java:88) [server-core-6.0.0-GA.jar:6.0.0-GA]
        at org.apache.skywalking.oap.server.core.analysis.worker.IndicatorAggregateWorker.onWork(IndicatorAggregateWorker.java:73) [server-core-6.0.0-GA.jar:6.0.0-GA]
        at org.apache.skywalking.oap.server.core.analysis.worker.IndicatorAggregateWorker.access$100(IndicatorAggregateWorker.java:38) [server-core-6.0.0-GA.jar:6.0.0-GA]
        at org.apache.skywalking.oap.server.core.analysis.worker.IndicatorAggregateWorker$AggregatorConsumer.consume(IndicatorAggregateWorker.java:131) [server-core-6.0.0-GA.jar:6.0.0-GA]
        at org.apache.skywalking.apm.commons.datacarrier.consumer.ConsumerThread.consume(ConsumerThread.java:101) [apm-datacarrier-6.0.0-GA.jar:6.0.0-GA]
        at org.apache.skywalking.apm.commons.datacarrier.consumer.ConsumerThread.run(ConsumerThread.java:68) [apm-datacarrier-6.0.0-GA.jar:6.0.0-GA]
2019-03-28 18:34:22,254 - org.apache.skywalking.oap.server.core.analysis.worker.IndicatorRemoteWorker - 53 [DataCarrier.IndicatorAggregateWorker.instance_jvm_memory_noheap_max.Consumser.0.Thread] ERROR [] - / by zero
java.lang.ArithmeticException: / by zero
        at org.apache.skywalking.oap.server.core.remote.selector.HashCodeSelector.select(HashCodeSelector.java:32) ~[server-core-6.0.0-GA.jar:6.0.0-GA]
        at org.apache.skywalking.oap.server.core.remote.RemoteSenderService.send(RemoteSenderService.java:50) ~[server-core-6.0.0-GA.jar:6.0.0-GA]
        at org.apache.skywalking.oap.server.core.analysis.worker.IndicatorRemoteWorker.in(IndicatorRemoteWorker.java:51) ~[server-core-6.0.0-GA.jar:6.0.0-GA]
        at org.apache.skywalking.oap.server.core.analysis.worker.IndicatorRemoteWorker.in(IndicatorRemoteWorker.java:33) ~[server-core-6.0.0-GA.jar:6.0.0-GA]
        at org.apache.skywalking.oap.server.core.analysis.worker.IndicatorAggregateWorker.lambda$sendToNext$0(IndicatorAggregateWorker.java:93) ~[server-core-6.0.0-GA.jar:6.0.0-GA]
        at java.util.HashMap$Values.forEach(HashMap.java:972) [?:1.8.0_74]
        at org.apache.skywalking.oap.server.core.analysis.worker.IndicatorAggregateWorker.sendToNext(IndicatorAggregateWorker.java:88) [server-core-6.0.0-GA.jar:6.0.0-GA]
        at org.apache.skywalking.oap.server.core.analysis.worker.IndicatorAggregateWorker.onWork(IndicatorAggregateWorker.java:73) [server-core-6.0.0-GA.jar:6.0.0-GA]
        at org.apache.skywalking.oap.server.core.analysis.worker.IndicatorAggregateWorker.access$100(IndicatorAggregateWorker.java:38) [server-core-6.0.0-GA.jar:6.0.0-GA]
        at org.apache.skywalking.oap.server.core.analysis.worker.IndicatorAggregateWorker$AggregatorConsumer.consume(IndicatorAggregateWorker.java:131) [server-core-6.0.0-GA.jar:6.0.0-GA]
        at org.apache.skywalking.apm.commons.datacarrier.consumer.ConsumerThread.consume(ConsumerThread.java:101) [apm-datacarrier-6.0.0-GA.jar:6.0.0-GA]
        at org.apache.skywalking.apm.commons.datacarrier.consumer.ConsumerThread.run(ConsumerThread.java:68) [apm-datacarrier-6.0.0-GA.jar:6.0.0-GA]
`

**Comment by wu-sheng** [comment]
> org.apache.skywalking.oap.server.core.remote.selector.HashCodeSelector.select(HashCodeSelector.java:32) ~[server-core-6.0.0-GA.jar:6.0.0-GA] at 

From here, I am assuming your cluster management is not working well.
