### ISSUE TITLE
oap 部署在k8s 内部，使用集群方式部署异常

### ISSUE THREAD

**Issue by linliaoy** [apache/incubator-skywalking#2435]
Please answer these questions before submitting your issue.

- Why do you submit this issue?
- [ ] Question or discussion
- [ ] Bug
- [ ] Requirement
- [ ] Feature or performance improvement

___
### Question
在k8s 集群内部搭建oap，使用k8s 管理集群方式，使用standlone 方式部署没有问题。
配置是按照文档6.0.0-GA，不一样的配置如下：
application.yml: |-
    cluster:
      kubernetes:
        watchTimeoutSeconds: 60
        labelSelector: app=oap
        uidEnvName: SKYWALKING_COLLECTOR_UID
    core:
      default:
        role: Aggregator

oap报错信息
2019-04-02 07:41:30,435 - org.apache.skywalking.oap.server.core.analysis.worker.IndicatorRemoteWorker -56226 [DataCarrier.IndicatorAggregateWorker.instance_jvm_cpu.Consumser.0.Thread] ERROR [] - / by zero
java.lang.ArithmeticException: / by zero
	at org.apache.skywalking.oap.server.core.remote.selector.HashCodeSelector.select(HashCodeSelector.java:32) ~[server-core-6.0.0-GA.jar:6.0.0-GA]
	at org.apache.skywalking.oap.server.core.remote.RemoteSenderService.send(RemoteSenderService.java:50) ~[server-core-6.0.0-GA.jar:6.0.0-GA]
	at org.apache.skywalking.oap.server.core.analysis.worker.IndicatorRemoteWorker.in(IndicatorRemoteWorker.java:51) ~[server-core-6.0.0-GA.jar:6.0.0-GA]
	at org.apache.skywalking.oap.server.core.analysis.worker.IndicatorRemoteWorker.in(IndicatorRemoteWorker.java:33) ~[server-core-6.0.0-GA.jar:6.0.0-GA]
	at org.apache.skywalking.oap.server.core.analysis.worker.IndicatorAggregateWorker.lambda$sendToNext$0(IndicatorAggregateWorker.java:93) ~[server-core-6.0.0-GA.jar:6.0.0-GA]
	at java.util.HashMap$Values.forEach(HashMap.java:981) [?:1.8.0_181]
	at org.apache.skywalking.oap.server.core.analysis.worker.IndicatorAggregateWorker.sendToNext(IndicatorAggregateWorker.java:88) [server-core-6.0.0-GA.jar:6.0.0-GA]
	at org.apache.skywalking.oap.server.core.analysis.worker.IndicatorAggregateWorker.onWork(IndicatorAggregateWorker.java:73) [server-core-6.0.0-GA.jar:6.0.0-GA]
	at org.apache.skywalking.oap.server.core.analysis.worker.IndicatorAggregateWorker.access$100(IndicatorAggregateWorker.java:38) [server-core-6.0.0-GA.jar:6.0.0-GA]
	at org.apache.skywalking.oap.server.core.analysis.worker.IndicatorAggregateWorker$AggregatorConsumer.consume(IndicatorAggregateWorker.java:131) [server-core-6.0.0-GA.jar:6.0.0-GA]
	at org.apache.skywalking.apm.commons.datacarrier.consumer.ConsumerThread.consume(ConsumerThread.java:101) [apm-datacarrier-6.0.0-GA.jar:6.0.0-GA]
	at org.apache.skywalking.apm.commons.datacarrier.consumer.ConsumerThread.run(ConsumerThread.java:68) [apm-datacarrier-6.0.0-GA.jar:6.0.0-GA]

**Comment by wu-sheng** [comment]
English only, please. Which cluster management do you use? If k8s, then, do you have API server access right?

**Comment by linliaoy** [comment]
I the correct use of 00 - rbac. Yml, but I use the namespace is the default, the other is to operate according to the document (https://github.com/apache/incubator-skywalking-kubernetes).

**Comment by wu-sheng** [comment]
If you want to understand the mode, you need to understand how skywalking cluster runs. The config we provided is only for `Mixed` mode.
