### ISSUE TITLE
cluster module exist 2 providers

### ISSUE THREAD

**Issue by LiuZeng520** [apache/incubator-skywalking#2452]
Exception in thread "main" org.apache.skywalking.oap.server.library.module.DuplicateProviderException: cluster module exist 2 providers
        at org.apache.skywalking.oap.server.library.module.ModuleDefine.provider(ModuleDefine.java:142)
        at org.apache.skywalking.oap.server.library.module.ModuleDefine.provider(ModuleDefine.java:30)
        at org.apache.skywalking.oap.server.core.CoreModuleProvider.notifyAfterCompleted(CoreModuleProvider.java:169)
        at org.apache.skywalking.oap.server.library.module.BootstrapFlow.notifyAfterCompleted(BootstrapFlow.java:63)
        at org.apache.skywalking.oap.server.library.module.ModuleManager.init(ModuleManager.java:66)
        at org.apache.skywalking.oap.server.starter.OAPServerStartUp.main(OAPServerStartUp.java:43)

**Comment by LiuZeng520** [comment]
org.apache.skywalking.oap.server.core.remote.client.RemoteClientManager - 110 [pool-5-thread-1] ERROR [] - cluster module exist 2 providers
org.apache.skywalking.oap.server.library.module.DuplicateProviderException: cluster module exist 2 providers
        at org.apache.skywalking.oap.server.library.module.ModuleDefine.provider(ModuleDefine.java:142) ~[library-module-6.0.0-GA.jar:6.0.0-GA]
        at org.apache.skywalking.oap.server.library.module.ModuleDefine.provider(ModuleDefine.java:30) ~[library-module-6.0.0-GA.jar:6.0.0-GA]
        at org.apache.skywalking.oap.server.core.remote.client.RemoteClientManager.refresh(RemoteClientManager.java:74) ~[server-core-6.0.0-GA.jar:6.0.0-GA]

**Comment by LiuZeng520** [comment]
请一下这个问题怎么解决

**Comment by LiuZeng520** [comment]
请教一下这个问题怎么解决

**Comment by LiuZeng520** [comment]
Above is oap.log Error Information . How to Solve the Problem？

**Comment by wu-sheng** [comment]
I think our document has told what is module and what is providor. You open two providor in yaml. which cause this issue. In your log, it says, two providors in cluster module. You need to check the yml.

If you don't know what is provider, read this https://github.com/apache/incubator-skywalking/blob/master/docs/en/setup/backend/backend-setup.md#applicationyml

**Comment by LiuZeng520** [comment]
It works. Thank you very much.
