### ISSUE TITLE
class[class io.undertow.server.Connectors] after static method[executeRootHandler] intercept failure:null 

### ISSUE THREAD

**Issue by srddrs** [apache/incubator-skywalking#2467]
Please answer these questions before submitting your issue.

Why do you submit this issue?
  Question or discussion
  Bug
  Requirement
  Feature or performance improvement
Question
Bug
Which version of SkyWalking, OS and JRE?
skywalking 6.0.0-GA, linux,, java1.8

Which company or project?

What happen
DEBUG 2019-04-10 05:13:04:220 TraceIgnoreExtendService :  operationName : /actuator/prometheus Ignore tracking 
DEBUG 2019-04-10 05:13:04:289 TraceIgnoreExtendService :  operationName : /actuator/prometheus Ignore tracking 
DEBUG 2019-04-10 05:13:04:927 ServiceAndEndpointRegisterClient :  ServiceAndEndpointRegisterClient running, status:CONNECTED. 
DEBUG 2019-04-10 05:13:05:685 GRPCChannelManager :  Selected collector grpc service running, reconnect:false. 
ERROR 2019-04-10 05:13:05:773 StaticMethodsInter :  class[class io.undertow.server.Connectors] after static method[executeRootHandler] intercept failure:null 
java.lang.NullPointerException
	at org.apache.skywalking.apm.agent.core.context.ContextManager.activeSpan(ContextManager.java:156)
	at org.apache.skywalking.apm.plugin.undertow.v2x.ExecuteRootHandlerInterceptor.afterMethod(ExecuteRootHandlerInterceptor.java:63)
	at org.apache.skywalking.apm.agent.core.plugin.interceptor.enhance.StaticMethodsInter.intercept(StaticMethodsInter.java:97)
	at io.undertow.server.Connectors.executeRootHandler(Connectors.java)
	at io.undertow.server.HttpServerExchange$1.run(HttpServerExchange.java:830)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
	at java.lang.Thread.run(Thread.java:748)

**Comment by wu-sheng** [comment]
We may need a demo to reproduce the issue
