### ISSUE TITLE
receiver.trace.provider.parser.SegmentParseV2 NullPointerException

### ISSUE THREAD

**Issue by movetocloud** [apache/incubator-skywalking#2476]
Please answer these questions before submitting your issue.

- Why do you submit this issue?
- [] Bug

___
### Bug
- Which version of SkyWalking, OS and JRE?
6.0.0-GA，Centos7.4  JRE1.8.0_201

- Which company or project?

- What happen?
If possible, provide a way for reproducing the error. e.g. demo application, component version.

2019-04-12 09:27:36,520 - org.apache.skywalking.oap.server.core.register.service.ServiceInstanceInventoryRegister - 108 [grpc-default-executor-5] WARN  [] - Service instance 53 heartbeat, but not found in storage.
2019-04-12 09:27:36,521 - org.apache.skywalking.oap.server.receiver.register.provider.handler.v6.grpc.ServiceInstancePingServiceHandler - 61 [grpc-default-executor-5] WARN  [] - Can't found service by service instance id from cache, service instance id is: 53
2019-04-12 09:27:36,523 - org.apache.skywalking.oap.server.receiver.trace.provider.parser.SegmentParseV2 - 111 [grpc-default-executor-7] ERROR [] - null
java.lang.NullPointerException: null
	at org.apache.skywalking.oap.server.receiver.trace.provider.parser.standardization.SpanIdExchanger.exchange(SpanIdExchanger.java:115) ~[skywalking-trace-receiver-plugin-6.0.0-GA.jar:6.0.0-GA]
	at org.apache.skywalking.oap.server.receiver.trace.provider.parser.SegmentParseV2.preBuild(SegmentParseV2.java:146) ~[skywalking-trace-receiver-plugin-6.0.0-GA.jar:6.0.0-GA]
	at org.apache.skywalking.oap.server.receiver.trace.provider.parser.SegmentParseV2.parse(SegmentParseV2.java:89) [skywalking-trace-receiver-plugin-6.0.0-GA.jar:6.0.0-GA]
	at org.apache.skywalking.oap.server.receiver.trace.provider.parser.SegmentParseV2$Producer.send(SegmentParseV2.java:265) [skywalking-trace-receiver-plugin-6.0.0-GA.jar:6.0.0-GA]
	at org.apache.skywalking.oap.server.receiver.trace.provider.handler.v6.grpc.TraceSegmentReportServiceHandler$1.onNext(TraceSegmentReportServiceHandler.java:58) [skywalking-trace-receiver-plugin-6.0.0-GA.jar:6.0.0-GA]
	at org.apache.skywalking.oap.server.receiver.trace.provider.handler.v6.grpc.TraceSegmentReportServiceHandler$1.onNext(TraceSegmentReportServiceHandler.java:50) [skywalking-trace-receiver-plugin-6.0.0-GA.jar:6.0.0-GA]
	at io.grpc.stub.ServerCalls$StreamingServerCallHandler$StreamingServerCallListener.onMessage(ServerCalls.java:248) [grpc-stub-1.15.1.jar:1.15.1]
	at io.grpc.internal.ServerCallImpl$ServerStreamListenerImpl.messagesAvailable(ServerCallImpl.java:263) [grpc-core-1.15.1.jar:1.15.1]
	at io.grpc.internal.ServerImpl$JumpToApplicationThreadServerStreamListener$1MessagesAvailable.runInContext(ServerImpl.java:683) [grpc-core-1.15.1.jar:1.15.1]
	at io.grpc.internal.ContextRunnable.run(ContextRunnable.java:37) [grpc-core-1.15.1.jar:1.15.1]
	at io.grpc.internal.SerializingExecutor.run(SerializingExecutor.java:123) [grpc-core-1.15.1.jar:1.15.1]
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149) [?:1.8.0_201]
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624) [?:1.8.0_201]

___
### Requirement or improvement
- Please describe about your requirements or improvement suggestions.

**Comment by wu-sheng** [comment]
The log is clear.
> org.apache.skywalking.oap.server.core.register.service.ServiceInstanceInventoryRegister - 108 [grpc-default-executor-5] WARN [] - Service instance 53 heartbeat, but not found in storage.

The data has been removed by someone from the database.

**Comment by movetocloud** [comment]
ok,we have changed the storage from h2 to es. 
dose restart the agent can fixs this error?
