### ISSUE TITLE
[Agent] Custom plugin fails

### ISSUE THREAD

**Issue by suxiaoyong** [apache/incubator-skywalking#687]
基于v3.2.6新开发了一个插件，根据正则表达式匹配类名，并trace所有方法。

在enhance class 时报下面错误，目前看起来跟目标类无关，应该是我代码的问题，麻烦帮我看看是哪里的问题。

代码见附件
```
ERROR 2017-12-16 17:54:58 SkyWalkingAgent :  Enhance class com.operations.sessionmanager.AuthTokenRequestOperation error. 
java.lang.IllegalArgumentException: Cannot resolve ambiguous delegation of public abstract java.lang.Object org.skywalking.apm.agent.core.plugin.interceptor.enhance.EnhancedInstance.getSkyWalkingDynamicField() to org.skywalking.apm.dependencies.net.bytebuddy.implementation.bind.MethodDelegationBinder$MethodBinding$Builder$Build@e577ee67 or org.skywalking.apm.dependencies.net.bytebuddy.implementation.bind.MethodDelegationBinder$MethodBinding$Builder$Build@74c4a417
        at org.skywalking.apm.dependencies.net.bytebuddy.implementation.bind.MethodDelegationBinder$BindingResolver$Default.doResolve(MethodDelegationBinder.java:604)
        at org.skywalking.apm.dependencies.net.bytebuddy.implementation.bind.MethodDelegationBinder$BindingResolver$Default.resolve(MethodDelegationBinder.java:553)
        at org.skywalking.apm.dependencies.net.bytebuddy.implementation.bind.MethodDelegationBinder$Processor.bind(MethodDelegationBinder.java:1028)
        at org.skywalking.apm.dependencies.net.bytebuddy.implementation.MethodDelegation$Appender.apply(MethodDelegation.java:1051)
        at org.skywalking.apm.dependencies.net.bytebuddy.dynamic.scaffold.TypeWriter$MethodPool$Record$ForDefinedMethod$WithBody.applyCode(TypeWriter.java:620)
        at org.skywalking.apm.dependencies.net.bytebuddy.dynamic.scaffold.TypeWriter$MethodPool$Record$ForDefinedMethod$WithBody.applyBody(TypeWriter.java:609)
        at org.skywalking.apm.dependencies.net.bytebuddy.dynamic.scaffold.TypeWriter$MethodPool$Record$ForDefinedMethod.apply(TypeWriter.java:526)
        at org.skywalking.apm.dependencies.net.bytebuddy.dynamic.scaffold.TypeWriter$Default$ForInlining$RedefinitionClassVisitor.visitEnd(TypeWriter.java:3854)
        at org.skywalking.apm.dependencies.net.bytebuddy.jar.asm.ClassReader.accept(ClassReader.java:702)
        at org.skywalking.apm.dependencies.net.bytebuddy.jar.asm.ClassReader.accept(ClassReader.java:500)
```

[internal.zip](https://github.com/apache/incubator-skywalking/files/1564646/internal.zip)

**Comment by wu-sheng** [comment]
Suggestion first, next time, when you want to post some codes, please use markdown format to write in the issue directly. It is good for reading and documenting. Then all issues should be in English.

**Comment by wu-sheng** [comment]
To resolve your issues, I want to know: Do you remove all existed plugins, we provided. Because I am not sure this caused your codes only, or the compatible issue between ours and your custom plugin.

And here is my guess:
1. You class is being enhanced more than once, for some reason I am not sure.
1. `#getSkyWalkingDynamicField` is a dynamic method generated by SkyWalking core. If you want to enhance class again(already enhanced once), please skip this method.

**Comment by wu-sheng** [comment]
> You class is being enhanced more than once, for some reason I am not sure.

@suxiaoyong This is the key, I think.

**Comment by wu-sheng** [comment]
Closing this, no active comments in 4 months.
