### ISSUE TITLE
[Agent] spring boot client start failed

### ISSUE THREAD

**Issue by myoss** [apache/incubator-skywalking#694]
Please answer these questions before submitting your issue.

### What version of sky-walking are you using?
3.2.6

What is the cause? help me, thanks.

```
DEBUG 2017-12-20 11:11:24 PluginBootstrap :  loading plugin class org.skywalking.apm.toolkit.activation.log.logback.v1.x.LogbackPatternConverterActivation.
DEBUG 2017-12-20 11:11:24 PluginBootstrap :  loading plugin class org.skywalking.apm.toolkit.activation.log.logback.v1.x.mdc.MDCConverterActivation.
DEBUG 2017-12-20 11:11:24 PluginBootstrap :  loading plugin class org.skywalking.apm.toolkit.activation.trace.ActiveSpanTagActivation.
DEBUG 2017-12-20 11:11:24 PluginBootstrap :  loading plugin class org.skywalking.apm.toolkit.activation.trace.TraceAnnotationActivation.
DEBUG 2017-12-20 11:11:24 PluginBootstrap :  loading plugin class org.skywalking.apm.toolkit.activation.trace.TraceContextActivation.
DEBUG 2017-12-20 11:11:24 PluginBootstrap :  loading plugin class org.skywalking.apm.toolkit.activation.log.log4j.v2.x.Log4j2OutputAppenderActivation.
DEBUG 2017-12-20 11:11:24 GRPCChannelManager :  Selected collector grpc service running, reconnect:true.
DEBUG 2017-12-20 11:11:24 GRPCChannelManager :  Selected collector grpc service is not available. Wait 30 seconds to retry
DEBUG 2017-12-20 11:11:24 AppAndServiceRegisterClient :  AppAndServiceRegisterClient running, status:DISCONNECT.
ERROR 2017-12-20 11:11:25 ServiceManager :  ServiceManager try to shutdown [org.skywalking.apm.agent.core.sampling.SamplingService] fail.
java.lang.NullPointerException
        at org.skywalking.apm.agent.core.sampling.SamplingService.shutdown(SamplingService.java:85)
        at org.skywalking.apm.agent.core.boot.ServiceManager.shutdown(ServiceManager.java:51)
        at org.skywalking.apm.agent.SkyWalkingAgent$1.run(SkyWalkingAgent.java:66)
        at java.lang.Thread.run(Thread.java:745)

DEBUG 2017-12-20 11:11:25 GRPCChannelManager :  Selected collector grpc service shutdown.
```

**Comment by wu-sheng** [comment]
```
java.lang.NullPointerException
        at org.skywalking.apm.agent.core.sampling.SamplingService.shutdown(SamplingService.java:85)
        at org.skywalking.apm.agent.core.boot.ServiceManager.shutdown(ServiceManager.java:51)
        at org.skywalking.apm.agent.SkyWalkingAgent$1.run(SkyWalkingAgent.java:66)
        at java.lang.Thread.run(Thread.java:745)
```

@myoss This is not a startup fail. This is a shutdown exception, only. And it is no harm. Also, I have fixed it already in #691
