### ISSUE TITLE
[collector] '/ by zero'  error in 5.0.0-alpha

### ISSUE THREAD

**Issue by zhangkewei** [apache/incubator-skywalking#939]
Please answer these questions before submitting your issue.

- Why do you submit this issue?
- [ ] Question or discussion
- [x] Bug
- [ ] Requirement
- [ ] Feature or performance improvement

___
### Bug
- Which version of SkyWalking, OS and JRE?
 SkyWalking：5.0.0-alpha
 JRE: 1.8.0_131
 OS: CentOS release 6.7 x64
- What happen?
  
   In my application environment, I found that some collector api call with 'java.lang.ArithmeticException: / by zero' error.

   /getServerResponseTimeTrend
   /getApplicationTopology
   /getClusterTopology

  
```
The detail message is ：
java.lang.ArithmeticException: / by zero
	at org.apache.skywalking.apm.collector.storage.es.dao.ui.InstanceMetricEsUIDAO.getResponseTimeTrend(InstanceMetricEsUIDAO.java:147) ~[collector-storage-es-provider-5.0.0-alpha.jar:5.0.0-alpha]
	at org.apache.skywalking.apm.collector.ui.service.ServerService.getServerResponseTimeTrend(ServerService.java:100) ~[collector-ui-jetty-provider-5.0.0-alpha.jar:5.0.0-alpha]
	at org.apache.skywalking.apm.collector.ui.query.ServerQuery.getServerResponseTimeTrend(ServerQuery.java:70) ~[collector-ui-jetty-provider-5.0.0-alpha.jar:5.0.0-alpha]
	at org.apache.skywalking.apm.collector.ui.query.ServerQueryMethodAccess.invoke(Unknown Source) ~[reflectasm-1.11.3.jar:5.0.0-alpha]
	at com.coxautodev.graphql.tools.MethodFieldResolverDataFetcher.get(MethodFieldResolver.kt:132) ~[graphql-java-tools-4.3.0.jar:?]
	at graphql.execution.ExecutionStrategy.fetchField(ExecutionStrategy.java:219) [graphql-java-6.0.jar:?]
	at graphql.execution.ExecutionStrategy.resolveField(ExecutionStrategy.java:165) [graphql-java-6.0.jar:?]
	at graphql.execution.AsyncExecutionStrategy.execute(AsyncExecutionStrategy.java:55) [graphql-java-6.0.jar:?]
	at graphql.execution.Execution.executeOperation(Execution.java:154) [graphql-java-6.0.jar:?]
	at graphql.execution.Execution.execute(Execution.java:98) [graphql-java-6.0.jar:?]
	at graphql.GraphQL.execute(GraphQL.java:546) [graphql-java-6.0.jar:?]
	at graphql.GraphQL.parseValidateAndExecute(GraphQL.java:488) [graphql-java-6.0.jar:?]
	at graphql.GraphQL.executeAsync(GraphQL.java:463) [graphql-java-6.0.jar:?]
	at graphql.GraphQL.execute(GraphQL.java:394) [graphql-java-6.0.jar:?]
	at org.apache.skywalking.apm.collector.ui.jetty.handler.GraphQLHandler.execute(GraphQLHandler.java:121) [collector-ui-jetty-provider-5.0.0-alpha.jar:5.0.0-alpha]
	at org.apache.skywalking.apm.collector.ui.jetty.handler.GraphQLHandler.doPost(GraphQLHandler.java:115) [collector-ui-jetty-provider-5.0.0-alpha.jar:5.0.0-alpha]
	at org.apache.skywalking.apm.collector.server.jetty.JettyHandler.doPost(JettyHandler.java:65) [server-component-5.0.0-alpha.jar:5.0.0-alpha]
	at javax.servlet.http.HttpServlet.service(HttpServlet.java:707) [javax.servlet-api-3.1.0.jar:3.1.0]
	at org.apache.skywalking.apm.collector.server.jetty.JettyHandler.service(JettyHandler.java:112) [server-component-5.0.0-alpha.jar:5.0.0-alpha]
```

**Comment by wu-sheng** [comment]
elasticsearch data:
[data-0313.tar.gz](https://github.com/apache/incubator-skywalking/files/1807616/data-0313.tar.gz)  report by @zhangkewei

**Comment by wu-sheng** [comment]
I assume this is same as #930 , but the better thing is data provided. @peng-yongsheng

**Comment by cyberdak** [comment]
review the code , the question is here
```java
                long callTimes = ((Number)response.getResponse().getSource().get(InstanceMetricTable.COLUMN_TRANSACTION_CALLS)).longValue();
                long errorCallTimes = ((Number)response.getResponse().getSource().get(InstanceMetricTable.COLUMN_TRANSACTION_ERROR_CALLS)).longValue();
                long durationSum = ((Number)response.getResponse().getSource().get(InstanceMetricTable.COLUMN_TRANSACTION_DURATION_SUM)).longValue();
                long errorDurationSum = ((Number)response.getResponse().getSource().get(InstanceMetricTable.COLUMN_BUSINESS_TRANSACTION_ERROR_DURATION_SUM)).longValue();
responseTimeTrends.add((int)((durationSum - errorDurationSum) / (callTimes - errorCallTimes)));
```
if all call is error,that will cause this error.

i think it should return 0 or errorCallDurationAvg.

**Comment by wu-sheng** [comment]
@cyberdak I think 0 is a good choice. Can you send a pull reuqest to fix?

**Comment by cyberdak** [comment]
PR submited.

**Comment by wu-sheng** [comment]
@cyberdak are you using skywalking in company now?

**Comment by cyberdak** [comment]
@wu-sheng no,last time i want try skywalking to trace some performance issue , then i meet #773 issue.
So i am looking forward #773's PR merged.

**Comment by wu-sheng** [comment]
@cyberdak Yes, I am looking forward #773 too. @peng-yongsheng is still working on test tools.
