### ISSUE TITLE
cluster module no provider exists

### ISSUE THREAD

**Issue by Anarchists** [apache/incubator-skywalking#991]
In Interllij IDEA, running the org.skywalking.apm.collector.boot.CollectorBootStartUp's #main(args) method ，the Collector can successfully be started, but when I package apm-collector-boot into an executable jar package, execute java - Jar apm-collector-boot.jar，reporting the following error

`2018-03-26 18:56:33,124 - org.apache.skywalking.apm.collector.boot.config.ApplicationConfigLoader -515  [main] INFO  [] - Get a module define from application.yml, module name: naming
2018-03-26 18:56:33,129 - org.apache.skywalking.apm.collector.boot.config.ApplicationConfigLoader -520  [main] INFO  [] - Get a provider define belong to naming module, provider name: jetty
2018-03-26 18:56:33,129 - org.apache.skywalking.apm.collector.boot.config.ApplicationConfigLoader -520  [main] INFO  [] - The property with key: host, value: localhost, in jetty provider
2018-03-26 18:56:33,129 - org.apache.skywalking.apm.collector.boot.config.ApplicationConfigLoader -520  [main] INFO  [] - The property with key: port, value: 10800, in jetty provider
2018-03-26 18:56:33,129 - org.apache.skywalking.apm.collector.boot.config.ApplicationConfigLoader -520  [main] INFO  [] - The property with key: context_path, value: /, in jetty provider
2018-03-26 18:56:33,130 - org.apache.skywalking.apm.collector.boot.config.ApplicationConfigLoader -521  [main] INFO  [] - Get a module define from application.yml, module name: remote
2018-03-26 18:56:33,130 - org.apache.skywalking.apm.collector.boot.config.ApplicationConfigLoader -521  [main] INFO  [] - Get a provider define belong to remote module, provider name: gRPC
2018-03-26 18:56:33,130 - org.apache.skywalking.apm.collector.boot.config.ApplicationConfigLoader -521  [main] INFO  [] - The property with key: host, value: localhost, in gRPC provider
2018-03-26 18:56:33,130 - org.apache.skywalking.apm.collector.boot.config.ApplicationConfigLoader -521  [main] INFO  [] - The property with key: port, value: 11800, in gRPC provider
2018-03-26 18:56:33,130 - org.apache.skywalking.apm.collector.boot.config.ApplicationConfigLoader -521  [main] INFO  [] - Get a module define from application.yml, module name: agent_gRPC
2018-03-26 18:56:33,130 - org.apache.skywalking.apm.collector.boot.config.ApplicationConfigLoader -521  [main] INFO  [] - Get a provider define belong to agent_gRPC module, provider name: gRPC
2018-03-26 18:56:33,130 - org.apache.skywalking.apm.collector.boot.config.ApplicationConfigLoader -521  [main] INFO  [] - The property with key: host, value: localhost, in gRPC provider
2018-03-26 18:56:33,131 - org.apache.skywalking.apm.collector.boot.config.ApplicationConfigLoader -522  [main] INFO  [] - The property with key: port, value: 11800, in gRPC provider
2018-03-26 18:56:33,131 - org.apache.skywalking.apm.collector.boot.config.ApplicationConfigLoader -522  [main] INFO  [] - Get a module define from application.yml, module name: agent_jetty
2018-03-26 18:56:33,131 - org.apache.skywalking.apm.collector.boot.config.ApplicationConfigLoader -522  [main] INFO  [] - Get a provider define belong to agent_jetty module, provider name: jetty
2018-03-26 18:56:33,131 - org.apache.skywalking.apm.collector.boot.config.ApplicationConfigLoader -522  [main] INFO  [] - The property with key: host, value: localhost, in jetty provider
2018-03-26 18:56:33,131 - org.apache.skywalking.apm.collector.boot.config.ApplicationConfigLoader -522  [main] INFO  [] - The property with key: port, value: 12800, in jetty provider
2018-03-26 18:56:33,131 - org.apache.skywalking.apm.collector.boot.config.ApplicationConfigLoader -522  [main] INFO  [] - The property with key: context_path, value: /, in jetty provider
2018-03-26 18:56:33,131 - org.apache.skywalking.apm.collector.boot.config.ApplicationConfigLoader -522  [main] INFO  [] - Get a module define from application.yml, module name: analysis_register
2018-03-26 18:56:33,131 - org.apache.skywalking.apm.collector.boot.config.ApplicationConfigLoader -522  [main] INFO  [] - Get a provider define belong to analysis_register module, provider name: default
2018-03-26 18:56:33,131 - org.apache.skywalking.apm.collector.boot.config.ApplicationConfigLoader -522  [main] INFO  [] - Get a module define from application.yml, module name: analysis_jvm
2018-03-26 18:56:33,132 - org.apache.skywalking.apm.collector.boot.config.ApplicationConfigLoader -523  [main] INFO  [] - Get a provider define belong to analysis_jvm module, provider name: default
2018-03-26 18:56:33,132 - org.apache.skywalking.apm.collector.boot.config.ApplicationConfigLoader -523  [main] INFO  [] - Get a module define from application.yml, module name: analysis_segment_parser
2018-03-26 18:56:33,132 - org.apache.skywalking.apm.collector.boot.config.ApplicationConfigLoader -523  [main] INFO  [] - Get a provider define belong to analysis_segment_parser module, provider name: default
2018-03-26 18:56:33,133 - org.apache.skywalking.apm.collector.boot.config.ApplicationConfigLoader -524  [main] INFO  [] - The property with key: buffer_file_path, value: ../buffer/, in default provider
2018-03-26 18:56:33,133 - org.apache.skywalking.apm.collector.boot.config.ApplicationConfigLoader -524  [main] INFO  [] - The property with key: buffer_offset_max_file_size, value: 10M, in default provider
2018-03-26 18:56:33,134 - org.apache.skywalking.apm.collector.boot.config.ApplicationConfigLoader -525  [main] INFO  [] - The property with key: buffer_segment_max_file_size, value: 500M, in default provider
2018-03-26 18:56:33,136 - org.apache.skywalking.apm.collector.boot.config.ApplicationConfigLoader -527  [main] INFO  [] - Get a module define from application.yml, module name: ui
2018-03-26 18:56:33,140 - org.apache.skywalking.apm.collector.boot.config.ApplicationConfigLoader -531  [main] INFO  [] - Get a provider define belong to ui module, provider name: jetty
2018-03-26 18:56:33,140 - org.apache.skywalking.apm.collector.boot.config.ApplicationConfigLoader -531  [main] INFO  [] - The property with key: host, value: localhost, in jetty provider
2018-03-26 18:56:33,140 - org.apache.skywalking.apm.collector.boot.config.ApplicationConfigLoader -531  [main] INFO  [] - The property with key: port, value: 12800, in jetty provider
2018-03-26 18:56:33,141 - org.apache.skywalking.apm.collector.boot.config.ApplicationConfigLoader -532  [main] INFO  [] - The property with key: context_path, value: /, in jetty provider
2018-03-26 18:56:33,142 - org.apache.skywalking.apm.collector.boot.config.ApplicationConfigLoader -533  [main] INFO  [] - Get a module define from application.yml, module name: storage
2018-03-26 18:56:33,142 - org.apache.skywalking.apm.collector.boot.config.ApplicationConfigLoader -533  [main] INFO  [] - Get a provider define belong to storage module, provider name: elasticsearch
2018-03-26 18:56:33,143 - org.apache.skywalking.apm.collector.boot.config.ApplicationConfigLoader -534  [main] INFO  [] - The property with key: cluster_name, value: CollectorDBCluster, in elasticsearch provider
2018-03-26 18:56:33,143 - org.apache.skywalking.apm.collector.boot.config.ApplicationConfigLoader -534  [main] INFO  [] - The property with key: cluster_transport_sniffer, value: true, in elasticsearch provider
2018-03-26 18:56:33,144 - org.apache.skywalking.apm.collector.boot.config.ApplicationConfigLoader -535  [main] INFO  [] - The property with key: cluster_nodes, value: localhost:9300, in elasticsearch provider
2018-03-26 18:56:33,144 - org.apache.skywalking.apm.collector.boot.config.ApplicationConfigLoader -535  [main] INFO  [] - The property with key: index_shards_number, value: 2, in elasticsearch provider
2018-03-26 18:56:33,144 - org.apache.skywalking.apm.collector.boot.config.ApplicationConfigLoader -535  [main] INFO  [] - The property with key: index_replicas_number, value: 0, in elasticsearch provider
2018-03-26 18:56:33,146 - org.apache.skywalking.apm.collector.boot.config.ApplicationConfigLoader -537  [main] INFO  [] - The property with key: ttl, value: 7, in elasticsearch provider
2018-03-26 18:56:33,147 - org.apache.skywalking.apm.collector.boot.config.ApplicationConfigLoader -538  [main] INFO  [] - Get a module define from application.yml, module name: configuration
2018-03-26 18:56:33,147 - org.apache.skywalking.apm.collector.boot.config.ApplicationConfigLoader -538  [main] INFO  [] - Get a provider define belong to configuration module, provider name: default
2018-03-26 18:56:33,148 - org.apache.skywalking.apm.collector.boot.config.ApplicationConfigLoader -539  [main] INFO  [] - The property with key: application_apdex_threshold, value: 2000, in default provider
2018-03-26 18:56:33,148 - org.apache.skywalking.apm.collector.boot.config.ApplicationConfigLoader -539  [main] INFO  [] - The property with key: service_error_rate_threshold, value: 10.0, in default provider
2018-03-26 18:56:33,149 - org.apache.skywalking.apm.collector.boot.config.ApplicationConfigLoader -540  [main] INFO  [] - The property with key: service_average_response_time_threshold, value: 2000, in default provider
2018-03-26 18:56:33,149 - org.apache.skywalking.apm.collector.boot.config.ApplicationConfigLoader -540  [main] INFO  [] - The property with key: instance_error_rate_threshold, value: 10.0, in default provider
2018-03-26 18:56:33,150 - org.apache.skywalking.apm.collector.boot.config.ApplicationConfigLoader -541  [main] INFO  [] - The property with key: instance_average_response_time_threshold, value: 2000, in default provider
2018-03-26 18:56:33,150 - org.apache.skywalking.apm.collector.boot.config.ApplicationConfigLoader -541  [main] INFO  [] - The property with key: application_error_rate_threshold, value: 10.0, in default provider
2018-03-26 18:56:33,151 - org.apache.skywalking.apm.collector.boot.config.ApplicationConfigLoader -542  [main] INFO  [] - The property with key: application_average_response_time_threshold, value: 2000, in default provider
2018-03-26 18:56:33,159 - org.apache.skywalking.apm.collector.boot.config.ApplicationConfigLoader -550  [main] WARN  [] - The cluster module did't define in application.yml, use default
2018-03-26 18:56:33,162 - org.apache.skywalking.apm.collector.boot.config.ApplicationConfigLoader -553  [main] WARN  [] - The cache module did't define in application.yml, use default
2018-03-26 18:56:33,162 - org.apache.skywalking.apm.collector.boot.config.ApplicationConfigLoader -553  [main] WARN  [] - The analysis_metric module did't define in application.yml, use default
2018-03-26 18:56:33,163 - org.apache.skywalking.apm.collector.boot.config.ApplicationConfigLoader -554  [main] WARN  [] - The analysis_alarm module did't define in application.yml, use default
2018-03-26 18:56:33,163 - org.apache.skywalking.apm.collector.boot.config.ApplicationConfigLoader -554  [main] WARN  [] - The jetty_manager module did't define in application.yml, use default
2018-03-26 18:56:33,164 - org.apache.skywalking.apm.collector.boot.config.ApplicationConfigLoader -555  [main] WARN  [] - The gRPC_manager module did't define in application.yml, use default
2018-03-26 18:56:33,169 - org.apache.skywalking.apm.collector.boot.CollectorBootStartUp -560  [main] ERROR [] - cluster module no provider exists.
org.apache.skywalking.apm.collector.core.module.ProviderNotFoundException: cluster module no provider exists.
        at org.apache.skywalking.apm.collector.core.module.Module.prepare(Module.java:82) ~[apm-collector-boot.jar:?]
        at org.apache.skywalking.apm.collector.core.module.ModuleManager.init(ModuleManager.java:57) ~[apm-collector-boot.jar:?]
        at org.apache.skywalking.apm.collector.boot.CollectorBootStartUp.main(CollectorBootStartUp.java:43) [apm-collector-boot.jar:?]`

**Comment by wu-sheng** [comment]
Please rewrite the question in English. And I think this has been fixed in master branch.

**Comment by wu-sheng** [comment]
@Anarchists I assume this has been fixed by https://github.com/apache/incubator-skywalking/pull/987

**Comment by peng-yongsheng** [comment]
@breakenknife Is this collector jar packaged by yourself? This bug was fixed. You can download release package from this [site](http://skywalking.apache.org/downloads/)

**Comment by breakenknife** [comment]
@peng-yongsheng No,I download the apache-skywalking-apm-incubating-5.0.0-alpha.tar.gz last week. Is it because I can't use the *.tar.gz packages on windows?

**Comment by coolwangbo** [comment]
You can only use .zip on windows. The problem was solved when I use .zip on windows .
在windows上必须使用zip格式的包，否则就会出现这个问题。我一开始也是在windows上使用tar这种包，结果也是遇到这个问题，后来换成zip包，就好了。在linux上，可以使用tar包。

**Comment by akankshagupta18** [comment]
@wu-sheng 
Hi, I just faced similar issue. 
es version: 7
skywalking version: apache-skywalking-apm-8.3.0.tar.gz
my system: mac

**error in oap server log:**

2020-12-29 07:28:08,436 - org.apache.skywalking.oap.server.starter.OAPServerBootstrap - 57 [main] ERROR [] - storage module no provider found.
org.apache.skywalking.oap.server.library.module.ProviderNotFoundException: storage module no provider found.
	at org.apache.skywalking.oap.server.library.module.ModuleDefine.prepare(ModuleDefine.java:86) ~[library-module-8.3.0.jar:8.3.0]
	at org.apache.skywalking.oap.server.library.module.ModuleManager.init(ModuleManager.java:47) ~[library-module-8.3.0.jar:8.3.0]
	at org.apache.skywalking.oap.server.starter.OAPServerBootstrap.start(OAPServerBootstrap.java:43) [server-bootstrap-8.3.0.jar:8.3.0]
	at org.apache.skywalking.oap.server.starter.OAPServerStartUp.main(OAPServerStartUp.java:26) [server-starter-8.3.0.jar:8.3.0]


storage:
  selector: ${SW_STORAGE:elasticsearch7}
  elasticsearch:
    nameSpace: ${SW_NAMESPACE:""}
    clusterNodes: ${SW_STORAGE_ES_CLUSTER_NODES:localhost:9200}
    protocol: ${SW_STORAGE_ES_HTTP_PROTOCOL:"http"}
    user: ${SW_ES_USER:""}
    password: ${SW_ES_PASSWORD:""}
    trustStorePath: ${SW_STORAGE_ES_SSL_JKS_PATH:""}
    trustStorePass: ${SW_STORAGE_ES_SSL_JKS_PASS:""}
    secretsManagementFile: ${SW_ES_SECRETS_MANAGEMENT_FILE:""} # Secrets management file in the properties format includes the username, password, which are managed by 3rd party tool.
    dayStep: ${SW_STORAGE_DAY_STEP:1} # Represent the number of days in the one minute/hour/day index.
    indexShardsNumber: ${SW_STORAGE_ES_INDEX_SHARDS_NUMBER:1} # Shard number of new indexes
    indexReplicasNumber: ${SW_STORAGE_ES_INDEX_REPLICAS_NUMBER:1} # Replicas number of new indexes
    # Super data set has been defined in the codes, such as trace segments.The following 3 config would be improve es performance when storage super size data in es.
    superDatasetDayStep: ${SW_SUPERDATASET_STORAGE_DAY_STEP:-1} # Represent the number of days in the super size dataset record index, the default value is the same as dayStep when the value is less than 0
    superDatasetIndexShardsFactor: ${SW_STORAGE_ES_SUPER_DATASET_INDEX_SHARDS_FACTOR:5} #  This factor provides more shards for the super data set, shards number = indexShardsNumber * superDatasetIndexShardsFactor. Also, this factor effects Zipkin and Jaeger traces.
    superDatasetIndexReplicasNumber: ${SW_STORAGE_ES_SUPER_DATASET_INDEX_REPLICAS_NUMBER:0} # Represent the replicas number in the super size dataset record index, the default value is 0.
    bulkActions: ${SW_STORAGE_ES_BULK_ACTIONS:1000} # Execute the async bulk record data every ${SW_STORAGE_ES_BULK_ACTIONS} requests
    syncBulkActions: ${SW_STORAGE_ES_SYNC_BULK_ACTIONS:50000} # Execute the sync bulk metrics data every ${SW_STORAGE_ES_SYNC_BULK_ACTIONS} requests
    flushInterval: ${SW_STORAGE_ES_FLUSH_INTERVAL:10} # flush the bulk every 10 seconds whatever the number of requests
    concurrentRequests: ${SW_STORAGE_ES_CONCURRENT_REQUESTS:2} # the number of concurrent requests
    resultWindowMaxSize: ${SW_STORAGE_ES_QUERY_MAX_WINDOW_SIZE:10000}
    metadataQueryMaxSize: ${SW_STORAGE_ES_QUERY_MAX_SIZE:5000}
    segmentQueryMaxSize: ${SW_STORAGE_ES_QUERY_SEGMENT_SIZE:200}
    profileTaskQueryMaxSize: ${SW_STORAGE_ES_QUERY_PROFILE_TASK_SIZE:200}
    advanced: ${SW_STORAGE_ES_ADVANCED:""}
  elasticsearch7:
    nameSpace: ${SW_NAMESPACE:""}
    clusterNodes: ${SW_STORAGE_ES_CLUSTER_NODES:localhost:9200}
    protocol: ${SW_STORAGE_ES_HTTP_PROTOCOL:"http"}
    trustStorePath: ${SW_STORAGE_ES_SSL_JKS_PATH:""}
    trustStorePass: ${SW_STORAGE_ES_SSL_JKS_PASS:""}
    dayStep: ${SW_STORAGE_DAY_STEP:1} # Represent the number of days in the one minute/hour/day index.
    indexShardsNumber: ${SW_STORAGE_ES_INDEX_SHARDS_NUMBER:1} # Shard number of new indexes
    indexReplicasNumber: ${SW_STORAGE_ES_INDEX_REPLICAS_NUMBER:1} # Replicas number of new indexes
    # Super data set has been defined in the codes, such as trace segments.The following 3 config would be improve es performance when storage super size data in es.
    superDatasetDayStep: ${SW_SUPERDATASET_STORAGE_DAY_STEP:-1} # Represent the number of days in the super size dataset record index, the default value is the same as dayStep when the value is less than 0
    superDatasetIndexShardsFactor: ${SW_STORAGE_ES_SUPER_DATASET_INDEX_SHARDS_FACTOR:5} #  This factor provides more shards for the super data set, shards number = indexShardsNumber * superDatasetIndexShardsFactor. Also, this factor effects Zipkin and Jaeger traces.
    superDatasetIndexReplicasNumber: ${SW_STORAGE_ES_SUPER_DATASET_INDEX_REPLICAS_NUMBER:0} # Represent the replicas number in the super size dataset record index, the default value is 0.
    user: ${SW_ES_USER:""}
    password: ${SW_ES_PASSWORD:""}
    secretsManagementFile: ${SW_ES_SECRETS_MANAGEMENT_FILE:""} # Secrets management file in the properties format includes the username, password, which are managed by 3rd party tool.
    bulkActions: ${SW_STORAGE_ES_BULK_ACTIONS:1000} # Execute the async bulk record data every ${SW_STORAGE_ES_BULK_ACTIONS} requests
    syncBulkActions: ${SW_STORAGE_ES_SYNC_BULK_ACTIONS:50000} # Execute the sync bulk metrics data every ${SW_STORAGE_ES_SYNC_BULK_ACTIONS} requests
    flushInterval: ${SW_STORAGE_ES_FLUSH_INTERVAL:10} # flush the bulk every 10 seconds whatever the number of requests
    concurrentRequests: ${SW_STORAGE_ES_CONCURRENT_REQUESTS:2} # the number of concurrent requests
    resultWindowMaxSize: ${SW_STORAGE_ES_QUERY_MAX_WINDOW_SIZE:10000}
    metadataQueryMaxSize: ${SW_STORAGE_ES_QUERY_MAX_SIZE:5000}
    segmentQueryMaxSize: ${SW_STORAGE_ES_QUERY_SEGMENT_SIZE:200}
    profileTaskQueryMaxSize: ${SW_STORAGE_ES_QUERY_PROFILE_TASK_SIZE:200}
    advanced: ${SW_STORAGE_ES_ADVANCED:""}

**Comment by kezhenxu94** [comment]
@akankshagupta18 please use the corresponding startup class in server-starter-es7 if you configure elasticseatch7 as storage. 

As this issue is rather stale, I’ll lock this issue, if you have other question, please open a new one or better ask in the mailing list.
