### ISSUE TITLE
Collector throws unexpected exception cause by server heart beat

### ISSUE THREAD

**Issue by lilanlong** [apache/incubator-skywalking#999]
2018-03-29 15:25:51,532 - org.apache.skywalking.apm.collector.analysis.worker.model.impl.PersistenceWorker -514096 [pool-8-thread-1] ERROR [] - There is no need to merge stream data with database data.
org.apache.skywalking.apm.collector.core.UnexpectedException: There is no need to merge stream data with database data.
	at org.apache.skywalking.apm.collector.storage.es.dao.InstanceHeartBeatEsPersistenceDAO.prepareBatchInsert(InstanceHeartBeatEsPersistenceDAO.java:64) ~[collector-storage-es-provider-5.0.0-alpha.jar:5.0.0-alpha]
	at org.apache.skywalking.apm.collector.storage.es.dao.InstanceHeartBeatEsPersistenceDAO.prepareBatchInsert(InstanceHeartBeatEsPersistenceDAO.java:38) ~[collector-storage-es-provider-5.0.0-alpha.jar:5.0.0-alpha]
	at org.apache.skywalking.apm.collector.analysis.worker.model.impl.PersistenceWorker.lambda$prepareBatch$0(PersistenceWorker.java:114) ~[analysis-worker-model-5.0.0-alpha.jar:5.0.0-alpha]
	at java.util.concurrent.ConcurrentHashMap.forEach(ConcurrentHashMap.java:1597) ~[?:1.8.0_66]
	at org.apache.skywalking.apm.collector.analysis.worker.model.impl.PersistenceWorker.prepareBatch(PersistenceWorker.java:101) ~[analysis-worker-model-5.0.0-alpha.jar:5.0.0-alpha]
	at org.apache.skywalking.apm.collector.analysis.worker.model.impl.PersistenceWorker.buildBatchCollection(PersistenceWorker.java:90) ~[analysis-worker-model-5.0.0-alpha.jar:5.0.0-alpha]
	at org.apache.skywalking.apm.collector.analysis.worker.timer.PersistenceTimer.lambda$extractDataAndSave$3(PersistenceTimer.java:65) ~[analysis-worker-model-5.0.0-alpha.jar:5.0.0-alpha]
	at java.util.ArrayList.forEach(ArrayList.java:1249) ~[?:1.8.0_66]
	at org.apache.skywalking.apm.collector.analysis.worker.timer.PersistenceTimer.extractDataAndSave(PersistenceTimer.java:61) ~[analysis-worker-model-5.0.0-alpha.jar:5.0.0-alpha]
	at org.apache.skywalking.apm.collector.analysis.worker.timer.PersistenceTimer.lambda$start$1(PersistenceTimer.java:54) ~[analysis-worker-model-5.0.0-alpha.jar:5.0.0-alpha]
	at org.apache.skywalking.apm.util.RunnableWithExceptionProtection.run(RunnableWithExceptionProtection.java:36) [apm-util-5.0.0-alpha.jar:5.0.0-alpha]
	at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511) [?:1.8.0_66]
	at java.util.concurrent.FutureTask.runAndReset(FutureTask.java:308) [?:1.8.0_66]
	at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.access$301(ScheduledThreadPoolExecutor.java:180) [?:1.8.0_66]
	at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.run(ScheduledThreadPoolExecutor.java:294) [?:1.8.0_66]
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142) [?:1.8.0_66]
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617) [?:1.8.0_66]
	at java.lang.Thread.run(Thread.java:745) [?:1.8.0_66]

**Comment by wu-sheng** [comment]
@peng-yongsheng Please recheck this.

**Comment by peng-yongsheng** [comment]
@lilanlong I'm not sure this is a real problem. Do you delete or clean the elasticsearch data?

**Comment by lilanlong** [comment]
@peng-yongsheng ES is the first time to use

**Comment by peng-yongsheng** [comment]
@lilanlong I checked the agent and collector codes, but not found which codes make this bug.  So, I will add some logs about the instance id which will make us find out the bug where it was came from.

**Comment by peng-yongsheng** [comment]
Don't close this issue, this bug not really fixed.

**Comment by hepyu** [comment]
Sky-v3.2.6 has this problem either, I start three collector, only third node report this exception stack.

**Comment by wu-sheng** [comment]
Haven't received this issue in new versions, especially in 6.
